// packages/react/src/primitives/PropertyList/PropertyListRoot.tsx
import type { ReactNode } from 'react'

import { PropertyListProvider } from '#react/primitives/PropertyList/context'
import type {
  PropertyListActions,
  PropertyListContext,
  PropertyListIdentity,
  PropertyListItemFor,
  PropertyListKey,
  PropertyListPatchFor,
  PropertyListRootProps,
  PropertyListRootSlotProps
} from './types'

type PropertyListRootReactProps<K extends PropertyListKey> = PropertyListRootProps<K> & {
  children?: ReactNode | ((props: PropertyListRootSlotProps<K>) => ReactNode)
  onAdd?: (item: PropertyListItemFor<K>) => void
  onRemove?: (index: number) => void
  onUpdate?: (index: number, item: PropertyListItemFor<K>) => void
  onPatch?: (index: number, changes: PropertyListPatchFor<K>) => void
  onToggleVisibility?: (index: number) => void
  onReorder?: (fromIndex: number, toIndex: number) => void
}

export function PropertyListRoot<K extends PropertyListKey>({
  propKey,
  items,
  mixed = false,
  disabled = false,
  getKey,
  children,
  onAdd,
  onRemove,
  onUpdate,
  onPatch,
  onToggleVisibility,
  onReorder
}: PropertyListRootReactProps<K>) {
  function keyOf(item: PropertyListItemFor<K>, index: number): PropertyListIdentity {
    return getKey?.(item, index) ?? index
  }

  const actions: PropertyListActions<K> = {
    add: (item) => { if (!disabled) onAdd?.(item) },
    remove: (index) => { if (!disabled) onRemove?.(index) },
    update: (index, item) => { if (!disabled) onUpdate?.(index, item) },
    patch: (index, changes) => { if (!disabled) onPatch?.(index, changes) },
    toggleVisibility: (index) => { if (!disabled) onToggleVisibility?.(index) },
    reorder: (fromIndex, toIndex) => { if (!disabled) onReorder?.(fromIndex, toIndex) }
  }

  const ctx: PropertyListContext<K> = {
    propKey,
    items,
    isMixed: mixed,
    disabled,
    keyOf,
    actions
  }

  const slotProps: PropertyListRootSlotProps<K> = {
    items,
    isMixed: mixed,
    disabled,
    keyOf,
    actions
  }

  return (
    <PropertyListProvider value={ctx as PropertyListContext}>
      {typeof children === 'function' ? children(slotProps) : children}
    </PropertyListProvider>
  )
}

// packages/vue/src/primitives/PropertyList/PropertyListRoot.vue
<script setup lang="ts" generic="K extends PropertyListKey">
import { computed } from 'vue'

import { providePropertyList } from '#vue/primitives/PropertyList/context'
import type {
  PropertyListActions,
  PropertyListIdentity,
  PropertyListItemFor,
  PropertyListKey,
  PropertyListPatchFor,
  PropertyListRootProps,
  PropertyListRootSlots
} from './types'

const {
  propKey,
  items: itemsProp,
  mixed = false,
  disabled: disabledProp = false,
  getKey
} = defineProps<PropertyListRootProps<K>>()
const emit = defineEmits<{
  add: [item: PropertyListItemFor<K>]
  remove: [index: number]
  update: [index: number, item: PropertyListItemFor<K>]
  patch: [index: number, changes: PropertyListPatchFor<K>]
  toggleVisibility: [index: number]
  reorder: [fromIndex: number, toIndex: number]
}>()
defineSlots<PropertyListRootSlots<K>>()

const items = computed(() => itemsProp)
const isMixed = computed(() => mixed)
const disabled = computed(() => disabledProp)

function keyOf(item: PropertyListItemFor<K>, index: number): PropertyListIdentity {
  return getKey?.(item, index) ?? index
}

const actions: PropertyListActions<K> = {
  add: (item) => {
    if (!disabled.value) emit('add', item)
  },
  remove: (index) => {
    if (!disabled.value) emit('remove', index)
  },
  update: (index, item) => {
    if (!disabled.value) emit('update', index, item)
  },
  patch: (index, changes) => {
    if (!disabled.value) emit('patch', index, changes)
  },
  toggleVisibility: (index) => {
    if (!disabled.value) emit('toggleVisibility', index)
  },
  reorder: (fromIndex, toIndex) => {
    if (!disabled.value) emit('reorder', fromIndex, toIndex)
  }
}

providePropertyList({ propKey, items, isMixed, disabled, keyOf, actions })
</script>

<template>
  <slot
    :items="items"
    :is-mixed="isMixed"
    :disabled="disabled"
    :key-of="keyOf"
    :actions="actions"
  />
</template>
