// src/components/settings/mcp/MCPSettingsPanel.vue
<script setup lang="ts">
import type { ToolEffect } from '@open-pencil/mcp/tools'
import { computed, onMounted, ref } from 'vue'
import { useI18n } from '@open-pencil/vue'

import {
  configurableMCPTools,
  disabledMCPTools,
  mcpAuthenticationEnabled,
  mcpRootDirectory,
  setMCPToolCategoryEnabled,
  setMCPToolEnabled
} from '@/app/automation/mcp/preferences'
import { mcpRuntime, refreshMCPRuntime, restartMCPRuntime } from '@/app/automation/mcp/runtime'
import { isTauri } from '@/app/tauri/env'
import AppInput from '@/components/ui/AppInput.vue'
import AppSwitch from '@/components/ui/AppSwitch.vue'

const { settings, automation, common } = useI18n()
const statusMessage = computed(() => {
  switch (mcpRuntime.status) {
    case 'idle':
      return automation.value.statusIdle
    case 'starting':
      return automation.value.statusStarting
    case 'running':
      return automation.value.statusRunning
    case 'stopped':
      return automation.value.statusStopped
    case 'error':
      return automation.value.statusError
  }
})
const toolSearch = ref('')
const disabledToolNames = computed(() => new Set(disabledMCPTools.value))
function categoryStatus(effect: ToolEffect) {
  const tools = configurableMCPTools.value.filter((tool) => tool.effect === effect)
  const enabled = tools.filter((tool) => !disabledToolNames.value.has(tool.name)).length
  return {
    enabled: enabled > 0,
    state: enabled > 0 && enabled < tools.length ? ('mixed' as const) : ('idle' as const)
  }
}
const inspectionToolsStatus = computed(() => categoryStatus('read'))
const modificationToolsStatus = computed(() => categoryStatus('write'))
const enabledToolCount = computed(
  () => configurableMCPTools.value.filter((tool) => !disabledToolNames.value.has(tool.name)).length
)
const visibleTools = computed(() => {
  const query = toolSearch.value.trim().toLowerCase()
  if (!query) return configurableMCPTools.value
  return configurableMCPTools.value.filter(
    (tool) =>
      tool.name.toLowerCase().includes(query) || tool.description.toLowerCase().includes(query)
  )
})

onMounted(() => {
  void refreshMCPRuntime()
})

function restart(): void {
  void restartMCPRuntime()
}

async function chooseRootDirectory(): Promise<void> {
  if (!isTauri()) return
  const { open } = await import('@tauri-apps/plugin-dialog')
  const directory = await open({ directory: true, multiple: false })
  if (typeof directory === 'string') mcpRootDirectory.value = directory
}

function isToolEnabled(name: string): boolean {
  return !disabledToolNames.value.has(name)
}

function enableAllTools(): void {
  disabledMCPTools.value = []
}
</script>

<template>
  <section class="flex flex-col gap-4" data-test-id="settings-mcp-automation-panel">
    <div>
      <h3 class="text-xs font-semibold text-surface">{{ settings.automation }}</h3>
      <p class="mt-1 text-[11px] text-muted">{{ automation.description }}</p>
    </div>

    <div class="rounded border border-border bg-panel p-3 text-[11px]">
      <dl class="grid grid-cols-[7rem_1fr] gap-x-3 gap-y-2">
        <dt class="text-muted">{{ automation.status }}</dt>
        <dd class="flex items-center gap-2 text-surface">
          <span
            class="size-2 rounded-full"
            :class="
              mcpRuntime.status === 'running'
                ? 'bg-green-500'
                : mcpRuntime.status === 'error'
                  ? 'bg-red-500'
                  : 'bg-muted'
            "
          />
          {{ statusMessage }}
        </dd>
        <dt class="text-muted">{{ automation.port }}</dt>
        <dd class="font-mono text-surface">{{ mcpRuntime.port }}</dd>
        <dt class="text-muted">{{ automation.address }}</dt>
        <dd class="select-all font-mono text-surface">127.0.0.1</dd>
        <template v-if="mcpRuntime.version">
          <dt class="text-muted">{{ automation.version }}</dt>
          <dd class="font-mono text-surface">{{ mcpRuntime.version }}</dd>
        </template>
      </dl>

      <div class="mt-3 border-t border-border pt-3">
        <div class="flex items-center justify-between gap-3">
          <div>
            <p class="text-[10px] font-medium text-surface">{{ automation.authentication }}</p>
            <p class="mt-0.5 text-[10px] leading-relaxed text-muted">
              {{ automation.authenticationDescription }}
            </p>
          </div>
          <AppSwitch
            v-model="mcpAuthenticationEnabled"
            :label="automation.authentication"
            data-test-id="settings-mcp-authentication"
          />
        </div>
      </div>

      <div class="mt-3 border-t border-border pt-3">
        <div class="flex items-center justify-between gap-3">
          <div class="min-w-0">
            <p class="text-[10px] font-medium text-surface">{{ automation.rootDirectory }}</p>
            <p class="mt-0.5 truncate font-mono text-[10px] text-muted">
              {{ mcpRootDirectory || automation.rootDirectoryDefault }}
            </p>
          </div>
          <div class="flex shrink-0 gap-1.5">
            <button
              v-if="mcpRootDirectory"
              type="button"
              class="rounded border border-border px-2 py-1 text-[10px] text-muted hover:bg-hover hover:text-surface"
              @click="mcpRootDirectory = ''"
            >
              {{ automation.useDefaultRoot }}
            </button>
            <button
              v-if="isTauri()"
              type="button"
              class="rounded border border-border px-2 py-1 text-[10px] text-surface hover:bg-hover"
              data-test-id="settings-mcp-root-directory"
              @click="chooseRootDirectory"
            >
              {{ automation.chooseRootDirectory }}
            </button>
          </div>
        </div>
        <p class="mt-1.5 text-[10px] leading-relaxed text-muted">
          {{ automation.rootDirectoryDescription }}
        </p>
      </div>
    </div>

    <p
      v-if="mcpRuntime.error"
      class="rounded border border-red-500/30 bg-red-500/10 p-3 text-[11px] text-red-400"
    >
      {{ mcpRuntime.error }}
    </p>

    <div class="overflow-hidden rounded border border-border bg-panel">
      <div class="flex items-start justify-between gap-4 border-b border-border p-3">
        <div>
          <h4 class="text-[11px] font-medium text-surface">{{ automation.tools }}</h4>
          <p class="mt-0.5 text-[10px] text-muted">
            {{
              automation.toolsEnabled({
                enabled: enabledToolCount,
                total: configurableMCPTools.length
              })
            }}
          </p>
        </div>
        <button
          v-if="disabledMCPTools.length"
          type="button"
          class="text-[10px] text-accent hover:underline"
          @click="enableAllTools"
        >
          {{ automation.enableAllTools }}
        </button>
      </div>

      <div class="border-b border-border p-2">
        <AppInput
          v-model="toolSearch"
          type="search"
          size="sm"
          :placeholder="common.search"
          :aria-label="automation.searchTools"
          data-test-id="settings-mcp-tool-search"
        />
      </div>

      <div class="grid grid-cols-2 gap-2 border-b border-border p-2.5">
        <div class="flex items-center justify-between gap-2 rounded bg-input px-2.5 py-2">
          <span class="text-[10px] text-surface">{{ automation.readOnlyTools }}</span>
          <AppSwitch
            :model-value="inspectionToolsStatus.enabled"
            :state="inspectionToolsStatus.state"
            :label="automation.readOnlyTools"
            data-test-id="settings-mcp-inspection-tools"
            @update:model-value="setMCPToolCategoryEnabled('read', $event)"
          />
        </div>
        <div class="flex items-center justify-between gap-2 rounded bg-input px-2.5 py-2">
          <span class="text-[10px] text-surface">{{ automation.sideEffectTools }}</span>
          <AppSwitch
            :model-value="modificationToolsStatus.enabled"
            :state="modificationToolsStatus.state"
            :label="automation.sideEffectTools"
            data-test-id="settings-mcp-modification-tools"
            @update:model-value="setMCPToolCategoryEnabled('write', $event)"
          />
        </div>
      </div>

      <ul class="max-h-72 divide-y divide-border overflow-y-auto">
        <li v-for="tool in visibleTools" :key="tool.name" class="flex items-start gap-3 p-2.5">
          <div class="min-w-0 flex-1">
            <code class="text-[10px] font-medium text-surface">{{ tool.name }}</code>
            <p class="mt-0.5 text-[10px] leading-relaxed text-muted">{{ tool.description }}</p>
          </div>
          <AppSwitch
            :model-value="isToolEnabled(tool.name)"
            :label="tool.name"
            :data-test-id="`settings-mcp-tool-${tool.name}`"
            @update:model-value="setMCPToolEnabled(tool.name, $event)"
          />
        </li>
      </ul>

      <p class="border-t border-border px-3 py-2 text-[10px] text-muted">
        {{
          mcpRuntime.externallyManaged
            ? automation.externalRestartNotice
            : automation.toolsRestartNotice
        }}
      </p>
    </div>

    <div>
      <button
        type="button"
        class="rounded bg-accent px-3 py-1.5 text-[11px] font-medium text-white hover:bg-accent/90 disabled:opacity-50"
        :disabled="mcpRuntime.status === 'starting' || mcpRuntime.externallyManaged"
        data-test-id="settings-mcp-restart"
        @click="restart"
      >
        {{
          mcpRuntime.status === 'starting' || mcpRuntime.checking
            ? automation.starting
            : mcpRuntime.externallyManaged
              ? automation.externallyManaged
              : automation.restart
        }}
      </button>
    </div>
  </section>
</template>

// packages/react/src/components/settings/mcp/MCPSettingsPanel.tsx
import { useEffect, useMemo, useState } from 'react'
import { useStore } from '@nanostores/react'

import {
  disabledMCPTools,
  enableAllMCPTools,
  mcpAuthenticationEnabled,
  mcpRootDirectory,
  setMCPToolCategoryEnabled,
  setMCPToolEnabled
} from '#react/app/automation/mcp/preferences'
import { mcpRuntime, refreshMCPRuntime, restartMCPRuntime } from '#react/app/automation/mcp/runtime'
import { configurableMCPTools, type MCPToolEffect } from '#react/app/automation/mcp/tools'
import { AppInput } from '#react/components/ui/AppInput'
import { AppSwitch } from '#react/components/ui/AppSwitch'
import { useI18n } from '#react/i18n'

function categoryStatus(effect: MCPToolEffect, disabled: ReadonlySet<string>) {
  const tools = configurableMCPTools().filter((tool) => tool.effect === effect)
  const enabled = tools.filter((tool) => !disabled.has(tool.name)).length
  return {
    enabled: enabled > 0,
    state: enabled > 0 && enabled < tools.length ? ('mixed' as const) : ('idle' as const)
  }
}

export function MCPSettingsPanel() {
  const { dialogs } = useI18n()
  const runtime = useStore(mcpRuntime)
  const disabledTools = useStore(disabledMCPTools)
  const authenticationEnabled = useStore(mcpAuthenticationEnabled)
  const rootDirectory = useStore(mcpRootDirectory)
  const [toolSearch, setToolSearch] = useState('')
  const tools = useMemo(() => configurableMCPTools(), [])
  const disabledToolNames = useMemo(() => new Set(disabledTools), [disabledTools])
  const inspectionToolsStatus = categoryStatus('read', disabledToolNames)
  const modificationToolsStatus = categoryStatus('write', disabledToolNames)
  const enabledToolCount = tools.filter((tool) => !disabledToolNames.has(tool.name)).length
  const query = toolSearch.trim().toLowerCase()
  const visibleTools = query
    ? tools.filter(
        (tool) =>
          tool.name.toLowerCase().includes(query) || tool.description.toLowerCase().includes(query)
      )
    : tools
  const statusLabel =
    runtime.status === 'idle'
      ? dialogs.mcpStatus_idle
      : runtime.status === 'starting'
        ? dialogs.mcpStatus_starting
        : runtime.status === 'running'
          ? dialogs.mcpStatus_running
          : runtime.status === 'error'
            ? dialogs.mcpStatus_error
            : dialogs.mcpStatus_stopped

  useEffect(() => {
    void refreshMCPRuntime()
  }, [])

  return (
    <section className="flex flex-col gap-4" data-test-id="settings-mcp-automation-panel">
      <div>
        <h3 className="text-xs font-semibold text-surface">{dialogs.settingsMCP}</h3>
        <p className="mt-1 text-[11px] text-muted">{dialogs.mcpDescription}</p>
      </div>

      <div className="rounded border border-border bg-panel p-3 text-[11px]">
        <dl className="grid grid-cols-[7rem_1fr] gap-x-3 gap-y-2">
          <dt className="text-muted">{dialogs.mcpStatus}</dt>
          <dd className="flex items-center gap-2 text-surface">
            <span
              className={`size-2 rounded-full ${
                runtime.status === 'running'
                  ? 'bg-green-500'
                  : runtime.status === 'error'
                    ? 'bg-red-500'
                    : 'bg-muted'
              }`}
            />
            {statusLabel}
          </dd>
          <dt className="text-muted">{dialogs.mcpPort}</dt>
          <dd className="font-mono text-surface">{runtime.port}</dd>
          <dt className="text-muted">{dialogs.mcpAddress}</dt>
          <dd className="select-all font-mono text-surface">127.0.0.1</dd>
          {runtime.version ? (
            <>
              <dt className="text-muted">{dialogs.mcpVersion}</dt>
              <dd className="font-mono text-surface">{runtime.version}</dd>
            </>
          ) : null}
        </dl>

        <div className="mt-3 border-t border-border pt-3">
          <div className="flex items-center justify-between gap-3">
            <div>
              <p className="text-[10px] font-medium text-surface">{dialogs.mcpAuthentication}</p>
              <p className="mt-0.5 text-[10px] leading-relaxed text-muted">
                {dialogs.mcpAuthenticationDescription}
              </p>
            </div>
            <AppSwitch
              checked={authenticationEnabled}
              label={dialogs.mcpAuthentication}
              data-test-id="settings-mcp-authentication"
              onCheckedChange={(enabled) => mcpAuthenticationEnabled.set(enabled)}
            />
          </div>
        </div>

        <div className="mt-3 border-t border-border pt-3">
          <div className="min-w-0">
            <p className="text-[10px] font-medium text-surface">{dialogs.mcpRootDirectory}</p>
            <p className="mt-0.5 truncate font-mono text-[10px] text-muted">
              {rootDirectory || dialogs.mcpRootDirectoryDefault}
            </p>
          </div>
          <p className="mt-1.5 text-[10px] leading-relaxed text-muted">
            {dialogs.mcpRootDirectoryDescription}
          </p>
        </div>
      </div>

      {runtime.error ? (
        <p className="rounded border border-red-500/30 bg-red-500/10 p-3 text-[11px] text-red-400">
          {runtime.error}
        </p>
      ) : null}

      <div className="overflow-hidden rounded border border-border bg-panel">
        <div className="flex items-start justify-between gap-4 border-b border-border p-3">
          <div>
            <h4 className="text-[11px] font-medium text-surface">{dialogs.mcpTools}</h4>
            <p className="mt-0.5 text-[10px] text-muted">
              {dialogs.mcpToolsEnabled({ enabled: enabledToolCount, total: tools.length })}
            </p>
          </div>
          {disabledTools.length > 0 ? (
            <button
              type="button"
              className="text-[10px] text-accent hover:underline"
              onClick={enableAllMCPTools}
            >
              {dialogs.mcpEnableAllTools}
            </button>
          ) : null}
        </div>

        <div className="border-b border-border p-2">
          <AppInput
            type="search"
            tone="default"
            size="sm"
            value={toolSearch}
            placeholder={dialogs.search}
            aria-label={dialogs.mcpSearchTools}
            data-test-id="settings-mcp-tool-search"
            onChange={(event) => setToolSearch(event.target.value)}
          />
        </div>

        <div className="grid grid-cols-2 gap-2 border-b border-border p-2.5">
          <div className="flex items-center justify-between gap-2 rounded bg-input px-2.5 py-2">
            <span className="text-[10px] text-surface">{dialogs.mcpReadOnlyTools}</span>
            <AppSwitch
              checked={inspectionToolsStatus.enabled}
              state={inspectionToolsStatus.state}
              label={dialogs.mcpReadOnlyTools}
              data-test-id="settings-mcp-inspection-tools"
              onCheckedChange={(enabled) => setMCPToolCategoryEnabled('read', enabled)}
            />
          </div>
          <div className="flex items-center justify-between gap-2 rounded bg-input px-2.5 py-2">
            <span className="text-[10px] text-surface">{dialogs.mcpSideEffectTools}</span>
            <AppSwitch
              checked={modificationToolsStatus.enabled}
              state={modificationToolsStatus.state}
              label={dialogs.mcpSideEffectTools}
              data-test-id="settings-mcp-modification-tools"
              onCheckedChange={(enabled) => setMCPToolCategoryEnabled('write', enabled)}
            />
          </div>
        </div>

        <ul className="max-h-72 divide-y divide-border overflow-y-auto">
          {visibleTools.map((tool) => (
            <li key={tool.name} className="flex items-start gap-3 p-2.5">
              <div className="min-w-0 flex-1">
                <code className="text-[10px] font-medium text-surface">{tool.name}</code>
                <p className="mt-0.5 text-[10px] leading-relaxed text-muted">{tool.description}</p>
              </div>
              <AppSwitch
                checked={!disabledToolNames.has(tool.name)}
                label={tool.name}
                data-test-id={`settings-mcp-tool-${tool.name}`}
                onCheckedChange={(enabled) => setMCPToolEnabled(tool.name, enabled)}
              />
            </li>
          ))}
        </ul>

        <p className="border-t border-border px-3 py-2 text-[10px] text-muted">
          {runtime.externallyManaged
            ? dialogs.mcpExternalRestartNotice
            : dialogs.mcpToolsRestartNotice}
        </p>
      </div>

      <div>
        <button
          type="button"
          className="rounded bg-accent px-3 py-1.5 text-[11px] font-medium text-white hover:bg-accent/90 disabled:opacity-50"
          disabled={runtime.status === 'starting' || runtime.externallyManaged}
          data-test-id="settings-mcp-restart"
          onClick={() => void restartMCPRuntime()}
        >
          {runtime.status === 'starting' || runtime.checking
            ? dialogs.mcpStarting
            : runtime.externallyManaged
              ? dialogs.mcpExternallyManaged
              : dialogs.mcpRestart}
        </button>
      </div>
    </section>
  )
}
