// src/components/ColorPicker/ColorInput.vue
<script setup lang="ts">
import { useAttrs } from 'vue'

import type { Color } from '@open-pencil/scene-graph/primitives'
import { ColorInputRoot, inputValue } from '@open-pencil/vue'
import type { OkHCLControls } from '@open-pencil/vue'

import ColorPicker from '@/components/ColorPicker/ColorPicker.vue'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()

const {
  editable = false,
  color,
  okhcl = null
} = defineProps<{
  color: Color
  editable?: boolean
  okhcl?: OkHCLControls | null
}>()
const emit = defineEmits<{ update: [color: Color]; openChange: [open: boolean] }>()
</script>

<template>
  <ColorInputRoot
    :color="color"
    :editable="editable"
    :okhcl="okhcl"
    @update="emit('update', $event)"
  >
    <template #default="{ editable: isEditable, hex, actions, okhcl: okhclControls }">
      <div v-bind="attrs" class="flex items-center gap-1.5">
        <ColorPicker
          :color="color"
          :okhcl="okhclControls"
          @update="actions.updateColor($event)"
          @open-change="emit('openChange', $event)"
        />
        <input
          v-if="isEditable"
          data-test-id="color-hex-input"
          class="min-w-0 flex-1 border-none bg-transparent font-mono text-xs text-surface outline-none"
          :value="hex"
          maxlength="6"
          @change="actions.updateFromHex(inputValue($event))"
        />
        <span v-else class="min-w-0 flex-1 truncate font-mono text-xs text-muted">
          {{ hex }}
        </span>
      </div>
    </template>
  </ColorInputRoot>
</template>

// src/react_app/pickers/ColorInput.tsx
import { ColorPicker } from '@/react_app/pickers/ColorPicker'
import { ColorInputRoot, type OkHCLControls } from '@open-pencil/react'

import type { Color } from '@open-pencil/core'

export function ColorInput({
  color,
  editable = false,
  okhcl = null,
  className,
  onUpdate
}: {
  color: Color
  editable?: boolean
  okhcl?: OkHCLControls | null
  className?: string
  onUpdate: (color: Color) => void
}) {
  return (
    <ColorInputRoot color={color} editable={editable} okhcl={okhcl} onUpdate={onUpdate}>
      {({ editable: isEditable, hex, updateFromHex, updateColor, okhcl: okhclControls }) => (
        <div className={`flex items-center gap-1.5 ${className ?? ''}`}>
          <ColorPicker color={color} okhcl={okhclControls} onUpdate={updateColor} />
          {isEditable ? (
            <input
              data-test-id="color-hex-input"
              className="min-w-0 flex-1 border-none bg-transparent font-mono text-xs text-surface outline-none"
              defaultValue={hex}
              key={hex}
              maxLength={6}
              onChange={(e) => updateFromHex(e.currentTarget.value)}
            />
          ) : (
            <span className="min-w-0 flex-1 truncate font-mono text-xs text-muted">{hex}</span>
          )}
        </div>
      )}
    </ColorInputRoot>
  )
}
