// packages/vue/src/primitives/BindableValue/BindableValueRoot.vue
<script setup lang="ts" generic="V">
import { computed, onBeforeUnmount, ref } from 'vue'

import { useBindingProvider } from '#vue/controls/binding-provider/context'
import type {
  BindingMutationSource,
  BindingProvider,
  BindingTarget
} from '#vue/controls/binding-provider/types'
import { provideBindableValue } from '#vue/primitives/BindableValue/context'
import type {
  BindableValueActions,
  BindableValueContext,
  BindableValueRootProps,
  BindableValueRootSlots,
  BindableValueSlotProps,
  BindableValueStateAttrs
} from '#vue/primitives/BindableValue/types'

const {
  provider: providerProp,
  targets: targetsProp,
  value: valueProp,
  policy: policyProp = 'detach-on-edit',
  batchLabel = 'Edit bound value'
} = defineProps<BindableValueRootProps<V>>()

defineSlots<BindableValueRootSlots<V>>()

const injectedProvider = useBindingProvider<V>()
const resolvedProvider = providerProp ?? injectedProvider
if (!resolvedProvider) {
  throw new Error(
    '[open-pencil] BindableValueRoot requires a provider prop or provideBindingProvider()'
  )
}
const provider: BindingProvider<V> = resolvedProvider
const beginProviderBatch = provider.beginBatch
const commitProviderBatch = provider.commitBatch
const rollbackProviderBatch = provider.rollbackBatch
const supportsInteractionBatch =
  beginProviderBatch !== undefined &&
  commitProviderBatch !== undefined &&
  rollbackProviderBatch !== undefined

const targets = computed(() => targetsProp)
const value = computed(() => valueProp)
const policy = computed(() => policyProp)
const open = ref(false)
const searchTerm = ref('')
const state = computed(() => {
  void provider.revision?.value
  return provider.getState(targets.value)
})
const variable = computed(() => {
  const target = targets.value[0]
  return state.value === 'bound' && target ? provider.getBound(target) : undefined
})
const resolvedValue = computed(() => {
  void provider.revision?.value
  const current = variable.value
  return current ? provider.resolve(current.id) : undefined
})
const variables = computed(() => {
  void provider.revision?.value
  return provider.filterVariables(searchTerm.value)
})
const stateAttrs = computed<BindableValueStateAttrs>(() => ({
  'data-unbound': state.value === 'unbound' ? '' : undefined,
  'data-bound': state.value === 'bound' ? '' : undefined,
  'data-mixed': state.value === 'mixed' ? '' : undefined,
  'data-picker-open': open.value ? '' : undefined,
  'data-policy': policy.value
}))

let interactionActive = false
let detachedForInteraction = false
let bindingSnapshot = new Map<BindingTarget, string>()
let resolvedSnapshot: V | undefined

function runImmediate(label: string, action: () => void) {
  if (provider.runBatch) provider.runBatch(label, action)
  else action()
}

function bind(variableId: string) {
  runImmediate('Bind variable', () => {
    for (const target of targets.value) provider.bind(target, variableId)
  })
  open.value = false
}

function unbind() {
  runImmediate('Unbind variable', () => {
    for (const target of targets.value) provider.unbind(target)
  })
}

function create(name: string) {
  const target = targets.value[0]
  if (!target || !provider.create) return
  runImmediate('Create and bind variable', () => provider.create?.(target, value.value, name))
  open.value = false
}

function openPicker() {
  open.value = true
}

function closePicker() {
  open.value = false
}

function togglePicker() {
  open.value = !open.value
}

function setSearchTerm(term: string) {
  searchTerm.value = term
}

function snapshotBindings() {
  bindingSnapshot = new Map()
  for (const target of targets.value) {
    const current = provider.getBound(target)
    if (current) bindingSnapshot.set(target, current.id)
  }
}

function beginMutation(source: BindingMutationSource): boolean {
  if (interactionActive) return true
  if (state.value === 'unbound') return true
  const startedMixed = state.value === 'mixed'
  if (!startedMixed && policy.value === 'readonly-when-bound') return false
  if (
    !startedMixed &&
    policy.value === 'edit-variable' &&
    (!variable.value || !provider.setValue)
  ) {
    return false
  }

  interactionActive = true
  void source
  snapshotBindings()
  resolvedSnapshot = resolvedValue.value
  if (supportsInteractionBatch) beginProviderBatch(batchLabel)

  if (startedMixed || policy.value === 'detach-on-edit') {
    detachedForInteraction = true
    for (const target of targets.value) provider.unbind(target)
  }
  return true
}

function applyValue(nextValue: V): boolean {
  if (policy.value !== 'edit-variable' || !interactionActive) return false
  const current = variable.value
  if (!current || !provider.setValue) return false
  provider.setValue(current.id, nextValue)
  return true
}

function resetInteraction() {
  interactionActive = false
  detachedForInteraction = false
  bindingSnapshot.clear()
  resolvedSnapshot = undefined
}

function commitMutation() {
  if (!interactionActive) return
  if (supportsInteractionBatch) commitProviderBatch()
  resetInteraction()
}

function restoreWithoutRollback() {
  if (detachedForInteraction) {
    for (const [target, variableId] of bindingSnapshot) provider.bind(target, variableId)
  } else if (
    policy.value === 'edit-variable' &&
    variable.value &&
    resolvedSnapshot !== undefined &&
    provider.setValue
  ) {
    provider.setValue(variable.value.id, resolvedSnapshot)
  }
}

function cancelMutation() {
  if (!interactionActive) return
  if (supportsInteractionBatch) rollbackProviderBatch()
  else restoreWithoutRollback()
  resetInteraction()
}

const actions: BindableValueActions<V> = {
  bind,
  unbind,
  create,
  openPicker,
  closePicker,
  togglePicker,
  setSearchTerm,
  beginMutation,
  applyValue,
  commitMutation,
  cancelMutation
}

const slotProps = computed<BindableValueSlotProps<V>>(() => ({
  state: state.value,
  variable: variable.value,
  resolvedValue: resolvedValue.value,
  policy: policy.value,
  open: open.value,
  searchTerm: searchTerm.value,
  variables: variables.value,
  stateAttrs: stateAttrs.value,
  actions
}))

const context: BindableValueContext<V> = {
  provider,
  targets,
  value,
  state,
  variable,
  resolvedValue,
  policy,
  open,
  searchTerm,
  variables,
  stateAttrs,
  slotProps,
  actions
}

provideBindableValue(context)
onBeforeUnmount(cancelMutation)
</script>

<template>
  <slot v-bind="slotProps" />
</template>

// packages/react/src/primitives/BindableValue/BindableValueRoot.tsx
import { useEffect, useMemo, useRef, useState } from 'react'

import { useBindingProvider } from '#react/controls/binding-provider/context'
import type {
  BindingMutationSource,
  BindingProvider,
  BindingTarget
} from '#react/controls/binding-provider/types'
import { BindableValueProvider } from '#react/primitives/BindableValue/context'
import type {
  BindableValueActions,
  BindableValueContext,
  BindableValueRootProps,
  BindableValueSlotProps,
  BindableValueStateAttrs
} from '#react/primitives/BindableValue/types'

export function BindableValueRoot<V>({
  provider: providerProp,
  targets,
  value,
  policy = 'detach-on-edit',
  batchLabel = 'Edit bound value',
  children
}: BindableValueRootProps<V>) {
  const injectedProvider = useBindingProvider<V>()
  const resolvedProvider = providerProp ?? injectedProvider
  if (!resolvedProvider) {
    throw new Error(
      '[open-pencil] BindableValueRoot requires a provider prop or provideBindingProvider()'
    )
  }
  const provider: BindingProvider<V> = resolvedProvider

  const supportsInteractionBatch =
    provider.beginBatch !== undefined &&
    provider.commitBatch !== undefined &&
    provider.rollbackBatch !== undefined

  const [open, setOpen] = useState(false)
  const [searchTerm, setSearchTerm] = useState('')
  // Revision counter from provider (if any) — trigger re-render when it changes
  const [, forceUpdate] = useState(0)

  // Track provider revision for reactivity
  const revisionRef = useRef<unknown>(undefined)
  const currentRevision = provider.revision?.value
  if (revisionRef.current !== currentRevision) {
    revisionRef.current = currentRevision
    // Will be caught on next render via the revision check
  }

  // Mutable interaction state — no re-renders needed
  const interactionActiveRef = useRef(false)
  const detachedForInteractionRef = useRef(false)
  const bindingSnapshotRef = useRef(new Map<BindingTarget, string>())
  const resolvedSnapshotRef = useRef<V | undefined>(undefined)

  const state = provider.getState(targets)
  const variable = state === 'bound' && targets[0] ? provider.getBound(targets[0]) : undefined
  const resolvedValue = variable ? provider.resolve(variable.id) : undefined
  const variables = provider.filterVariables(searchTerm)

  const stateAttrs = useMemo<BindableValueStateAttrs>(
    () => ({
      ...(state === 'unbound' ? { 'data-unbound': '' as const } : {}),
      ...(state === 'bound' ? { 'data-bound': '' as const } : {}),
      ...(state === 'mixed' ? { 'data-mixed': '' as const } : {}),
      ...(open ? { 'data-picker-open': '' as const } : {}),
      'data-policy': policy
    }),
    [state, open, policy]
  )

  function runImmediate(label: string, action: () => void) {
    if (provider.runBatch) provider.runBatch(label, action)
    else action()
  }

  function bind(variableId: string) {
    runImmediate('Bind variable', () => {
      for (const target of targets) provider.bind(target, variableId)
    })
    setOpen(false)
    forceUpdate((n) => n + 1)
  }

  function unbind() {
    runImmediate('Unbind variable', () => {
      for (const target of targets) provider.unbind(target)
    })
    forceUpdate((n) => n + 1)
  }

  function create(name: string) {
    if (targets.length === 0 || !provider.create) return
    const target = targets[0]
    runImmediate('Create and bind variable', () => provider.create?.(target, value, name))
    setOpen(false)
    forceUpdate((n) => n + 1)
  }

  function openPicker() { setOpen(true) }
  function closePicker() { setOpen(false) }
  function togglePicker() { setOpen((prev) => !prev) }
  function updateSearchTerm(term: string) { setSearchTerm(term) }

  function snapshotBindings() {
    const snapshot = new Map<BindingTarget, string>()
    for (const target of targets) {
      const current = provider.getBound(target)
      if (current) snapshot.set(target, current.id)
    }
    bindingSnapshotRef.current = snapshot
  }

  function beginMutation(source: BindingMutationSource): boolean {
    if (interactionActiveRef.current) return true
    if (state === 'unbound') return true
    const startedMixed = state === 'mixed'
    if (!startedMixed && policy === 'readonly-when-bound') return false
    if (!startedMixed && policy === 'edit-variable' && (!variable || !provider.setValue)) {
      return false
    }

    interactionActiveRef.current = true
    void source
    snapshotBindings()
    resolvedSnapshotRef.current = resolvedValue
    if (supportsInteractionBatch) provider.beginBatch?.(batchLabel)

    if (startedMixed || policy === 'detach-on-edit') {
      detachedForInteractionRef.current = true
      for (const target of targets) provider.unbind(target)
    }
    return true
  }

  function applyValue(nextValue: V): boolean {
    if (policy !== 'edit-variable' || !interactionActiveRef.current) return false
    if (!variable || !provider.setValue) return false
    provider.setValue(variable.id, nextValue)
    return true
  }

  function resetInteraction() {
    interactionActiveRef.current = false
    detachedForInteractionRef.current = false
    bindingSnapshotRef.current.clear()
    resolvedSnapshotRef.current = undefined
  }

  function commitMutation() {
    if (!interactionActiveRef.current) return
    if (supportsInteractionBatch) provider.commitBatch?.()
    resetInteraction()
  }

  function restoreWithoutRollback() {
    if (detachedForInteractionRef.current) {
      for (const [target, variableId] of bindingSnapshotRef.current) provider.bind(target, variableId)
    } else if (
      policy === 'edit-variable' &&
      variable &&
      resolvedSnapshotRef.current !== undefined &&
      provider.setValue
    ) {
      provider.setValue(variable.id, resolvedSnapshotRef.current)
    }
  }

  function cancelMutation() {
    if (!interactionActiveRef.current) return
    if (supportsInteractionBatch) provider.rollbackBatch?.()
    else restoreWithoutRollback()
    resetInteraction()
  }

  useEffect(() => () => cancelMutation(), [])

  const actions: BindableValueActions<V> = {
    bind,
    unbind,
    create,
    openPicker,
    closePicker,
    togglePicker,
    setSearchTerm: updateSearchTerm,
    beginMutation,
    applyValue,
    commitMutation,
    cancelMutation
  }

  const slotProps: BindableValueSlotProps<V> = {
    state,
    variable,
    resolvedValue,
    policy,
    open,
    searchTerm,
    variables,
    stateAttrs,
    actions
  }

  const ctx: BindableValueContext<V> = {
    provider,
    targets,
    value,
    state,
    variable,
    resolvedValue,
    policy,
    open,
    searchTerm,
    variables,
    stateAttrs,
    slotProps,
    actions
  }

  return (
    <BindableValueProvider value={ctx as BindableValueContext}>
      {typeof children === 'function' ? children(slotProps) : children}
    </BindableValueProvider>
  )
}
