// src/components/chat/ChatMessage.tsx
import { useState } from 'react'
import { isTextUIPart, isToolUIPart, getToolName } from 'ai'
import ReactMarkdown from 'react-markdown'

import IconLoaderCircle from '~icons/lucide/loader-circle'
import IconCheck from '~icons/lucide/check'
import IconTriangleAlert from '~icons/lucide/triangle-alert'
import IconChevronDown from '~icons/lucide/chevron-down'

import type { UIDataTypes, UIMessage, UIMessagePart, UITools } from 'ai'

type ToolPart = Extract<UIMessagePart<UIDataTypes, UITools>, { toolCallId: string }>

function toolDisplayName(part: ToolPart): string {
  return getToolName(part)
    .replace(/^mcp__[^_]+__/, '')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
}

function hasErrorOutput(part: ToolPart): boolean {
  return (
    part.state === 'output-available' &&
    typeof part.output === 'object' &&
    part.output !== null &&
    'error' in part.output
  )
}

function toolState(part: ToolPart): 'pending' | 'done' | 'error' {
  if (part.state === 'output-error' || hasErrorOutput(part)) return 'error'
  if (part.state === 'output-available') return 'done'
  return 'pending'
}

function partKey(part: UIMessagePart<UIDataTypes, UITools>, index: number): string {
  if ('toolCallId' in part) return part.toolCallId
  return `part-${index}`
}

interface ToolCallBlockProps {
  part: ToolPart
}

function ToolCallBlock({ part }: ToolCallBlockProps) {
  const [open, setOpen] = useState(false)
  const state = toolState(part)
  const isDone = state !== 'pending'

  return (
    <div className="rounded-lg border border-border bg-canvas p-2">
      <button
        className="flex w-full items-center gap-2 rounded px-1 py-0.5 hover:bg-hover"
        onClick={() => setOpen(!open)}
      >
        <div
          className={`flex size-4 items-center justify-center rounded-full ${
            state === 'pending'
              ? 'bg-accent/20 text-accent'
              : (state === 'done' ? 'bg-green-500/20 text-green-400' : 'bg-red-500/20 text-red-400')
          }`}
        >
          {state === 'pending'
            ? <IconLoaderCircle className="size-3 animate-spin" />
            : (state === 'done' ? <IconCheck className="size-3" /> : <IconTriangleAlert className="size-3" />)
          }
        </div>
        <span className="text-[11px] text-surface">{toolDisplayName(part)}</span>
        <span className="text-[10px] text-muted">
          {state === 'pending' ? 'Running…' : (state === 'done' ? 'Done' : 'Error')}
        </span>
        {isDone && (
          <IconChevronDown
            className={`ml-auto size-3 text-muted transition-transform ${open ? 'rotate-180' : ''}`}
          />
        )}
      </button>
      {isDone && open && (
        <pre className="mt-1 overflow-x-auto rounded bg-input p-2 text-[10px] text-muted">
          {(part.state === 'output-error' && part.errorText)
            ? part.errorText
            : (hasErrorOutput(part)
              ? (part.output as { error: string }).error
              : JSON.stringify(part.output, null, 2))}
        </pre>
      )}
    </div>
  )
}

interface ChatMessageProps {
  message: UIMessage
}

export function ChatMessage({ message }: ChatMessageProps) {
  return (
    <div
      data-test-id={`chat-message-${message.role}`}
      className={message.role === 'user' ? 'flex justify-end' : ''}
    >
      <div className={`min-w-0 space-y-1.5 ${message.role === 'user' ? 'max-w-[85%]' : ''}`}>
        {message.role === 'assistant' ? (
          message.parts.map((part, i) => {
            if (isToolUIPart(part)) {
              return <ToolCallBlock key={partKey(part, i)} part={part as ToolPart} />
            }
            if (isTextUIPart(part) && part.text) {
              return (
                <div
                  key={partKey(part, i)}
                  data-test-id="chat-text-bubble"
                  className="rounded-xl rounded-tl-md bg-hover px-3 py-2 text-xs leading-relaxed text-surface"
                >
                  <ReactMarkdown className="chat-markdown">{part.text}</ReactMarkdown>
                </div>
              )
            }
            return null
          })
        ) : (message.role === 'user' ? (
          <div
            data-test-id="chat-text-bubble"
            className="rounded-xl rounded-br-md bg-accent px-3 py-2 text-xs leading-relaxed whitespace-pre-wrap text-white"
          >
            {message.parts
              .filter(isTextUIPart)
              .map((p) => p.text)
              .join('')}
          </div>
        ) : null)}
      </div>
    </div>
  )
}

// src/components/chat/ChatMessage.vue
<script setup lang="ts">
import { computed } from 'vue'
import { isTextUIPart, isToolUIPart, getToolName } from 'ai'
import { CollapsibleContent, CollapsibleRoot, CollapsibleTrigger } from 'reka-ui'
import { Markdown } from 'vue-stream-markdown'
import { useI18n, vTestId } from '@open-pencil/vue'
import 'vue-stream-markdown/index.css'

import {
  imageAttachmentsForMessage,
  visibleUserMessageText
} from '@/app/ai/attachment/image/presentation'
import ImageAttachment from '@/components/chat/attachment/image/ImageAttachment.vue'
import { resolvedAppTheme } from '@/app/shell/theme'
import { classifyToolState } from './tool-state'

import type { UIDataTypes, UIMessage, UIMessagePart, UITools } from 'ai'

const { message, streaming = false } = defineProps<{
  message: UIMessage
  streaming?: boolean
}>()
const { ai } = useI18n()
const isDark = computed(() => resolvedAppTheme.value === 'dark')
const markdownMode = computed(() => (streaming ? 'streaming' : 'static'))
const imageAttachments = imageAttachmentsForMessage(message.id)

type ToolPart = Extract<UIMessagePart<UIDataTypes, UITools>, { toolCallId: string }>

function toolDisplayName(part: ToolPart): string {
  return getToolName(part)
    .replace(/^mcp__[^_]+__/, '')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
}

function hasErrorOutput(part: ToolPart): boolean {
  return (
    part.state === 'output-available' &&
    typeof part.output === 'object' &&
    part.output !== null &&
    'error' in part.output
  )
}

function toolState(part: ToolPart): 'pending' | 'done' | 'error' {
  return classifyToolState({
    toolName: getToolName(part),
    state: part.state,
    output: part.output
  })
}

function partKey(part: UIMessagePart<UIDataTypes, UITools>, index: number): string {
  if ('toolCallId' in part) return part.toolCallId
  return `part-${index}`
}
</script>

<template>
  <div
    v-test-id="`chat-message-${message.role}`"
    :class="message.role === 'user' ? 'flex justify-end' : ''"
  >
    <div
      class="min-w-0 space-y-2 select-text"
      :class="message.role === 'user' ? 'max-w-[85%]' : ''"
    >
      <template v-if="message.role === 'assistant'">
        <template v-for="(part, i) in message.parts" :key="partKey(part, i)">
          <!-- Tool call -->
          <div v-if="isToolUIPart(part)" class="rounded-lg border border-border bg-canvas p-2">
            <CollapsibleRoot>
              <CollapsibleTrigger
                class="flex w-full items-center gap-2 rounded px-1 py-0.5 hover:bg-hover"
              >
                <div
                  class="flex size-4 items-center justify-center rounded-full"
                  :class="{
                    'bg-accent/20 text-accent': toolState(part) === 'pending',
                    'bg-green-500/20 text-green-400': toolState(part) === 'done',
                    'bg-red-500/20 text-red-400': toolState(part) === 'error'
                  }"
                >
                  <icon-lucide-loader-circle
                    v-if="toolState(part) === 'pending'"
                    class="size-3 animate-spin"
                  />
                  <icon-lucide-check v-else-if="toolState(part) === 'done'" class="size-3" />
                  <icon-lucide-triangle-alert v-else class="size-3" />
                </div>
                <span class="text-[11px] text-surface">
                  {{ toolDisplayName(part) }}
                </span>
                <span class="text-[10px] text-muted">
                  {{
                    toolState(part) === 'pending'
                      ? ai.toolRunning
                      : toolState(part) === 'done'
                        ? ai.toolFinished
                        : ai.toolError
                  }}
                </span>
                <icon-lucide-chevron-down
                  v-if="toolState(part) !== 'pending'"
                  class="ml-auto size-3 text-muted transition-transform [[data-state=open]>&]:rotate-180"
                />
              </CollapsibleTrigger>
              <CollapsibleContent
                v-if="toolState(part) !== 'pending'"
                class="data-[state=closed]:collapsible-up data-[state=open]:collapsible-down overflow-hidden text-[10px]"
              >
                <pre class="mt-1 overflow-x-auto rounded bg-input p-2 text-muted">{{
                  part.state === 'output-error' && part.errorText
                    ? part.errorText
                    : hasErrorOutput(part)
                      ? (part.output as { error: string }).error
                      : JSON.stringify(part.output, null, 2)
                }}</pre>
              </CollapsibleContent>
            </CollapsibleRoot>
          </div>

          <!-- Text -->
          <div
            v-else-if="isTextUIPart(part) && part.text"
            data-test-id="chat-text-bubble"
            class="rounded-xl rounded-tl-md bg-hover px-3 py-2 text-xs leading-relaxed text-surface"
          >
            <Markdown
              :key="markdownMode"
              :content="part.text"
              :is-dark="isDark"
              :mermaid="false"
              :mode="markdownMode"
              :data-chat-markdown-mode="markdownMode"
              class="chat-markdown [&_[data-stream-markdown=code]]:!bg-input"
            />
          </div>
        </template>
      </template>

      <!-- User message -->
      <template v-else-if="message.role === 'user'">
        <div v-if="imageAttachments.length" class="flex flex-wrap justify-end gap-1.5">
          <ImageAttachment
            v-for="attachment in imageAttachments"
            :key="attachment.id"
            :attachment="attachment"
          />
        </div>
        <div
          data-test-id="chat-text-bubble"
          class="rounded-xl rounded-br-md bg-accent px-3 py-2 text-xs leading-relaxed whitespace-pre-wrap text-white"
        >
          {{
            visibleUserMessageText(
              message.id,
              message.parts
                .filter(isTextUIPart)
                .map((p) => p.text)
                .join('')
            )
          }}
        </div>
      </template>
    </div>
  </div>
</template>
