// packages/react/src/PositionControls/PositionControlsRoot.tsx
import type { ReactNode } from 'react'

import { MIXED, useNodeProps, type MixedValue } from '../controls/useNodeProps'

export interface PositionControlsRootSlotProps {
  active: boolean
  isMulti: boolean
  ids: string[]
  xValue: MixedValue<number>
  yValue: MixedValue<number>
  wValue: MixedValue<number>
  hValue: MixedValue<number>
  rotationValue: MixedValue<number>
  mixed: typeof MIXED
  updateProp: (key: string, value: number | string) => void
  commitProp: (key: string, value: number | string, previous: number | string) => void
  align: (axis: 'horizontal' | 'vertical', pos: 'min' | 'center' | 'max') => void
  flip: (axis: 'horizontal' | 'vertical') => void
  rotate: (degrees: number) => void
}

export interface PositionControlsRootProps {
  children?: ReactNode | ((state: PositionControlsRootSlotProps) => ReactNode)
}

export function PositionControlsRoot({ children }: PositionControlsRootProps) {
  const { updateProp, commitProp, node, nodes, isMulti, active, prop, store } = useNodeProps()

  const xValue = isMulti ? prop('x') : Math.round(node?.x ?? 0)
  const yValue = isMulti ? prop('y') : Math.round(node?.y ?? 0)
  const wValue = prop('width')
  const hValue = prop('height')
  const rotationValue = isMulti ? prop('rotation') : Math.round(node?.rotation ?? 0)
  const ids = nodes.map((n) => n.id)

  function align(axis: 'horizontal' | 'vertical', pos: 'min' | 'center' | 'max') {
    store.alignNodes(ids, axis, pos)
  }

  function flip(axis: 'horizontal' | 'vertical') {
    store.flipNodes(ids, axis)
  }

  function rotate(degrees: number) {
    store.rotateNodes(ids, degrees)
  }

  const slot: PositionControlsRootSlotProps = {
    active,
    isMulti,
    ids,
    xValue: xValue as MixedValue<number>,
    yValue: yValue as MixedValue<number>,
    wValue: wValue as MixedValue<number>,
    hValue: hValue as MixedValue<number>,
    rotationValue: rotationValue as MixedValue<number>,
    mixed: MIXED,
    updateProp,
    commitProp,
    align,
    flip,
    rotate
  }

  return <>{typeof children === 'function' ? children(slot) : children}</>
}

// packages/react/src/primitives/PositionControls/PositionControlsRoot.tsx
<script setup lang="ts">
import { computed } from 'vue'

import { MIXED, useNodeProps } from '#vue/controls/node-props/use'

const {
  updateProp,
  commitProp,
  node,
  nodes,
  isMulti,
  active,
  prop: multiProp,
  store
} = useNodeProps()

const xValue = computed(() =>
  isMulti.value ? multiProp('x').value : Math.round(node.value?.x ?? 0)
)
const yValue = computed(() =>
  isMulti.value ? multiProp('y').value : Math.round(node.value?.y ?? 0)
)
const wValue = multiProp('width')
const hValue = multiProp('height')
const rotationValue = computed(() =>
  isMulti.value ? multiProp('rotation').value : Math.round(node.value?.rotation ?? 0)
)
const ids = computed(() => nodes.value.map((n) => n.id))

function align(axis: 'horizontal' | 'vertical', pos: 'min' | 'center' | 'max') {
  store.alignNodes(ids.value, axis, pos)
}

function flip(axis: 'horizontal' | 'vertical') {
  store.flipNodes(ids.value, axis)
}

function rotate(degrees: number) {
  store.rotateNodes(ids.value, degrees)
}

const actions = {
  updateProp,
  commitProp,
  align,
  flip,
  rotate
}
</script>

<template>
  <slot
    :active="active"
    :is-multi="isMulti"
    :ids="ids"
    :x-value="xValue"
    :y-value="yValue"
    :w-value="wValue"
    :h-value="hValue"
    :rotation-value="rotationValue"
    :mixed="MIXED"
    :actions="actions"
  />
</template>
