// packages/vue/src/primitives/PositionControls/PositionControlsRoot.vue
<script setup lang="ts">
import { computed } from 'vue'

import { MIXED } from '#vue/controls/node-props/use'
import { usePosition } from '#vue/controls/position/use'

const {
  updateProp,
  commitProp,
  cancelProp,
  ids,
  align,
  flip,
  rotate,
  isMulti,
  active,
  prop: multiProp,
  panelProp,
  x,
  y,
  rotation
} = usePosition()

const multiX = panelProp('x')
const multiY = panelProp('y')
const multiRotation = panelProp('rotation')
const xValue = computed(() => (isMulti.value ? multiX.value : x.value))
const yValue = computed(() => (isMulti.value ? multiY.value : y.value))
const wValue = multiProp('width')
const hValue = multiProp('height')
const rotationValue = computed(() => (isMulti.value ? multiRotation.value : rotation.value))
const actions = {
  updateProp,
  commitProp,
  cancelProp,
  align,
  flip,
  rotate
}
</script>

<template>
  <slot
    :active="active"
    :is-multi="isMulti"
    :ids="ids"
    :x-value="xValue"
    :y-value="yValue"
    :w-value="wValue"
    :h-value="hValue"
    :rotation-value="rotationValue"
    :mixed="MIXED"
    :actions="actions"
  />
</template>

// packages/react/src/primitives/PositionControls/PositionControlsRoot.tsx
import { type ReactNode } from 'react'

import { MIXED } from '#react/controls/node-props/use'
import { usePosition } from '#react/controls/position/use'
import type { MixedValue } from '#react/controls/node-props/use'

interface PositionControlsActions {
  updateProp: (key: string, value: number) => void
  commitProp: (key: string, value: number, previous: number) => void
  align: (axis: 'horizontal' | 'vertical', pos: 'min' | 'center' | 'max') => void
  flip: (axis: 'horizontal' | 'vertical') => void
  rotate: (degrees: number) => void
}

interface PositionControlsRootSlotProps {
  active: boolean
  isMulti: boolean
  ids: string[]
  xValue: MixedValue<number>
  yValue: MixedValue<number>
  wValue: MixedValue<number>
  hValue: MixedValue<number>
  rotationValue: MixedValue<number>
  mixed: typeof MIXED
  actions: PositionControlsActions
}

interface PositionControlsRootProps {
  children?: ReactNode | ((props: PositionControlsRootSlotProps) => ReactNode)
}

export function PositionControlsRoot({ children }: PositionControlsRootProps) {
  const {
    active,
    isMulti,
    ids,
    x,
    y,
    width,
    height,
    rotation,
    updateProp,
    commitProp,
    align,
    flip,
    rotate
  } = usePosition()

  const actions: PositionControlsActions = {
    updateProp,
    commitProp,
    align,
    flip,
    rotate
  }

  const slotProps: PositionControlsRootSlotProps = {
    active: active.value,
    isMulti: isMulti.value,
    ids: ids.value,
    xValue: x.value,
    yValue: y.value,
    wValue: width.value,
    hValue: height.value,
    rotationValue: rotation.value,
    mixed: MIXED,
    actions
  }

  return typeof children === 'function' ? <>{children(slotProps)}</> : <>{children}</>
}
