// packages/react/src/components/editor/ZoomDropdown.tsx
import { useState } from 'react'
import { Check } from 'lucide-react'

import { formatShortcut } from '#react/editor/commands'
import { useEditorCommands } from '#react/editor/commands/use'
import { useI18n } from '#react/i18n'
import { useEditorStore } from '#react/app/editor/store'
import { AppShortcutText } from '#react/components/ui/AppShortcutText'
import { menuItem, useMenuUI } from '#react/components/ui/menu'
import { appMenuShortcut, appMenuShortcutLabel } from '#react/app/shell/menu/shortcut'

const ZOOM_PRESETS: ReadonlyArray<{ label: string; level: number; shortcut?: string }> = [
  { label: '50%', level: 0.5 },
  { label: '100%', level: 1, shortcut: appMenuShortcut('view.zoom100') },
  { label: '200%', level: 2 }
]

export function ZoomDropdown() {
  const store = useEditorStore()
  const { getCommand } = useEditorCommands()
  const { menu: menuText, commands } = useI18n()
  const [open, setOpen] = useState(false)
  const menuCls = useMenuUI({ content: 'min-w-52' })
  const itemCls = menuItem({ justify: 'start', class: 'relative pl-7' })
  const zoomPercent = Math.round(store.state.zoom * 100)

  function isActivePreset(level: number) {
    return Math.abs(store.state.zoom - level) < 0.005
  }

  return (
    <div className="relative ml-auto">
      <button
        type="button"
        data-test-id="zoom-dropdown"
        className="flex cursor-pointer items-center rounded px-2 py-1 text-[11px] text-muted hover:text-surface"
        onClick={() => setOpen((value) => !value)}
      >
        {zoomPercent}%
      </button>
      {open ? (
        <div className={`absolute right-0 z-20 mt-1 ${menuCls.content}`}>
          <button
            type="button"
            className={itemCls}
            onClick={() => {
              getCommand('view.zoomFit').run()
              setOpen(false)
            }}
          >
            <span>{commands.zoomToFit}</span>
            <AppShortcutText>{appMenuShortcutLabel('view.zoomFit')}</AppShortcutText>
          </button>
          <button
            type="button"
            className={itemCls}
            onClick={() => {
              getCommand('view.zoomSelection').run()
              setOpen(false)
            }}
          >
            <span>{commands.zoomToSelection}</span>
          </button>
          <div className={menuCls.separator} />
          {ZOOM_PRESETS.map((preset) => (
            <button
              key={preset.label}
              type="button"
              className={itemCls}
              onClick={() => {
                store.zoomToLevel(preset.level)
                setOpen(false)
              }}
            >
              <span className="absolute left-2 flex size-3.5 items-center justify-center">
                {isActivePreset(preset.level) ? <Check className="size-3" /> : null}
              </span>
              <span>{preset.label}</span>
              {preset.shortcut ? (
                <AppShortcutText>{formatShortcut(preset.shortcut)}</AppShortcutText>
              ) : null}
            </button>
          ))}
          <div className={menuCls.separator} />
          <button
            type="button"
            className={itemCls}
            onClick={() => {
              store.state.showRulers = !store.state.showRulers
              store.requestRepaint()
              store.notify()
              setOpen(false)
            }}
          >
            <span>{menuText.rulers}</span>
          </button>
        </div>
      ) : null}
    </div>
  )
}

// src/components/editor/ZoomDropdown.vue
<script setup lang="ts">
import {
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuPortal,
  DropdownMenuRoot,
  DropdownMenuSeparator,
  DropdownMenuTrigger
} from 'reka-ui'
import { nextTick, ref, watch } from 'vue'

import { useEditorCommands, useI18n, formatShortcut } from '@open-pencil/vue'

import { useEditorStore } from '@/app/editor/active-store'
import { setDesignIssuesOnCanvas } from '@/app/settings/preferences/apply'
import { appPreferences } from '@/app/settings/preferences/store'
import { appMenuShortcut, appMenuShortcutLabel } from '@/app/shell/menu/shortcut'
import AppShortcutText from '@/components/ui/menu/AppShortcutText.vue'
import { menuItem, useMenuUI } from '@/components/ui/menu/menu'

const store = useEditorStore()
const { getCommand } = useEditorCommands()
const { menu: menuText, commands, panels } = useI18n()

const open = ref(false)
const editing = ref(false)
const inputRef = ref<HTMLInputElement | null>()
const inputValue = ref('')

const menuCls = useMenuUI({ content: 'min-w-52' })
const itemCls = menuItem({ justify: 'start', class: 'relative pl-7' })

function zoomPercent() {
  return Math.round(store.state.zoom * 100)
}

function startEditing() {
  editing.value = true
  inputValue.value = String(zoomPercent())
  void nextTick(() => inputRef.value?.select())
}

function commitInput() {
  const parsed = Number.parseInt(inputValue.value, 10)
  if (!Number.isNaN(parsed) && parsed > 0) {
    store.zoomToLevel(parsed / 100)
  }
  editing.value = false
}

function cancelInput() {
  editing.value = false
}

function toggleRulers() {
  store.state.showRulers = !store.state.showRulers
  store.requestRepaint()
}

function toggleRemoteCursors() {
  store.state.showRemoteCursors = !store.state.showRemoteCursors
  store.requestRepaint()
}

function zoomIn() {
  const center = store.viewportScreenCenter()
  store.applyZoom(-100, center.x, center.y)
}

function zoomOut() {
  const center = store.viewportScreenCenter()
  store.applyZoom(100, center.x, center.y)
}

const ZOOM_PRESETS: ReadonlyArray<{ label: string; level: number; shortcut?: string }> = [
  { label: '50%', level: 0.5 },
  { label: '100%', level: 1, shortcut: appMenuShortcut('view.zoom100') },
  { label: '200%', level: 2 }
]

function isActivePreset(level: number) {
  return Math.abs(store.state.zoom - level) < 0.005
}

watch(open, (v) => {
  if (!v) editing.value = false
})
</script>

<template>
  <DropdownMenuRoot v-model:open="open">
    <DropdownMenuTrigger as-child>
      <button
        data-test-id="zoom-dropdown-trigger"
        class="ml-auto cursor-pointer rounded px-1.5 py-0.5 text-[11px] text-muted hover:bg-hover"
      >
        {{ zoomPercent() }}%
      </button>
    </DropdownMenuTrigger>

    <DropdownMenuPortal>
      <DropdownMenuContent
        side="bottom"
        :side-offset="4"
        align="end"
        :class="menuCls.content"
        @escape-key-down="cancelInput"
      >
        <div class="px-1 py-1">
          <input
            v-if="editing"
            ref="inputRef"
            v-model="inputValue"
            data-test-id="zoom-input"
            class="w-full rounded border border-accent bg-input px-2 py-1 text-xs text-surface outline-none"
            @blur="commitInput"
            @keydown.enter="commitInput"
            @keydown.escape.stop="cancelInput"
          />
          <button
            v-else
            data-test-id="zoom-input-trigger"
            class="w-full cursor-pointer rounded border border-border bg-input px-2 py-1 text-left text-xs text-surface hover:border-muted"
            @click="startEditing"
          >
            {{ zoomPercent() }}%
          </button>
        </div>

        <DropdownMenuSeparator :class="menuCls.separator" />

        <DropdownMenuItem :class="itemCls" @select="zoomIn">
          <span class="flex-1">{{ menuText.zoomIn }}</span>
          <AppShortcutText>{{ appMenuShortcutLabel('zoom-in') }}</AppShortcutText>
        </DropdownMenuItem>
        <DropdownMenuItem :class="itemCls" @select="zoomOut">
          <span class="flex-1">{{ menuText.zoomOut }}</span>
          <AppShortcutText>{{ appMenuShortcutLabel('zoom-out') }}</AppShortcutText>
        </DropdownMenuItem>
        <DropdownMenuItem :class="itemCls" @select="getCommand('view.zoomFit').run()">
          <span class="flex-1">{{ commands.zoomToFit }}</span>
          <AppShortcutText>{{ appMenuShortcutLabel('view.zoomFit') }}</AppShortcutText>
        </DropdownMenuItem>
        <DropdownMenuItem
          v-for="preset in ZOOM_PRESETS"
          :key="preset.level"
          :class="itemCls"
          @select="store.zoomToLevel(preset.level)"
        >
          <icon-lucide-check v-if="isActivePreset(preset.level)" class="absolute left-2 size-3.5" />
          <span class="flex-1">{{ preset.label }}</span>
          <AppShortcutText v-if="preset.shortcut">{{
            formatShortcut(preset.shortcut)
          }}</AppShortcutText>
        </DropdownMenuItem>

        <DropdownMenuSeparator :class="menuCls.separator" />

        <DropdownMenuItem :class="itemCls" @select.prevent="toggleRulers">
          <icon-lucide-check v-if="store.state.showRulers" class="absolute left-2 size-3.5" />
          <span class="flex-1">{{ panels.rulers }}</span>
        </DropdownMenuItem>
        <DropdownMenuItem :class="itemCls" @select.prevent="toggleRemoteCursors">
          <icon-lucide-check
            v-if="store.state.showRemoteCursors"
            class="absolute left-2 size-3.5"
          />
          <span class="flex-1">{{ panels.multiplayerCursors }}</span>
        </DropdownMenuItem>
        <DropdownMenuItem
          :class="itemCls"
          @select.prevent="setDesignIssuesOnCanvas(!appPreferences.designCheck.showOnCanvas)"
        >
          <icon-lucide-check
            v-if="appPreferences.designCheck.showOnCanvas"
            class="absolute left-2 size-3.5"
          />
          <span class="flex-1">{{ menuText.designIssues }}</span>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenuPortal>
  </DropdownMenuRoot>
</template>
