// src/components/editor/ZoomDropdown.vue
<script setup lang="ts">
import {
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuPortal,
  DropdownMenuRoot,
  DropdownMenuSeparator,
  DropdownMenuTrigger
} from 'reka-ui'
import { nextTick, ref, watch } from 'vue'

import { useEditorCommands, useI18n, formatShortcut } from '@open-pencil/vue'

import { useEditorStore } from '@/app/editor/active-store'
import { setDesignIssuesOnCanvas } from '@/app/settings/preferences/apply'
import { appPreferences } from '@/app/settings/preferences/store'
import { appMenuShortcut, appMenuShortcutLabel } from '@/app/shell/menu/shortcut'
import AppShortcutText from '@/components/ui/menu/AppShortcutText.vue'
import { menuItem, useMenuUI } from '@/components/ui/menu/menu'

const store = useEditorStore()
const { getCommand } = useEditorCommands()
const { menu: menuText, commands, panels } = useI18n()

const open = ref(false)
const editing = ref(false)
const inputRef = ref<HTMLInputElement | null>()
const inputValue = ref('')

const menuCls = useMenuUI({ content: 'min-w-52' })
const itemCls = menuItem({ justify: 'start', class: 'relative pl-7' })

function zoomPercent() {
  return Math.round(store.state.zoom * 100)
}

function startEditing() {
  editing.value = true
  inputValue.value = String(zoomPercent())
  void nextTick(() => inputRef.value?.select())
}

function commitInput() {
  const parsed = Number.parseInt(inputValue.value, 10)
  if (!Number.isNaN(parsed) && parsed > 0) {
    store.zoomToLevel(parsed / 100)
  }
  editing.value = false
}

function cancelInput() {
  editing.value = false
}

function toggleRulers() {
  store.state.showRulers = !store.state.showRulers
  store.requestRepaint()
}

function toggleRemoteCursors() {
  store.state.showRemoteCursors = !store.state.showRemoteCursors
  store.requestRepaint()
}

function zoomIn() {
  const center = store.viewportScreenCenter()
  store.applyZoom(-100, center.x, center.y)
}

function zoomOut() {
  const center = store.viewportScreenCenter()
  store.applyZoom(100, center.x, center.y)
}

const ZOOM_PRESETS: ReadonlyArray<{ label: string; level: number; shortcut?: string }> = [
  { label: '50%', level: 0.5 },
  { label: '100%', level: 1, shortcut: appMenuShortcut('view.zoom100') },
  { label: '200%', level: 2 }
]

function isActivePreset(level: number) {
  return Math.abs(store.state.zoom - level) < 0.005
}

watch(open, (v) => {
  if (!v) editing.value = false
})
</script>

<template>
  <DropdownMenuRoot v-model:open="open">
    <DropdownMenuTrigger as-child>
      <button
        data-test-id="zoom-dropdown-trigger"
        class="ml-auto cursor-pointer rounded px-1.5 py-0.5 text-[11px] text-muted hover:bg-hover"
      >
        {{ zoomPercent() }}%
      </button>
    </DropdownMenuTrigger>

    <DropdownMenuPortal>
      <DropdownMenuContent
        side="bottom"
        :side-offset="4"
        align="end"
        :class="menuCls.content"
        @escape-key-down="cancelInput"
      >
        <div class="px-1 py-1">
          <input
            v-if="editing"
            ref="inputRef"
            v-model="inputValue"
            data-test-id="zoom-input"
            class="w-full rounded border border-accent bg-input px-2 py-1 text-xs text-surface outline-none"
            @blur="commitInput"
            @keydown.enter="commitInput"
            @keydown.escape.stop="cancelInput"
          />
          <button
            v-else
            data-test-id="zoom-input-trigger"
            class="w-full cursor-pointer rounded border border-border bg-input px-2 py-1 text-left text-xs text-surface hover:border-muted"
            @click="startEditing"
          >
            {{ zoomPercent() }}%
          </button>
        </div>

        <DropdownMenuSeparator :class="menuCls.separator" />

        <DropdownMenuItem :class="itemCls" @select="zoomIn">
          <span class="flex-1">{{ menuText.zoomIn }}</span>
          <AppShortcutText>{{ appMenuShortcutLabel('zoom-in') }}</AppShortcutText>
        </DropdownMenuItem>
        <DropdownMenuItem :class="itemCls" @select="zoomOut">
          <span class="flex-1">{{ menuText.zoomOut }}</span>
          <AppShortcutText>{{ appMenuShortcutLabel('zoom-out') }}</AppShortcutText>
        </DropdownMenuItem>
        <DropdownMenuItem :class="itemCls" @select="getCommand('view.zoomFit').run()">
          <span class="flex-1">{{ commands.zoomToFit }}</span>
          <AppShortcutText>{{ appMenuShortcutLabel('view.zoomFit') }}</AppShortcutText>
        </DropdownMenuItem>
        <DropdownMenuItem
          v-for="preset in ZOOM_PRESETS"
          :key="preset.level"
          :class="itemCls"
          @select="store.zoomToLevel(preset.level)"
        >
          <icon-lucide-check v-if="isActivePreset(preset.level)" class="absolute left-2 size-3.5" />
          <span class="flex-1">{{ preset.label }}</span>
          <AppShortcutText v-if="preset.shortcut">{{
            formatShortcut(preset.shortcut)
          }}</AppShortcutText>
        </DropdownMenuItem>

        <DropdownMenuSeparator :class="menuCls.separator" />

        <DropdownMenuItem :class="itemCls" @select.prevent="toggleRulers">
          <icon-lucide-check v-if="store.state.showRulers" class="absolute left-2 size-3.5" />
          <span class="flex-1">{{ panels.rulers }}</span>
        </DropdownMenuItem>
        <DropdownMenuItem :class="itemCls" @select.prevent="toggleRemoteCursors">
          <icon-lucide-check
            v-if="store.state.showRemoteCursors"
            class="absolute left-2 size-3.5"
          />
          <span class="flex-1">{{ panels.multiplayerCursors }}</span>
        </DropdownMenuItem>
        <DropdownMenuItem
          :class="itemCls"
          @select.prevent="setDesignIssuesOnCanvas(!appPreferences.designCheck.showOnCanvas)"
        >
          <icon-lucide-check
            v-if="appPreferences.designCheck.showOnCanvas"
            class="absolute left-2 size-3.5"
          />
          <span class="flex-1">{{ menuText.designIssues }}</span>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenuPortal>
  </DropdownMenuRoot>
</template>

// src/components/editor/ZoomDropdown.tsx
import { useRef, useState } from 'react'
import { DropdownMenuContent, DropdownMenuItem, DropdownMenuPortal, Root as DropdownMenuRoot, DropdownMenuSeparator, DropdownMenuTrigger } from '@radix-ui/react-dropdown-menu'

import { useEditorCommands, useI18n, formatShortcut, useEditorEvent } from '@open-pencil/react'
import { AppShortcutText } from '@/components/ui/AppShortcutText'
import { menuItem, useMenuUI } from '@/components/ui/menu'
import { useEditorStore } from '@/app/editor/active-store'
import { appMenuShortcut, appMenuShortcutLabel } from '@/app/shell/menu/shortcut'

import IconLucideCheck from '~icons/lucide/check'

const ZOOM_PRESETS: ReadonlyArray<{ label: string; level: number; shortcut?: string }> = [
  { label: '50%', level: 0.5 },
  { label: '100%', level: 1, shortcut: appMenuShortcut('view.zoom100') },
  { label: '200%', level: 2 }
]

export default function ZoomDropdown() {
  const store = useEditorStore()
  const { getCommand } = useEditorCommands()
  const { menu: menuText, commands, panels } = useI18n()
  const [open, setOpen] = useState(false)
  const [editing, setEditing] = useState(false)
  const [inputValue, setInputValue] = useState('')
  const [zoom, setZoom] = useState(store.state.zoom)
  const inputRef = useRef<HTMLInputElement>(null)

  const menuCls = useMenuUI({ content: 'min-w-52' })
  const itemCls = menuItem({ justify: 'start', class: 'relative pl-7' })

  useEditorEvent('viewport:changed', () => setZoom(store.state.zoom))
  useEditorEvent('render:requested', () => setZoom(store.state.zoom))

  function zoomPercent() {
    return Math.round(zoom * 100)
  }

  function startEditing() {
    setEditing(true)
    setInputValue(String(zoomPercent()))
    setTimeout(() => inputRef.current?.select(), 0)
  }

  function commitInput() {
    const parsed = Number.parseInt(inputValue, 10)
    if (!Number.isNaN(parsed) && parsed > 0) {
      store.zoomToLevel(parsed / 100)
    }
    setEditing(false)
  }

  function cancelInput() {
    setEditing(false)
  }

  function toggleRulers() {
    store.state.showRulers = !store.state.showRulers
    store.requestRepaint()
  }

  function toggleRemoteCursors() {
    store.state.showRemoteCursors = !store.state.showRemoteCursors
    store.requestRepaint()
  }

  function zoomIn() {
    const center = store.viewportScreenCenter()
    store.applyZoom(-100, center.x, center.y)
  }

  function zoomOut() {
    const center = store.viewportScreenCenter()
    store.applyZoom(100, center.x, center.y)
  }

  function isActivePreset(level: number) {
    return Math.abs(zoom - level) < 0.005
  }

  return (
    <DropdownMenuRoot open={open} onOpenChange={(v) => { setOpen(v); if (!v) setEditing(false) }}>
      <DropdownMenuTrigger asChild>
        <button
          data-test-id="zoom-dropdown-trigger"
          type="button"
          className="ml-auto cursor-pointer rounded px-1.5 py-0.5 text-[11px] text-muted hover:bg-hover"
        >
          {zoomPercent()}%
        </button>
      </DropdownMenuTrigger>

      <DropdownMenuPortal>
        <DropdownMenuContent
          side="bottom"
          sideOffset={4}
          align="end"
          className={menuCls.content}
          onEscapeKeyDown={cancelInput}
        >
          <div className="px-1 py-1">
            {editing ? (
              <input
                ref={inputRef}
                value={inputValue}
                data-test-id="zoom-input"
                className="w-full rounded border border-accent bg-input px-2 py-1 text-xs text-surface outline-none"
                onChange={(e) => setInputValue(e.target.value)}
                onBlur={commitInput}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') commitInput()
                  if (e.key === 'Escape') { e.stopPropagation(); cancelInput() }
                }}
              />
            ) : (
              <button
                data-test-id="zoom-input-trigger"
                type="button"
                className="w-full cursor-pointer rounded border border-border bg-input px-2 py-1 text-left text-xs text-surface hover:border-muted"
                onClick={startEditing}
              >
                {zoomPercent()}%
              </button>
            )}
          </div>

          <DropdownMenuSeparator className={menuCls.separator} />

          <DropdownMenuItem className={itemCls} onSelect={zoomIn}>
            <span className="flex-1">{menuText.zoomIn}</span>
            <AppShortcutText>{appMenuShortcutLabel('zoom-in')}</AppShortcutText>
          </DropdownMenuItem>
          <DropdownMenuItem className={itemCls} onSelect={zoomOut}>
            <span className="flex-1">{menuText.zoomOut}</span>
            <AppShortcutText>{appMenuShortcutLabel('zoom-out')}</AppShortcutText>
          </DropdownMenuItem>
          <DropdownMenuItem className={itemCls} onSelect={() => getCommand('view.zoomFit').run()}>
            <span className="flex-1">{commands.zoomToFit}</span>
            <AppShortcutText>{appMenuShortcutLabel('view.zoomFit')}</AppShortcutText>
          </DropdownMenuItem>
          {ZOOM_PRESETS.map((preset) => (
            <DropdownMenuItem
              key={preset.level}
              className={itemCls}
              onSelect={() => store.zoomToLevel(preset.level)}
            >
              {isActivePreset(preset.level) && (
                <IconLucideCheck className="absolute left-2 size-3.5" />
              )}
              <span className="flex-1">{preset.label}</span>
              {preset.shortcut && (
                <AppShortcutText>{formatShortcut(preset.shortcut)}</AppShortcutText>
              )}
            </DropdownMenuItem>
          ))}

          <DropdownMenuSeparator className={menuCls.separator} />

          <DropdownMenuItem className={itemCls} onSelect={(e) => { e.preventDefault(); toggleRulers() }}>
            {store.state.showRulers && <IconLucideCheck className="absolute left-2 size-3.5" />}
            <span className="flex-1">{panels.rulers}</span>
          </DropdownMenuItem>
          <DropdownMenuItem className={itemCls} onSelect={(e) => { e.preventDefault(); toggleRemoteCursors() }}>
            {store.state.showRemoteCursors && <IconLucideCheck className="absolute left-2 size-3.5" />}
            <span className="flex-1">{panels.multiplayerCursors}</span>
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenuPortal>
    </DropdownMenuRoot>
  )
}
