// packages/react/src/primitives/PropertySection/PropertySectionRoot.tsx
import { useState, type ReactNode } from 'react'
import * as Collapsible from '@radix-ui/react-collapsible'

import { ProvidePropertySection } from '#react/primitives/PropertySection/context'
import type {
  PropertySectionActionAPI,
  PropertySectionContext,
  PropertySectionRootProps,
  PropertySectionSlotProps,
  PropertySectionStateAttrs
} from '#react/primitives/PropertySection/types'

type PropertySectionRootReactProps = PropertySectionRootProps & {
  children?: ReactNode | ((props: PropertySectionSlotProps) => ReactNode)
  className?: string
  [key: string]: unknown
}

export function PropertySectionRoot({
  open: openProp,
  defaultOpen = true,
  empty = false,
  disabled = false,
  unmountOnHide = false,
  children,
  ...attrs
}: PropertySectionRootReactProps) {
  const controlled = openProp !== undefined
  const [uncontrolledOpen, setUncontrolledOpen] = useState(defaultOpen)
  const open = openProp !== undefined ? openProp : uncontrolledOpen

  function setOpen(value: boolean) {
    if (!controlled) setUncontrolledOpen(value)
  }

  const stateAttrs: PropertySectionStateAttrs = {
    'data-state': open ? 'open' : 'closed',
    ...(empty ? { 'data-empty': '' as const } : {}),
    ...(disabled ? { 'data-disabled': '' as const } : {})
  }

  const actions: PropertySectionActionAPI = {
    open: () => { if (!disabled) setOpen(true) },
    close: () => { if (!disabled) setOpen(false) },
    toggle: () => { if (!disabled) setOpen(!open) }
  }

  const slotProps: PropertySectionSlotProps = { open, empty, stateAttrs, actions }
  const ctx: PropertySectionContext = { open, empty, disabled, stateAttrs, slotProps, actions }

  return (
    <ProvidePropertySection value={ctx}>
      <Collapsible.Root
        {...attrs}
        {...stateAttrs}
        open={open}
        disabled={disabled}
        onOpenChange={setOpen}
        {...(unmountOnHide ? {} : { forceMount: true as const })}
      >
        {typeof children === 'function' ? children(slotProps) : children}
      </Collapsible.Root>
    </ProvidePropertySection>
  )
}

// packages/vue/src/primitives/PropertySection/PropertySectionRoot.vue
<script setup lang="ts">
import { computed, getCurrentInstance, ref } from 'vue'
import { CollapsibleRoot } from 'reka-ui'

import { providePropertySection } from '#vue/primitives/PropertySection/context'
import type {
  PropertySectionActionAPI,
  PropertySectionRootProps,
  PropertySectionRootSlots,
  PropertySectionSlotProps,
  PropertySectionStateAttrs
} from '#vue/primitives/PropertySection/types'

const {
  open: openProp,
  defaultOpen = true,
  empty: emptyProp = false,
  disabled: disabledProp = false,
  unmountOnHide = false
} = defineProps<PropertySectionRootProps>()

const emit = defineEmits<{
  'update:open': [open: boolean]
}>()
defineSlots<PropertySectionRootSlots>()
defineOptions({ inheritAttrs: false })

const vnodeProps = getCurrentInstance()?.vnode.props
const controlled = vnodeProps ? Object.hasOwn(vnodeProps, 'open') : false
const uncontrolledOpen = ref(defaultOpen)
const open = computed({
  get: () => (controlled ? openProp : uncontrolledOpen.value),
  set: (value: boolean) => {
    if (!controlled) uncontrolledOpen.value = value
    emit('update:open', value)
  }
})
const empty = computed(() => emptyProp)
const disabled = computed(() => disabledProp)
const stateAttrs = computed<PropertySectionStateAttrs>(() => ({
  'data-state': open.value ? 'open' : 'closed',
  'data-empty': empty.value ? '' : undefined,
  'data-disabled': disabled.value ? '' : undefined
}))

const actions: PropertySectionActionAPI = {
  open: () => {
    if (!disabled.value) open.value = true
  },
  close: () => {
    if (!disabled.value) open.value = false
  },
  toggle: () => {
    if (!disabled.value) open.value = !open.value
  }
}
const slotProps = computed<PropertySectionSlotProps>(() => ({
  open: open.value,
  empty: empty.value,
  stateAttrs: stateAttrs.value,
  actions
}))

providePropertySection({ open, empty, disabled, stateAttrs, slotProps, actions })
</script>

<template>
  <CollapsibleRoot
    v-bind="{ ...$attrs, ...stateAttrs }"
    :open="open"
    :disabled="disabled"
    :unmount-on-hide="unmountOnHide"
    @update:open="open = $event"
  >
    <slot v-bind="slotProps" />
  </CollapsibleRoot>
</template>
