// packages/react/src/primitives/ColorPicker/ColorPickerRoot.tsx
import { useMemo, type ReactNode } from 'react'
import * as Popover from '@radix-ui/react-popover'
import { colorToCSS } from '@open-pencil/core/color'

import type { Color } from '@open-pencil/scene-graph/primitives'

export interface ColorPickerUI {
  content?: string
  swatch?: string
}

interface ColorPickerRootProps {
  color: Color
  ui?: ColorPickerUI
  onUpdate?: (color: Color) => void
  children?: ReactNode | ((props: { color: Color }) => ReactNode)
  trigger?: ReactNode | ((props: { style: { background: string } }) => ReactNode)
}

export function ColorPickerRoot({ color, ui, onUpdate: _onUpdate, children, trigger }: ColorPickerRootProps) {
  const swatchBg = useMemo(() => colorToCSS(color), [color])

  const triggerContent =
    typeof trigger === 'function'
      ? trigger({ style: { background: swatchBg } })
      : (trigger ?? (
          <button
            data-test-id="color-picker-swatch"
            className={ui?.swatch}
            style={{ background: swatchBg }}
          />
        ))

  const pickerContent = typeof children === 'function' ? children({ color }) : children

  return (
    <Popover.Root>
      <Popover.Trigger asChild>{triggerContent}</Popover.Trigger>
      <Popover.Portal>
        <Popover.Content
          data-test-id="color-picker-popover"
          className={ui?.content}
          sideOffset={4}
          side="left"
        >
          {pickerContent}
        </Popover.Content>
      </Popover.Portal>
    </Popover.Root>
  )
}

// packages/vue/src/primitives/ColorPicker/ColorPickerRoot.vue
<script setup lang="ts">
import { computed } from 'vue'
import { PopoverContent, PopoverPortal, PopoverRoot, PopoverTrigger } from 'reka-ui'
import { colorToCSS } from '@open-pencil/core/color'

import type { Color } from '@open-pencil/scene-graph/primitives'

export interface ColorPickerUI {
  content?: string
  swatch?: string
}

const { color, ui } = defineProps<{
  color: Color
  ui?: ColorPickerUI
}>()

const emit = defineEmits<{ update: [color: Color] }>()

const swatchBg = computed(() => colorToCSS(color))
</script>

<template>
  <PopoverRoot>
    <PopoverTrigger as-child>
      <slot name="trigger" :style="{ background: swatchBg }">
        <button
          data-test-id="color-picker-swatch"
          :class="ui?.swatch"
          :style="{ background: swatchBg }"
        />
      </slot>
    </PopoverTrigger>

    <PopoverPortal>
      <PopoverContent
        data-test-id="color-picker-popover"
        :class="ui?.content"
        :side-offset="4"
        side="left"
      >
        <slot :color="color" />
      </PopoverContent>
    </PopoverPortal>
  </PopoverRoot>
</template>
