// packages/react/src/components/MobileHud/MobileActionToast.tsx
import { useMobileHudContext } from '#react/components/MobileHud/context'

export function MobileActionToast() {
  const hud = useMobileHudContext()
  if (!hud.actionToast) return null
  return (
    <div className="flex h-8 items-center rounded-full border border-accent/20 bg-panel/70 px-3 shadow-md backdrop-blur-xl">
      <span className="text-xs whitespace-nowrap text-accent">{hud.actionToast}</span>
    </div>
  )
}

// src/components/MobileHud/MobileActionToast.vue
<script setup lang="ts">
import { useMobileHudContext } from '@/components/MobileHud/context'
import { feedbackTransition } from '@/theme/motion/styles'

const hud = useMobileHudContext()
</script>

<template>
  <Transition v-bind="feedbackTransition">
    <div
      v-if="hud.actionToast"
      :key="hud.actionToast"
      class="flex h-8 items-center rounded-full border border-accent/20 bg-panel/70 px-3 shadow-md backdrop-blur-xl"
    >
      <span class="text-xs whitespace-nowrap text-primary">{{ hud.actionToast }}</span>
    </div>
  </Transition>
</template>
