// src/components/CollabPanel/CollabSharePopover.tsx
<script setup lang="ts">
import { computed } from 'vue'
import { tv } from 'tailwind-variants'
import { PopoverContent, PopoverPortal, PopoverRoot, PopoverTrigger } from 'reka-ui'

import ConnectedRoom from '@/components/CollabPanel/ConnectedRoom.vue'
import JoinRoomPrompt from '@/components/CollabPanel/JoinRoomPrompt.vue'
import ShareOrJoinRoom from '@/components/CollabPanel/ShareOrJoinRoom.vue'
import { useCollabPanelContext } from '@/components/CollabPanel/context'
import { usePopoverUI } from '@/components/ui/popover'
import collaborationTheme from '@/theme/collaboration'

const collab = useCollabPanelContext()
const cls = usePopoverUI({ content: 'z-50 w-72 p-3' })
const connection = computed(() => {
  if (collab.state.connected) return 'connected'
  if (collab.isJoining) return 'joining'
  return 'idle'
})
const collaboration = tv(collaborationTheme)
const styles = computed(() => collaboration({ connection: connection.value }))
</script>

<template>
  <PopoverRoot v-model:open="collab.popoverOpen">
    <PopoverTrigger as-child>
      <button
        data-test-id="collab-share-button"
        :data-connection="connection"
        :class="styles.shareButton()"
      >
        <icon-lucide-share-2 class="size-3.5" />
        {{
          collab.state.connected
            ? collab.dialogs.connected
            : collab.isJoining
              ? collab.dialogs.joinRoom
              : collab.dialogs.share
        }}
      </button>
    </PopoverTrigger>

    <PopoverPortal>
      <PopoverContent
        data-test-id="collab-popover"
        :class="cls.content"
        :side-offset="8"
        side="bottom"
        align="end"
      >
        <ConnectedRoom v-if="collab.state.connected" />
        <JoinRoomPrompt v-else-if="collab.isJoining" />
        <ShareOrJoinRoom v-else />
      </PopoverContent>
    </PopoverPortal>
  </PopoverRoot>
</template>

// packages/react/src/components/CollabPanel/CollabSharePopover.tsx
import { Share2 } from 'lucide-react'
import { tv } from 'tailwind-variants'

import { useCollabPanelContext } from '#react/components/CollabPanel/context'
import { usePopoverUI } from '#react/components/ui/popover'
import collaborationTheme from '#react/theme/collaboration'

export function CollabSharePopover() {
  const collab = useCollabPanelContext()
  const cls = usePopoverUI({ content: 'z-50 w-72 p-3' })
  const connection = collab.state.connected ? 'connected' : collab.isJoining ? 'joining' : 'idle'
  const styles = tv(collaborationTheme)({ connection })
  const label = collab.state.connected
    ? collab.dialogs.connected
    : collab.isJoining
      ? collab.dialogs.joinRoom
      : collab.dialogs.share

  return (
    <div className="relative">
      <button
        type="button"
        data-test-id="collab-share-button"
        data-connection={connection}
        className={styles.shareButton()}
        onClick={() => collab.setPopoverOpen(!collab.popoverOpen)}
      >
        <Share2 className="size-3.5" />
        {label}
      </button>
      {collab.popoverOpen ? (
        <div data-test-id="collab-popover" className={`absolute right-0 z-20 mt-2 ${cls.content}`}>
          <p className="text-[11px] text-muted">{collab.dialogs.share}</p>
        </div>
      ) : null}
    </div>
  )
}
