// packages/react/src/components/properties/component-properties/ComponentPropertiesSection.tsx
import { ComponentPropertyTextField } from '#react/components/properties/component-properties/ComponentPropertyTextField'
import { AppSelect } from '#react/components/ui/AppSelect'
import { AppSwitch } from '#react/components/ui/AppSwitch'
import { PanelFieldGroup } from '#react/components/ui/panel/PanelFieldGroup'
import { PanelSection } from '#react/components/ui/panel/PanelSection'
import { useComponentProperties } from '#react/controls/component-props'
import { MIXED } from '#react/controls/mixed'
import { useI18n } from '#react/i18n'

export function ComponentPropertiesSection() {
  const { active, controls, setValue } = useComponentProperties()
  const { panels } = useI18n()
  if (!active) return null

  const sectionLabel = controls.every((control) => control.type === 'VARIANT')
    ? panels.variants
    : panels.componentProperties

  return (
    <PanelSection label={sectionLabel} titleClass="text-component">
      <div className="flex flex-col gap-1.5">
        {controls.map((control) => {
          const selectOptions =
            control.value === MIXED
              ? [{ value: 'MIXED', label: panels.mixed }, ...control.options]
              : control.options
          const selectValue = control.value === MIXED ? 'MIXED' : control.value
          return (
            <PanelFieldGroup key={control.id} label={control.name}>
              {control.type === 'TEXT' ? (
                <ComponentPropertyTextField
                  label={control.name}
                  value={control.value === MIXED ? '' : control.value}
                  propertyId={control.id}
                  mixed={control.value === MIXED}
                  mixedPlaceholder={panels.mixed}
                  onCommit={(value) => setValue(control.id, value)}
                />
              ) : null}
              {control.type === 'BOOLEAN' ? (
                <div className="flex h-6 items-center">
                  <AppSwitch
                    checked={control.value !== MIXED && control.value === 'true'}
                    label={control.name}
                    state={control.value === MIXED ? 'mixed' : 'idle'}
                    data-property={control.id}
                    onCheckedChange={(checked) => setValue(control.id, String(checked))}
                  />
                </div>
              ) : null}
              {control.type !== 'TEXT' && control.type !== 'BOOLEAN' ? (
                <AppSelect
                  label={control.name}
                  data-property={control.id}
                  value={selectValue}
                  options={selectOptions}
                  onChange={(value) => {
                    if (value !== 'MIXED') setValue(control.id, value)
                  }}
                />
              ) : null}
            </PanelFieldGroup>
          )
        })}
      </div>
    </PanelSection>
  )
}

// src/components/properties/component-properties/ComponentPropertiesSection.tsx
<script setup lang="ts">
import { computed } from 'vue'

import { MIXED, useComponentProperties, useI18n } from '@open-pencil/vue'

import ComponentPropertyTextField from './ComponentPropertyTextField.vue'

import AppSelect from '@/components/ui/AppSelect.vue'
import AppSwitch from '@/components/ui/AppSwitch.vue'
import PanelFieldGroup from '@/components/ui/panel/PanelFieldGroup.vue'
import PanelSection from '@/components/ui/panel/PanelSection.vue'

const { active, controls, setValue } = useComponentProperties()
const { panels } = useI18n()
const componentSectionUI = { title: 'text-component' }

function selectOptions(control: (typeof controls.value)[number]) {
  return control.value === MIXED
    ? [{ value: 'MIXED', label: panels.value.mixed }, ...control.options]
    : control.options
}

function selectValue(control: (typeof controls.value)[number]) {
  return control.value === MIXED ? 'MIXED' : control.value
}

function updateSelect(propertyId: string, value: string) {
  if (value !== 'MIXED') setValue(propertyId, value)
}

function booleanValue(control: (typeof controls.value)[number]) {
  return control.value !== MIXED && control.value === 'true'
}

const sectionLabel = computed(() =>
  controls.value.every((control) => control.type === 'VARIANT')
    ? panels.value.variants
    : panels.value.componentProperties
)
</script>

<template>
  <PanelSection v-if="active" :label="sectionLabel" :ui="componentSectionUI">
    <div class="flex flex-col gap-1.5">
      <PanelFieldGroup v-for="control in controls" :key="control.id" :label="control.name">
        <ComponentPropertyTextField
          v-if="control.type === 'TEXT'"
          :value="control.value"
          :label="control.name"
          :data-property="control.id"
          @commit="setValue(control.id, $event)"
        />
        <div v-else-if="control.type === 'BOOLEAN'" class="flex h-field items-center">
          <AppSwitch
            :model-value="booleanValue(control)"
            :label="control.name"
            :state="control.value === MIXED ? 'mixed' : 'idle'"
            :data-property="control.id"
            @update:model-value="setValue(control.id, String($event))"
          />
        </div>
        <AppSelect
          v-else
          :label="control.name"
          :model-value="selectValue(control)"
          :options="selectOptions(control)"
          :data-property="control.id"
          @update:model-value="updateSelect(control.id, $event)"
        />
      </PanelFieldGroup>
    </div>
  </PanelSection>
</template>
