// src/components/canvas/CanvasMenu.vue
<script setup lang="ts">
import {
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuSeparator,
  ContextMenuSub,
  ContextMenuSubTrigger,
  ContextMenuSubContent,
  ContextMenuPortal
} from 'reka-ui'
import { computed, type Component } from 'vue'
import IconChevronRight from '~icons/lucide/chevron-right'
import IconCombine from '~icons/lucide/combine'
import IconCopyMinus from '~icons/lucide/copy-minus'
import IconCopyX from '~icons/lucide/copy-x'
import IconListCollapse from '~icons/lucide/list-collapse'
import IconSpline from '~icons/lucide/spline'
import IconSquaresIntersect from '~icons/lucide/squares-intersect'
import IconTypeOutline from '~icons/lucide/type-outline'

import {
  vTestId,
  useEditorCommands,
  useI18n,
  useMenuModel,
  useSelectionState,
  editorCommandMetadata,
  formatShortcut
} from '@open-pencil/vue'
import type { EditorCommandId } from '@open-pencil/vue'

import { useEditorStore } from '@/app/editor/active-store'
import { createCanvasMenuActions } from '@/app/editor/canvas/menu/actions'
import { useCanvasContextMenu } from '@/app/editor/canvas/menu/context'
import { canvasMenuItemClass, canvasMenuShortcutClass } from '@/app/editor/canvas/menu/model'
import { appMenuShortcutLabel } from '@/app/shell/menu/shortcut'
import AppShortcutText from '@/components/ui/menu/AppShortcutText.vue'
import { menu, useMenuUI } from '@/components/ui/menu/menu'

const store = useEditorStore()

const { editor, selectedIds, hasSelection } = useSelectionState()
const { getCommand } = useEditorCommands()
const { canvasMenu } = useMenuModel()
const { menu: t } = useI18n()

const canvasMenuActions = createCanvasMenuActions(store, selectedIds)
const { execCommand } = canvasMenuActions
const contextMenu = useCanvasContextMenu(canvasMenu, hasSelection, editor, canvasMenuActions, t)

const selectedGuide = computed(() => store.state.guides.selected)

function removeSelectedGuide() {
  const guide = selectedGuide.value
  if (!guide) return
  store.removeGuide(guide.ownerId, guide.guideId)
  store.setSelectedGuide(null)
}

const menuCls = useMenuUI({
  content: 'min-w-56 shadow-[0_8px_30px_rgb(0_0_0/0.4)] animate-in fade-in zoom-in-95',
  separator: 'my-1'
})
const componentMenu = menu({ tone: 'component' })

const cls = {
  menu: menuCls.content,
  submenu: menuCls.content.replace('min-w-56', 'min-w-0 w-max'),
  item: menuCls.item,
  component: componentMenu.item(),
  sep: menuCls.separator
}

const booleanCommandIcons = {
  'selection.booleanUnion': IconCombine,
  'selection.booleanSubtract': IconCopyMinus,
  'selection.booleanIntersect': IconSquaresIntersect,
  'selection.booleanExclude': IconCopyX,
  'selection.flatten': IconListCollapse,
  'selection.outlineText': IconTypeOutline,
  'selection.outlineStroke': IconSpline
} satisfies Partial<Record<EditorCommandId, Component>>

function contextCommandTestId(id: EditorCommandId | undefined): string | undefined {
  return id ? editorCommandMetadata(id).contextTestId : undefined
}

function contextCommandIcon(id: EditorCommandId | undefined): Component | undefined {
  if (!id) return undefined
  return (booleanCommandIcons as Partial<Record<EditorCommandId, Component>>)[id]
}
</script>

<template>
  <ContextMenuContent :class="cls.menu" :side-offset="2" align="start">
    <template v-if="selectedGuide">
      <ContextMenuItem data-property="guide" :class="cls.item" @select="removeSelectedGuide">
        <span>{{ t.removeGuide }}</span>
      </ContextMenuItem>
    </template>
    <template v-else>
      <ContextMenuItem
        data-test-id="context-copy"
        :class="cls.item"
        :disabled="!hasSelection"
        @select="execCommand('copy')"
      >
        <span>{{ t.copy }}</span
        ><AppShortcutText>{{ appMenuShortcutLabel('copy') }}</AppShortcutText>
      </ContextMenuItem>
      <ContextMenuItem
        data-test-id="context-cut"
        :class="cls.item"
        :disabled="!hasSelection"
        @select="execCommand('cut')"
      >
        <span>{{ t.cut }}</span
        ><AppShortcutText>{{ appMenuShortcutLabel('cut') }}</AppShortcutText>
      </ContextMenuItem>
      <ContextMenuItem
        data-test-id="context-paste"
        :class="cls.item"
        @select="execCommand('paste')"
      >
        <span>{{ t.pasteHere }}</span
        ><AppShortcutText>{{ appMenuShortcutLabel('paste') }}</AppShortcutText>
      </ContextMenuItem>
      <ContextMenuItem
        data-test-id="context-paste-to-replace"
        :class="cls.item"
        :disabled="!hasSelection"
        @select="canvasMenuActions.pasteToReplace"
      >
        <span>{{ t.pasteToReplace }}</span>
      </ContextMenuItem>
      <ContextMenuItem
        data-test-id="context-duplicate"
        :class="cls.item"
        :disabled="!hasSelection"
        @select="getCommand('selection.duplicate').run()"
      >
        <span>{{ getCommand('selection.duplicate').label }}</span
        ><AppShortcutText>{{
          formatShortcut(editorCommandMetadata('selection.duplicate').shortcut)
        }}</AppShortcutText>
      </ContextMenuItem>
      <ContextMenuItem
        data-test-id="context-delete"
        :class="cls.item"
        :disabled="!hasSelection"
        @select="getCommand('selection.delete').run()"
      >
        <span>{{ getCommand('selection.delete').label }}</span
        ><AppShortcutText>{{ editorCommandMetadata('selection.delete').shortcut }}</AppShortcutText>
      </ContextMenuItem>

      <template v-for="(item, i) in contextMenu" :key="`menu-${i}`">
        <ContextMenuSeparator v-if="item.separator" :class="cls.sep" />
        <ContextMenuSub v-else-if="item.sub">
          <ContextMenuSubTrigger v-test-id="item.testId" :class="cls.item">
            <span>{{ item.label }}</span>
            <IconChevronRight class="size-3.5 text-muted" />
          </ContextMenuSubTrigger>
          <ContextMenuPortal>
            <ContextMenuSubContent :class="cls.submenu">
              <ContextMenuItem
                v-for="(sub, j) in item.sub"
                :key="j"
                :class="cls.item"
                v-test-id="sub.separator ? undefined : sub.testId"
                :disabled="sub.separator ? true : sub.disabled"
                @select="!sub.separator && sub.action?.()"
              >
                <template v-if="!sub.separator">
                  <span class="flex min-w-0 flex-1 items-center gap-2">
                    <component
                      :is="contextCommandIcon(sub.id)"
                      v-if="contextCommandIcon(sub.id)"
                      class="size-3.5 shrink-0 text-muted"
                    />
                    <span class="truncate">{{ sub.label }}</span>
                  </span>
                  <AppShortcutText v-if="sub.shortcut">{{ sub.shortcut }}</AppShortcutText>
                </template>
              </ContextMenuItem>
            </ContextMenuSubContent>
          </ContextMenuPortal>
        </ContextMenuSub>
        <ContextMenuItem
          v-else
          v-test-id="item.testId ?? contextCommandTestId(item.id)"
          :class="canvasMenuItemClass(item.label, cls)"
          :disabled="item.disabled"
          @select="item.action?.()"
        >
          <span class="flex min-w-0 flex-1 items-center gap-2">
            <component
              :is="contextCommandIcon(item.id)"
              v-if="contextCommandIcon(item.id)"
              class="size-3.5 shrink-0 text-muted"
            />
            <span class="truncate">{{ item.label }}</span>
          </span>
          <span
            v-if="item.shortcut"
            class="text-[11px]"
            :class="canvasMenuShortcutClass(item.label)"
            >{{ item.shortcut }}</span
          >
        </ContextMenuItem>
      </template>
    </template>
  </ContextMenuContent>
</template>

// packages/react/src/components/canvas/CanvasMenu.tsx
import { useEffect, useState } from 'react'
import { createPortal } from 'react-dom'
import { ChevronRight } from 'lucide-react'

import { IS_BROWSER } from '@open-pencil/core/constants'

import { createCanvasMenuActions } from '#react/app/editor/canvas/menu/actions'
import { buildCanvasContextMenuEntries } from '#react/app/editor/canvas/menu/context'
import { canvasMenuItemClass, canvasMenuShortcutClass } from '#react/app/editor/canvas/menu/model'
import { useEditorStore } from '#react/app/editor/store'
import { appMenuShortcutLabel } from '#react/app/shell/menu/shortcut'
import { AppShortcutText } from '#react/components/ui/AppShortcutText'
import { menu, useMenuUI } from '#react/components/ui/menu'
import { editorCommandMetadata, formatShortcut, useEditorCommands } from '#react/editor/commands'
import { useMenuModel } from '#react/editor/menu-model/use'
import type { MenuEntry } from '#react/editor/menu-model/types'
import { useSelectionState } from '#react/editor/selection-state/use'
import { useI18n } from '#react/i18n'

export function CanvasMenu({
  x,
  y,
  onClose
}: {
  x: number
  y: number
  onClose: () => void
}) {
  const store = useEditorStore()
  const { editor, selectedIds, hasSelection } = useSelectionState()
  const { getCommand } = useEditorCommands()
  const { canvasMenu } = useMenuModel()
  const { menu: t } = useI18n()
  const actions = createCanvasMenuActions(store, selectedIds)
  const selectedGuide = store.state.guides.selected
  const entries = buildCanvasContextMenuEntries(canvasMenu, hasSelection, editor, actions, t)
  const menuCls = useMenuUI({
    content: 'min-w-56 shadow-[0_8px_30px_rgb(0_0_0/0.4)] animate-in fade-in zoom-in-95',
    separator: 'my-1'
  })
  const componentMenu = menu({ tone: 'component' })
  const cls = {
    item: menuCls.item,
    component: componentMenu.item(),
    sep: menuCls.separator
  }
  const duplicate = getCommand('selection.duplicate')
  const remove = getCommand('selection.delete')
  const left = IS_BROWSER ? Math.min(x, window.innerWidth - 240) : x
  const top = IS_BROWSER ? Math.min(y, window.innerHeight - 320) : y

  useEffect(() => {
    function onKey(event: KeyboardEvent) {
      if (event.key === 'Escape') onClose()
    }
    function onPointerDown(event: PointerEvent) {
      const target = event.target
      if (target instanceof Element && target.closest('[data-slot=canvas-context-menu]')) return
      onClose()
    }
    window.addEventListener('keydown', onKey)
    window.addEventListener('pointerdown', onPointerDown, true)
    return () => {
      window.removeEventListener('keydown', onKey)
      window.removeEventListener('pointerdown', onPointerDown, true)
    }
  }, [onClose])

  function removeSelectedGuide() {
    if (!selectedGuide) return
    store.removeGuide(selectedGuide.ownerId, selectedGuide.guideId)
    store.setSelectedGuide(null)
    onClose()
  }

  function run(action?: () => void) {
    action?.()
    onClose()
  }

  const menuNode = (
    <div
      data-slot="canvas-context-menu"
      className={`fixed z-50 ${menuCls.content}`}
      style={{ left, top }}
      role="menu"
      onContextMenu={(event) => event.preventDefault()}
    >
      {selectedGuide ? (
        <MenuRow
          className={cls.item}
          label={t.removeGuide}
          property="guide"
          onClick={removeSelectedGuide}
        />
      ) : (
        <>
          <MenuRow
            testId="context-copy"
            className={cls.item}
            disabled={!hasSelection}
            label={t.copy}
            shortcut={appMenuShortcutLabel('copy')}
            onClick={() => run(() => actions.execCommand('copy'))}
          />
          <MenuRow
            testId="context-cut"
            className={cls.item}
            disabled={!hasSelection}
            label={t.cut}
            shortcut={appMenuShortcutLabel('cut')}
            onClick={() => run(() => actions.execCommand('cut'))}
          />
          <MenuRow
            testId="context-paste"
            className={cls.item}
            label={t.pasteHere}
            shortcut={appMenuShortcutLabel('paste')}
            onClick={() => run(() => actions.execCommand('paste'))}
          />
          <MenuRow
            testId="context-paste-to-replace"
            className={cls.item}
            disabled={!hasSelection}
            label={t.pasteToReplace}
            onClick={() => run(actions.pasteToReplace)}
          />
          <MenuRow
            testId="context-duplicate"
            className={cls.item}
            disabled={!hasSelection}
            label={duplicate.label}
            shortcut={formatShortcut(editorCommandMetadata('selection.duplicate').shortcut)}
            onClick={() => run(() => duplicate.run())}
          />
          <MenuRow
            testId="context-delete"
            className={cls.item}
            disabled={!hasSelection}
            label={remove.label}
            shortcut={editorCommandMetadata('selection.delete').shortcut}
            onClick={() => run(() => remove.run())}
          />
          {entries.map((item, index) => (
            <CanvasMenuEntry key={`menu-${index}`} item={item} cls={cls} onRun={run} />
          ))}
        </>
      )}
    </div>
  )

  if (!IS_BROWSER) return menuNode
  return createPortal(menuNode, document.body)
}

function MenuRow({
  testId,
  className,
  disabled,
  label,
  shortcut,
  property,
  onClick
}: {
  testId?: string
  className: string
  disabled?: boolean
  label: string
  shortcut?: string
  property?: string
  onClick: () => void
}) {
  return (
    <button
      type="button"
      data-test-id={testId}
      data-property={property}
      className={className}
      disabled={disabled}
      data-disabled={disabled ? '' : undefined}
      onClick={onClick}
    >
      <span>{label}</span>
      {shortcut ? <AppShortcutText>{shortcut}</AppShortcutText> : null}
    </button>
  )
}

function CanvasMenuEntry({
  item,
  cls,
  onRun
}: {
  item: MenuEntry
  cls: { item: string; component: string; sep: string }
  onRun: (action?: () => void) => void
}) {
  const [open, setOpen] = useState(false)
  if (item.separator) return <div className={cls.sep} />
  if (item.sub) {
    return (
      <div className="relative" onMouseEnter={() => setOpen(true)} onMouseLeave={() => setOpen(false)}>
        <button type="button" data-test-id={item.testId} className={cls.item}>
          <span>{item.label}</span>
          <ChevronRight className="size-3.5 text-muted" />
        </button>
        {open ? (
          <div className="absolute top-0 left-full z-10 min-w-44 rounded-xl bg-panel p-1 shadow-[0_8px_30px_rgb(0_0_0/0.4)]">
            {item.sub.map((sub, index) =>
              sub.separator ? (
                <div key={index} className={cls.sep} />
              ) : (
                <button
                  key={index}
                  type="button"
                  data-test-id={sub.testId}
                  className={cls.item}
                  disabled={sub.disabled}
                  data-disabled={sub.disabled ? '' : undefined}
                  onClick={() => onRun(sub.action)}
                >
                  <span className="truncate">{sub.label}</span>
                  {sub.shortcut ? <AppShortcutText>{sub.shortcut}</AppShortcutText> : null}
                </button>
              )
            )}
          </div>
        ) : null}
      </div>
    )
  }
  return (
    <button
      type="button"
      data-test-id={item.testId ?? (item.id ? editorCommandMetadata(item.id).contextTestId : undefined)}
      className={canvasMenuItemClass(item.label, cls)}
      disabled={item.disabled}
      data-disabled={item.disabled ? '' : undefined}
      onClick={() => onRun(item.action)}
    >
      <span className="truncate">{item.label}</span>
      {item.shortcut ? (
        <span className={`text-[11px] ${canvasMenuShortcutClass(item.label)}`}>{item.shortcut}</span>
      ) : null}
    </button>
  )
}
