// packages/vue/src/primitives/PageList/PageListRoot.vue
<script setup lang="ts">
import { computed } from 'vue'

import { isPageDivider, PAGE_DIVIDER_PATTERN } from '#vue/primitives/PageList/divider'
import { usePageList } from '#vue/primitives/PageList/usePageList'

const { dividerPattern: customDividerPattern } = defineProps<{
  dividerPattern?: RegExp
}>()

const emit = defineEmits<{
  add: []
  switch: [pageId: string]
  rename: [pageId: string, name: string]
  delete: [pageId: string]
  move: [pageId: string, index: number]
}>()

const { pages, currentPageId, switchPage, addPage, renamePage, deletePage, movePage } =
  usePageList()

const dividerPattern = computed(() => customDividerPattern ?? PAGE_DIVIDER_PATTERN)

function isDivider(page: { name: string; childIds: string[] }) {
  return isPageDivider(page, dividerPattern.value)
}

function handleAdd() {
  addPage()
  emit('add')
}

function handleSwitch(pageId: string) {
  switchPage(pageId)
  emit('switch', pageId)
}

function handleRename(pageId: string, name: string) {
  renamePage(pageId, name)
  emit('rename', pageId, name)
}

function handleDelete(pageId: string) {
  deletePage(pageId)
  emit('delete', pageId)
}

function handleMove(pageId: string, index: number) {
  movePage(pageId, index)
  emit('move', pageId, index)
}

const actions = {
  add: handleAdd,
  switch: handleSwitch,
  rename: handleRename,
  delete: handleDelete,
  move: handleMove
}
</script>

<template>
  <slot
    :pages="pages"
    :current-page-id="currentPageId"
    :is-divider="isDivider"
    :actions="actions"
  />
</template>

// packages/react/src/primitives/PageList/PageListRoot.tsx
import { type ReactNode } from 'react'
import type { SceneNode } from '@open-pencil/scene-graph'

import { usePageList } from '#react/primitives/PageList/usePageList'

interface PageListActions {
  add: () => void
  switch: (pageId: string) => void
  rename: (pageId: string, name: string) => void
  delete: (pageId: string) => void
  move: (pageId: string, index: number) => void
}

interface PageListRootSlotProps {
  pages: SceneNode[]
  currentPageId: string
  isDivider: (page: { name: string; childIds: string[] }) => boolean
  actions: PageListActions
}

interface PageListRootProps {
  dividerPattern?: RegExp
  onAdd?: () => void
  onSwitch?: (pageId: string) => void
  onRename?: (pageId: string, name: string) => void
  onDelete?: (pageId: string) => void
  onMove?: (pageId: string, index: number) => void
  children?: ReactNode | ((props: PageListRootSlotProps) => ReactNode)
}

export function PageListRoot({
  dividerPattern: customDividerPattern,
  onAdd,
  onSwitch,
  onRename,
  onDelete,
  onMove,
  children
}: PageListRootProps) {
  const { pages, currentPageId, switchPage, addPage, renamePage, deletePage, movePage } =
    usePageList()

  const dividerPattern = customDividerPattern ?? /^[-–—*\s]+$/

  function isDivider(page: { name: string; childIds: string[] }) {
    return page.childIds.length === 0 && dividerPattern.test(page.name)
  }

  const actions: PageListActions = {
    add: () => {
      addPage()
      onAdd?.()
    },
    switch: (pageId: string) => {
      void switchPage(pageId)
      onSwitch?.(pageId)
    },
    rename: (pageId: string, name: string) => {
      renamePage(pageId, name)
      onRename?.(pageId, name)
    },
    delete: (pageId: string) => {
      deletePage(pageId)
      onDelete?.(pageId)
    },
    move: (pageId: string, index: number) => {
      movePage(pageId, index)
      onMove?.(pageId, index)
    }
  }

  const slotProps: PageListRootSlotProps = {
    pages,
    currentPageId: currentPageId.value,
    isDivider,
    actions
  }

  return typeof children === 'function' ? <>{children(slotProps)}</> : <>{children}</>
}
