// packages/react/src/components/assets-panel/AssetRemoteThumbnail.tsx
import { Component } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'

import { useEditorStore } from '#react/app/editor/store'
import { getLib } from '#react/graph/remote-lib'
import { renderAssetPreview } from '#react/components/assets-panel/assets'
import { ASSET_GRID_THUMBNAIL_SIZE, ASSET_THUMBNAIL_RENDER_SCALE } from '#react/constants'

export function AssetRemoteThumbnail({
  nodeId,
  alt,
  remoteKey,
  size
}: {
  nodeId: string
  alt: string
  remoteKey: string
  size: number
}) {
  const store = useEditorStore()
  const rootRef = useRef<HTMLDivElement>(null)
  const [visible, setVisible] = useState(false)
  const [previewURL, setPreviewURL] = useState<string | null>(null)
  const isGridThumbnail = size === ASSET_GRID_THUMBNAIL_SIZE

  useEffect(() => {
    const root = rootRef.current
    if (!root) return
    const observer = new IntersectionObserver(([entry]) => {
      setVisible(Boolean(entry?.isIntersecting))
    })
    observer.observe(root)
    return () => observer.disconnect()
  }, [])

  useEffect(() => {
    if (!visible) return
    const graph = getLib(store.graph, remoteKey)?.graph
    const node = graph?.getNode(nodeId)
    if (!graph || !node) {
      setPreviewURL(null)
      return
    }
    let cancelled = false
    let objectURL: string | null = null
    const pageId = graph.getPages()[0]?.id
    const maxDimension = Math.max(node.width, node.height, 1)
    const scale = (size * ASSET_THUMBNAIL_RENDER_SCALE) / maxDimension
    void renderAssetPreview(store, nodeId, scale, pageId, graph).then((blob) => {
      if (cancelled) return
      if (!blob) {
        setPreviewURL(null)
        return
      }
      objectURL = URL.createObjectURL(blob)
      setPreviewURL(objectURL)
    })
    return () => {
      cancelled = true
      if (objectURL) URL.revokeObjectURL(objectURL)
    }
  }, [nodeId, remoteKey, size, store, visible])

  return (
    <div
      ref={rootRef}
      data-slot="asset-thumbnail"
      className={`flex shrink-0 items-center justify-center overflow-hidden rounded bg-canvas/60 ${
        isGridThumbnail ? 'size-24' : 'size-10'
      }`}
    >
      {previewURL ? (
        <img src={previewURL} alt={alt} className="max-h-full max-w-full object-contain" draggable={false} />
      ) : (
        <Component className="size-4 text-component" aria-hidden="true" />
      )}
    </div>
  )
}

// src/components/assets-panel/AssetRemoteThumbnail.vue
<script setup lang="ts">
import { useElementVisibility, useObjectUrl } from '@vueuse/core'
import { computed, shallowRef, useTemplateRef, watch } from 'vue'

import { useEditorStore } from '@/app/editor/active-store'
import { ASSET_GRID_THUMBNAIL_SIZE, ASSET_THUMBNAIL_RENDER_SCALE } from '@/constants'
import { renderRemoteExportImage } from '@/app/document/export/files.ts'

const { nodeId, alt, remoteKey, size } = defineProps<{
  nodeId: string
  alt: string
  remoteKey: string
  size: number
}>()

const editor = useEditorStore()
const isGridThumbnail = computed(() => size === ASSET_GRID_THUMBNAIL_SIZE)
const thumbnail = useTemplateRef<HTMLElement>('thumbnail')
const isVisible = useElementVisibility(thumbnail)
const previewBlob = shallowRef<Blob | null>(null)
const previewUrl = useObjectUrl(previewBlob)
let requestId = 0

async function updatePreview() {
  const currentRequest = ++requestId
  const lib = editor.graph.getLib(remoteKey)
  const graph = lib?.graph

  const node = graph?.getNode(nodeId)
  if (!node || !graph) {
    previewBlob.value = null
    return
  }
  const pageId = graph?.getPages()[0]?.id
  const maxDimension = Math.max(node.width, node.height, 1)
  const scale = (size * ASSET_THUMBNAIL_RENDER_SCALE) / maxDimension
  try {
    const data = await renderRemoteExportImage(editor, graph, [nodeId], pageId, scale, 'PNG')
    if (currentRequest !== requestId) return
    previewBlob.value = data ? new Blob([data], { type: 'image/png' }) : null
  } catch {
    if (currentRequest === requestId) previewBlob.value = null
  }
}

watch(
  () => [nodeId, size, remoteKey, isVisible.value],
  ([, , , visible]) => {
    if (visible) void updatePreview()
  },
  { immediate: true, flush: 'post' }
)
</script>

<template>
  <div
    ref="thumbnail"
    data-slot="asset-thumbnail"
    :class="[
      'flex shrink-0 items-center justify-center overflow-hidden rounded bg-canvas/60',
      isGridThumbnail ? 'size-24' : 'size-10'
    ]"
  >
    <img
      v-if="previewUrl"
      :src="previewUrl"
      :alt="alt"
      class="max-h-full max-w-full object-contain"
      draggable="false"
    />
    <icon-lucide-component v-else class="size-4 text-component" aria-hidden="true" />
  </div>
</template>
