// packages/vue/src/primitives/NumberField/NumberFieldInput.vue
<script setup lang="ts">
import { computed, watchEffect } from 'vue'
import { templateRef } from '@vueuse/core'

import { useNumberField } from '#vue/primitives/NumberField/context'

const ctx = useNumberField()
const inputEl = templateRef<HTMLInputElement>('inputEl')

const ariaAttrs = computed(() => ({
  role: 'spinbutton' as const,
  'aria-valuenow': ctx.isMixed.value ? undefined : ctx.numericValue.value,
  'aria-valuemin': Number.isFinite(ctx.min.value) ? ctx.min.value : undefined,
  'aria-valuemax': Number.isFinite(ctx.max.value) ? ctx.max.value : undefined,
  'aria-disabled': ctx.disabled.value ? ('true' as const) : undefined,
  'aria-label': ctx.ariaLabel.value
}))

watchEffect(() => {
  ctx.inputRef.value = inputEl.value
})

defineOptions({ inheritAttrs: false })
</script>

<template>
  <input
    v-if="ctx.editing.value"
    ref="inputEl"
    v-bind="{ ...$attrs, ...ctx.stateAttrs.value, ...ariaAttrs }"
    data-slot="input"
    type="text"
    inputmode="decimal"
    autocomplete="off"
    :spellcheck="false"
    :disabled="ctx.disabled.value"
    :value="ctx.draftValue.value"
    @blur="ctx.actions.commitEdit"
    @keydown.stop="ctx.actions.keydown"
    @input="ctx.actions.input"
  />
</template>

// packages/react/src/primitives/NumberField/NumberFieldInput.tsx
import { useNumberField } from '#react/primitives/NumberField/context'

interface NumberFieldInputProps {
  className?: string
  [key: string]: unknown
}

export function NumberFieldInput({ ...attrs }: NumberFieldInputProps) {
  const ctx = useNumberField()
  if (!ctx.editing) return null

  const ariaAttrs = {
    role: 'spinbutton' as const,
    'aria-valuenow': ctx.isMixed ? undefined : ctx.numericValue,
    'aria-valuemin': Number.isFinite(ctx.min) ? ctx.min : undefined,
    'aria-valuemax': Number.isFinite(ctx.max) ? ctx.max : undefined,
    'aria-disabled': ctx.disabled ? ('true' as const) : undefined,
    'aria-label': ctx.ariaLabel
  }

  return (
    <input
      {...attrs}
      {...ctx.stateAttrs}
      {...ariaAttrs}
      ref={ctx.inputRef}
      data-slot="input"
      type="text"
      inputMode="decimal"
      autoComplete="off"
      spellCheck={false}
      disabled={ctx.disabled}
      value={ctx.draftValue}
      onChange={() => {/* controlled via onInput */}}
      onBlur={() => ctx.actions.commitEdit()}
      onKeyDown={(e) => ctx.actions.keydown(e.nativeEvent)}
      onInput={(e) => ctx.actions.input(e.nativeEvent)}
    />
  )
}
