// src/components/chat/ProviderSettings/ProviderSettingsField.tsx
import { memo, type ReactNode } from 'react'

import AppTextButton from '@/components/ui/AppTextButton'

export type ProviderSettingsFieldProps = {
  label: string
  clearLabel?: string
  onClear?: () => void
  children: ReactNode
  hint?: ReactNode
}

export const ProviderSettingsField = memo(function ProviderSettingsField({
  label,
  clearLabel,
  onClear,
  children,
  hint
}: ProviderSettingsFieldProps) {
  return (
    <div className="flex flex-col gap-1">
      <div className="flex items-center justify-between">
        <label className="text-[10px] text-muted">{label}</label>
        {clearLabel && onClear ? (
          <AppTextButton onClick={onClear}>{clearLabel}</AppTextButton>
        ) : null}
      </div>
      {children}
      {hint}
    </div>
  )
})

ProviderSettingsField.displayName = 'ProviderSettingsField'
export default ProviderSettingsField

// src/components/settings/provider/ProviderSettingsField.vue
<script setup lang="ts">
import AppButton from '@/components/ui/button/AppButton.vue'

interface ProviderSettingsFieldProps {
  label: string
  labelFor?: string
  clearLabel?: string
}

defineOptions({ inheritAttrs: false })

const { label, labelFor, clearLabel } = defineProps<ProviderSettingsFieldProps>()

const emit = defineEmits<{ clear: [] }>()
</script>

<template>
  <div class="flex flex-col gap-1">
    <div class="flex items-center justify-between">
      <label :for="labelFor" class="text-[10px] text-muted">{{ label }}</label>
      <AppButton
        v-if="clearLabel"
        color="neutral"
        variant="link"
        size="xs"
        v-bind="$attrs"
        @click="emit('clear')"
      >
        {{ clearLabel }}
      </AppButton>
    </div>
    <slot />
    <slot name="hint" />
  </div>
</template>
