// src/components/chat/ProviderSettings/ProviderSettingsKeyField.tsx
import { useI18n } from '@open-pencil/react'
import { ProviderSettingsField } from '@/components/chat/ProviderSettings/ProviderSettingsField'
import { ProviderSettingsInput } from '@/components/chat/ProviderSettings/ProviderSettingsInput'
import { ProviderSettingsLink } from '@/components/chat/ProviderSettings/ProviderSettingsLink'

interface ProviderSettingsKeyFieldProps {
  label: string
  value: string
  saved: boolean
  kind: 'api' | 'pexels' | 'unsplash'
  placeholder: string
  keyUrl?: string
  keyUrlLabel?: string
  onChange?: (value: string) => void
  onClear?: () => void
}

export function ProviderSettingsKeyField({
  label,
  value,
  saved,
  kind,
  placeholder,
  keyUrl,
  keyUrlLabel,
  onChange,
  onClear
}: ProviderSettingsKeyFieldProps) {
  const { dialogs } = useI18n()

  const inputDataTestId =
    kind === 'pexels' ? 'provider-settings-pexels-key'
    : (kind === 'unsplash' ? 'provider-settings-unsplash-key' : 'provider-settings-api-key')

  const clearDataTestId =
    kind === 'pexels' ? 'provider-settings-clear-pexels-key'
    : (kind === 'unsplash' ? 'provider-settings-clear-unsplash-key' : 'provider-settings-clear-key')

  return (
    <ProviderSettingsField
      label={label}
      clearLabel={saved ? dialogs.clear : undefined}
      data-test-id={clearDataTestId}
      onClear={onClear}
      hint={
        keyUrl && keyUrlLabel ? (
          <ProviderSettingsLink href={keyUrl}>{keyUrlLabel}</ProviderSettingsLink>
        ) : undefined
      }
    >
      <ProviderSettingsInput
        value={value}
        type="password"
        data-test-id={inputDataTestId}
        placeholder={placeholder}
        onChange={(v) => onChange?.(String(v))}
      />
    </ProviderSettingsField>
  )
}

// src/components/settings/provider/ProviderSettingsKeyField.vue
<script setup lang="ts">
import { computed } from 'vue'

import { useI18n } from '@open-pencil/vue'

import ProviderSettingsField from '@/components/settings/provider/ProviderSettingsField.vue'
import ProviderSettingsInput from '@/components/settings/provider/ProviderSettingsInput.vue'
import ProviderSettingsLink from '@/components/settings/provider/ProviderSettingsLink.vue'

const { label, modelValue, saved, kind, placeholder, keyURL, keyURLLabel, inputId } = defineProps<{
  label: string
  modelValue: string
  saved: boolean
  kind: 'api' | 'pexels' | 'unsplash'
  placeholder: string
  inputId?: string
  keyURL?: string
  keyURLLabel?: string
}>()

const emit = defineEmits<{
  'update:modelValue': [value: string]
  change: []
  clear: []
}>()

const { common } = useI18n()

const inputDataTestId = computed(() => {
  if (kind === 'pexels') return 'provider-settings-pexels-key'
  if (kind === 'unsplash') return 'provider-settings-unsplash-key'
  return 'provider-settings-api-key'
})

const clearDataTestId = computed(() => {
  if (kind === 'pexels') return 'provider-settings-clear-pexels-key'
  if (kind === 'unsplash') return 'provider-settings-clear-unsplash-key'
  return 'provider-settings-clear-key'
})
</script>

<template>
  <ProviderSettingsField
    :label="label"
    :label-for="inputId"
    :clear-label="saved ? common.clear : undefined"
    :data-test-id="clearDataTestId"
    @clear="emit('clear')"
  >
    <ProviderSettingsInput
      :model-value="modelValue"
      :id="inputId"
      type="password"
      :data-test-id="inputDataTestId"
      :placeholder="placeholder"
      @update:model-value="emit('update:modelValue', String($event))"
      @change="emit('change')"
    />
    <template #hint>
      <ProviderSettingsLink v-if="keyURL && keyURLLabel" :href="keyURL">
        {{ keyURLLabel }}
      </ProviderSettingsLink>
    </template>
  </ProviderSettingsField>
</template>
