// src/components/ui/binding/BindingTrigger.tsx
import type { ComponentPropsWithoutRef, ReactNode } from 'react'

import type { BindingState } from '@open-pencil/react'
import { useBindingFieldUI, type BindingFieldUI } from '@/components/ui/binding/ui'

import IconLucideDiamond from '~icons/lucide/diamond'
import IconLucideDiamondPlus from '~icons/lucide/diamond-plus'

export interface BindingTriggerProps extends Omit<ComponentPropsWithoutRef<'button'>, 'className'> {
  label: string
  state?: BindingState
  open?: boolean
  disabled?: boolean
  derived?: boolean
  className?: string
  ui?: BindingFieldUI
  children?: ReactNode
}

export function BindingTrigger({
  label,
  state = 'unbound',
  open = false,
  disabled = false,
  derived = false,
  className,
  ui,
  children,
  ...rest
}: BindingTriggerProps) {
  const styles = useBindingFieldUI(
    { state, open, disabled, derived },
    { ...ui, trigger: [ui?.trigger, className].filter(Boolean).join(' ') }
  )

  return (
    <button
      {...rest}
      type="button"
      className={styles.trigger}
      disabled={disabled}
      aria-label={label}
      aria-disabled={disabled ? 'true' : undefined}
      data-state={state}
      data-open={open ? '' : undefined}
      data-disabled={disabled ? '' : undefined}
      data-derived={derived ? '' : undefined}
      data-slot="trigger"
    >
      {children ?? (state === 'bound' ? (
        <IconLucideDiamond className="size-3" />
      ) : (
        <IconLucideDiamondPlus className="size-3" />
      ))}
    </button>
  )
}

// src/components/ui/binding/BindingTrigger.vue
<script lang="ts">
import { compact } from 'es-toolkit/array'
import type { PrimitiveProps } from 'reka-ui'
import type { HTMLAttributes } from 'vue'

import type { BindingState } from '@open-pencil/vue'

import type { BindingFieldUI } from './ui'

export interface BindingTriggerProps extends PrimitiveProps {
  label: string
  state?: BindingState
  open?: boolean
  disabled?: boolean
  derived?: boolean
  class?: HTMLAttributes['class']
  ui?: BindingFieldUI
}
</script>

<script setup lang="ts">
import { Primitive } from 'reka-ui'
import { computed, normalizeClass } from 'vue'

import { useBindingFieldUI } from '@/components/ui/binding/ui'

const {
  as = 'button',
  asChild = false,
  label,
  state = 'unbound',
  open = false,
  disabled = false,
  derived = false,
  class: className,
  ui
} = defineProps<BindingTriggerProps>()

const styles = computed(() =>
  useBindingFieldUI(
    { state, open, disabled, derived },
    { ...ui, trigger: compact([ui?.trigger, normalizeClass(className)]).join(' ') }
  )
)

defineOptions({ inheritAttrs: false })
</script>

<template>
  <Primitive
    v-bind="$attrs"
    :as="as"
    :as-child="asChild"
    :class="styles.trigger"
    :type="!asChild && as === 'button' ? 'button' : undefined"
    :disabled="!asChild && as === 'button' ? disabled : undefined"
    :aria-label="label"
    :aria-disabled="disabled ? 'true' : undefined"
    :data-state="state"
    :data-open="open ? '' : undefined"
    :data-disabled="disabled ? '' : undefined"
    :data-derived="derived ? '' : undefined"
    data-slot="trigger"
  >
    <slot>
      <icon-lucide-diamond v-if="state === 'bound'" class="size-3" />
      <icon-lucide-diamond-plus v-else class="size-3" />
    </slot>
  </Primitive>
</template>
