// packages/react/src/components/properties/LayoutSection/LayoutSection.tsx
import {
  Columns2,
  LayoutGrid,
  LayoutPanelTop,
  Move,
  Rows2,
  WrapText
} from 'lucide-react'
import type { LayoutMode } from '@open-pencil/scene-graph'

import { IconButton } from '#react/components/ui/IconButton'
import { PanelSection } from '#react/components/ui/panel/PanelSection'
import { SegmentedControl } from '#react/components/ui/SegmentedControl'
import { Tip } from '#react/components/ui/Tip'
import {
  LayoutControlsProvider,
  useLayout,
  useLayoutControlsContext
} from '#react/controls/layout/use'
import { ClipContentControl } from '#react/components/properties/LayoutSection/ClipContentControl'
import { FlexControls } from '#react/components/properties/LayoutSection/FlexControls'
import { GridControls } from '#react/components/properties/LayoutSection/GridControls'
import { PaddingControls } from '#react/components/properties/LayoutSection/PaddingControls'
import { SizeControls } from '#react/components/properties/LayoutSection/SizeControls'
import { TextResizingControl } from '#react/components/properties/LayoutSection/TextResizingControl'
import { useI18n } from '#react/i18n'

const CONTAINER_TYPES = new Set(['FRAME', 'COMPONENT', 'COMPONENT_SET', 'INSTANCE'])

export function LayoutSection() {
  const layout = useLayout()
  if (!layout.node) return null
  return (
    <LayoutControlsProvider value={layout}>
      <LayoutSectionBody />
    </LayoutControlsProvider>
  )
}

function LayoutSectionBody() {
  const ctx = useLayoutControlsContext()
  const { panels } = useI18n()
  const node = ctx.node
  if (!node) return null
  const isContainer = CONTAINER_TYPES.has(node.type)

  return (
    <PanelSection label={node.layoutMode === 'NONE' ? panels.layout : panels.autoLayout} actions={
      isContainer ? (
        <IconButton
          label={node.layoutMode === 'NONE' ? panels.addAutoLayout : panels.removeAutoLayout}
          size="xs"
          active={node.layoutMode !== 'NONE'}
          className="data-[state=on]:bg-accent/15"
          onClick={() =>
            ctx.editor.setLayoutMode(node.id, node.layoutMode === 'NONE' ? 'VERTICAL' : 'NONE')
          }
        >
          <LayoutPanelTop className="size-3.5" />
        </IconButton>
      ) : undefined
    }>
      {isContainer ? <AutoLayoutControls /> : null}
      <div className="mt-2 mb-1 text-[11px] text-muted">{panels.dimensions}</div>
      {node.type === 'TEXT' ? <TextResizingControl /> : null}
      <SizeControls />
      {isContainer && node.layoutMode === 'NONE' ? <ClipContentControl /> : null}
      {isContainer && node.layoutMode !== 'NONE' ? (
        <>
          {ctx.isFlex ? <FlexControls /> : null}
          {ctx.isGrid ? (
            <>
              <GridControls />
              <PaddingControls />
              <ClipContentControl />
            </>
          ) : null}
        </>
      ) : null}
    </PanelSection>
  )
}

function AutoLayoutControls() {
  const ctx = useLayoutControlsContext()
  const { panels } = useI18n()
  const node = ctx.node
  if (!node) return null

  const layoutModes: Array<{ value: LayoutMode; label: string }> = [
    { value: 'NONE', label: panels.freeform },
    { value: 'VERTICAL', label: panels.layoutVertical },
    { value: 'HORIZONTAL', label: panels.layoutHorizontal },
    { value: 'GRID', label: panels.layoutGrid }
  ]

  return (
    <div>
      <label className="mb-1 block text-[11px] text-muted">{panels.flow}</label>
      <div className="flex items-center gap-1.5">
        <SegmentedControl
          value={node.layoutMode}
          options={layoutModes}
          label={panels.flow}
          ui={{ root: 'flex min-w-0 flex-1' }}
          onChange={(mode) => ctx.editor.setLayoutMode(node.id, mode as LayoutMode)}
          renderOption={(option) => (
            <Tip label={option.label}>
              <span className="flex items-center justify-center">
                {option.value === 'NONE' ? <Move className="size-3.5" /> : null}
                {option.value === 'VERTICAL' ? <Rows2 className="size-3.5" /> : null}
                {option.value === 'HORIZONTAL' ? <Columns2 className="size-3.5" /> : null}
                {option.value === 'GRID' ? <LayoutGrid className="size-3.5" /> : null}
              </span>
            </Tip>
          )}
        />
        {ctx.isFlex ? (
          <IconButton
            label={panels.layoutWrap}
            size="xs"
            active={node.layoutWrap === 'WRAP'}
            onClick={() =>
              ctx.editor.updateNodeWithUndo(
                node.id,
                { layoutWrap: node.layoutWrap === 'WRAP' ? 'NO_WRAP' : 'WRAP' },
                'Toggle wrap'
              )
            }
          >
            <WrapText className="size-3.5" />
          </IconButton>
        ) : null}
      </div>
    </div>
  )
}

// src/components/properties/layout/LayoutSection.vue
<script setup lang="ts">
import { LayoutControlsRoot, useI18n } from '@open-pencil/vue'

import ClipContentControl from '@/components/properties/layout/ClipContentControl.vue'
import FlexControls from '@/components/properties/layout/flex/FlexControls.vue'
import GridControls from '@/components/properties/layout/grid/GridControls.vue'
import LayoutFlowControl from '@/components/properties/layout/LayoutFlowControl.vue'
import PaddingControls from '@/components/properties/layout/padding/PaddingControls.vue'
import SizeControls from '@/components/properties/layout/size/SizeControls.vue'
import TextResizingControl from '@/components/properties/layout/TextResizingControl.vue'
import IconButton from '@/components/ui/button/IconButton.vue'
import PanelSection from '@/components/ui/panel/PanelSection.vue'

const { panels } = useI18n()

const CONTAINER_TYPES = ['FRAME', 'COMPONENT', 'COMPONENT_SET', 'INSTANCE']
</script>

<template>
  <LayoutControlsRoot v-slot="ctx">
    <template v-if="ctx.node">
      <PanelSection :label="ctx.node.layoutMode === 'NONE' ? panels.layout : panels.autoLayout">
        <template v-if="CONTAINER_TYPES.includes(ctx.node.type)" #actions>
          <IconButton
            :label="ctx.node.layoutMode === 'NONE' ? panels.addAutoLayout : panels.removeAutoLayout"
            size="xs"
            :active="ctx.node.layoutMode !== 'NONE'"
            class="data-[state=on]:bg-accent/15"
            @click="
              ctx.editor.setLayoutMode(
                ctx.node.id,
                ctx.node.layoutMode === 'NONE' ? 'VERTICAL' : 'NONE'
              )
            "
          >
            <icon-lucide-layout-panel-top class="size-3.5" />
          </IconButton>
        </template>

        <LayoutFlowControl v-if="CONTAINER_TYPES.includes(ctx.node.type)" />
        <div class="mt-2 mb-1 text-[11px] text-muted">{{ panels.dimensions }}</div>
        <TextResizingControl v-if="ctx.node.type === 'TEXT'" />
        <SizeControls />
        <ClipContentControl
          v-if="CONTAINER_TYPES.includes(ctx.node.type) && ctx.node.layoutMode === 'NONE'"
        />

        <template v-if="CONTAINER_TYPES.includes(ctx.node.type) && ctx.node.layoutMode !== 'NONE'">
          <FlexControls v-if="ctx.isFlex" />
          <template v-if="ctx.isGrid">
            <GridControls />
            <PaddingControls />
            <ClipContentControl />
          </template>
        </template>
      </PanelSection>
    </template>
  </LayoutControlsRoot>
</template>
