// src/components/assets-panel/AssetsPanel.vue
<script setup lang="ts">
import { useObjectUrl } from '@vueuse/core'
import { computed, ref, shallowRef, watch } from 'vue'
import {
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuPortal,
  ContextMenuRoot,
  ContextMenuTrigger,
  DialogClose,
  DialogTitle
} from 'reka-ui'

import type { SceneNode } from '@open-pencil/scene-graph'
import { useI18n } from '@open-pencil/vue'

import { nodeIcon } from '@/app/editor/icons'
import { useEditorStore } from '@/app/editor/active-store'
import { openExternalLink } from '@/app/shell/ui'
import AssetThumbnail from '@/components/assets-panel/AssetThumbnail.vue'
import { findAssetPage } from '@/components/assets-panel/page'
import AppInput from '@/components/ui/AppInput.vue'
import AppPlaceholder from '@/components/ui/AppPlaceholder.vue'
import { useButtonUI } from '@/components/ui/button'
import { AppDialogRoot, useDialogUI } from '@/components/ui/dialog'
import { useMenuUI } from '@/components/ui/menu'
import SegmentedControl from '@/components/ui/SegmentedControl.vue'
import Tip from '@/components/ui/Tip.vue'
import { ASSET_GRID_THUMBNAIL_SIZE, ASSET_LIST_THUMBNAIL_SIZE } from '@/constants'
import apiClient from '@/lib/client.ts'
import { readFigFile } from '#core/io'

type AssetView = 'grid' | 'list'

type LocalAsset = {
  id: string
  name: string
  node: SceneNode
  componentId: string | null
  variants: Array<{ name: string; values: string[] }>
  variantCount: number
  hasConflicts: boolean
  sourceLibraryKey: string | null
  description: string
  docsUrl: string | null
  pageId: string
  pageName: string
}

type AssetGroup = {
  pageId: string
  pageName: string
  assets: LocalAsset[]
}

const editor = useEditorStore()
const { panels, commands } = useI18n()
const query = ref('')
const assetView = ref<AssetView>('grid')
const detailsOpen = ref(false)

const selectedAssetId = ref<string | null>(null)
const previewBlob = shallowRef<Blob | null>(null)
const previewUrl = useObjectUrl(previewBlob)
const previewLoading = ref(false)
const canAddRemoteLibList = ref<{ key: string; name: string }[]>([])
const canAddRemoteLibLoading = ref(false)
const canAddRemoteLibModalOpen = ref(false)
let previewRequestId = 0
const insertButton = useButtonUI({ tone: 'ghost', size: 'iconSm' })
const primaryButton = useButtonUI({ tone: 'accent', size: 'md' })
const dialog = useDialogUI()
const contextMenu = useMenuUI({ content: 'min-w-44' })
const viewOptions = computed(() => [
  { value: 'grid', label: panels.value.gridView },
  { value: 'list', label: panels.value.listView }
])
const viewUI = { root: 'w-16', item: 'px-1' }

const activeLibKey = ref('')
function componentSetVariantInfo(componentSetId: string) {
  return [...editor.collectVariantOptions(componentSetId)].map(([name, values]) => ({
    name,
    values: [...values].sort((a, b) => a.localeCompare(b))
  }))
}

const graphNodes = computed(() => {
  if (activeLibKey.value && activeLibKey.value !== 'default') {
    const lib = editor.graph.getLib(activeLibKey.value)
    const graph = lib?.graph
    if (graph) {
      return {
        sceneVersion: graph.sceneVersion,
        nodes: [...graph?.nodes.values()]
      }
    }
  }

  return {
    sceneVersion: editor.state.sceneVersion,
    nodes: [...editor.graph.nodes.values()]
  }
})

const assetNodes = computed(() =>
  graphNodes.value.nodes.filter(
    (node) => node.type === 'COMPONENT' || node.type === 'COMPONENT_SET'
  )
)

const pageByNodeId = computed(() => {
  const pages = new Map<string, { id: string; name: string }>()
  for (const node of assetNodes.value) {
    let graph = editor.graph
    if (activeLib?.value?.remote) {
      const lib = editor.graph.getLib(activeLib.value.key)
      graph = lib?.graph || editor.graph
    }
    const page = findAssetPage(node, graph)
    if (page) pages.set(node.id, { id: page.id, name: page.name })
  }
  return pages
})
const currentPageId = computed(() => editor.state.currentPageId)

const libList = ref([])

const calculateRemoteList = () => {
  const remoteLibs = editor.graph.getRemoteImports()
  const list = [...remoteLibs.values()].map((it) => ({
    key: it.source,
    name: it.name,
    remote: true
  }))
  libList.value = [
    { name: 'Created in this file', key: 'default', thumbnail: '', remote: false },
    ...list
  ]
}
watch(
  () => editor.graph.getRemoteImports(),
  () => {
    calculateRemoteList()
  }
)

const activeLib = computed(() => {
  if (!activeLibKey.value) return null
  return libList.value.find((lib) => lib.key === activeLibKey.value) ?? null
})
const assets = computed<LocalAsset[]>(() => {
  let graph = editor.graph
  if (activeLib?.value?.remote) {
    const lib = editor.graph.getLib(activeLib.value.key)
    graph = lib?.graph || editor.graph
  }
  return assetNodes.value
    .filter((node) => {
      if (node.type === 'COMPONENT_SET') return true

      const parent = node.parentId ? graph.getNode(node.parentId) : null
      return parent?.type !== 'COMPONENT_SET'
    })
    .map((node) => {
      const defaultVariant =
        node.type === 'COMPONENT_SET'
          ? editor.getDefaultVariantForComponentSet(node.id, graph)
          : node
      const conflicts =
        node.type === 'COMPONENT_SET' ? editor.getComponentSetVariantConflicts(node.id) : []
      const variants = node.type === 'COMPONENT_SET' ? componentSetVariantInfo(node.id) : []
      const page = pageByNodeId.value.get(node.id)
      return {
        id: node.id,
        name: node.name,
        node,
        componentId: defaultVariant?.id ?? null,
        variants,
        variantCount: node.type === 'COMPONENT_SET' ? node.childIds.length : 0,
        hasConflicts: conflicts.length > 0,
        sourceLibraryKey: node.sourceLibraryKey,
        description: node.symbolDescription,
        docsUrl: node.symbolLinks[0]?.uri ?? null,
        pageId: page?.id ?? editor.state.currentPageId,
        pageName: page?.name ?? panels.value.page
      }
    })
    .sort((a, b) => a.name.localeCompare(b.name))
})

const filteredAssets = computed(() => {
  const normalized = query.value.trim().toLowerCase()
  if (!normalized) return assets.value
  return assets.value.filter((asset) => asset.name.toLowerCase().includes(normalized))
})

const assetGroups = computed<AssetGroup[]>(() => {
  const groups = new Map<string, AssetGroup>()
  for (const asset of filteredAssets.value) {
    const group = groups.get(asset.pageId) ?? {
      pageId: asset.pageId,
      pageName: asset.pageName,
      assets: []
    }
    group.assets.push(asset)
    groups.set(asset.pageId, group)
  }
  return [...groups.values()].sort((a, b) => a.pageName.localeCompare(b.pageName))
})

const selectedAsset = computed(
  () => assets.value.find((asset) => asset.id === selectedAssetId.value) ?? null
)
const selectedPreviewNodeId = computed(() => selectedAsset.value?.componentId ?? null)

function clearPreview() {
  previewBlob.value = null
}

async function updatePreview() {
  const requestId = ++previewRequestId
  const nodeId = selectedPreviewNodeId.value
  if (!detailsOpen.value || !nodeId) {
    clearPreview()
    return
  }

  const node = editor.getNode(nodeId)
  if (!node) {
    clearPreview()
    return
  }

  previewLoading.value = true
  try {
    const maxSize = Math.max(node.width, node.height, 1)
    const scale = Math.min(176 / maxSize, 2)
    const data = await editor.renderExportImage([nodeId], scale, 'PNG', selectedAsset.value?.pageId)
    if (requestId !== previewRequestId) return
    previewBlob.value = data ? new Blob([data], { type: 'image/png' }) : null
  } catch {
    if (requestId === previewRequestId) clearPreview()
  } finally {
    if (requestId === previewRequestId) previewLoading.value = false
  }
}

watch([detailsOpen, selectedPreviewNodeId, () => editor.state.sceneVersion], updatePreview, {
  flush: 'post'
})

function openDetails(asset: LocalAsset) {
  selectedAssetId.value = asset.id
  detailsOpen.value = true
}

function insertionPoint(component: SceneNode, parentId: string) {
  const canvasCenter = editor.viewportCanvasCenter()
  const center = editor.screenToCanvas(canvasCenter.x, canvasCenter.y)
  const parentOffset =
    parentId === editor.state.currentPageId
      ? { x: 0, y: 0 }
      : editor.graph.getAbsolutePosition(parentId)
  return {
    x: center.x - parentOffset.x - component.width / 2,
    y: center.y - parentOffset.y - component.height / 2
  }
}

function insertAsset(asset: LocalAsset) {
  if (!asset.componentId) return

  let graph = editor.graph
  if (activeLib?.value?.remote) {
    const lib = editor.graph.getLib(activeLib.value.key)
    graph = lib?.graph || editor.graph
  }
  const component = graph.getNode(asset.componentId)
  if (!component) return
  const parentId = editor.state.enteredContainerId ?? editor.state.currentPageId
  const point = insertionPoint(component, parentId)
  editor.createInstanceFromComponent(
    asset.componentId,
    point.x,
    point.y,
    parentId,
    activeLib?.value?.key
  )
  editor.requestRender()
}

function onDragStart(event: DragEvent, asset: LocalAsset) {
  if (!event.dataTransfer || !asset.componentId) return
  event.dataTransfer.setData('application/x-openpencil-component', asset.componentId)
  event.dataTransfer.effectAllowed = 'copy'
}

function focusAsset(asset: LocalAsset) {
  void editor.focusComponent(asset.id)
}

function onAssetKeydown(event: KeyboardEvent, asset: LocalAsset) {
  if ((event.metaKey || event.ctrlKey) && event.code === 'Enter') {
    event.preventDefault()
    openDetails(asset)
    return
  }
  if (event.code === 'Enter' || event.code === 'Space') {
    event.preventDefault()
    insertAsset(asset)
  }
}

function insertSelectedAsset() {
  if (!selectedAsset.value) return
  insertAsset(selectedAsset.value)
  detailsOpen.value = false
}

const fetchCanAddRemoteLib = async () => {
  canAddRemoteLibLoading.value = true
  const res = await apiClient.get('/api/libraries/list')
  canAddRemoteLibLoading.value = false
  canAddRemoteLibList.value = res.data
}

const changeActiveLib = (key: string) => {
  activeLibKey.value = key
}
const openCanAddRemoteLibModal = () => {
  fetchCanAddRemoteLib()
  canAddRemoteLibModalOpen.value = true
}

const addRemoteLibClick = async (item: any) => {
  const res = await apiClient.get<ArrayBuffer>(`/api/oss/download?path=${item.url}`, {
    responseType: 'arraybuffer' // 重要：指定响应类型为二进制
  })
  const bytes = new Uint8Array(res.data)

  const fileBytes = new Uint8Array(bytes.byteLength)
  fileBytes.set(bytes)
  const file = new File([fileBytes.buffer], `${item.key}.fig`, {
    type: 'application/octet-stream'
  })
  const imported = await readFigFile(file, { populate: 'first-page' })
  editor.graph.addLib(item.key, item.name, item.url, imported)
  calculateRemoteList()
  canAddRemoteLibModalOpen.value = false
}
</script>

<template>
  <section data-test-id="assets-panel" class="flex min-h-0 flex-1 flex-col overflow-hidden">
    <div class="flex shrink-0 items-center gap-2 px-2 py-2" v-if="activeLibKey">
      <AppInput
        v-model="query"
        type="search"
        data-test-id="assets-search"
        size="sm"
        class="min-w-0 flex-1"
        :placeholder="panels.searchLocalComponents"
      />
      <SegmentedControl
        v-model="assetView"
        data-test-id="assets-view-toggle"
        :options="viewOptions"
        :label="panels.assetView"
        :ui="viewUI"
      >
        <template #option="{ option }">
          <icon-lucide-layout-grid v-if="option.value === 'grid'" class="size-3" />
          <icon-lucide-list v-else class="size-3" />
        </template>
      </SegmentedControl>
    </div>

    <div v-if="activeLib" class="inline-flex items-center px-2 py-2 mb-4">
      <icon-lucide-chevron-left
        class="size-4 text-surface cursor-pointer"
        @click="() => changeActiveLib('')"
      />
      <span>{{ activeLib?.name }}</span>
    </div>

    <div class="scrollbar-thin flex min-h-0 flex-1 flex-col overflow-y-auto px-2 pb-2">
      <div v-if="!activeLibKey" class="space-x-1">
        <div
          v-for="libItem in libList"
          :key="libItem.key"
          @click="() => changeActiveLib(libItem.key)"
        >
          <div>
            <AssetThumbnail
              :node-id="currentPageId"
              v-if="!activeLib?.remote"
              :alt="`${libItem.name} preview`"
              :size="assetView === 'grid' ? ASSET_GRID_THUMBNAIL_SIZE : ASSET_LIST_THUMBNAIL_SIZE"
            />

            <div
              v-if="activeLib?.remote"
              :node-id="currentPageId"
              remoteKey="activeLib?.key"
              :alt="`${libItem.name} preview`"
              :size="assetView === 'grid' ? ASSET_GRID_THUMBNAIL_SIZE : ASSET_LIST_THUMBNAIL_SIZE"
            />
          </div>
          <div>{{ libItem.name }}</div>
        </div>
        <div class="mt-4">
          <button
            @click="openCanAddRemoteLibModal"
            class="flex h-7 w-full cursor-pointer items-center justify-center rounded border border-border bg-transparent text-xs text-muted hover:bg-hover hover:text-surface"
          >
            Add more libraries
          </button>
        </div>
      </div>
      <section v-if="activeLibKey" v-for="group in assetGroups" :key="group.pageId" class="mb-3">
        <h2 class="mb-1 px-1 text-[10px] font-medium tracking-wide text-muted uppercase">
          {{ group.pageName }}
        </h2>
        <div :class="assetView === 'grid' ? 'grid grid-cols-2 gap-2' : 'flex flex-col gap-0.5'">
          <ContextMenuRoot v-for="asset in group.assets" :key="asset.id">
            <ContextMenuTrigger as-child>
              <div
                role="button"
                tabindex="0"
                data-test-id="asset-item"
                :data-asset-id="asset.id"
                :draggable="!!asset.componentId"
                :class="[
                  'group/asset rounded text-left text-xs text-surface outline-none hover:bg-hover focus-visible:ring-1 focus-visible:ring-accent',
                  assetView === 'grid'
                    ? 'flex min-w-0 flex-col items-center gap-1 p-1.5'
                    : 'flex w-full items-center gap-2 px-1.5 py-1'
                ]"
                @click="openDetails(asset)"
                @keydown="onAssetKeydown($event, asset)"
                @dragstart="onDragStart($event, asset)"
              >
                <AssetThumbnail
                  v-if="asset.componentId && !activeLib?.remote"
                  :node-id="asset.componentId"
                  :alt="`${asset.name} preview`"
                  :size="
                    assetView === 'grid' ? ASSET_GRID_THUMBNAIL_SIZE : ASSET_LIST_THUMBNAIL_SIZE
                  "
                />
                <AssetRemoteThumbnail
                  v-if="asset.componentId && activeLib?.remote"
                  :node-id="asset.componentId"
                  :alt="`${asset.name} preview`"
                  :remote-key="activeLib?.key"
                  :size="
                    assetView === 'grid' ? ASSET_GRID_THUMBNAIL_SIZE : ASSET_LIST_THUMBNAIL_SIZE
                  "
                />
                <component
                  :is="nodeIcon(asset.node)"
                  v-else
                  class="size-4 shrink-0 text-component"
                  aria-hidden="true"
                />
                <span :class="assetView === 'grid' ? 'w-full min-w-0' : 'min-w-0 flex-1'">
                  <span class="flex min-w-0 items-center gap-1">
                    <span data-test-id="asset-name" class="truncate">{{ asset.name }}</span>
                    <span
                      v-if="asset.sourceLibraryKey"
                      data-test-id="asset-library-badge"
                      class="shrink-0 rounded bg-component/15 px-1 py-px text-[9px] font-medium text-component uppercase"
                    >
                      {{ panels.assetLibraryBadge }}
                    </span>
                  </span>
                  <span
                    v-if="assetView === 'list' && asset.variants.length > 0"
                    data-test-id="asset-variant-summary"
                    class="mt-0.5 block truncate text-[10px] text-muted"
                  >
                    {{
                      panels.assetVariantSummary({
                        count: asset.variantCount,
                        names: asset.variants.map((variant) => variant.name).join(', ')
                      })
                    }}
                  </span>
                  <span
                    v-if="assetView === 'list' && asset.description"
                    data-test-id="asset-description"
                    class="mt-0.5 block truncate text-[10px] text-muted"
                  >
                    {{ asset.description }}
                  </span>
                  <span
                    v-if="assetView === 'list' && asset.hasConflicts"
                    data-test-id="asset-variant-conflict"
                    class="mt-0.5 block truncate text-[10px] text-[var(--color-warning-text)]"
                  >
                    {{ panels.duplicateVariantValues }}
                  </span>
                </span>
                <div v-if="assetView === 'list'" class="flex shrink-0 items-center">
                  <Tip v-if="asset.docsUrl" :label="panels.openDocumentation">
                    <button
                      type="button"
                      :class="insertButton.base"
                      data-test-id="asset-docs"
                      @pointerdown.stop
                      @click.stop="asset.docsUrl ? openExternalLink(asset.docsUrl) : undefined"
                    >
                      <icon-lucide-book-open class="size-3" />
                    </button>
                  </Tip>
                  <Tip :label="commands.createInstance">
                    <button
                      type="button"
                      :class="insertButton.base"
                      data-test-id="asset-insert"
                      @pointerdown.stop
                      @click.stop="insertAsset(asset)"
                    >
                      <icon-lucide-plus class="size-3" />
                    </button>
                  </Tip>
                </div>
              </div>
            </ContextMenuTrigger>
            <ContextMenuPortal>
              <ContextMenuContent :class="contextMenu.content">
                <ContextMenuItem
                  data-test-id="asset-context-go-to-main"
                  :class="contextMenu.item"
                  @select="focusAsset(asset)"
                >
                  {{ panels.goToMainComponent }}
                </ContextMenuItem>
                <ContextMenuItem
                  data-test-id="asset-context-view-details"
                  :class="contextMenu.item"
                  @select="openDetails(asset)"
                >
                  {{ panels.viewDetails }}
                </ContextMenuItem>
              </ContextMenuContent>
            </ContextMenuPortal>
          </ContextMenuRoot>
        </div>
      </section>

      <AppPlaceholder
        v-if="filteredAssets.length === 0"
        data-test-id="assets-empty"
        :label="panels.noLocalComponents"
        size="compact"
      >
        <template #icon>
          <icon-lucide-component class="size-4" />
        </template>
      </AppPlaceholder>
    </div>

    <AppDialogRoot
      v-model:open="canAddRemoteLibModalOpen"
      size="lg"
      data-test-id="asset-details-dialog"
    >
      <div class="border-b border-border px-4 py-3">
        <div class="flex justify-end w-full">
          <DialogClose
            data-test-id="asset-details-close"
            class="flex size-7 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted"
          >
            <icon-lucide-x class="size-4" />
          </DialogClose>
        </div>

        <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 p-3">
          <div
            v-for="item in canAddRemoteLibList"
            :key="item.id || item.key"
            @click="addRemoteLibClick(item)"
            class="rounded-lg overflow-hidden bg-transparent border border-border hover:shadow-md transition-all cursor-pointer hover:bg-hover"
          >
            <!-- 缩略图 - 更大 -->
            <div class="w-full aspect-video flex items-center justify-center overflow-hidden">
              <img
                v-if="item.thumbnail_url"
                :src="item.thumbnail_url"
                :alt="item.name"
                class="w-full h-full object-cover"
              />
              <svg
                v-else
                class="w-10 h-10"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="1.5"
              >
                <rect x="2" y="2" width="20" height="20" rx="3" />
                <path d="M8 16l4-4 4 4" />
                <circle cx="8" cy="8" r="2" />
              </svg>
            </div>

            <!-- 内容 -->
            <div class="p-3">
              <div class="text-sm font-medium truncate">
                {{ item.name }}
              </div>
              <div class="text-muted flex justify-between">
                <div class="text-[10px] mt-1.5">v{{ item.version || '1.0.0' }}</div>
              </div>
            </div>
          </div>

          <!-- 空状态 -->
          <div
            v-if="!canAddRemoteLibList || canAddRemoteLibList.length === 0"
            class="col-span-full"
          >
            <div class="text-center py-12 text-gray-400 text-sm">暂无远程库</div>
          </div>
        </div>
      </div>
    </AppDialogRoot>

    <AppDialogRoot
      v-if="selectedAsset"
      v-model:open="detailsOpen"
      size="lg"
      data-test-id="asset-details-dialog"
    >
      <div class="flex items-center justify-between border-b border-border px-4 py-3">
        <div class="flex min-w-0 items-center gap-2">
          <component :is="nodeIcon(selectedAsset.node)" class="size-4 shrink-0 text-component" />
          <div class="min-w-0">
            <DialogTitle :class="dialog.title" class="truncate">{{
              selectedAsset.name
            }}</DialogTitle>
            <p class="mt-0.5 text-[11px] text-muted">
              {{
                selectedAsset.node.type === 'COMPONENT_SET' ? panels.componentSet : panels.component
              }}
              <span v-if="selectedAsset.variantCount > 0">
                · {{ selectedAsset.variantCount }} variants</span
              >
            </p>
          </div>
        </div>
        <DialogClose
          data-test-id="asset-details-close"
          class="flex size-7 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted hover:bg-hover hover:text-surface"
        >
          <icon-lucide-x class="size-4" />
        </DialogClose>
      </div>

      <div class="grid min-h-0 grid-cols-[260px_1fr] gap-0">
        <div class="border-r border-border p-4">
          <div
            data-test-id="asset-details-preview"
            class="flex h-36 items-center justify-center overflow-hidden rounded-lg border border-border bg-canvas/60"
          >
            <img
              v-if="previewUrl"
              data-test-id="asset-details-preview-image"
              :src="previewUrl"
              :alt="`${selectedAsset.name} preview`"
              class="max-h-[120px] max-w-[210px] object-contain"
            />
            <div v-else class="text-center">
              <icon-lucide-loader-2
                v-if="previewLoading"
                class="mx-auto size-5 animate-spin text-muted"
              />
              <component
                v-else
                :is="nodeIcon(selectedAsset.node)"
                class="mx-auto size-8 text-component"
              />
              <p class="mt-2 max-w-44 truncate text-xs font-medium text-surface">
                {{ selectedAsset.name }}
              </p>
            </div>
          </div>
          <button
            data-test-id="asset-details-insert"
            :class="primaryButton.base"
            class="mt-3 w-full"
            @click="insertSelectedAsset"
          >
            {{ panels.insertInstance }}
          </button>
        </div>

        <div class="min-w-0 p-4">
          <section v-if="selectedAsset.description" class="mb-4">
            <h3 class="text-[11px] font-medium tracking-wider text-muted uppercase">
              {{ panels.description }}
            </h3>
            <p data-test-id="asset-details-description" class="mt-1 text-xs leading-5 text-surface">
              {{ selectedAsset.description }}
            </p>
          </section>

          <section v-if="selectedAsset.sourceLibraryKey" class="mb-4">
            <h3 class="text-[11px] font-medium tracking-wider text-muted uppercase">
              {{ panels.assetLibraryBadge }}
            </h3>
            <p data-test-id="asset-details-library" class="mt-1 break-all text-xs text-muted">
              {{ selectedAsset.sourceLibraryKey }}
            </p>
          </section>

          <section v-if="selectedAsset.docsUrl" class="mb-4">
            <h3 class="text-[11px] font-medium tracking-wider text-muted uppercase">
              {{ panels.documentation }}
            </h3>
            <button
              data-test-id="asset-details-docs"
              class="mt-1 inline-flex items-center gap-1 rounded px-1 py-0.5 text-xs text-component hover:bg-component/10"
              @click="selectedAsset.docsUrl ? openExternalLink(selectedAsset.docsUrl) : undefined"
            >
              <icon-lucide-book-open class="size-3" />
              {{ panels.openDocs }}
            </button>
          </section>

          <section v-if="selectedAsset.variants.length > 0">
            <h3 class="text-[11px] font-medium tracking-wider text-muted uppercase">
              {{ panels.properties }}
            </h3>
            <div class="mt-2 flex flex-col gap-2">
              <div
                v-for="variant in selectedAsset.variants"
                :key="variant.name"
                data-test-id="asset-details-property"
                class="rounded border border-border bg-input/40 px-2 py-1.5"
              >
                <div class="text-xs font-medium text-surface">{{ variant.name }}</div>
                <div class="mt-1 text-[11px] text-muted">{{ variant.values.join(', ') }}</div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </AppDialogRoot>
  </section>
</template>

// packages/react/src/components/assets-panel/AssetsPanel.tsx
import { BookOpen, ChevronLeft, Component, LayoutGrid, List, Plus } from 'lucide-react'
import { useMemo, useState, type DragEvent, type KeyboardEvent, type MouseEvent } from 'react'
import { useParams } from 'react-router-dom'

import { attachRemoteLibrary } from '#react/app/document/libraries'
import { getLib } from '#react/graph/remote-lib'
import { nodeIcon } from '#react/app/editor/icons'
import { useEditorStore } from '#react/app/editor/store'
import { AddLibraryDialog } from '#react/components/assets-panel/AddLibraryDialog'
import { AssetDetailsDialog } from '#react/components/assets-panel/AssetDetailsDialog'
import { AssetRemoteThumbnail } from '#react/components/assets-panel/AssetRemoteThumbnail'
import { AssetThumbnail } from '#react/components/assets-panel/AssetThumbnail'
import {
  COMPONENT_LIB_MIME,
  COMPONENT_MIME,
  filterAssets,
  groupAssets,
  insertAssetInstance,
  listAssetLibraries,
  listAssets,
  openExternalLink,
  type LocalAsset
} from '#react/components/assets-panel/assets'
import { AppInput } from '#react/components/ui/AppInput'
import { AppPlaceholder } from '#react/components/ui/AppPlaceholder'
import { IconButton } from '#react/components/ui/IconButton'
import { FloatingMenu } from '#react/components/properties/variables/FloatingMenu'
import { SegmentedControl } from '#react/components/ui/SegmentedControl'
import { useMenuUI } from '#react/components/ui/menu'
import { ASSET_GRID_THUMBNAIL_SIZE, ASSET_LIST_THUMBNAIL_SIZE } from '#react/constants'
import { useI18n } from '#react/i18n'
import { libraryAPI, type RemoteLibraryCatalogItem } from '#react/lib/client'

type AssetView = 'grid' | 'list'

export function AssetsPanel() {
  const store = useEditorStore()
  const { fileKey } = useParams<{ fileKey?: string }>()
  const { panels, commands } = useI18n()
  const contextMenu = useMenuUI({ content: 'min-w-44' })
  const [query, setQuery] = useState('')
  const [assetView, setAssetView] = useState<AssetView>('grid')
  const [activeLibKey, setActiveLibKey] = useState('')
  const [libRevision, setLibRevision] = useState(0)
  const [detailsAssetId, setDetailsAssetId] = useState<string | null>(null)
  const [menu, setMenu] = useState<{ assetId: string; x: number; y: number } | null>(null)
  const [addOpen, setAddOpen] = useState(false)
  const [catalog, setCatalog] = useState<RemoteLibraryCatalogItem[]>([])
  const [catalogLoading, setCatalogLoading] = useState(false)

  const libraries = useMemo(
    () => listAssetLibraries(store.graph, panels.createdInThisFile),
    [libRevision, panels.createdInThisFile, store.graph, store.state.sceneVersion]
  )
  const activeLib = libraries.find((lib) => lib.key === activeLibKey) ?? null
  const sourceLibraryKey = activeLib?.remote ? activeLib.key : undefined
  const activeGraph = sourceLibraryKey
    ? (getLib(store.graph, sourceLibraryKey)?.graph ?? store.graph)
    : store.graph

  const assets = useMemo(
    () => (activeLibKey ? listAssets(store, activeGraph, panels.page) : []),
    [activeGraph, activeLibKey, panels.page, store, store.state.sceneVersion]
  )
  const filteredAssets = useMemo(() => filterAssets(assets, query), [assets, query])
  const assetGroups = useMemo(() => groupAssets(filteredAssets), [filteredAssets])
  const detailsAsset = assets.find((asset) => asset.id === detailsAssetId) ?? null
  const viewOptions = [
    { value: 'grid', label: panels.gridView },
    { value: 'list', label: panels.listView }
  ]

  function refreshLibraries() {
    setLibRevision((value) => value + 1)
    store.notify()
  }

  async function openAddLibraries() {
    setAddOpen(true)
    setCatalogLoading(true)
    try {
      const res = await libraryAPI.list()
      setCatalog(Array.isArray(res.data) ? res.data : [])
    } catch {
      setCatalog([])
    } finally {
      setCatalogLoading(false)
    }
  }

  async function onSelectCatalogItem(item: RemoteLibraryCatalogItem) {
    await attachRemoteLibrary(store, fileKey, item)
    refreshLibraries()
    setAddOpen(false)
  }

  function onDragStart(event: DragEvent<HTMLDivElement>, asset: LocalAsset) {
    if (!event.dataTransfer || !asset.componentId) return
    event.dataTransfer.setData(COMPONENT_MIME, asset.componentId)
    if (sourceLibraryKey) event.dataTransfer.setData(COMPONENT_LIB_MIME, sourceLibraryKey)
    event.dataTransfer.effectAllowed = 'copy'
  }

  function onAssetKeydown(event: KeyboardEvent<HTMLDivElement>, asset: LocalAsset) {
    if ((event.metaKey || event.ctrlKey) && event.code === 'Enter') {
      event.preventDefault()
      setDetailsAssetId(asset.id)
      return
    }
    if (event.code === 'Enter' || event.code === 'Space') {
      event.preventDefault()
      insertAssetInstance(store, asset, sourceLibraryKey)
    }
  }

  function onContextMenu(event: MouseEvent<HTMLDivElement>, asset: LocalAsset) {
    event.preventDefault()
    setMenu({ assetId: asset.id, x: event.clientX, y: event.clientY })
  }

  const menuAsset = assets.find((asset) => asset.id === menu?.assetId) ?? null

  return (
    <section data-test-id="assets-panel" className="flex min-h-0 flex-1 flex-col overflow-hidden">
      {activeLibKey ? (
        <div className="flex shrink-0 items-center gap-2 px-2 py-2">
          <AppInput
            type="search"
            data-test-id="assets-search"
            size="sm"
            className="min-w-0 flex-1"
            placeholder={panels.searchLocalComponents}
            value={query}
            onChange={(event) => setQuery(event.target.value)}
          />
          <div data-test-id="assets-view-toggle">
            <SegmentedControl
              value={assetView}
              options={viewOptions}
              label={panels.assetView}
              ui={{ root: 'w-16', item: 'px-1' }}
              onChange={(value) => {
                if (value === 'grid' || value === 'list') setAssetView(value)
              }}
              renderOption={(option) =>
                option.value === 'grid' ? (
                  <LayoutGrid className="size-3" />
                ) : (
                  <List className="size-3" />
                )
              }
            />
          </div>
        </div>
      ) : null}

      {activeLib ? (
        <div className="mb-4 inline-flex items-center px-2 py-2">
          <button
            type="button"
            data-test-id="assets-lib-back"
            className="cursor-pointer border-none bg-transparent p-0 text-surface"
            onClick={() => setActiveLibKey('')}
          >
            <ChevronLeft className="size-4" />
          </button>
          <span className="truncate text-xs text-surface">{activeLib.name}</span>
        </div>
      ) : null}

      <div className="scrollbar-thin flex min-h-0 flex-1 flex-col overflow-y-auto px-2 pb-2">
        {!activeLibKey ? (
          <div className="space-y-1">
            {libraries.map((libItem) => (
              <button
                key={libItem.key}
                type="button"
                data-test-id="assets-lib-item"
                data-lib-key={libItem.key}
                className="flex w-full cursor-pointer items-center gap-2 rounded px-1.5 py-1.5 text-left text-xs text-surface hover:bg-hover"
                onClick={() => setActiveLibKey(libItem.key)}
              >
                {libItem.remote ? (
                  <AssetRemoteThumbnail
                    nodeId={getLib(store.graph, libItem.key)?.graph.getPages()[0]?.id ?? ''}
                    remoteKey={libItem.key}
                    alt={`${libItem.name} preview`}
                    size={ASSET_LIST_THUMBNAIL_SIZE}
                  />
                ) : (
                  <AssetThumbnail
                    nodeId={store.state.currentPageId}
                    alt={`${libItem.name} preview`}
                    size={ASSET_LIST_THUMBNAIL_SIZE}
                  />
                )}
                <span className="truncate">{libItem.name}</span>
              </button>
            ))}
            <button
              type="button"
              data-test-id="assets-add-libraries"
              className="mt-4 flex h-7 w-full cursor-pointer items-center justify-center rounded border border-border bg-transparent text-xs text-muted hover:bg-hover hover:text-surface"
              onClick={() => void openAddLibraries()}
            >
              {panels.addMoreLibraries}
            </button>
          </div>
        ) : null}

        {activeLibKey
          ? assetGroups.map((group) => (
              <section key={group.pageId} className="mb-3">
                <h2 className="mb-1 px-1 text-[10px] font-medium tracking-wide text-muted uppercase">
                  {group.pageName}
                </h2>
                <div
                  className={assetView === 'grid' ? 'grid grid-cols-2 gap-2' : 'flex flex-col gap-0.5'}
                >
                  {group.assets.map((asset) => {
                    const Icon = nodeIcon(asset.node)
                    return (
                      <div
                        key={asset.id}
                        role="button"
                        tabIndex={0}
                        data-test-id="asset-item"
                        data-asset-id={asset.id}
                        draggable={Boolean(asset.componentId)}
                        className={`group/asset rounded text-left text-xs text-surface outline-none hover:bg-hover focus-visible:ring-1 focus-visible:ring-accent ${
                          assetView === 'grid'
                            ? 'flex min-w-0 flex-col items-center gap-1 p-1.5'
                            : 'flex w-full items-center gap-2 px-1.5 py-1'
                        }`}
                        onClick={() => setDetailsAssetId(asset.id)}
                        onKeyDown={(event) => onAssetKeydown(event, asset)}
                        onContextMenu={(event) => onContextMenu(event, asset)}
                        onDragStart={(event) => onDragStart(event, asset)}
                      >
                        {asset.componentId && sourceLibraryKey ? (
                          <AssetRemoteThumbnail
                            nodeId={asset.componentId}
                            remoteKey={sourceLibraryKey}
                            alt={`${asset.name} preview`}
                            size={
                              assetView === 'grid'
                                ? ASSET_GRID_THUMBNAIL_SIZE
                                : ASSET_LIST_THUMBNAIL_SIZE
                            }
                          />
                        ) : asset.componentId ? (
                          <AssetThumbnail
                            nodeId={asset.componentId}
                            alt={`${asset.name} preview`}
                            size={
                              assetView === 'grid'
                                ? ASSET_GRID_THUMBNAIL_SIZE
                                : ASSET_LIST_THUMBNAIL_SIZE
                            }
                          />
                        ) : (
                          <Icon className="size-4 shrink-0 text-component" aria-hidden="true" />
                        )}
                        <span className={assetView === 'grid' ? 'w-full min-w-0' : 'min-w-0 flex-1'}>
                          <span className="flex min-w-0 items-center gap-1">
                            <span data-test-id="asset-name" className="truncate">
                              {asset.name}
                            </span>
                            {asset.sourceLibraryKey ? (
                              <span
                                data-test-id="asset-library-badge"
                                className="shrink-0 rounded bg-component/15 px-1 py-px text-[9px] font-medium text-component uppercase"
                              >
                                {panels.assetLibraryBadge}
                              </span>
                            ) : null}
                          </span>
                          {assetView === 'list' && asset.variants.length > 0 ? (
                            <span
                              data-test-id="asset-variant-summary"
                              className="mt-0.5 block truncate text-[10px] text-muted"
                            >
                              {panels.assetVariantSummary({
                                count: asset.variantCount,
                                names: asset.variants.map((variant) => variant.name).join(', ')
                              })}
                            </span>
                          ) : null}
                          {assetView === 'list' && asset.description ? (
                            <span
                              data-test-id="asset-description"
                              className="mt-0.5 block truncate text-[10px] text-muted"
                            >
                              {asset.description}
                            </span>
                          ) : null}
                          {assetView === 'list' && asset.hasConflicts ? (
                            <span
                              data-test-id="asset-variant-conflict"
                              className="mt-0.5 block truncate text-[10px] text-[var(--color-warning-text)]"
                            >
                              {panels.duplicateVariantValues}
                            </span>
                          ) : null}
                        </span>
                        {assetView === 'list' ? (
                          <div className="flex shrink-0 items-center">
                            {asset.docsURL ? (
                              <IconButton
                                label={panels.openDocumentation}
                                data-test-id="asset-docs"
                                size="xs"
                                onPointerDown={(event) => event.stopPropagation()}
                                onClick={(event) => {
                                  event.stopPropagation()
                                  if (asset.docsURL) openExternalLink(asset.docsURL)
                                }}
                              >
                                <BookOpen className="size-3" />
                              </IconButton>
                            ) : null}
                            <IconButton
                              label={commands.createInstance}
                              data-test-id="asset-insert"
                              size="xs"
                              onPointerDown={(event) => event.stopPropagation()}
                              onClick={(event) => {
                                event.stopPropagation()
                                insertAssetInstance(store, asset, sourceLibraryKey)
                              }}
                            >
                              <Plus className="size-3" />
                            </IconButton>
                          </div>
                        ) : null}
                      </div>
                    )
                  })}
                </div>
              </section>
            ))
          : null}

        {activeLibKey && filteredAssets.length === 0 ? (
          <AppPlaceholder
            data-test-id="assets-empty"
            label={panels.noLocalComponents}
            size="compact"
            icon={<Component className="size-4" />}
          />
        ) : null}
      </div>

      <FloatingMenu
        open={Boolean(menu && menuAsset)}
        point={menu ? { x: menu.x, y: menu.y } : undefined}
        onClose={() => setMenu(null)}
        className={contextMenu.content}
      >
        {menuAsset ? (
          <>
            <button
              type="button"
              data-test-id="asset-context-go-to-main"
              className={contextMenu.item}
              onClick={() => {
                void store.focusComponent(menuAsset.id)
                setMenu(null)
              }}
            >
              {panels.goToMainComponent}
            </button>
            <button
              type="button"
              data-test-id="asset-context-view-details"
              className={contextMenu.item}
              onClick={() => {
                setDetailsAssetId(menuAsset.id)
                setMenu(null)
              }}
            >
              {panels.viewDetails}
            </button>
          </>
        ) : null}
      </FloatingMenu>

      {detailsAsset ? (
        <AssetDetailsDialog
          asset={detailsAsset}
          libraryKey={sourceLibraryKey}
          onClose={() => setDetailsAssetId(null)}
        />
      ) : null}

      {addOpen ? (
        <AddLibraryDialog
          items={catalog}
          loading={catalogLoading}
          onClose={() => setAddOpen(false)}
          onSelect={(item) => void onSelectCatalogItem(item)}
        />
      ) : null}
    </section>
  )
}
