// src/components/properties/BoundVariableButton.vue
<script setup lang="ts">
import Tip from '@/components/ui/Tip.vue'

interface BoundVariableButtonProps {
  label: string
}

defineOptions({ inheritAttrs: false })

const { label } = defineProps<BoundVariableButtonProps>()

const emit = defineEmits<{
  detach: []
}>()
</script>

<template>
  <Tip :label="label">
    <button
      v-bind="$attrs"
      :aria-label="label"
      class="shrink-0 cursor-pointer border-none bg-transparent p-0 text-violet-400 hover:text-surface"
      @click="emit('detach')"
    >
      <icon-lucide-diamond-minus class="size-3.5" />
    </button>
  </Tip>
</template>

// src/components/properties/BoundVariableButton.tsx
import type { ButtonHTMLAttributes } from 'react'

import IconDiamondMinus from '~icons/lucide/diamond-minus'

import { Tip } from '@/components/ui/Tip'

interface BoundVariableButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  label: string
  onDetach?: () => void
}

export function BoundVariableButton({ label, onDetach, ...attrs }: BoundVariableButtonProps) {
  return (
    <Tip label={label}>
      <button
        {...attrs}
        aria-label={label}
        className="shrink-0 cursor-pointer border-none bg-transparent p-0 text-violet-400 hover:text-surface"
        onClick={onDetach}
      >
        <IconDiamondMinus className="size-3.5" />
      </button>
    </Tip>
  )
}
