// packages/react/src/components/properties/FillSection.tsx
import { Plus, Trash2 } from 'lucide-react'

import { DEFAULT_SHAPE_FILL } from '@open-pencil/core/constants'
import type { Fill, SceneNode } from '@open-pencil/scene-graph'

import { ColorRow } from '#react/components/properties/ColorRow'
import { IconButton } from '#react/components/ui/IconButton'
import { PanelSection } from '#react/components/ui/panel/PanelSection'
import { useEditor } from '#react/editor/context'
import { useSelectionState } from '#react/editor/selection-state/use'
import { useSceneComputed } from '#react/internal/scene-computed/use'
import { useI18n } from '#react/i18n'

export function FillSection() {
  const editor = useEditor()
  const { hasSelection } = useSelectionState()
  const { panels } = useI18n()
  const nodes = useSceneComputed(() => editor.getSelectedNodes())
  if (!hasSelection) return null

  const fills = nodes[0]?.fills ?? []
  const empty = fills.length === 0

  function patchNodeFills(node: SceneNode, mutator: (fills: Fill[]) => Fill[], label: string) {
    editor.updateNodeWithUndo(node.id, { fills: mutator(structuredClone(node.fills)) }, label)
  }

  function addFill() {
    for (const node of nodes) {
      patchNodeFills(node, (current) => [...current, structuredClone(DEFAULT_SHAPE_FILL)], 'Add fill')
    }
  }

  return (
    <PanelSection
      label={panels.fill}
      empty={empty}
      actions={
        <IconButton label={panels.addFill} onClick={addFill}>
          <Plus className="size-3.5" />
        </IconButton>
      }
    >
      {fills.map((fill, index) => (
          <div key={`${nodes[0]?.id ?? 'fill'}:${index}:${fill.visible ? 'visible' : 'hidden'}`} className="mb-1.5 last:mb-0">
          <div className="flex items-start gap-1">
            <div className="min-w-0 flex-1">
              <ColorRow
                color={fill.color}
                opacity={fill.opacity}
                label={panels.fill}
                onColor={(color) => {
                  for (const node of nodes) {
                    patchNodeFills(
                      node,
                      (current) =>
                        current.map((item, itemIndex) =>
                          itemIndex === index && item.type === 'SOLID' ? { ...item, color } : item
                        ),
                      'Update fill'
                    )
                  }
                }}
                onOpacity={(opacity) => {
                  for (const node of nodes) {
                    patchNodeFills(
                      node,
                      (current) =>
                        current.map((item, itemIndex) =>
                          itemIndex === index ? { ...item, opacity } : item
                        ),
                      'Update fill'
                    )
                  }
                }}
              />
            </div>
            <IconButton
              label={panels.removeFill}
              onClick={() => {
                for (const node of nodes) {
                  patchNodeFills(
                    node,
                    (current) => current.filter((_, itemIndex) => itemIndex !== index),
                    'Remove fill'
                  )
                }
              }}
            >
              <Trash2 className="size-3.5" />
            </IconButton>
          </div>
        </div>
      ))}
    </PanelSection>
  )
}

// src/components/properties/FillSection.vue
<script setup lang="ts">
import { useFillControls, useOkHCL, useI18n, inputValue } from '@open-pencil/vue'
import { colorToHexRaw, parseColor } from '@open-pencil/core/color'

import FillPicker from '@/components/fill-picker/FillPicker.vue'
import PropertyListRoot from '@/components/properties/PropertyListRoot.vue'
import IconButton from '@/components/ui/IconButton.vue'
import PanelSection from '@/components/ui/panel/PanelSection.vue'
import ColorStyleRow from '@/components/properties/ColorStyleRow.vue'
import {
  boundVariableSwatchBackground,
  displayFillWithBoundVariable
} from '@/components/properties/color-style-row'
import { fillLabel } from '@/components/properties/fill-label'
import { createFillOkhclAdapter } from '@/components/properties/fill-okhcl'

import type { Fill, SceneNode } from '@open-pencil/scene-graph'

const fillCtx = useFillControls()
const okhcl = useOkHCL()
const { panels } = useI18n()

function updateFill(
  activeNode: SceneNode | null | undefined,
  index: number,
  fill: Fill,
  update: (index: number, fill: Fill) => void
) {
  if (activeNode && fillCtx.getBoundVariable(activeNode.id, index)) {
    fillCtx.unbindVariable(activeNode.id, index)
  }
  update(index, fill)
}

function updateFillHex(
  activeNode: SceneNode | null | undefined,
  index: number,
  fill: Fill,
  hex: string,
  update: (index: number, fill: Fill) => void
) {
  if (fill.type !== 'SOLID') return
  const parsed = parseColor(hex.startsWith('#') ? hex : `#${hex}`)
  if (!parsed) return
  updateFill(activeNode, index, { ...fill, color: { ...parsed, a: fill.color.a } }, update)
}
</script>

<template>
  <PropertyListRoot
    v-slot="{ items, isMixed, activeNode, actions }"
    prop-key="fills"
    :label="panels.fill"
  >
    <PanelSection :label="panels.fill" data-test-id="fill-section">
      <template #actions>
        <IconButton
          :label="panels.addFill"
          data-test-id="fill-section-add"
          @click="actions.add({ ...fillCtx.defaultFill })"
        >
          <icon-lucide-plus class="size-3.5" />
        </IconButton>
      </template>
      <p v-if="isMixed" class="text-[11px] text-muted">{{ panels.mixedFillsHelp }}</p>
      <ColorStyleRow
        v-for="(fill, i) in items"
        :key="`${i}:${fill.visible ? 'visible' : 'hidden'}`"
        :item="fill"
        :index="i"
        :active-node-id="activeNode?.id ?? null"
        :binding-api="fillCtx"
        :variable-color="fill.type === 'SOLID' ? fill.color : undefined"
        data-test-id="fill-item"
        :data-test-index="i"
        :remove-label="panels.removeFill"
        @patch="actions.patch(i, $event)"
        @toggle-visibility="actions.toggleVisibility(i)"
        @remove="actions.remove(i)"
      >
        <FillPicker
          :fill="activeNode ? displayFillWithBoundVariable(fillCtx, activeNode.id, i, fill) : fill"
          :okhcl="createFillOkhclAdapter(okhcl, activeNode, i)"
          :swatch-background="
            activeNode ? boundVariableSwatchBackground(fillCtx, activeNode.id, i) : undefined
          "
          @update="updateFill(activeNode, i, $event, actions.update)"
        />

        <input
          v-if="
            fill.type === 'SOLID' && !(activeNode && fillCtx.getBoundVariable(activeNode.id, i))
          "
          data-test-id="fill-hex-input"
          class="min-w-0 flex-1 border-none bg-transparent font-mono text-xs text-surface outline-none"
          :value="colorToHexRaw(fill.color)"
          maxlength="6"
          @change="updateFillHex(activeNode, i, fill, inputValue($event), actions.update)"
        />
        <span
          v-else
          class="min-w-0 flex-1 truncate font-mono text-xs"
          :class="
            activeNode && fillCtx.getBoundVariable(activeNode.id, i)
              ? 'rounded bg-violet-500/10 px-1 text-violet-400'
              : 'text-surface'
          "
        >
          {{ fillLabel(fill, activeNode ? fillCtx.getBoundVariable(activeNode.id, i) : undefined) }}
        </span>
      </ColorStyleRow>
    </PanelSection>
  </PropertyListRoot>
</template>
