// src/react_app/properties/FillSection.tsx
import { FillPicker } from '@/react_app/pickers/FillPicker'
import { ColorStyleRow } from '@/react_app/properties/ColorStyleRow'
import { iconButton } from '@/react_app/ui/iconButton'
import { sectionLabel, sectionWrapper } from '@/react_app/ui/section'
import { colorToHexRaw } from '@open-pencil/core'
import { PropertyListRoot, useFillControls, useI18n, useOkHCL } from '@open-pencil/react'

import type { Fill } from '@open-pencil/core'

export function FillSection() {
  const fillCtx = useFillControls()
  const okhcl = useOkHCL()
  const { panels } = useI18n()

  return (
    <PropertyListRoot propKey="fills" label={panels.fill}>
      {({ items, isMixed, activeNode, add, remove, update, patch, toggleVisibility }) => (
        <div data-test-id="fill-section" className={sectionWrapper()}>
          <div className="flex items-center justify-between">
            <label className={sectionLabel()}>{panels.fill}</label>
            <button
              type="button"
              data-test-id="fill-section-add"
              className={iconButton()}
              onClick={() => add({ ...fillCtx.defaultFill })}
            >
              +
            </button>
          </div>
          {isMixed ? <p className="text-[11px] text-muted">{panels.mixedFillsHelp}</p> : null}
          {(items as Fill[]).map((fill, i) => (
            <ColorStyleRow
              key={`${i}:${fill.visible ? 'visible' : 'hidden'}`}
              item={fill}
              index={i}
              activeNodeId={activeNode?.id ?? null}
              bindingApi={fillCtx}
              visibilityTestId={`fill-visibility-${i}`}
              unbindTestId="fill-unbind-variable"
              data-test-id="fill-item"
              data-test-index={i}
              onPatch={(changes) => patch(i, changes)}
              onToggleVisibility={() => toggleVisibility(i)}
              onRemove={() => remove(i)}
            >
              <FillPicker
                fill={fill}
                okhcl={
                  activeNode
                    ? {
                        fieldFormat: okhcl.getFieldFormat(activeNode, i, 'fill'),
                        fieldOptions: okhcl.fieldOptions,
                        okhcl: okhcl.getFillOkHCLColor(activeNode, i),
                        ...okhcl.getFillPreviewInfo(activeNode, i),
                        setFieldFormat: (event) => okhcl.setFillFieldFormat(activeNode, i, event),
                        updateOkHCL: (event) => okhcl.updateFillOkHCL(activeNode, i, event)
                      }
                    : null
                }
                onUpdate={(f) => update(i, f)}
              />

              {activeNode && fillCtx.getBoundVariable(activeNode.id, i) ? (
                <span className="min-w-0 flex-1 truncate rounded bg-violet-500/10 px-1 font-mono text-xs text-violet-400">
                  {fillCtx.getBoundVariable(activeNode.id, i)!.name}
                </span>
              ) : (
                <span className="min-w-0 flex-1 font-mono text-xs text-surface">
                  {fill.type === 'SOLID'
                    ? colorToHexRaw(fill.color)
                    : fill.type.startsWith('GRADIENT')
                      ? fill.type.replace('GRADIENT_', '')
                      : fill.type}
                </span>
              )}
            </ColorStyleRow>
          ))}
        </div>
      )}
    </PropertyListRoot>
  )
}

// src/components/properties/FillSection.vue
<script setup lang="ts">
import { PropertyListRoot, useFillControls, useOkHCL, useI18n, inputValue } from '@open-pencil/vue'
import { colorToHexRaw, parseColor } from '@open-pencil/core/color'

import FillPicker from '@/components/FillPicker.vue'
import Tip from '@/components/ui/Tip.vue'
import ColorStyleRow from '@/components/properties/ColorStyleRow.vue'
import {
  boundVariableSwatchBackground,
  displayFillWithBoundVariable
} from '@/components/properties/color-style-row'
import { fillLabel } from '@/components/properties/fill-label'
import { createFillOkhclAdapter } from '@/components/properties/fill-okhcl'
import { useIconButtonUI } from '@/components/ui/icon-button'
import { useSectionUI } from '@/components/ui/section'

import type { Fill, SceneNode } from '@open-pencil/core/scene-graph'

const fillCtx = useFillControls()
const okhcl = useOkHCL()
const { panels } = useI18n()
const sectionCls = useSectionUI()

function updateFill(
  activeNode: SceneNode | null | undefined,
  index: number,
  fill: Fill,
  update: (index: number, fill: Fill) => void
) {
  if (activeNode && fillCtx.getBoundVariable(activeNode.id, index)) {
    fillCtx.unbindVariable(activeNode.id, index)
  }
  update(index, fill)
}

function updateFillHex(
  activeNode: SceneNode | null | undefined,
  index: number,
  fill: Fill,
  hex: string,
  update: (index: number, fill: Fill) => void
) {
  if (fill.type !== 'SOLID') return
  const parsed = parseColor(hex.startsWith('#') ? hex : `#${hex}`)
  if (!parsed) return
  updateFill(activeNode, index, { ...fill, color: { ...parsed, a: fill.color.a } }, update)
}
</script>

<template>
  <PropertyListRoot
    v-slot="{ items, isMixed, activeNode, actions }"
    prop-key="fills"
    :label="panels.fill"
  >
    <div data-test-id="fill-section" :class="sectionCls.wrapper">
      <div class="flex items-center justify-between">
        <label :class="sectionCls.label">{{ panels.fill }}</label>
        <Tip :label="panels.addFill">
          <button
            data-test-id="fill-section-add"
            :class="useIconButtonUI().base"
            @click="actions.add({ ...fillCtx.defaultFill })"
          >
            +
          </button>
        </Tip>
      </div>
      <p v-if="isMixed" class="text-[11px] text-muted">{{ panels.mixedFillsHelp }}</p>
      <ColorStyleRow
        v-for="(fill, i) in items as Fill[]"
        :key="`${i}:${fill.visible ? 'visible' : 'hidden'}`"
        :item="fill"
        :index="i"
        :active-node-id="activeNode?.id ?? null"
        :binding-api="fillCtx"
        :variable-color="fill.type === 'SOLID' ? fill.color : undefined"
        :visibility-test-id="`fill-visibility-${i}`"
        :apply-variable-test-id="`fill-apply-variable-${i}`"
        unbind-test-id="fill-unbind-variable"
        data-test-id="fill-item"
        :data-test-index="i"
        :remove-label="panels.removeFill"
        @patch="actions.patch(i, $event)"
        @toggle-visibility="actions.toggleVisibility(i)"
        @remove="actions.remove(i)"
      >
        <FillPicker
          :fill="activeNode ? displayFillWithBoundVariable(fillCtx, activeNode.id, i, fill) : fill"
          :okhcl="createFillOkhclAdapter(okhcl, activeNode, i)"
          :swatch-background="
            activeNode ? boundVariableSwatchBackground(fillCtx, activeNode.id, i) : undefined
          "
          @update="updateFill(activeNode, i, $event, actions.update)"
        />

        <input
          v-if="
            fill.type === 'SOLID' && !(activeNode && fillCtx.getBoundVariable(activeNode.id, i))
          "
          data-test-id="fill-hex-input"
          class="min-w-0 flex-1 border-none bg-transparent font-mono text-xs text-surface outline-none"
          :value="colorToHexRaw(fill.color)"
          maxlength="6"
          @change="updateFillHex(activeNode, i, fill, inputValue($event), actions.update)"
        />
        <span
          v-else
          class="min-w-0 flex-1 truncate font-mono text-xs"
          :class="
            activeNode && fillCtx.getBoundVariable(activeNode.id, i)
              ? 'rounded bg-violet-500/10 px-1 text-violet-400'
              : 'text-surface'
          "
        >
          {{ fillLabel(fill, activeNode ? fillCtx.getBoundVariable(activeNode.id, i) : undefined) }}
        </span>
      </ColorStyleRow>
    </div>
  </PropertyListRoot>
</template>
