// packages/react/src/components/properties/PositionSection.tsx
import {
  AlignCenterHorizontal,
  AlignCenterVertical,
  AlignEndHorizontal,
  AlignEndVertical,
  AlignStartHorizontal,
  AlignStartVertical
} from 'lucide-react'

import { IconButton } from '#react/components/ui/IconButton'
import { NumberField } from '#react/components/inputs/NumberField'
import { PanelGrid } from '#react/components/ui/panel/PanelGrid'
import { PanelSection } from '#react/components/ui/panel/PanelSection'
import { Tip } from '#react/components/ui/Tip'
import { useNodePropCommit } from '#react/components/properties/useNodePropCommit'
import { useSelectionState } from '#react/editor/selection-state/use'
import { useSceneComputed } from '#react/internal/scene-computed/use'
import { useI18n } from '#react/i18n'

export function PositionSection() {
  const { editor, commit } = useNodePropCommit()
  const { selectedNode, selectedCount, hasSelection, selectedIds } = useSelectionState()
  const { panels } = useI18n()
  const node = useSceneComputed(() => editor.getSelectedNode() ?? selectedNode)
  if (!hasSelection || !node) return null

  const isMulti = selectedCount > 1
  const ids = [...selectedIds]

  function align(axis: 'horizontal' | 'vertical', pos: 'min' | 'center' | 'max') {
    editor.alignNodes(ids, axis, pos)
  }

  return (
    <PanelSection label={panels.position}>
      <div role="toolbar" aria-label={panels.position} className="mb-1.5 flex justify-between">
        <div className="flex gap-0.5">
          <IconButton label={panels.alignLeft} size="xs" onClick={() => align('horizontal', 'min')}>
            <AlignStartVertical className="size-3.5" />
          </IconButton>
          <IconButton
            label={panels.alignCenterHorizontally}
            size="xs"
            onClick={() => align('horizontal', 'center')}
          >
            <AlignCenterVertical className="size-3.5" />
          </IconButton>
          <IconButton label={panels.alignRight} size="xs" onClick={() => align('horizontal', 'max')}>
            <AlignEndVertical className="size-3.5" />
          </IconButton>
        </div>
        <div className="flex gap-0.5">
          <IconButton label={panels.alignTop} size="xs" onClick={() => align('vertical', 'min')}>
            <AlignStartHorizontal className="size-3.5" />
          </IconButton>
          <IconButton
            label={panels.alignCenterVertically}
            size="xs"
            onClick={() => align('vertical', 'center')}
          >
            <AlignCenterHorizontal className="size-3.5" />
          </IconButton>
          <IconButton label={panels.alignBottom} size="xs" onClick={() => align('vertical', 'max')}>
            <AlignEndHorizontal className="size-3.5" />
          </IconButton>
        </div>
      </div>

      <PanelGrid columns={2}>
        <Tip label={panels.xAxis}>
          <NumberField
            icon="X"
            data-property="x"
            aria-label={panels.xAxis}
            value={Math.round(node.x)}
            onCommit={(value, previous) => commit('x', value, previous)}
          />
        </Tip>
        <Tip label={panels.yAxis}>
          <NumberField
            icon="Y"
            data-property="y"
            aria-label={panels.yAxis}
            value={Math.round(node.y)}
            onCommit={(value, previous) => commit('y', value, previous)}
          />
        </Tip>
      </PanelGrid>

      <PanelGrid columns={2} className="mt-1.5">
        <Tip label={panels.width}>
          <NumberField
            icon="W"
            data-property="width"
            aria-label={panels.width}
            min={1}
            value={Math.round(node.width)}
            onCommit={(value, previous) => commit('width', value, previous)}
          />
        </Tip>
        <Tip label={panels.height}>
          <NumberField
            icon="H"
            data-property="height"
            aria-label={panels.height}
            min={1}
            value={Math.round(node.height)}
            onCommit={(value, previous) => commit('height', value, previous)}
          />
        </Tip>
      </PanelGrid>

      {isMulti ? null : (
        <PanelGrid columns={2} className="mt-1.5">
          <Tip label={panels.rotation}>
            <NumberField
              icon="R"
              data-property="rotation"
              aria-label={panels.rotation}
              value={Math.round(node.rotation)}
              onCommit={(value, previous) => commit('rotation', value, previous)}
            />
          </Tip>
        </PanelGrid>
      )}
    </PanelSection>
  )
}

// src/components/properties/PositionSection.vue
<script setup lang="ts">
import { PositionControlsRoot, useI18n } from '@open-pencil/vue'

import { useEditorStore } from '@/app/editor/active-store'
import NumberField from '@/components/inputs/NumberField.vue'
import IconButton from '@/components/ui/button/IconButton.vue'
import Tip from '@/components/ui/overlay/Tip.vue'
import PanelGrid from '@/components/ui/panel/PanelGrid.vue'
import PanelSection from '@/components/ui/panel/PanelSection.vue'

const { panels } = useI18n()
const store = useEditorStore()

function handleAlign(
  nodeAlign: (axis: 'horizontal' | 'vertical', pos: 'min' | 'center' | 'max') => void,
  axis: 'horizontal' | 'vertical',
  pos: 'min' | 'center' | 'max'
) {
  const editState = store.state.nodeEditState
  if (editState && editState.selectedVertexIndices.size >= 2) {
    store.nodeEditAlignVertices(axis, pos)
  } else {
    nodeAlign(axis, pos)
  }
}
</script>

<template>
  <PositionControlsRoot
    v-slot="{ active, isMulti, xValue, yValue, wValue, hValue, rotationValue, actions }"
  >
    <PanelSection v-if="active" :label="panels.position">
      <div role="toolbar" :aria-label="panels.position" class="mb-1.5 flex justify-between">
        <div class="flex gap-0.5">
          <IconButton
            :label="panels.alignLeft"
            size="xs"
            @click="handleAlign(actions.align, 'horizontal', 'min')"
          >
            <icon-lucide-align-start-vertical class="size-3.5" />
          </IconButton>
          <IconButton
            :label="panels.alignCenterHorizontally"
            size="xs"
            @click="handleAlign(actions.align, 'horizontal', 'center')"
          >
            <icon-lucide-align-center-vertical class="size-3.5" />
          </IconButton>
          <IconButton
            :label="panels.alignRight"
            size="xs"
            @click="handleAlign(actions.align, 'horizontal', 'max')"
          >
            <icon-lucide-align-end-vertical class="size-3.5" />
          </IconButton>
        </div>
        <div class="flex gap-0.5">
          <IconButton
            :label="panels.alignTop"
            size="xs"
            @click="handleAlign(actions.align, 'vertical', 'min')"
          >
            <icon-lucide-align-start-horizontal class="size-3.5" />
          </IconButton>
          <IconButton
            :label="panels.alignCenterVertically"
            size="xs"
            @click="handleAlign(actions.align, 'vertical', 'center')"
          >
            <icon-lucide-align-center-horizontal class="size-3.5" />
          </IconButton>
          <IconButton
            :label="panels.alignBottom"
            size="xs"
            @click="handleAlign(actions.align, 'vertical', 'max')"
          >
            <icon-lucide-align-end-horizontal class="size-3.5" />
          </IconButton>
        </div>
      </div>

      <PanelGrid :columns="2">
        <Tip :label="panels.xAxis">
          <NumberField
            icon="X"
            data-property="x"
            :aria-label="panels.xAxis"
            :model-value="xValue"
            @update:model-value="actions.updateProp('x', $event)"
            @commit="(v: number, p: number) => actions.commitProp('x', v, p)"
          />
        </Tip>
        <Tip :label="panels.yAxis">
          <NumberField
            icon="Y"
            data-property="y"
            :aria-label="panels.yAxis"
            :model-value="yValue"
            @update:model-value="actions.updateProp('y', $event)"
            @commit="(v: number, p: number) => actions.commitProp('y', v, p)"
          />
        </Tip>
      </PanelGrid>

      <PanelGrid v-if="isMulti" :columns="2" class="mt-1.5">
        <Tip :label="panels.width">
          <NumberField
            icon="W"
            data-property="width"
            :aria-label="panels.width"
            :model-value="wValue"
            :min="1"
            @update:model-value="actions.updateProp('width', $event)"
            @commit="(v: number, p: number) => actions.commitProp('width', v, p)"
          />
        </Tip>
        <Tip :label="panels.height">
          <NumberField
            icon="H"
            data-property="height"
            :aria-label="panels.height"
            :model-value="hValue"
            :min="1"
            @update:model-value="actions.updateProp('height', $event)"
            @commit="(v: number, p: number) => actions.commitProp('height', v, p)"
          />
        </Tip>
      </PanelGrid>

      <PanelGrid :columns="2" class="mt-1.5">
        <Tip :label="panels.rotation">
          <NumberField
            suffix="°"
            data-property="rotation"
            :aria-label="panels.rotation"
            :model-value="rotationValue"
            :min="-360"
            :max="360"
            @update:model-value="actions.updateProp('rotation', $event)"
            @commit="(v: number, p: number) => actions.commitProp('rotation', v, p)"
          >
            <template #icon>
              <icon-lucide-rotate-cw class="size-3" />
            </template>
          </NumberField>
        </Tip>
        <div class="flex h-6 items-center justify-end gap-0.5">
          <IconButton :label="panels.flipHorizontal" size="xs" @click="actions.flip('horizontal')">
            <icon-lucide-flip-horizontal-2 class="size-3.5" />
          </IconButton>
          <IconButton :label="panels.flipVertical" size="xs" @click="actions.flip('vertical')">
            <icon-lucide-flip-vertical-2 class="size-3.5" />
          </IconButton>
          <IconButton :label="panels.rotate90" size="xs" @click="actions.rotate(90)">
            <icon-lucide-rotate-cw-square class="size-3.5" />
          </IconButton>
        </div>
      </PanelGrid>
    </PanelSection>
  </PositionControlsRoot>
</template>
