// src/components/properties/StrokeSection.vue
<script setup lang="ts">
import { ref } from 'vue'

import {
  applySolidStrokeColor,
  BindableValueRoot,
  isStrokeCapValue,
  MIXED,
  useColorBindingProvider,
  useI18n,
  useOkHCL,
  useStrokeControls
} from '@open-pencil/vue'

import ColorPicker from '@/components/ColorPicker/ColorPicker.vue'
import NumberField from '@/components/inputs/NumberField.vue'
import PropertyItemRow from '@/components/properties/item-list/PropertyItemRow.vue'
import PaintField from '@/components/properties/paint/PaintField.vue'
import PaintValue from '@/components/properties/paint/PaintValue.vue'
import {
  applyPaintMutation,
  cancelPaintMutation,
  commitPaintMutation,
  paintBindingTargets
} from '@/components/properties/paint/binding'
import { createStrokeOkhclAdapter } from '@/components/properties/paint/okhcl'
import PropertyListRoot from '@/components/properties/PropertyListRoot.vue'
import SharedStyleField from '@/components/properties/shared-style/SharedStyleField.vue'
import VariableBindingPicker from '@/components/properties/binding/VariableBindingPicker.vue'
import AppSelect from '@/components/ui/AppSelect.vue'
import FillSwatch from '@/components/ui/FillSwatch.vue'
import IconButton from '@/components/ui/IconButton.vue'
import PanelFieldGroup from '@/components/ui/panel/PanelFieldGroup.vue'
import PanelGrid from '@/components/ui/panel/PanelGrid.vue'
import PanelSection from '@/components/ui/panel/PanelSection.vue'
import SegmentedControl from '@/components/ui/SegmentedControl.vue'
import Tip from '@/components/ui/Tip.vue'

import { colorToHexRaw } from '@open-pencil/core/color'
import type { Color, Fill, SceneNode, Stroke } from '@open-pencil/scene-graph'
import type { BindableValueActions } from '@open-pencil/vue'

const strokeCtx = useStrokeControls()
const { advancedActive, cap, join, miterLimit } = strokeCtx
const colorProvider = useColorBindingProvider()
const okhcl = useOkHCL()
const { panels, common } = useI18n()
const expandedSides = ref(false)

function strokePreview(stroke: Stroke, color: Color): Fill {
  return {
    type: 'SOLID',
    color,
    opacity: stroke.opacity,
    visible: stroke.visible
  }
}

function updateStrokeColor(
  binding: BindableValueActions<Color>,
  flush: () => void,
  color: Color,
  patch: (changes: Partial<Stroke>) => void,
  commit: boolean
) {
  if (!applyPaintMutation(binding, flush, () => patch(applySolidStrokeColor(color)))) return
  if (commit) commitPaintMutation(binding)
}

function setCap(value: string) {
  if (isStrokeCapValue(value)) {
    strokeCtx.setCap(value)
  }
}

function setJoin(value: string) {
  if (value === 'MITER' || value === 'BEVEL' || value === 'ROUND') {
    strokeCtx.setJoin(value)
  }
}

function onToggleSides(activeNode: SceneNode | null) {
  if (!activeNode) return
  const next = !expandedSides.value
  expandedSides.value = next
  if (next && !activeNode.independentStrokeWeights) {
    const weight = activeNode.strokes[0]?.weight ?? 1
    strokeCtx.selectSide('CUSTOM', {
      ...activeNode,
      borderTopWeight: weight,
      borderRightWeight: weight,
      borderBottomWeight: weight,
      borderLeftWeight: weight
    })
  } else if (!next && activeNode.independentStrokeWeights) {
    strokeCtx.selectSide('ALL', activeNode)
  }
}
</script>

<template>
  <PropertyListRoot
    v-slot="{ items, isMixed, activeNode, selectedNodeIds, flush, actions }"
    prop-key="strokes"
    :label="panels.stroke"
  >
    <PanelSection :label="panels.stroke" :empty="!isMixed && items.length === 0">
      <template #actions>
        <IconButton :label="panels.addStroke" @click="actions.add(strokeCtx.defaultStroke)">
          <icon-lucide-plus class="size-3.5" />
        </IconButton>
      </template>

      <SharedStyleField kind="stroke" :label="panels.strokeStyle" />

      <p v-if="isMixed" class="text-[11px] text-muted">{{ panels.mixedStrokesHelp }}</p>

      <PropertyItemRow
        v-for="(stroke, index) in items"
        :key="`${index}:${stroke.visible ? 'visible' : 'hidden'}`"
        prop-key="strokes"
        :index="index"
        :visibility-label="panels.toggleVisibility"
        :remove-label="panels.removeStroke"
      >
        <BindableValueRoot
          v-slot="binding"
          :provider="colorProvider"
          :targets="paintBindingTargets(selectedNodeIds, 'strokes', index)"
          :value="stroke.color"
          batch-label="Change stroke color"
        >
          <PaintField
            :opacity="stroke.opacity"
            :opacity-label="panels.opacity"
            @update:opacity="actions.patch(index, { opacity: $event })"
          >
            <template #preview>
              <ColorPicker
                :color="binding.resolvedValue ?? stroke.color"
                :okhcl="createStrokeOkhclAdapter(okhcl, activeNode, index)"
                @update="
                  updateStrokeColor(
                    binding.actions,
                    flush,
                    $event,
                    (changes) => actions.patch(index, changes),
                    false
                  )
                "
                @open-change="!$event && commitPaintMutation(binding.actions)"
                @cancel="cancelPaintMutation(binding.actions)"
              >
                <template #trigger>
                  <button
                    type="button"
                    :aria-label="panels.stroke"
                    class="size-4 shrink-0 cursor-pointer rounded-sm border-0 bg-transparent p-0"
                  >
                    <FillSwatch
                      :fill="strokePreview(stroke, binding.resolvedValue ?? stroke.color)"
                      class="size-full"
                    />
                  </button>
                </template>
              </ColorPicker>
            </template>

            <template #value>
              <PaintValue
                :color="stroke.color"
                :resolved-color="binding.resolvedValue"
                :variable-name="binding.variable?.name"
                :label="panels.stroke"
                @update="
                  updateStrokeColor(
                    binding.actions,
                    flush,
                    $event,
                    (changes) => actions.patch(index, changes),
                    true
                  )
                "
              />
            </template>

            <template #binding>
              <VariableBindingPicker
                :trigger-label="panels.applyVariable"
                :search-placeholder="common.search"
                :empty-label="panels.noVariablesFound"
                :detach-label="panels.detachVariable"
                :create-label="
                  panels.createColorVariable({ value: `#${colorToHexRaw(stroke.color)}` })
                "
                :create-name-placeholder="panels.variableName"
                :create-submit-label="panels.create"
              />
            </template>
          </PaintField>
        </BindableValueRoot>
      </PropertyItemRow>

      <div v-if="!isMixed && items.length > 0" class="mt-1 flex items-center gap-1.5">
        <AppSelect
          :label="panels.strokeType"
          :ui="{ trigger: 'w-[88px] flex-none' }"
          :model-value="strokeCtx.currentAlign(activeNode)"
          :options="strokeCtx.alignOptions"
          data-property="stroke-align"
          @update:model-value="strokeCtx.updateAlign($event as Stroke['align'], activeNode)"
        />
        <Tip :label="panels.strokeWeight">
          <NumberField
            v-if="!expandedSides"
            class="flex-1"
            icon="W"
            :model-value="items[0]?.weight ?? 1"
            :min="0"
            data-property="stroke-weight"
            @update:model-value="actions.patch(0, { weight: $event })"
          />
        </Tip>
        <IconButton
          :label="panels.strokeSides"
          size="xs"
          class="size-[26px] shrink-0"
          :active="expandedSides"
          data-property="stroke-sides"
          @click="onToggleSides(activeNode)"
        >
          <icon-lucide-layout-grid class="size-3.5" />
        </IconButton>
      </div>

      <div v-if="!isMixed && items.length > 0" class="mt-1.5 flex items-center gap-1.5">
        <IconButton
          :label="panels.strokeDash"
          size="xs"
          class="shrink-0"
          :active="strokeCtx.dashState(items[0]).on"
          data-property="stroke-dash"
          @click="actions.patch(0, strokeCtx.toggleDash(items[0]))"
        >
          <span class="flex items-center gap-0.5">
            <icon-lucide-minus class="size-2.5" />
            <icon-lucide-minus class="size-2.5" />
          </span>
        </IconButton>
        <template v-if="strokeCtx.dashState(items[0]).on">
          <NumberField
            class="flex-1"
            icon="D"
            :model-value="items[0]?.dashPattern?.[0] ?? 6"
            :min="1"
            data-property="stroke-dash-length"
            @update:model-value="actions.patch(0, strokeCtx.setDash(items[0], $event))"
          />
          <NumberField
            class="flex-1"
            icon="G"
            :model-value="items[0]?.dashPattern?.[1] ?? items[0]?.dashPattern?.[0] ?? 6"
            :min="1"
            data-property="stroke-dash-gap"
            @update:model-value="actions.patch(0, strokeCtx.setGap(items[0], $event))"
          />
        </template>
      </div>

      <PanelGrid v-if="advancedActive" :columns="3" class="mt-1.5">
        <PanelFieldGroup :label="panels.strokeCap">
          <SegmentedControl
            :model-value="cap === MIXED ? 'MIXED' : cap"
            :options="strokeCtx.capOptions"
            :label="panels.strokeCap"
            data-property="stroke-cap"
            @update:model-value="setCap"
          >
            <template #option="{ option }">
              <Tip :label="option.label">
                <icon-lucide-minus v-if="option.value === 'NONE'" class="size-3" />
                <icon-lucide-circle v-else-if="option.value === 'ROUND'" class="size-2.5" />
                <icon-lucide-square v-else-if="option.value === 'SQUARE'" class="size-2.5" />
                <icon-lucide-arrow-right
                  v-else-if="option.value === 'ARROW_LINES'"
                  class="size-3"
                />
                <icon-lucide-triangle v-else class="size-2.5" />
              </Tip>
            </template>
          </SegmentedControl>
        </PanelFieldGroup>

        <PanelFieldGroup :label="panels.strokeJoin">
          <SegmentedControl
            :model-value="join === MIXED ? 'MIXED' : join"
            :options="strokeCtx.joinOptions"
            :label="panels.strokeJoin"
            data-property="stroke-join"
            @update:model-value="setJoin"
          >
            <template #option="{ option }">
              <Tip :label="option.label">
                <icon-lucide-corner-up-right v-if="option.value === 'MITER'" class="size-3" />
                <icon-lucide-triangle v-else-if="option.value === 'BEVEL'" class="size-2.5" />
                <icon-lucide-circle v-else class="size-2.5" />
              </Tip>
            </template>
          </SegmentedControl>
        </PanelFieldGroup>

        <PanelFieldGroup :label="panels.strokeMiterLimit">
          <NumberField
            :model-value="miterLimit"
            :min="1"
            data-property="stroke-miter-limit"
            :aria-label="panels.strokeMiterLimit"
            @update:model-value="strokeCtx.updateMiterLimit"
            @commit="strokeCtx.commitMiterLimit"
          >
            <template #icon>
              <icon-lucide-triangle-right class="size-3" />
            </template>
          </NumberField>
        </PanelFieldGroup>
      </PanelGrid>

      <div
        v-if="!isMixed && items.length > 0 && expandedSides"
        class="mt-1.5 grid grid-cols-2 gap-1.5"
      >
        <NumberField
          v-for="side in strokeCtx.borderSides"
          :key="side"
          :label="side[0].toUpperCase()"
          :model-value="strokeCtx.borderWeight(activeNode, side)"
          :min="0"
          :data-property="`stroke-${side}-weight`"
          @update:model-value="strokeCtx.updateBorderWeight(side, $event, activeNode)"
        />
      </div>
    </PanelSection>
  </PropertyListRoot>
</template>

// src/components/properties/StrokeSection.tsx
import IconLucideCircle from '~icons/lucide/circle'
import IconLucideCornerUpRight from '~icons/lucide/corner-up-right'
import IconLucideLayoutGrid from '~icons/lucide/layout-grid'
import IconLucideMinus from '~icons/lucide/minus'
import IconLucidePlus from '~icons/lucide/plus'
import IconLucideSquare from '~icons/lucide/square'
import IconLucideTriangle from '~icons/lucide/triangle'
import IconLucideTriangleRight from '~icons/lucide/triangle-right'
import {
  applySolidStrokeColor,
  BindableValueRoot,
  MIXED,
  useColorBindingProvider,
  useI18n,
  useOkHCL,
  useStrokeControls,
  type BindableValueActions
} from '@open-pencil/react'
import { memo, useCallback, useState } from 'react'

import { colorToHexRaw } from '@open-pencil/core/color'
import ColorPicker from '@/components/ColorPicker/ColorPicker'
import NumberField from '@/components/inputs/NumberField'
import PropertyItemRow from '@/components/properties/item-list/PropertyItemRow'
import PaintField from '@/components/properties/paint/PaintField'
import PaintValue from '@/components/properties/paint/PaintValue'
import {
  applyPaintMutation,
  cancelPaintMutation,
  commitPaintMutation,
  paintBindingTargets
} from '@/components/properties/paint/binding'
import { createStrokeOkhclAdapter } from '@/components/properties/paint/okhcl'
import PropertyListRoot from '@/components/properties/PropertyListRoot'
import SharedStyleField from '@/components/properties/shared-style/SharedStyleField'
import VariableBindingPicker from '@/components/properties/binding/VariableBindingPicker'
import AppSelect from '@/components/ui/AppSelect'
import FillSwatch from '@/components/ui/FillSwatch'
import IconButton from '@/components/ui/IconButton'
import PanelFieldGroup from '@/components/ui/panel/PanelFieldGroup'
import PanelGrid from '@/components/ui/panel/PanelGrid'
import PanelSection from '@/components/ui/panel/PanelSection'
import SegmentedControl from '@/components/ui/SegmentedControl'
import Tip from '@/components/ui/Tip'

import type { Color, Fill, SceneNode, Stroke } from '@open-pencil/scene-graph'

function strokePreview(stroke: Stroke, color: Color): Fill {
  return {
    type: 'SOLID',
    color,
    opacity: stroke.opacity,
    visible: stroke.visible
  }
}

function updateStrokeColor(
  binding: BindableValueActions<Color>,
  flush: () => void,
  color: Color,
  patch: (changes: Partial<Stroke>) => void,
  commit: boolean
) {
  if (!applyPaintMutation(binding, flush, () => patch(applySolidStrokeColor(color)))) return
  if (commit) commitPaintMutation(binding)
}

export const StrokeSection = memo(function StrokeSection() {
  const strokeCtx = useStrokeControls()
  const { advancedActive, cap, join, miterLimit } = strokeCtx
  const colorProvider = useColorBindingProvider()
  const okhcl = useOkHCL()
  const { panels, dialogs } = useI18n()
  const [expandedSides, setExpandedSides] = useState(false)

  const setCap = useCallback(
    (value: string) => {
      if (value === 'NONE' || value === 'ROUND' || value === 'SQUARE') {
        strokeCtx.setCap(value)
      }
    },
    [strokeCtx]
  )

  const setJoin = useCallback(
    (value: string) => {
      if (value === 'MITER' || value === 'BEVEL' || value === 'ROUND') {
        strokeCtx.setJoin(value)
      }
    },
    [strokeCtx]
  )

  const onToggleSides = useCallback(
    (activeNode: SceneNode | null) => {
      if (!activeNode) return
      const next = !expandedSides
      setExpandedSides(next)
      if (next && !activeNode.independentStrokeWeights) {
        const weight = activeNode.strokes[0]?.weight ?? 1
        strokeCtx.selectSide('CUSTOM', {
          ...activeNode,
          borderTopWeight: weight,
          borderRightWeight: weight,
          borderBottomWeight: weight,
          borderLeftWeight: weight
        })
      } else if (!next && activeNode.independentStrokeWeights) {
        strokeCtx.selectSide('ALL', activeNode)
      }
    },
    [expandedSides, strokeCtx]
  )

  return (
    <PropertyListRoot propKey="strokes" label={panels.stroke}>
      {({ items, isMixed, activeNode, selectedNodeIds, flush, actions }) => (
        <PanelSection
          label={panels.stroke}
          empty={!isMixed && items.length === 0}
          actions={
            <IconButton label={panels.addStroke} onClick={() => actions.add(strokeCtx.defaultStroke)}>
              <IconLucidePlus className="size-3.5" />
            </IconButton>
          }
        >
          <SharedStyleField kind="stroke" label={panels.strokeStyle} />

          {isMixed ? <p className="text-[11px] text-muted">{panels.mixedStrokesHelp}</p> : null}

          {items.map((stroke, index) => (
            <PropertyItemRow
              key={`${index}:${stroke.visible ? 'visible' : 'hidden'}`}
              propKey="strokes"
              index={index}
              visibilityLabel={panels.toggleVisibility}
              removeLabel={panels.removeStroke}
            >
              <BindableValueRoot
                provider={colorProvider}
                targets={paintBindingTargets(selectedNodeIds, 'strokes', index)}
                value={stroke.color}
                batchLabel="Change stroke color"
              >
                {(binding) => (
                  <PaintField
                    opacity={stroke.opacity}
                    opacityLabel={panels.opacity}
                    onOpacityChange={(opacity) => actions.patch(index, { opacity })}
                    preview={
                      <ColorPicker
                        color={binding.resolvedValue ?? stroke.color}
                        okhcl={createStrokeOkhclAdapter(okhcl, activeNode, index)}
                        onUpdate={(color) =>
                          updateStrokeColor(
                            binding.actions,
                            flush,
                            color,
                            (changes) => actions.patch(index, changes),
                            false
                          )
                        }
                        onOpenChange={(open) => {
                          if (!open) commitPaintMutation(binding.actions)
                        }}
                        onCancel={() => cancelPaintMutation(binding.actions)}
                        trigger={
                          <button
                            type="button"
                            aria-label={panels.stroke}
                            className="size-5 shrink-0 cursor-pointer rounded border-0 bg-transparent p-0"
                          >
                            <FillSwatch
                              fill={strokePreview(stroke, binding.resolvedValue ?? stroke.color)}
                              className="size-full"
                            />
                          </button>
                        }
                      />
                    }
                    value={
                      <PaintValue
                        color={stroke.color}
                        resolvedColor={binding.resolvedValue}
                        variableName={binding.variable?.name}
                        label={panels.stroke}
                        onUpdate={(color) =>
                          updateStrokeColor(
                            binding.actions,
                            flush,
                            color,
                            (changes) => actions.patch(index, changes),
                            true
                          )
                        }
                      />
                    }
                    binding={
                      <VariableBindingPicker
                        triggerLabel={panels.applyVariable}
                        searchPlaceholder={dialogs.search}
                        emptyLabel={panels.noVariablesFound}
                        detachLabel={panels.detachVariable}
                        createLabel={panels.createColorVariable({
                          value: `#${colorToHexRaw(stroke.color)}`
                        })}
                        createNamePlaceholder={panels.variableName}
                        createSubmitLabel={panels.create}
                      />
                    }
                  />
                )}
              </BindableValueRoot>
            </PropertyItemRow>
          ))}

          {!isMixed && items.length > 0 ? (
            <div className="mt-1 flex items-center gap-1.5">
              <AppSelect
                label={panels.strokeType}
                ui={{ trigger: 'w-[88px] flex-none' }}
                value={strokeCtx.currentAlign(activeNode)}
                options={strokeCtx.alignOptions}
                data-property="stroke-align"
                onValueChange={(value) =>
                  strokeCtx.updateAlign(value as Stroke['align'], activeNode)
                }
              />
              {!expandedSides ? (
                <Tip label={panels.strokeWeight}>
                  <NumberField
                    className="flex-1"
                    icon="W"
                    value={items[0]?.weight ?? 1}
                    min={0}
                    data-property="stroke-weight"
                    onValueChange={(weight) => actions.patch(0, { weight })}
                  />
                </Tip>
              ) : null}
              <IconButton
                label={panels.strokeSides}
                size="md"
                className="size-[26px] shrink-0"
                active={expandedSides}
                data-property="stroke-sides"
                onClick={() => onToggleSides(activeNode)}
              >
                <IconLucideLayoutGrid className="size-3.5" />
              </IconButton>
            </div>
          ) : null}

          {!isMixed && items.length > 0 ? (
            <div className="mt-1.5 flex items-center gap-1.5">
              <IconButton
                label={panels.strokeDash}
                size="md"
                className="shrink-0"
                active={strokeCtx.dashState(items[0]).on}
                data-property="stroke-dash"
                onClick={() => actions.patch(0, strokeCtx.toggleDash(items[0]))}
              >
                <span className="flex items-center gap-0.5">
                  <IconLucideMinus className="size-2.5" />
                  <IconLucideMinus className="size-2.5" />
                </span>
              </IconButton>
              {strokeCtx.dashState(items[0]).on ? (
                <>
                  <NumberField
                    className="flex-1"
                    icon="D"
                    value={items[0]?.dashPattern?.[0] ?? 6}
                    min={1}
                    data-property="stroke-dash-length"
                    onValueChange={(value) => actions.patch(0, strokeCtx.setDash(items[0], value))}
                  />
                  <NumberField
                    className="flex-1"
                    icon="G"
                    value={items[0]?.dashPattern?.[1] ?? items[0]?.dashPattern?.[0] ?? 6}
                    min={1}
                    data-property="stroke-dash-gap"
                    onValueChange={(value) => actions.patch(0, strokeCtx.setGap(items[0], value))}
                  />
                </>
              ) : null}
            </div>
          ) : null}

          {advancedActive ? (
            <PanelGrid columns="three" className="mt-1.5">
              <PanelFieldGroup label={panels.strokeCap}>
                <SegmentedControl
                  value={cap === MIXED ? 'MIXED' : String(cap)}
                  options={strokeCtx.capOptions}
                  label={panels.strokeCap}
                  data-property="stroke-cap"
                  onValueChange={setCap}
                  renderOption={({ option }) => (
                    <Tip label={option.label}>
                      {option.value === 'NONE' ? (
                        <IconLucideMinus className="size-3" />
                      ) : option.value === 'ROUND' ? (
                        <IconLucideCircle className="size-2.5" />
                      ) : (
                        <IconLucideSquare className="size-2.5" />
                      )}
                    </Tip>
                  )}
                />
              </PanelFieldGroup>

              <PanelFieldGroup label={panels.strokeJoin}>
                <SegmentedControl
                  value={join === MIXED ? 'MIXED' : String(join)}
                  options={strokeCtx.joinOptions}
                  label={panels.strokeJoin}
                  data-property="stroke-join"
                  onValueChange={setJoin}
                  renderOption={({ option }) => (
                    <Tip label={option.label}>
                      {option.value === 'MITER' ? (
                        <IconLucideCornerUpRight className="size-3" />
                      ) : option.value === 'BEVEL' ? (
                        <IconLucideTriangle className="size-2.5" />
                      ) : (
                        <IconLucideCircle className="size-2.5" />
                      )}
                    </Tip>
                  )}
                />
              </PanelFieldGroup>

              <PanelFieldGroup label={panels.strokeMiterLimit}>
                <NumberField
                  value={miterLimit}
                  min={1}
                  data-property="stroke-miter-limit"
                  aria-label={panels.strokeMiterLimit}
                  icon={<IconLucideTriangleRight className="size-3" />}
                  onValueChange={strokeCtx.updateMiterLimit}
                  onCommit={strokeCtx.commitMiterLimit}
                />
              </PanelFieldGroup>
            </PanelGrid>
          ) : null}

          {!isMixed && items.length > 0 && expandedSides ? (
            <div className="mt-1.5 grid grid-cols-2 gap-1.5">
              {strokeCtx.borderSides.map((side) => (
                <NumberField
                  key={side}
                  label={side[0].toUpperCase()}
                  value={strokeCtx.borderWeight(activeNode, side)}
                  min={0}
                  data-property={`stroke-${side}-weight`}
                  onValueChange={(weight) => strokeCtx.updateBorderWeight(side, weight, activeNode)}
                />
              ))}
            </div>
          ) : null}
        </PanelSection>
      )}
    </PropertyListRoot>
  )
})

StrokeSection.displayName = 'StrokeSection'
export default StrokeSection
