// src/components/properties/VariableNumberField.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue'

import { BindableValueRoot, useI18n, useNumberBindingProvider } from '@open-pencil/vue'
import type { BindingTarget, NumberBindingPath } from '@open-pencil/vue'

import NumberField from '@/components/inputs/NumberField.vue'
import VariableBindingPicker from '@/components/properties/binding/VariableBindingPicker.vue'
import { BindingPill, useBindingFieldUI } from '@/components/ui/binding'

const {
  modelValue,
  min,
  max,
  step,
  icon,
  label,
  suffix,
  sensitivity,
  placeholder,
  nodeId,
  bindingPath
} = defineProps<{
  modelValue: number | symbol
  min?: number
  max?: number
  step?: number
  icon?: string
  label?: string
  suffix?: string
  sensitivity?: number
  placeholder?: string
  nodeId: string
  bindingPath: NumberBindingPath
}>()

const emit = defineEmits<{
  'update:modelValue': [value: number]
  commit: [value: number, previous: number]
}>()

const { panels, common } = useI18n()
const provider = useNumberBindingProvider()
const attrs = useAttrs()
const targets = computed<BindingTarget[]>(() => [{ nodeId, path: bindingPath }])
const accessibleLabel = computed(() => {
  const ariaLabel = attrs['aria-label']
  return typeof ariaLabel === 'string' ? ariaLabel : (label ?? bindingPath)
})
const bindingStyles = useBindingFieldUI()

function bindingTooltip(name: string, resolvedValue: unknown) {
  if (typeof resolvedValue !== 'number') return name
  return `${name} · ${resolvedValue}${suffix ?? ''}`
}

defineOptions({ inheritAttrs: false })
</script>

<template>
  <BindableValueRoot
    v-slot="binding"
    :provider="provider"
    :targets="targets"
    :value="typeof modelValue === 'number' ? modelValue : 0"
  >
    <NumberField
      v-bind="$attrs"
      :icon="icon"
      :label="label"
      :suffix="suffix"
      :sensitivity="sensitivity"
      :placeholder="placeholder"
      :model-value="modelValue"
      :min="min"
      :max="max"
      :step="step"
      :ui="{ root: bindingStyles.root }"
      :data-property="bindingPath"
      :aria-label="accessibleLabel"
      @update:model-value="emit('update:modelValue', $event)"
      @commit="(value: number, previous: number) => emit('commit', value, previous)"
    >
      <template v-if="$slots.icon" #icon>
        <slot name="icon" />
      </template>
      <template v-if="$slots.display" #display="display">
        <slot name="display" v-bind="display" />
      </template>
      <template v-if="binding.variable || binding.state === 'unresolved'" #bound>
        <BindingPill
          :unresolved="binding.state === 'unresolved'"
          :label="binding.variable?.name ?? binding.bindingId ?? panels.unresolvedVariable"
          :tooltip="
            binding.state === 'unresolved'
              ? panels.unresolvedVariable
              : bindingTooltip(binding.variable?.name ?? '', binding.resolvedValue)
          "
        />
      </template>
      <template #suffix>
        <span :class="$slots['after-variable'] ? '' : 'pr-1'" class="flex items-center">
          <VariableBindingPicker
            :trigger-label="panels.applyVariable"
            :search-placeholder="common.search"
            :empty-label="panels.noVariablesFound"
            :detach-label="panels.detachVariable"
            :create-label="
              panels.createNumberVariable({
                value: typeof modelValue === 'number' ? Math.round(modelValue) : 0
              })
            "
            :create-name-placeholder="panels.variableName"
            :create-submit-label="panels.create"
          />
        </span>
        <slot name="after-variable" />
      </template>
    </NumberField>
  </BindableValueRoot>
</template>

// src/components/properties/VariableNumberField.tsx
import { useMemo, type ReactNode, type HTMLAttributes } from 'react'

import { BindableValueRoot, useI18n, useNumberBindingProvider } from '@open-pencil/react'
import { BindingPill, useBindingFieldUI } from '@/components/ui/binding'

import { NumberField } from '@/components/inputs/NumberField'
import { VariableBindingPicker } from '@/components/properties/binding/VariableBindingPicker'

import type { NumberBindingPath, BindingTarget } from '@open-pencil/react'

interface VariableNumberFieldProps extends HTMLAttributes<HTMLDivElement> {
  value: number | symbol
  min?: number
  max?: number
  step?: number
  icon?: string
  iconSlot?: ReactNode
  label?: string
  suffix?: string
  sensitivity?: number
  placeholder?: string
  nodeId: string
  bindingPath: NumberBindingPath
  onChange?: (value: number) => void
  onCommit?: (value: number, previous: number) => void
  afterVariable?: ReactNode
}

export function VariableNumberField({
  value,
  min,
  max,
  step,
  icon,
  iconSlot,
  label,
  suffix,
  sensitivity,
  placeholder,
  nodeId,
  bindingPath,
  onChange,
  onCommit,
  afterVariable,
  className,
  ...attrs
}: VariableNumberFieldProps) {
  const { panels, dialogs } = useI18n()
  const provider = useNumberBindingProvider()
  const bindingStyles = useBindingFieldUI()

  const targets = useMemo<BindingTarget[]>(
    () => [{ nodeId, path: bindingPath }],
    [nodeId, bindingPath]
  )

  const ariaLabel = (attrs['aria-label'] as string | undefined) ?? label ?? bindingPath

  return (
    <BindableValueRoot
      provider={provider}
      targets={targets}
      value={typeof value === 'number' ? value : 0}
    >
      {(binding) => (
        <NumberField
          icon={icon}
          iconSlot={iconSlot}
          label={label}
          suffix={suffix}
          sensitivity={sensitivity}
          placeholder={placeholder}
          value={value}
          min={min}
          max={max}
          step={step}
          ui={{ root: bindingStyles.root }}
          data-property={bindingPath}
          aria-label={ariaLabel}
          className={className}
          onChange={onChange}
          onCommit={onCommit}
          bound={binding.state === 'bound'}
          boundSlot={
            binding.variable ? (
              <BindingPill
                label={binding.variable.name}
                tooltip={
                  typeof binding.resolvedValue === 'number'
                    ? `${binding.variable.name} · ${binding.resolvedValue}${suffix ?? ''}`
                    : binding.variable.name
                }
              />
            ) : undefined
          }
          suffixSlot={
            <>
              <span className={afterVariable ? '' : 'pr-1'} style={{ display: 'flex', alignItems: 'center' }}>
                <VariableBindingPicker
                  triggerLabel={panels.applyVariable}
                  searchPlaceholder={dialogs.search}
                  emptyLabel={panels.noVariablesFound}
                  detachLabel={panels.detachVariable}
                  createLabel={panels.createNumberVariable({
                    value: typeof value === 'number' ? Math.round(value) : 0
                  })}
                  createNamePlaceholder={panels.variableName}
                  createSubmitLabel={panels.create}
                />
              </span>
              {afterVariable}
            </>
          }
        />
      )}
    </BindableValueRoot>
  )
}
