// src/components/chat/ChatMessage.vue
<script setup lang="ts">
import { computed } from 'vue'
import { isTextUIPart, isToolUIPart, getToolName } from 'ai'
import { CollapsibleContent, CollapsibleRoot, CollapsibleTrigger } from 'reka-ui'
import { Markdown } from 'vue-stream-markdown'
import { useI18n, vTestId } from '@open-pencil/vue'
import 'vue-stream-markdown/index.css'

import {
  imageAttachmentsForMessage,
  visibleUserMessageText
} from '@/app/ai/attachment/image/presentation'
import ImageAttachment from '@/components/chat/attachment/image/ImageAttachment.vue'
import { resolvedAppTheme } from '@/app/shell/theme'
import { classifyToolState } from './tool-state'

import type { UIDataTypes, UIMessage, UIMessagePart, UITools } from 'ai'

const { message, streaming = false } = defineProps<{
  message: UIMessage
  streaming?: boolean
}>()
const { ai } = useI18n()
const isDark = computed(() => resolvedAppTheme.value === 'dark')
const markdownMode = computed(() => (streaming ? 'streaming' : 'static'))
const imageAttachments = imageAttachmentsForMessage(message.id)

type ToolPart = Extract<UIMessagePart<UIDataTypes, UITools>, { toolCallId: string }>

function toolDisplayName(part: ToolPart): string {
  return getToolName(part)
    .replace(/^mcp__[^_]+__/, '')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
}

function hasErrorOutput(part: ToolPart): boolean {
  return (
    part.state === 'output-available' &&
    typeof part.output === 'object' &&
    part.output !== null &&
    'error' in part.output
  )
}

function toolState(part: ToolPart): 'pending' | 'done' | 'error' {
  return classifyToolState({
    toolName: getToolName(part),
    state: part.state,
    output: part.output
  })
}

function partKey(part: UIMessagePart<UIDataTypes, UITools>, index: number): string {
  if ('toolCallId' in part) return part.toolCallId
  return `part-${index}`
}
</script>

<template>
  <div
    v-test-id="`chat-message-${message.role}`"
    :class="message.role === 'user' ? 'flex justify-end' : ''"
  >
    <div
      class="min-w-0 space-y-2 select-text"
      :class="message.role === 'user' ? 'max-w-[85%]' : ''"
    >
      <template v-if="message.role === 'assistant'">
        <template v-for="(part, i) in message.parts" :key="partKey(part, i)">
          <!-- Tool call -->
          <div v-if="isToolUIPart(part)" class="rounded-lg border border-border bg-canvas p-2">
            <CollapsibleRoot>
              <CollapsibleTrigger
                class="flex w-full items-center gap-2 rounded px-1 py-0.5 hover:bg-hover"
              >
                <div
                  class="flex size-4 items-center justify-center rounded-full"
                  :class="{
                    'bg-accent/20 text-accent': toolState(part) === 'pending',
                    'bg-green-500/20 text-green-400': toolState(part) === 'done',
                    'bg-red-500/20 text-red-400': toolState(part) === 'error'
                  }"
                >
                  <icon-lucide-loader-circle
                    v-if="toolState(part) === 'pending'"
                    class="size-3 animate-spin"
                  />
                  <icon-lucide-check v-else-if="toolState(part) === 'done'" class="size-3" />
                  <icon-lucide-triangle-alert v-else class="size-3" />
                </div>
                <span class="text-[11px] text-surface">
                  {{ toolDisplayName(part) }}
                </span>
                <span class="text-[10px] text-muted">
                  {{
                    toolState(part) === 'pending'
                      ? ai.toolRunning
                      : toolState(part) === 'done'
                        ? ai.toolFinished
                        : ai.toolError
                  }}
                </span>
                <icon-lucide-chevron-down
                  v-if="toolState(part) !== 'pending'"
                  class="ml-auto size-3 text-muted transition-transform [[data-state=open]>&]:rotate-180"
                />
              </CollapsibleTrigger>
              <CollapsibleContent
                v-if="toolState(part) !== 'pending'"
                class="data-[state=closed]:collapsible-up data-[state=open]:collapsible-down overflow-hidden text-[10px]"
              >
                <pre class="mt-1 overflow-x-auto rounded bg-input p-2 text-muted">{{
                  part.state === 'output-error' && part.errorText
                    ? part.errorText
                    : hasErrorOutput(part)
                      ? (part.output as { error: string }).error
                      : JSON.stringify(part.output, null, 2)
                }}</pre>
              </CollapsibleContent>
            </CollapsibleRoot>
          </div>

          <!-- Text -->
          <div
            v-else-if="isTextUIPart(part) && part.text"
            data-test-id="chat-text-bubble"
            class="rounded-xl rounded-tl-md bg-hover px-3 py-2 text-xs leading-relaxed text-surface"
          >
            <Markdown
              :key="markdownMode"
              :content="part.text"
              :is-dark="isDark"
              :mermaid="false"
              :mode="markdownMode"
              :data-chat-markdown-mode="markdownMode"
              class="chat-markdown [&_[data-stream-markdown=code]]:!bg-input"
            />
          </div>
        </template>
      </template>

      <!-- User message -->
      <template v-else-if="message.role === 'user'">
        <div v-if="imageAttachments.length" class="flex flex-wrap justify-end gap-1.5">
          <ImageAttachment
            v-for="attachment in imageAttachments"
            :key="attachment.id"
            :attachment="attachment"
          />
        </div>
        <div
          data-test-id="chat-text-bubble"
          class="rounded-xl rounded-br-md bg-accent px-3 py-2 text-xs leading-relaxed whitespace-pre-wrap text-white"
        >
          {{
            visibleUserMessageText(
              message.id,
              message.parts
                .filter(isTextUIPart)
                .map((p) => p.text)
                .join('')
            )
          }}
        </div>
      </template>
    </div>
  </div>
</template>

// packages/react/src/components/chat/ChatMessage.tsx
import { useCallback, useState, useSyncExternalStore } from 'react'
import { Check, ChevronDown, LoaderCircle, TriangleAlert } from 'lucide-react'

import {
  imageAttachmentsForMessage,
  subscribeImagePresentations,
  visibleUserMessageText
} from '#react/app/ai/attachment/image/presentation'
import { isTextPart, isToolPart, type ChatMessage } from '#react/app/ai/chat/types'
import { ImageAttachment } from '#react/components/chat/attachment/image/ImageAttachment'
import { classifyToolState } from '#react/components/chat/tool-state'
import { useI18n } from '#react/i18n'

export function ChatMessageView({
  message,
  streaming = false
}: {
  message: ChatMessage
  streaming?: boolean
}) {
  const { dialogs } = useI18n()
  const getAttachments = useCallback(() => imageAttachmentsForMessage(message.id), [message.id])
  const attachments = useSyncExternalStore(
    subscribeImagePresentations,
    getAttachments,
    getAttachments
  )

  return (
    <div
      data-test-id={`chat-message-${message.role}`}
      className={message.role === 'user' ? 'flex justify-end' : undefined}
    >
      <div
        className={`min-w-0 space-y-2 select-text ${message.role === 'user' ? 'max-w-[85%]' : ''}`}
      >
        {message.role === 'assistant'
          ? message.parts.map((part, index) => {
              if (isToolPart(part)) {
                const state = classifyToolState({
                  toolName: part.toolName,
                  state: part.state,
                  output: part.output
                })
                return (
                  <ToolCallCard
                    key={part.toolCallId}
                    name={toolDisplayName(part.toolName)}
                    state={state}
                    runningLabel={dialogs.toolRunning}
                    doneLabel={dialogs.toolFinished}
                    errorLabel={dialogs.toolError}
                    output={
                      part.state === 'output-error' && part.errorText
                        ? part.errorText
                        : JSON.stringify(part.output, null, 2)
                    }
                  />
                )
              }
              if (isTextPart(part) && part.text) {
                return (
                  <div
                    key={`part-${index}`}
                    data-test-id="chat-text-bubble"
                    data-chat-markdown-mode={streaming ? 'streaming' : 'static'}
                    className="rounded-xl rounded-tl-md bg-hover px-3 py-2 text-xs leading-relaxed whitespace-pre-wrap text-surface"
                  >
                    {part.text}
                  </div>
                )
              }
              return null
            })
          : null}

        {message.role === 'user' ? (
          <>
            {attachments.length > 0 ? (
              <div className="flex flex-wrap justify-end gap-1.5">
                {attachments.map((attachment) => (
                  <ImageAttachment key={attachment.id} attachment={attachment} />
                ))}
              </div>
            ) : null}
            <div
              data-test-id="chat-text-bubble"
              className="rounded-xl rounded-br-md bg-accent px-3 py-2 text-xs leading-relaxed whitespace-pre-wrap text-white"
            >
              {visibleUserMessageText(
                message.id,
                message.parts.filter(isTextPart).map((part) => part.text).join('')
              )}
            </div>
          </>
        ) : null}
      </div>
    </div>
  )
}

function toolDisplayName(name: string) {
  return name
    .replace(/^mcp__[^_]+__/, '')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (char) => char.toUpperCase())
}

function ToolCallCard({
  name,
  state,
  runningLabel,
  doneLabel,
  errorLabel,
  output
}: {
  name: string
  state: 'pending' | 'done' | 'error'
  runningLabel: string
  doneLabel: string
  errorLabel: string
  output: string
}) {
  const [open, setOpen] = useState(false)
  return (
    <div className="rounded-lg border border-border bg-canvas p-2">
      <button
        type="button"
        className="flex w-full items-center gap-2 rounded px-1 py-0.5 hover:bg-hover"
        onClick={() => state !== 'pending' && setOpen((value) => !value)}
      >
        <div
          className={`flex size-4 items-center justify-center rounded-full ${
            state === 'pending'
              ? 'bg-accent/20 text-accent'
              : state === 'done'
                ? 'bg-green-500/20 text-green-400'
                : 'bg-red-500/20 text-red-400'
          }`}
        >
          {state === 'pending' ? (
            <LoaderCircle className="size-3 animate-spin" />
          ) : state === 'done' ? (
            <Check className="size-3" />
          ) : (
            <TriangleAlert className="size-3" />
          )}
        </div>
        <span className="text-[11px] text-surface">{name}</span>
        <span className="text-[10px] text-muted">
          {state === 'pending' ? runningLabel : state === 'done' ? doneLabel : errorLabel}
        </span>
        {state !== 'pending' ? (
          <ChevronDown
            className={`ml-auto size-3 text-muted transition-transform ${open ? 'rotate-180' : ''}`}
          />
        ) : null}
      </button>
      {open && state !== 'pending' ? (
        <pre className="mt-1 overflow-x-auto rounded bg-input p-2 text-[10px] text-muted">
          {output}
        </pre>
      ) : null}
    </div>
  )
}
