// src/components/settings/provider/ProviderSettingsLink.vue
<script setup lang="ts">
import { openExternalLink } from '@/app/shell/ui'
import AppButton from '@/components/ui/button/AppButton.vue'

const { href } = defineProps<{ href: string }>()
</script>

<template>
  <AppButton
    color="primary"
    variant="link"
    size="xs"
    class="self-start text-left"
    @click="openExternalLink(href)"
  >
    <slot />
  </AppButton>
</template>

// src/components/chat/ProviderSettings/ProviderSettingsLink.tsx
<script setup lang="ts">
import { openExternalLink } from '@/app/shell/ui'
import AppTextButton from '@/components/ui/AppTextButton.vue'

const { href } = defineProps<{ href: string }>()
</script>

<template>
  <AppTextButton size="xs" underline @click="openExternalLink(href)">
    <slot />
  </AppTextButton>
</template>
