// src/components/settings/provider/StockPhotoKeysSection.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from '@open-pencil/vue'

import { useAIChat } from '@/app/ai/chat/use'
import ProviderSettingsKeyField from '@/components/settings/provider/ProviderSettingsKeyField.vue'

const { media, credentials } = useI18n()
const { pexelsKeyStatus, setPexelsKey, unsplashKeyStatus, setUnsplashKey } = useAIChat()
const pexelsKeyInput = ref('')
const unsplashKeyInput = ref('')
const hasExistingPexelsKey = computed(() => pexelsKeyStatus.value === 'configured')
const hasExistingUnsplashKey = computed(() => unsplashKeyStatus.value === 'configured')

async function savePexelsKey(): Promise<void> {
  const value = pexelsKeyInput.value.trim()
  if (!value) return
  await setPexelsKey(value)
  pexelsKeyInput.value = ''
}

async function saveUnsplashKey(): Promise<void> {
  const value = unsplashKeyInput.value.trim()
  if (!value) return
  await setUnsplashKey(value)
  unsplashKeyInput.value = ''
}

async function clearPexelsKey(): Promise<void> {
  await setPexelsKey('')
  pexelsKeyInput.value = ''
}

async function clearUnsplashKey(): Promise<void> {
  await setUnsplashKey('')
  unsplashKeyInput.value = ''
}
</script>

<template>
  <ProviderSettingsKeyField
    v-model="pexelsKeyInput"
    :label="media.pexelsAPIKey"
    :saved="hasExistingPexelsKey"
    kind="pexels"
    :placeholder="hasExistingPexelsKey ? credentials.savedReplace : media.stockPhotoToolOptional"
    key-u-r-l="https://www.pexels.com/api/"
    :key-u-r-l-label="media.getPexelsAPIKey"
    @clear="clearPexelsKey"
    @change="savePexelsKey"
  />

  <ProviderSettingsKeyField
    v-model="unsplashKeyInput"
    :label="media.unsplashAccessKey"
    :saved="hasExistingUnsplashKey"
    kind="unsplash"
    :placeholder="
      hasExistingUnsplashKey ? credentials.savedReplace : media.pexelsAlternativeOptional
    "
    key-u-r-l="https://unsplash.com/oauth/applications"
    :key-u-r-l-label="media.getUnsplashAccessKey"
    @clear="clearUnsplashKey"
    @change="saveUnsplashKey"
  />
</template>

// src/components/chat/ProviderSettings/StockPhotoKeysSection.tsx
import { useI18n } from '@open-pencil/react'
import { ProviderSettingsKeyField } from '@/components/chat/ProviderSettings/ProviderSettingsKeyField'
import { useProviderSettingsContext } from '@/components/chat/ProviderSettings/context'

export function StockPhotoKeysSection() {
  const ctx = useProviderSettingsContext()
  const { dialogs } = useI18n()

  return (
    <>
      <ProviderSettingsKeyField
        label={dialogs.pexelsAPIKey}
        value={ctx.pexelsKeyInput}
        saved={!!ctx.pexelsApiKey.get()}
        kind="pexels"
        placeholder={ctx.hasExistingPexelsKey ? dialogs.keySavedReplace : dialogs.stockPhotoToolOptional}
        keyUrl="https://www.pexels.com/api/"
        keyUrlLabel={dialogs.getPexelsAPIKey}
        onChange={ctx.setPexelsKeyInput}
        onClear={ctx.clearPexelsKey}
      />
      <ProviderSettingsKeyField
        label={dialogs.unsplashAccessKey}
        value={ctx.unsplashKeyInput}
        saved={!!ctx.unsplashAccessKey.get()}
        kind="unsplash"
        placeholder={ctx.hasExistingUnsplashKey ? dialogs.keySavedReplace : dialogs.pexelsAlternativeOptional}
        keyUrl="https://unsplash.com/oauth/applications"
        keyUrlLabel={dialogs.getUnsplashAccessKey}
        onChange={ctx.setUnsplashKeyInput}
        onClear={ctx.clearUnsplashKey}
      />
    </>
  )
}
