// src/react_app/pickers/FontPicker.tsx
import { Check, ChevronDown, Search } from 'lucide-react'

import { listFamilies } from '@/engine/fonts'
import { usePopoverUI } from '@/react_app/ui/popover'
import { useSelectUI } from '@/react_app/ui/select'
import { FontPickerRoot } from '@open-pencil/react'

export function FontPicker({
  value,
  className,
  onSelect
}: {
  value: string
  className?: string
  onSelect: (family: string) => void
}) {
  const cls = usePopoverUI({
    content:
      'absolute z-[100] mt-1 w-full min-w-56 overflow-hidden rounded-lg border border-border bg-panel p-0 shadow-xl'
  })
  const selectCls = useSelectUI({
    trigger: 'w-full rounded px-2 py-1 text-xs',
    item: 'w-full gap-2 px-2 py-2 text-sm'
  })

  return (
    <div className={className} data-test-id="font-picker-root">
      <FontPickerRoot
        value={value}
        listFamilies={listFamilies}
        onSelect={onSelect}
        onValueChange={onSelect}
      >
        {(ctx) => (
          <div className="relative inline-block w-full">
            <button
              type="button"
              data-test-id="font-picker-trigger"
              className={selectCls.trigger}
              onClick={() => ctx.setOpen(!ctx.open)}
            >
              <span className="truncate">{ctx.value}</span>
              <ChevronDown className="size-3 shrink-0 text-muted" />
            </button>
            {ctx.open ? (
              <div className={cls.content} role="listbox">
                <div className="flex items-center gap-1 border-b border-border px-2 py-1">
                  <Search className="size-3 shrink-0 text-muted" />
                  <input
                    ref={ctx.setInputRef}
                    className="min-w-0 flex-1 border-none bg-transparent text-xs text-surface outline-none placeholder:text-muted"
                    placeholder="Search fonts…"
                    autoComplete="off"
                    autoCorrect="off"
                    autoCapitalize="off"
                    spellCheck={false}
                    value={ctx.searchTerm}
                    onChange={(e) => ctx.setSearchTerm(e.currentTarget.value)}
                  />
                </div>
                <div className="max-h-72 overflow-y-auto">
                  {ctx.filtered.map((family) => {
                    const selected = family === ctx.value
                    return (
                      <button
                        key={family}
                        type="button"
                        data-test-id="font-picker-item"
                        className={`flex ${selectCls.item}`}
                        style={{ fontFamily: `'${family}', sans-serif` }}
                        onClick={() => ctx.select(family)}
                      >
                        {selected ? (
                          <Check className="size-3 shrink-0 text-accent" />
                        ) : (
                          <span className="size-3 shrink-0" />
                        )}
                        <span className="truncate">{family}</span>
                      </button>
                    )
                  })}
                  {ctx.filtered.length === 0 ? (
                    <div className="px-2 py-3 text-center text-xs text-muted">
                      {ctx.searchTerm
                        ? 'No fonts found'
                        : 'Use the desktop app or Chrome/Edge to access system fonts.'}
                    </div>
                  ) : null}
                </div>
              </div>
            ) : null}
          </div>
        )}
      </FontPickerRoot>
    </div>
  )
}

// src/components/font-picker/FontPicker.vue
<script setup lang="ts">
import { computed } from 'vue'
import { FontPickerRoot } from '@open-pencil/vue'

import { useSelectUI } from '@/components/ui/select'
import { usePopoverUI } from '@/components/ui/popover'
import {
  listFamilies,
  loadFont,
  localFontAccessState,
  requestLocalFontAccess
} from '@/app/editor/fonts'

import { WEB_FONT_PROVIDER_IDS } from '@open-pencil/core/text'

import type { FontPickerUI } from '@open-pencil/vue'

const modelValue = defineModel<string>({ required: true })
const emit = defineEmits<{ select: [family: string] }>()

const cls = usePopoverUI({
  content: 'w-[var(--reka-combobox-trigger-width)] min-w-56 overflow-hidden p-0'
})
const selectCls = useSelectUI({
  trigger: 'w-full rounded px-2 py-1 text-xs',
  item: 'w-full gap-2 px-3 py-2.5 text-sm leading-tight'
})

const ui = computed<FontPickerUI>(() => ({
  trigger: selectCls.trigger,
  content: cls.content,
  item: selectCls.item,
  search:
    'w-full border-b border-border bg-transparent px-3 py-2 text-sm text-surface outline-none placeholder:text-muted',
  empty: 'px-2 py-3 text-center text-xs text-muted',
  emptyAction: 'mt-2 rounded bg-accent px-2 py-1 text-xs font-medium text-white disabled:opacity-50'
}))

const previewFontLoads = new Set<string>()

const localFontAccess = {
  state: localFontAccessState,
  load: requestLocalFontAccess
}

function loadPreviewFont(family: string, source: string) {
  if (!WEB_FONT_PROVIDER_IDS.includes(source as (typeof WEB_FONT_PROVIDER_IDS)[number])) return
  if (previewFontLoads.has(family)) return
  previewFontLoads.add(family)
  void loadFont(family)
}
</script>

<template>
  <FontPickerRoot
    v-model="modelValue"
    data-test-id="font-picker-root"
    :list-families="listFamilies"
    :local-font-access="localFontAccess"
    :ui="ui"
    empty-fonts-hint="Use the desktop app or Chrome/Edge to access system fonts."
    @select="emit('select', $event)"
  >
    <template #trigger>
      <button data-test-id="font-picker-trigger" :class="selectCls.trigger">
        <span class="truncate">{{ modelValue }}</span>
        <icon-lucide-chevron-down class="size-3 shrink-0 text-muted" />
      </button>
    </template>

    <template #item="{ family, selected, source }">
      <div
        data-test-id="font-picker-item"
        class="flex min-w-0 flex-1 items-center gap-2"
        @vue:mounted="loadPreviewFont(family, source)"
      >
        <icon-lucide-check v-if="selected" class="size-3 shrink-0 text-accent" />
        <span v-else class="size-3 shrink-0" />
        <span class="truncate" :style="{ fontFamily: `'${family}', sans-serif` }">{{
          family
        }}</span>
        <span
          class="font-sans ml-auto shrink-0 rounded bg-input px-1.5 py-0.5 text-[9px] uppercase text-muted"
        >
          {{ source }}
        </span>
      </div>
    </template>
  </FontPickerRoot>
</template>
