// src/components/ui/AppInput.tsx
<script setup lang="ts">
import { computed } from 'vue'
import { tv } from 'tailwind-variants'

import theme from '@/theme/input'

interface AppInputProps {
  type?: 'text' | 'password' | 'number' | 'search'
  placeholder?: string
  readonly?: boolean
  disabled?: boolean
  autofocus?: boolean
  min?: number
  max?: number
  step?: number
  tone?: 'default' | 'panel'
  size?: 'sm' | 'md'
  state?: 'idle' | 'mixed' | 'bound' | 'invalid'
}

const {
  type = 'text',
  placeholder,
  readonly,
  disabled,
  autofocus,
  min,
  max,
  step,
  tone = 'default',
  size = 'md',
  state = 'idle'
} = defineProps<AppInputProps>()

const inputClass = computed(() => tv(theme)({ tone, size, state }))

const modelValue = defineModel<string | number>({ required: true })
const emit = defineEmits<{
  change: []
  enter: [event: KeyboardEvent]
  focus: [event: FocusEvent]
}>()
</script>

<template>
  <input
    v-model="modelValue"
    :type="type"
    :placeholder="placeholder"
    :readonly="readonly"
    :disabled="disabled"
    :autofocus="autofocus"
    :min="min"
    :max="max"
    :step="step"
    :class="inputClass"
    @change="emit('change')"
    @keydown.enter="emit('enter', $event)"
    @focus="emit('focus', $event)"
  />
</template>

// packages/react/src/components/ui/AppInput.tsx
import type { InputHTMLAttributes } from 'react'
import { tv } from 'tailwind-variants'

import type { ControlSize } from '#react/theme/control'
import theme from '#react/theme/input'

export type AppInputTone = 'default' | 'panel'
export type AppInputState = 'idle' | 'mixed' | 'bound' | 'invalid'

export function AppInput({
  className,
  tone = 'panel',
  size = 'xs',
  state = 'idle',
  ...rest
}: Omit<InputHTMLAttributes<HTMLInputElement>, 'size'> & {
  tone?: AppInputTone
  size?: ControlSize
  state?: AppInputState
}) {
  return <input {...rest} className={tv(theme)({ tone, size, state, class: className })} />
}
