// src/components/properties/layout/padding/PaddingControls.vue
<script setup lang="ts">
import { useI18n, useLayoutControlsContext } from '@open-pencil/vue'

import type { PaddingProp } from '@/components/properties/layout/types'
import VariableNumberField from '@/components/properties/VariableNumberField.vue'
import IconButton from '@/components/ui/button/IconButton.vue'

const ctx = useLayoutControlsContext()
const { panels } = useI18n()

const paddingSides: Array<{ prop: PaddingProp; icon: string }> = [
  { prop: 'paddingTop', icon: 'top' },
  { prop: 'paddingRight', icon: 'right' },
  { prop: 'paddingBottom', icon: 'bottom' },
  { prop: 'paddingLeft', icon: 'left' }
]
</script>

<template>
  <div class="flex items-start gap-1.5">
    <div class="min-w-0 flex-1">
      <div
        v-if="!ctx.showIndividualPadding && ctx.hasSymmetricPadding"
        class="mt-1.5 grid grid-cols-2 gap-1.5"
      >
        <VariableNumberField
          data-test-id="layout-horizontal-padding-input"
          :model-value="Math.round(ctx.node.paddingLeft)"
          :min="0"
          :node-id="ctx.node.id"
          binding-path="paddingLeft"
          @update:model-value="ctx.setHorizontalPadding"
          @commit="ctx.commitHorizontalPadding"
        >
          <template #icon>
            <icon-lucide-separator-vertical class="size-3.5" />
          </template>
        </VariableNumberField>
        <VariableNumberField
          data-test-id="layout-vertical-padding-input"
          :model-value="Math.round(ctx.node.paddingTop)"
          :min="0"
          :node-id="ctx.node.id"
          binding-path="paddingTop"
          @update:model-value="ctx.setVerticalPadding"
          @commit="ctx.commitVerticalPadding"
        >
          <template #icon>
            <icon-lucide-separator-horizontal class="size-3.5" />
          </template>
        </VariableNumberField>
      </div>

      <div v-else-if="ctx.isGrid || ctx.isFlex" class="mt-1.5 grid grid-cols-2 gap-1.5">
        <VariableNumberField
          v-for="side in paddingSides"
          :key="side.prop"
          :model-value="Math.round(ctx.node[side.prop])"
          :min="0"
          :node-id="ctx.node.id"
          :binding-path="side.prop"
          @update:model-value="ctx.updateProp(side.prop, $event)"
          @commit="(v: number, p: number) => ctx.commitProp(side.prop, v, p)"
        >
          <template #icon>
            <icon-lucide-panel-top v-if="side.icon === 'top'" class="size-3.5" />
            <icon-lucide-panel-right v-else-if="side.icon === 'right'" class="size-3.5" />
            <icon-lucide-panel-bottom v-else-if="side.icon === 'bottom'" class="size-3.5" />
            <icon-lucide-panel-left v-else class="size-3.5" />
          </template>
        </VariableNumberField>
      </div>
    </div>
    <IconButton
      v-if="ctx.isFlex || ctx.isGrid"
      :label="panels.individualPadding"
      :active="ctx.showIndividualPadding"
      class="mt-1.5"
      @click="ctx.toggleIndividualPadding"
    >
      <icon-lucide-scan class="size-3.5" />
    </IconButton>
  </div>
</template>

// src/components/properties/LayoutSection/PaddingControls.tsx
import IconPanelTop from '~icons/lucide/panel-top'
import IconPanelRight from '~icons/lucide/panel-right'
import IconPanelBottom from '~icons/lucide/panel-bottom'
import IconPanelLeft from '~icons/lucide/panel-left'
import IconSeparatorVertical from '~icons/lucide/separator-vertical'
import IconSeparatorHorizontal from '~icons/lucide/separator-horizontal'

import { useLayoutControlsContext } from '@open-pencil/react'
import { VariableNumberField } from '@/components/properties/VariableNumberField'
import type { PaddingProp } from '@/components/properties/LayoutSection/types'

const paddingSides: Array<{ prop: PaddingProp; side: string }> = [
  { prop: 'paddingTop', side: 'top' },
  { prop: 'paddingRight', side: 'right' },
  { prop: 'paddingBottom', side: 'bottom' },
  { prop: 'paddingLeft', side: 'left' }
]

function PaddingIcon({ side }: { side: string }) {
  if (side === 'top') return <IconPanelTop className="size-3.5" />
  if (side === 'right') return <IconPanelRight className="size-3.5" />
  if (side === 'bottom') return <IconPanelBottom className="size-3.5" />
  return <IconPanelLeft className="size-3.5" />
}

export function PaddingControls() {
  const ctx = useLayoutControlsContext()
  const node = ctx.node.value
  if (!node) return null

  if (!ctx.showIndividualPadding.value && ctx.hasSymmetricPadding.value) {
    return (
      <div className="mt-1.5 grid grid-cols-2 gap-1.5">
        <VariableNumberField
          data-test-id="layout-horizontal-padding-input"
          value={Math.round(node.paddingLeft)}
          min={0}
          nodeId={node.id}
          bindingPath="paddingLeft"
          iconSlot={<IconSeparatorVertical className="size-3.5" />}
          onChange={ctx.setHorizontalPadding}
          onCommit={ctx.commitHorizontalPadding}
        />
        <VariableNumberField
          data-test-id="layout-vertical-padding-input"
          value={Math.round(node.paddingTop)}
          min={0}
          nodeId={node.id}
          bindingPath="paddingTop"
          iconSlot={<IconSeparatorHorizontal className="size-3.5" />}
          onChange={ctx.setVerticalPadding}
          onCommit={ctx.commitVerticalPadding}
        />
      </div>
    )
  }

  if (ctx.isGrid.value || ctx.isFlex.value) {
    return (
      <div className="mt-1.5 grid grid-cols-2 gap-1.5">
        {paddingSides.map((side) => (
          <VariableNumberField
            key={side.prop}
            value={Math.round(node[side.prop])}
            min={0}
            nodeId={node.id}
            bindingPath={side.prop}
            iconSlot={<PaddingIcon side={side.side} />}
            onChange={(v) => ctx.updateProp(side.prop, v)}
            onCommit={(v, p) => ctx.commitProp(side.prop, v, p)}
          />
        ))}
      </div>
    )
  }

  return null
}
