// src/components/properties/AppearanceSection.vue
<script setup lang="ts">
import type { BlendMode } from '@open-pencil/scene-graph'
import { AppearanceControlsRoot, MIXED, useI18n } from '@open-pencil/vue'

import NumberField from '@/components/inputs/NumberField.vue'
import { useBlendModeOptions } from '@/components/properties/blend-mode/use'
import VariableNumberField from '@/components/properties/VariableNumberField.vue'
import IconButton from '@/components/ui/button/IconButton.vue'
import PanelFieldGroup from '@/components/ui/panel/PanelFieldGroup.vue'
import PanelGrid from '@/components/ui/panel/PanelGrid.vue'
import PanelSection from '@/components/ui/panel/PanelSection.vue'
import AppSelect from '@/components/ui/select/AppSelect.vue'

const { panels } = useI18n()
type BlendModeSelectValue = BlendMode | 'MIXED'

const baseBlendModeOptions = useBlendModeOptions(true)

function blendModeOptions(value: BlendMode | typeof MIXED) {
  return value === MIXED
    ? [{ value: 'MIXED' as const, label: panels.value.mixed }, ...baseBlendModeOptions.value]
    : baseBlendModeOptions.value
}
</script>

<template>
  <AppearanceControlsRoot
    v-slot="{
      node,
      isMulti,
      active,
      hasCornerRadius,
      independentCorners,
      showIndependentCorners,
      cornerRadiusValue,
      cornerSmoothingPercent,
      opacityPercent,
      blendModeValue,
      visibilityState,
      actions
    }"
  >
    <PanelSection v-if="active" :label="panels.appearance">
      <template #actions>
        <IconButton
          :label="panels.toggleVisibility"
          :active="visibilityState === 'hidden'"
          @click="actions.toggleVisibility"
        >
          <icon-lucide-eye v-if="visibilityState === 'visible'" class="size-3.5" />
          <icon-lucide-eye-off v-else-if="visibilityState === 'hidden'" class="size-3.5" />
          <icon-lucide-eye v-else class="size-3.5 opacity-50" />
        </IconButton>
      </template>

      <PanelGrid :columns="2" distribution="wide-first">
        <PanelFieldGroup :label="panels.blendMode">
          <AppSelect
            :model-value="blendModeValue === MIXED ? 'MIXED' : blendModeValue"
            class="w-full"
            :label="panels.blendMode"
            :options="blendModeOptions(blendModeValue)"
            @update:model-value="
              (value: BlendModeSelectValue) => value !== 'MIXED' && actions.setBlendMode(value)
            "
          />
        </PanelFieldGroup>

        <PanelFieldGroup :label="panels.opacity">
          <VariableNumberField
            v-if="node && !isMulti"
            suffix="%"
            :aria-label="panels.opacity"
            :model-value="opacityPercent"
            :min="0"
            :max="100"
            :node-id="node.id"
            binding-path="opacity"
            @update:model-value="actions.updateProp('opacity', $event / 100)"
            @commit="(v: number, p: number) => actions.commitProp('opacity', v / 100, p / 100)"
          >
            <template #icon>
              <icon-lucide-blend class="size-3" />
            </template>
          </VariableNumberField>
          <NumberField
            v-else
            suffix="%"
            data-property="opacity"
            :aria-label="panels.opacity"
            :model-value="opacityPercent"
            :min="0"
            :max="100"
            @update:model-value="actions.updateProp('opacity', $event / 100)"
            @commit="(v: number, p: number) => actions.commitProp('opacity', v / 100, p / 100)"
          >
            <template #icon>
              <icon-lucide-blend class="size-3" />
            </template>
          </NumberField>
        </PanelFieldGroup>
      </PanelGrid>

      <PanelGrid v-if="hasCornerRadius && !showIndependentCorners" :columns="2" class="mt-1.5">
        <PanelFieldGroup :label="panels.radius">
          <VariableNumberField
            v-if="node && !isMulti"
            :aria-label="panels.radius"
            :model-value="cornerRadiusValue"
            :min="0"
            :node-id="node.id"
            binding-path="cornerRadius"
            @update:model-value="actions.updateProp('cornerRadius', $event)"
            @commit="(v: number, p: number) => actions.commitProp('cornerRadius', v, p)"
          >
            <template #icon>
              <icon-lucide-square-round-corner class="size-3" />
            </template>
          </VariableNumberField>
          <NumberField
            v-else
            data-property="cornerRadius"
            :aria-label="panels.radius"
            :model-value="cornerRadiusValue"
            :min="0"
            @update:model-value="actions.updateProp('cornerRadius', $event)"
            @commit="(v: number, p: number) => actions.commitProp('cornerRadius', v, p)"
          >
            <template #icon>
              <icon-lucide-square-round-corner class="size-3" />
            </template>
          </NumberField>
        </PanelFieldGroup>
        <div class="flex h-6 items-center justify-end">
          <IconButton
            :label="panels.independentCornerRadii"
            size="xs"
            :active="independentCorners === true"
            @click="actions.toggleIndependentCorners"
          >
            <icon-lucide-square-round-corner class="size-3" />
          </IconButton>
        </div>
      </PanelGrid>

      <PanelGrid
        v-else-if="hasCornerRadius && !isMulti && node"
        :columns="2"
        class="mt-1.5 [&>[data-slot=actions]]:self-start"
        data-corner-grid
      >
        <VariableNumberField
          label="TL"
          :model-value="node.topLeftRadius"
          :min="0"
          :node-id="node.id"
          binding-path="topLeftRadius"
          @update:model-value="actions.updateCornerProp('topLeftRadius', $event)"
          @commit="(v: number, p: number) => actions.commitCornerProp('topLeftRadius', v, p)"
        />
        <VariableNumberField
          label="TR"
          :model-value="node.topRightRadius"
          :min="0"
          :node-id="node.id"
          binding-path="topRightRadius"
          @update:model-value="actions.updateCornerProp('topRightRadius', $event)"
          @commit="(v: number, p: number) => actions.commitCornerProp('topRightRadius', v, p)"
        />
        <VariableNumberField
          label="BL"
          :model-value="node.bottomLeftRadius"
          :min="0"
          :node-id="node.id"
          binding-path="bottomLeftRadius"
          @update:model-value="actions.updateCornerProp('bottomLeftRadius', $event)"
          @commit="(v: number, p: number) => actions.commitCornerProp('bottomLeftRadius', v, p)"
        />
        <VariableNumberField
          label="BR"
          :model-value="node.bottomRightRadius"
          :min="0"
          :node-id="node.id"
          binding-path="bottomRightRadius"
          @update:model-value="actions.updateCornerProp('bottomRightRadius', $event)"
          @commit="(v: number, p: number) => actions.commitCornerProp('bottomRightRadius', v, p)"
        />
        <template #actions>
          <IconButton
            :label="panels.independentCornerRadii"
            size="xs"
            active
            @click="actions.toggleIndependentCorners"
          >
            <icon-lucide-square-round-corner class="size-3" />
          </IconButton>
        </template>
      </PanelGrid>

      <PanelGrid v-if="hasCornerRadius" :columns="2" class="mt-1.5">
        <PanelFieldGroup :label="panels.cornerSmoothing">
          <NumberField
            suffix="%"
            :model-value="cornerSmoothingPercent"
            :min="0"
            :max="100"
            :aria-label="panels.cornerSmoothing"
            data-property="corner-smoothing"
            @update:model-value="actions.updateCornerProp('cornerSmoothing', $event / 100)"
            @commit="
              (v: number, p: number) =>
                actions.commitCornerProp('cornerSmoothing', v / 100, p / 100)
            "
          >
            <template #icon>
              <icon-lucide-squircle class="size-3" />
            </template>
          </NumberField>
        </PanelFieldGroup>
      </PanelGrid>
    </PanelSection>
  </AppearanceControlsRoot>
</template>

// packages/react/src/components/properties/AppearanceSection.tsx
import { Blend, Eye, EyeOff, SquareRoundCorner } from 'lucide-react'

import { IconButton } from '#react/components/ui/IconButton'
import { NumberField } from '#react/components/inputs/NumberField'
import { PanelGrid } from '#react/components/ui/panel/PanelGrid'
import { PanelSection } from '#react/components/ui/panel/PanelSection'
import { useNodePropCommit } from '#react/components/properties/useNodePropCommit'
import { useSelectionState } from '#react/editor/selection-state/use'
import { useSceneComputed } from '#react/internal/scene-computed/use'
import { useI18n } from '#react/i18n'

const CORNER_TYPES = new Set([
  'RECTANGLE',
  'FRAME',
  'COMPONENT',
  'COMPONENT_SET',
  'INSTANCE',
  'VECTOR',
  'POLYGON',
  'STAR'
])

export function AppearanceSection() {
  const { editor, commit } = useNodePropCommit()
  const { selectedNode, hasSelection } = useSelectionState()
  const { panels } = useI18n()
  const node = useSceneComputed(() => editor.getSelectedNode() ?? selectedNode)
  if (!hasSelection || !node) return null

  const hidden = node.visible === false
  const hasCorners = CORNER_TYPES.has(node.type)

  return (
    <PanelSection
      label={panels.appearance}
      actions={
        <IconButton
          label={panels.toggleVisibility}
          active={hidden}
          onClick={() => editor.toggleVisibility()}
        >
          {hidden ? <EyeOff className="size-3.5" /> : <Eye className="size-3.5" />}
        </IconButton>
      }
    >
      <PanelGrid columns={2} distribution="wide-first">
        <div className="flex h-6 items-center gap-1.5 text-[11px] text-muted">
          <Blend className="size-3" />
          {panels.opacity}
        </div>
        <NumberField
          data-property="opacity"
          aria-label={panels.opacity}
          suffix="%"
          min={0}
          max={100}
          value={Math.round(node.opacity * 100)}
          onCommit={(value) => editor.setOpacity(value / 100)}
        />
      </PanelGrid>
      {hasCorners ? (
        <PanelGrid columns={2} className="mt-1.5">
          <NumberField
            data-property="cornerRadius"
            aria-label={panels.radius}
            min={0}
            value={Math.round(node.cornerRadius)}
            onCommit={(value, previous) => commit('cornerRadius', value, previous)}
          />
          <div className="flex h-6 items-center text-[11px] text-muted">
            <SquareRoundCorner className="mr-1 size-3" />
            {panels.radius}
          </div>
        </PanelGrid>
      ) : null}
    </PanelSection>
  )
}
