// src/components/properties/EffectsSection.vue
<script setup lang="ts">
import type { Effect, Fill } from '@open-pencil/scene-graph'
import { useEffectsControls, useI18n } from '@open-pencil/vue'

import ColorInput from '@/components/ColorPicker/ColorInput.vue'
import NumberField from '@/components/inputs/NumberField.vue'
import {
  commitDiscretePropertyListChange,
  useBlendModeOptions
} from '@/components/properties/blend-mode/use'
import PropertyItemRow from '@/components/properties/item-list/PropertyItemRow.vue'
import PropertyListRoot from '@/components/properties/PropertyListRoot.vue'
import SharedStyleField from '@/components/properties/shared-style/SharedStyleField.vue'
import IconButton from '@/components/ui/button/IconButton.vue'
import Tip from '@/components/ui/overlay/Tip.vue'
import FillSwatch from '@/components/ui/paint/FillSwatch.vue'
import PanelFieldGroup from '@/components/ui/panel/PanelFieldGroup.vue'
import PanelSection from '@/components/ui/panel/PanelSection.vue'
import AppSelect from '@/components/ui/select/AppSelect.vue'

const effectsCtx = useEffectsControls()
const { panels } = useI18n()
const blendModeOptions = useBlendModeOptions()

function effectPreview(effect: Effect): Fill {
  return {
    type: 'SOLID',
    color: effect.color,
    opacity: 1,
    visible: effect.visible
  }
}
</script>

<template>
  <PropertyListRoot
    v-slot="{ items, isMixed, activeNode, flush, actions }"
    prop-key="effects"
    :label="panels.effects"
  >
    <PanelSection :label="panels.effects" :empty="!isMixed && items.length === 0">
      <template #actions>
        <IconButton
          :label="panels.addEffect"
          @click="actions.add(effectsCtx.createDefaultEffect())"
        >
          <icon-lucide-plus class="size-3.5" />
        </IconButton>
      </template>

      <SharedStyleField kind="effect" :label="panels.effectStyle" />

      <p v-if="isMixed" class="text-[11px] text-muted">{{ panels.mixedEffectsHelp }}</p>

      <div
        v-for="(effect, index) in items"
        :key="`${index}:${effect.visible ? 'visible' : 'hidden'}`"
        :data-effect-index="index"
        data-effect-group
      >
        <PropertyItemRow
          prop-key="effects"
          :index="index"
          :visibility-label="panels.toggleVisibility"
          :remove-label="panels.removeEffect"
          class="items-start"
          @remove="effectsCtx.adjustExpandedAfterRemove(index)"
        >
          <div class="flex min-w-0 flex-1 flex-col">
            <div class="flex min-w-0 items-center gap-1.5">
              <Tip
                :label="
                  effectsCtx.expandedIndex.value === index
                    ? panels.collapseEffectSettings
                    : panels.expandEffectSettings
                "
              >
                <button
                  type="button"
                  :aria-expanded="effectsCtx.expandedIndex.value === index"
                  :aria-label="
                    effectsCtx.expandedIndex.value === index
                      ? panels.collapseEffectSettings
                      : panels.expandEffectSettings
                  "
                  data-property="effect-expand"
                  class="flex size-5 shrink-0 cursor-pointer items-center justify-center overflow-hidden rounded border border-border bg-input p-0"
                  @click="effectsCtx.toggleExpand(index)"
                >
                  <FillSwatch
                    v-if="effectsCtx.isShadow(effect.type)"
                    :fill="effectPreview(effect)"
                    class="size-full border-0"
                  />
                  <icon-lucide-blend v-else class="size-3 text-muted" />
                </button>
              </Tip>

              <AppSelect
                class="min-w-0 flex-1"
                :model-value="effect.type"
                :options="effectsCtx.effectOptions"
                :label="panels.effects"
                data-property="effect-type"
                @update:model-value="
                  effectsCtx.updateType(actions.patch, activeNode, index, $event as Effect['type'])
                "
              />
            </div>
          </div>
        </PropertyItemRow>

        <div
          v-if="effectsCtx.expandedIndex.value === index"
          class="flex flex-col gap-1.5 py-2"
          data-slot="effect-settings"
        >
          <PanelFieldGroup :label="panels.blendMode">
            <AppSelect
              :model-value="effect.blendMode ?? 'NORMAL'"
              :options="blendModeOptions"
              :label="panels.blendMode"
              data-property="effect-blend-mode"
              @update:model-value="
                commitDiscretePropertyListChange(flush, () =>
                  actions.patch(index, { blendMode: $event as Effect['blendMode'] })
                )
              "
            />
          </PanelFieldGroup>
          <template v-if="effectsCtx.isShadow(effect.type)">
            <div class="flex items-center gap-1.5">
              <Tip :label="panels.xAxis">
                <NumberField
                  icon="X"
                  :model-value="effect.offset.x"
                  data-property="effect-offset-x"
                  @update:model-value="
                    effectsCtx.scrubEffect(activeNode, index, {
                      offset: { ...effect.offset, x: $event }
                    })
                  "
                  @commit="
                    effectsCtx.commitEffect(activeNode, index, {
                      offset: { ...effect.offset, x: $event }
                    })
                  "
                />
              </Tip>
              <Tip :label="panels.yAxis">
                <NumberField
                  icon="Y"
                  :model-value="effect.offset.y"
                  data-property="effect-offset-y"
                  @update:model-value="
                    effectsCtx.scrubEffect(activeNode, index, {
                      offset: { ...effect.offset, y: $event }
                    })
                  "
                  @commit="
                    effectsCtx.commitEffect(activeNode, index, {
                      offset: { ...effect.offset, y: $event }
                    })
                  "
                />
              </Tip>
            </div>

            <div class="flex items-center gap-1.5">
              <Tip :label="panels.radius">
                <NumberField
                  icon="B"
                  :model-value="effect.radius"
                  :min="0"
                  data-property="effect-radius"
                  @update:model-value="
                    effectsCtx.scrubEffect(activeNode, index, { radius: $event })
                  "
                  @commit="effectsCtx.commitEffect(activeNode, index, { radius: $event })"
                />
              </Tip>
              <Tip :label="panels.spread">
                <NumberField
                  icon="S"
                  :model-value="effect.spread"
                  data-property="effect-spread"
                  @update:model-value="
                    effectsCtx.scrubEffect(activeNode, index, { spread: $event })
                  "
                  @commit="effectsCtx.commitEffect(activeNode, index, { spread: $event })"
                />
              </Tip>
            </div>

            <div class="flex items-center gap-1.5">
              <ColorInput
                class="min-w-0 flex-1"
                :color="effect.color"
                editable
                @update="effectsCtx.updateColor(actions.patch, index, $event)"
              />
              <Tip :label="panels.opacity">
                <NumberField
                  class="w-14"
                  suffix="%"
                  :model-value="Math.round(effect.color.a * 100)"
                  :min="0"
                  :max="100"
                  data-property="effect-opacity"
                  @update:model-value="
                    effectsCtx.scrubEffect(activeNode, index, {
                      color: { ...effect.color, a: Math.max(0, Math.min(1, $event / 100)) }
                    })
                  "
                  @commit="
                    effectsCtx.commitEffect(activeNode, index, {
                      color: { ...effect.color, a: Math.max(0, Math.min(1, $event / 100)) }
                    })
                  "
                />
              </Tip>
            </div>
          </template>

          <NumberField
            v-else
            class="w-24 flex-none"
            icon="B"
            :model-value="effect.radius"
            :min="0"
            data-property="effect-radius"
            @update:model-value="effectsCtx.scrubEffect(activeNode, index, { radius: $event })"
            @commit="effectsCtx.commitEffect(activeNode, index, { radius: $event })"
          />
        </div>
      </div>
    </PanelSection>
  </PropertyListRoot>
</template>

// packages/react/src/components/properties/EffectsSection.tsx
import { NumberField } from '#react/components/inputs/NumberField'
import { ColorRow } from '#react/components/properties/ColorRow'
import { SharedStyleField } from '#react/components/properties/shared-style/SharedStyleField'
import { AppSelect } from '#react/components/ui/AppSelect'
import { IconButton } from '#react/components/ui/IconButton'
import { PanelFieldGroup } from '#react/components/ui/panel/PanelFieldGroup'
import { PanelSection } from '#react/components/ui/panel/PanelSection'
import { Tip } from '#react/components/ui/Tip'
import { patchEffectsForNodes, useEffectsControls } from '#react/controls/effects'
import { useSharedStyleBinding } from '#react/controls/shared-style'
import { useEditor } from '#react/editor/context'
import { useSelectionState } from '#react/editor/selection-state/use'
import { useI18n } from '#react/i18n'
import { useSceneComputed } from '#react/internal/scene-computed/use'
import { Blend, Eye, EyeOff, Minus, Plus } from 'lucide-react'

import type { BlendMode, Effect, SceneNode } from '@open-pencil/scene-graph'

function useBlendModeOptions() {
  const { panels } = useI18n()
  return [
    { value: 'NORMAL' as const, label: panels.blendModeNormal },
    { value: 'DARKEN' as const, label: panels.blendModeDarken },
    { value: 'MULTIPLY' as const, label: panels.blendModeMultiply },
    { value: 'COLOR_BURN' as const, label: panels.blendModeColorBurn },
    { value: 'LIGHTEN' as const, label: panels.blendModeLighten },
    { value: 'SCREEN' as const, label: panels.blendModeScreen },
    { value: 'COLOR_DODGE' as const, label: panels.blendModeColorDodge },
    { value: 'OVERLAY' as const, label: panels.blendModeOverlay },
    { value: 'SOFT_LIGHT' as const, label: panels.blendModeSoftLight },
    { value: 'HARD_LIGHT' as const, label: panels.blendModeHardLight },
    { value: 'DIFFERENCE' as const, label: panels.blendModeDifference },
    { value: 'EXCLUSION' as const, label: panels.blendModeExclusion },
    { value: 'HUE' as const, label: panels.blendModeHue },
    { value: 'SATURATION' as const, label: panels.blendModeSaturation },
    { value: 'COLOR' as const, label: panels.blendModeColor },
    { value: 'LUMINOSITY' as const, label: panels.blendModeLuminosity }
  ]
}

export function EffectsSection() {
  const editor = useEditor()
  const { hasSelection } = useSelectionState()
  const { panels } = useI18n()
  const effectsCtx = useEffectsControls()
  const effectStyle = useSharedStyleBinding('effect')
  const blendModeOptions = useBlendModeOptions()
  const nodes = useSceneComputed(() => editor.getSelectedNodes())
  if (!hasSelection) return null

  const activeNode = nodes[0] ?? null
  const items = activeNode?.effects ?? []
  const mixed =
    nodes.length > 1 &&
    nodes.some(
      (node) =>
        node.effects.length !== items.length ||
        node.effects.some((effect, index) => effect.type !== items[index]?.type)
    )

  return (
    <PanelSection
      label={panels.effects}
      empty={!mixed && items.length === 0 && !effectStyle.visible}
      actions={
        <IconButton
          label={panels.addEffect}
          onClick={() =>
            patchEffectsForNodes(
              editor,
              nodes,
              (effects) => [...effects, effectsCtx.createDefaultEffect()],
              'Add effect'
            )
          }
        >
          <Plus className="size-3.5" />
        </IconButton>
      }
    >
      <SharedStyleField binding={effectStyle} label={panels.effectStyle} />
      {mixed ? <p className="text-[11px] text-muted">{panels.mixedEffectsHelp}</p> : null}
      {items.map((effect, index) => (
        <EffectRow
          key={`${index}:${effect.visible ? 'visible' : 'hidden'}`}
          effect={effect}
          index={index}
          node={activeNode}
          blendModeOptions={blendModeOptions}
          effectsCtx={effectsCtx}
        />
      ))}
    </PanelSection>
  )
}

function EffectRow({
  effect,
  index,
  node,
  blendModeOptions,
  effectsCtx
}: {
  effect: Effect
  index: number
  node: SceneNode | null
  blendModeOptions: Array<{ value: BlendMode; label: string }>
  effectsCtx: ReturnType<typeof useEffectsControls>
}) {
  const { panels } = useI18n()
  const expanded = effectsCtx.expandedIndex === index
  const shadow = effectsCtx.isShadow(effect.type)

  return (
    <div className="mb-1.5 last:mb-0" data-effect-index={index} data-effect-group="">
      <div className="flex items-start gap-1">
        <div className="flex min-w-0 flex-1 flex-col">
          <div className="flex min-w-0 items-center gap-1.5">
            <Tip label={expanded ? panels.collapseEffectSettings : panels.expandEffectSettings}>
              <button
                type="button"
                aria-expanded={expanded}
                aria-label={expanded ? panels.collapseEffectSettings : panels.expandEffectSettings}
                data-property="effect-expand"
                className="flex size-5 shrink-0 cursor-pointer items-center justify-center overflow-hidden rounded border border-border bg-input p-0"
                onClick={() => effectsCtx.toggleExpand(index)}
              >
                {shadow ? (
                  <span
                    className="size-full"
                    style={{
                      backgroundColor: `rgb(${effect.color.r * 255} ${effect.color.g * 255} ${effect.color.b * 255})`
                    }}
                  />
                ) : (
                  <Blend className="size-3 text-muted" />
                )}
              </button>
            </Tip>
            <AppSelect
              className="min-w-0 flex-1"
              label={panels.effects}
              data-property="effect-type"
              value={effect.type}
              options={effectsCtx.effectOptions}
              onChange={(type) => effectsCtx.updateType(node, index, type)}
            />
          </div>
          {expanded ? (
            <div className="flex flex-col gap-1.5 py-1.5" data-slot="effect-settings">
              <PanelFieldGroup label={panels.blendMode}>
                <AppSelect
                  label={panels.blendMode}
                  data-property="effect-blend-mode"
                  value={effect.blendMode ?? 'NORMAL'}
                  options={blendModeOptions}
                  onChange={(blendMode) => effectsCtx.commitEffect(node, index, { blendMode })}
                />
              </PanelFieldGroup>
              {shadow ? (
                <>
                  <div className="flex items-center gap-1.5">
                    <Tip label={panels.xAxis}>
                      <NumberField
                        icon="X"
                        data-property="effect-offset-x"
                        value={effect.offset.x}
                        onCommit={(value) =>
                          effectsCtx.commitEffect(node, index, {
                            offset: { ...effect.offset, x: value }
                          })
                        }
                      />
                    </Tip>
                    <Tip label={panels.yAxis}>
                      <NumberField
                        icon="Y"
                        data-property="effect-offset-y"
                        value={effect.offset.y}
                        onCommit={(value) =>
                          effectsCtx.commitEffect(node, index, {
                            offset: { ...effect.offset, y: value }
                          })
                        }
                      />
                    </Tip>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <Tip label={panels.radius}>
                      <NumberField
                        icon="B"
                        min={0}
                        data-property="effect-radius"
                        value={effect.radius}
                        onCommit={(value) =>
                          effectsCtx.commitEffect(node, index, { radius: value })
                        }
                      />
                    </Tip>
                    <Tip label={panels.spread}>
                      <NumberField
                        icon="S"
                        data-property="effect-spread"
                        value={effect.spread}
                        onCommit={(value) =>
                          effectsCtx.commitEffect(node, index, { spread: value })
                        }
                      />
                    </Tip>
                  </div>
                  <ColorRow
                    color={effect.color}
                    opacity={effect.color.a}
                    label={panels.editColor}
                    onColor={(color) => effectsCtx.updateColor(node, index, color)}
                    onOpacity={(opacity) =>
                      effectsCtx.commitEffect(node, index, {
                        color: { ...effect.color, a: opacity }
                      })
                    }
                  />
                </>
              ) : (
                <NumberField
                  icon="B"
                  min={0}
                  data-property="effect-radius"
                  value={effect.radius}
                  onCommit={(value) => effectsCtx.commitEffect(node, index, { radius: value })}
                />
              )}
            </div>
          ) : null}
        </div>
        <IconButton
          label={panels.toggleVisibility}
          active={effect.visible === false}
          onClick={() => effectsCtx.toggleVisibility(node, index)}
        >
          {effect.visible === false ? (
            <EyeOff className="size-3.5" />
          ) : (
            <Eye className="size-3.5" />
          )}
        </IconButton>
        <IconButton
          label={panels.removeEffect}
          onClick={() => effectsCtx.removeEffect(node, index)}
        >
          <Minus className="size-3.5" />
        </IconButton>
      </div>
    </div>
  )
}
