// src/components/properties/LayoutSection/size/SizeAxisField.tsx
import IconLucideCheck from '~icons/lucide/check'
import IconLucideChevronDown from '~icons/lucide/chevron-down'
import * as Select from '@radix-ui/react-select'
import { memo, useCallback, useMemo } from 'react'

import { useI18n, type SizeLimitProp } from '@open-pencil/react'
import type { LayoutSizing } from '@open-pencil/scene-graph'

import VariableNumberField from '@/components/properties/VariableNumberField'
import { useLayoutContext } from '@/components/properties/LayoutSection/types'
import type { SizeAxisFieldProps } from '@/components/properties/LayoutSection/size/types'
import Tip from '@/components/ui/Tip'
import { useSelectUI } from '@/components/ui/select'

type SizeSelectValue = LayoutSizing | `add-${SizeLimitProp}` | `remove-${SizeLimitProp}`

export const SizeAxisField = memo(function SizeAxisField({ axis, icon, label }: SizeAxisFieldProps) {
  const ctx = useLayoutContext()
  const { panels } = useI18n()
  const selectUI = useSelectUI({ item: 'rounded py-1.5 pr-2 pl-6 text-xs' })

  const sizing = axis === 'width' ? ctx.widthSizing : ctx.heightSizing
  const sizingOptions = axis === 'width' ? ctx.widthSizingOptions : ctx.heightSizingOptions
  const sizingLabel =
    sizing === 'HUG'
      ? panels.sizingHugShort
      : sizing === 'FILL'
        ? panels.sizingFillShort
        : ''

  const limitItems = useMemo(
    () =>
      axis === 'width'
        ? [
            { prop: 'minWidth' as const, addLabel: panels.addMinWidth, removeLabel: panels.removeMinWidth },
            { prop: 'maxWidth' as const, addLabel: panels.addMaxWidth, removeLabel: panels.removeMaxWidth }
          ]
        : [
            {
              prop: 'minHeight' as const,
              addLabel: panels.addMinHeight,
              removeLabel: panels.removeMinHeight
            },
            {
              prop: 'maxHeight' as const,
              addLabel: panels.addMaxHeight,
              removeLabel: panels.removeMaxHeight
            }
          ],
    [
      axis,
      panels.addMaxHeight,
      panels.addMaxWidth,
      panels.addMinHeight,
      panels.addMinWidth,
      panels.removeMaxHeight,
      panels.removeMaxWidth,
      panels.removeMinHeight,
      panels.removeMinWidth
    ]
  )

  const handleSelect = useCallback(
    (value: SizeSelectValue) => {
      if (value === 'FIXED' || value === 'HUG' || value === 'FILL') {
        ctx.setAxisSizing(axis, value)
        return
      }

      const [action, prop] = value.split('-') as ['add' | 'remove', SizeLimitProp]
      if (action === 'add') ctx.addSizeLimit(prop)
      else ctx.removeSizeLimit(prop)
    },
    [axis, ctx]
  )

  const sizingMenu = (
    <Select.Root value={sizing} onValueChange={(value) => handleSelect(value as SizeSelectValue)}>
      <Select.Trigger
        data-slot="sizing-trigger"
        aria-label={label}
        className="flex shrink-0 cursor-pointer items-center gap-0.5 self-stretch border-none bg-transparent px-1.5 text-[10px] text-muted outline-none data-[state=open]:text-foreground"
        onPointerDown={(event) => event.stopPropagation()}
      >
        {sizingLabel ? <span>{sizingLabel}</span> : null}
        <IconLucideChevronDown className="size-3" />
      </Select.Trigger>
      <Select.Portal>
        <Select.Content position="popper" align="start" sideOffset={4} className={selectUI.content}>
          <Select.Viewport className="p-0.5">
            {sizingOptions.map((option) => (
              <Select.Item key={option.value} value={option.value} className={selectUI.item}>
                <Select.ItemIndicator className="absolute left-1.5 inline-flex items-center justify-center">
                  <IconLucideCheck className="size-3 text-accent" />
                </Select.ItemIndicator>
                <Select.ItemText>{option.label}</Select.ItemText>
              </Select.Item>
            ))}
            {limitItems.map((item) => (
              <Select.Item
                key={item.prop}
                value={`${ctx.node[item.prop] == null ? 'add' : 'remove'}-${item.prop}`}
                className={selectUI.item}
              >
                <Select.ItemText>
                  {ctx.node[item.prop] == null ? item.addLabel : item.removeLabel}
                </Select.ItemText>
              </Select.Item>
            ))}
          </Select.Viewport>
        </Select.Content>
      </Select.Portal>
    </Select.Root>
  )

  return (
    <Tip label={label}>
      <VariableNumberField
        icon={icon}
        aria-label={label}
        value={Math.round(ctx.node[axis])}
        min={0}
        nodeId={ctx.node.id}
        bindingPath={axis}
        afterVariable={sizingMenu}
        onValueChange={(value) => ctx.updateAxisSize(axis, value)}
        onCommit={(value, previous) => ctx.commitAxisSize(axis, value, previous)}
      />
    </Tip>
  )
})

SizeAxisField.displayName = 'SizeAxisField'
export default SizeAxisField

// src/components/properties/layout/size/SizeAxisField.vue
<script setup lang="ts">
import {
  SelectContent,
  SelectItem,
  SelectItemIndicator,
  SelectItemText,
  SelectPortal,
  SelectRoot,
  SelectTrigger,
  SelectViewport
} from 'reka-ui'

import type { LayoutSizing } from '@open-pencil/scene-graph'
import { useI18n, useLayoutControlsContext } from '@open-pencil/vue'
import type { SizeLimitProp } from '@open-pencil/vue'

import type { SizeAxisFieldProps } from '@/components/properties/layout/size/types'
import VariableNumberField from '@/components/properties/VariableNumberField.vue'
import Tip from '@/components/ui/overlay/Tip.vue'
import { useSelectUI } from '@/components/ui/select/select'

type SizeSelectValue = LayoutSizing | `add-${SizeLimitProp}` | `remove-${SizeLimitProp}`

const { axis, icon, label } = defineProps<SizeAxisFieldProps>()

const ctx = useLayoutControlsContext()
const { panels } = useI18n()
const selectUI = useSelectUI({ item: 'rounded py-1.5 pr-2 pl-6 text-xs' })

const sizing = () => (axis === 'width' ? ctx.widthSizing : ctx.heightSizing)
const sizingOptions = () => (axis === 'width' ? ctx.widthSizingOptions : ctx.heightSizingOptions)
const sizingLabel = () => {
  if (sizing() === 'HUG') return panels.value.sizingHugShort
  if (sizing() === 'FILL') return panels.value.sizingFillShort
  return ''
}
const limitItems = () =>
  axis === 'width'
    ? [
        {
          prop: 'minWidth' as const,
          addLabel: panels.value.addMinWidth,
          removeLabel: panels.value.removeMinWidth
        },
        {
          prop: 'maxWidth' as const,
          addLabel: panels.value.addMaxWidth,
          removeLabel: panels.value.removeMaxWidth
        }
      ]
    : [
        {
          prop: 'minHeight' as const,
          addLabel: panels.value.addMinHeight,
          removeLabel: panels.value.removeMinHeight
        },
        {
          prop: 'maxHeight' as const,
          addLabel: panels.value.addMaxHeight,
          removeLabel: panels.value.removeMaxHeight
        }
      ]

function handleSelect(value: SizeSelectValue) {
  if (value === 'FIXED' || value === 'HUG' || value === 'FILL') {
    ctx.setAxisSizing(axis, value)
    return
  }

  const [action, prop] = value.split('-') as ['add' | 'remove', SizeLimitProp]
  if (action === 'add') ctx.addSizeLimit(prop)
  else ctx.removeSizeLimit(prop)
}
</script>

<template>
  <Tip :label="label">
    <VariableNumberField
      :icon="icon"
      :aria-label="label"
      :model-value="Math.round(ctx.node[axis])"
      :min="0"
      :node-id="ctx.node.id"
      :binding-path="axis"
      @update:model-value="ctx.updateAxisSize(axis, $event)"
      @commit="(value: number, previous: number) => ctx.commitAxisSize(axis, value, previous)"
    >
      <template #after-variable>
        <SelectRoot
          :model-value="sizing()"
          @update:model-value="handleSelect($event as SizeSelectValue)"
        >
          <SelectTrigger
            data-slot="sizing-trigger"
            :aria-label="label"
            class="flex shrink-0 cursor-pointer items-center gap-0.5 self-stretch border-none bg-transparent px-1.5 text-[10px] text-muted outline-none data-[state=open]:text-foreground"
            @pointerdown.stop
          >
            <span v-if="sizingLabel()">{{ sizingLabel() }}</span>
            <icon-lucide-chevron-down class="size-3" />
          </SelectTrigger>
          <SelectPortal>
            <SelectContent
              position="popper"
              align="start"
              :side-offset="4"
              :class="selectUI.content"
            >
              <SelectViewport class="p-0.5">
                <SelectItem
                  v-for="option in sizingOptions()"
                  :key="option.value"
                  :value="option.value"
                  :class="selectUI.item"
                >
                  <SelectItemIndicator
                    class="absolute left-1.5 inline-flex items-center justify-center"
                  >
                    <icon-lucide-check class="size-3 text-accent" />
                  </SelectItemIndicator>
                  <SelectItemText>{{ option.label }}</SelectItemText>
                </SelectItem>
                <SelectItem
                  v-for="item in limitItems()"
                  :key="item.prop"
                  :value="`${ctx.node[item.prop] == null ? 'add' : 'remove'}-${item.prop}`"
                  :class="selectUI.item"
                >
                  <SelectItemText>
                    {{ ctx.node[item.prop] == null ? item.addLabel : item.removeLabel }}
                  </SelectItemText>
                </SelectItem>
              </SelectViewport>
            </SelectContent>
          </SelectPortal>
        </SelectRoot>
      </template>
    </VariableNumberField>
  </Tip>
</template>
