// src/components/properties/AppearanceSection.tsx
<script setup lang="ts">
import { computed, ref } from 'vue'

import { useAppearance, useI18n } from '@open-pencil/vue'

import ScrubInput from '@/components/ScrubInput.vue'
import Tip from '@/components/ui/Tip.vue'
import { sectionWrapper } from '@/components/ui/section'

const { panels } = useI18n()
const {
  node,
  isMulti,
  active,
  hasCornerRadius,
  independentCorners,
  cornerRadiusValue,
  opacityPercent,
  visibilityState,
  updateProp,
  commitProp,
  toggleVisibility,
  toggleIndependentCorners,
  updateCornerProp,
  commitCornerProp
} = useAppearance()

const manualExpanded = ref<boolean | null>(null)

const showIndependentCorners = computed(() => {
  if (manualExpanded.value !== null) return manualExpanded.value
  if (independentCorners.value === true) return true
  const n = node.value
  if (!n) return false
  return !(
    n.topLeftRadius === n.topRightRadius &&
    n.topLeftRadius === n.bottomRightRadius &&
    n.topLeftRadius === n.bottomLeftRadius
  )
})

function onToggleCorners() {
  manualExpanded.value = !showIndependentCorners.value
  toggleIndependentCorners()
}
</script>

<template>
  <div v-if="active" data-test-id="appearance-section" :class="sectionWrapper()">
    <div class="mb-1.5 flex items-center justify-between">
      <label class="text-[11px] text-muted">{{ panels.appearance }}</label>
      <Tip :label="panels.toggleVisibility">
        <button
          data-test-id="appearance-visibility"
          class="flex cursor-pointer items-center justify-center rounded border-none bg-transparent p-0.5 text-muted hover:bg-hover hover:text-surface"
          :class="{ 'text-accent': visibilityState === 'hidden' }"
          @click="toggleVisibility"
        >
          <icon-lucide-eye v-if="visibilityState === 'visible'" class="size-3.5" />
          <icon-lucide-eye-off v-else-if="visibilityState === 'hidden'" class="size-3.5" />
          <icon-lucide-eye v-else class="size-3.5 opacity-50" />
        </button>
      </Tip>
    </div>

    <div class="flex gap-1.5">
      <ScrubInput
        suffix="%"
        :model-value="opacityPercent"
        :min="0"
        :max="100"
        @update:model-value="updateProp('opacity', $event / 100)"
        @commit="(v: number, p: number) => commitProp('opacity', v / 100, p / 100)"
      >
        <template #icon>
          <icon-lucide-blend class="size-3" />
        </template>
      </ScrubInput>

      <template v-if="hasCornerRadius">
        <ScrubInput
          v-if="!showIndependentCorners"
          :model-value="cornerRadiusValue"
          :min="0"
          @update:model-value="updateProp('cornerRadius', $event)"
          @commit="(v: number, p: number) => commitProp('cornerRadius', v, p)"
        >
          <template #icon>
            <icon-lucide-square-round-corner class="size-3" />
          </template>
        </ScrubInput>

        <Tip :label="panels.independentCornerRadii">
          <button
            data-test-id="independent-corners-toggle"
            class="flex size-[26px] shrink-0 cursor-pointer items-center justify-center rounded border border-border bg-input text-muted hover:bg-hover hover:text-surface"
            :class="{ '!border-accent !text-accent': showIndependentCorners }"
            @click="onToggleCorners"
          >
            <svg
              class="size-3"
              viewBox="0 0 12 12"
              fill="none"
              stroke="currentColor"
              stroke-width="1.5"
            >
              <path d="M1 4V2.5A1.5 1.5 0 0 1 2.5 1H4" />
              <path d="M8 1h1.5A2.5 2.5 0 0 1 11 3.5V5" />
              <path d="M11 8v1a2 2 0 0 1-2 2H8" />
              <path d="M4 11H3a2 2 0 0 1-2-2V8" />
            </svg>
          </button>
        </Tip>
      </template>
    </div>

    <div
      v-if="hasCornerRadius && showIndependentCorners && !isMulti && node"
      data-test-id="independent-corners-grid"
      class="mt-1.5 grid grid-cols-2 gap-1.5"
    >
      <ScrubInput
        :model-value="node.topLeftRadius"
        :min="0"
        @update:model-value="updateCornerProp('topLeftRadius', $event)"
        @commit="(v: number, p: number) => commitCornerProp('topLeftRadius', v, p)"
      >
        <template #icon>
          <svg
            class="size-3"
            viewBox="0 0 12 12"
            fill="none"
            stroke="currentColor"
            stroke-width="1.5"
          >
            <path d="M1 11V4a3 3 0 0 1 3-3h7" />
          </svg>
        </template>
      </ScrubInput>
      <ScrubInput
        :model-value="node.topRightRadius"
        :min="0"
        @update:model-value="updateCornerProp('topRightRadius', $event)"
        @commit="(v: number, p: number) => commitCornerProp('topRightRadius', v, p)"
      >
        <template #icon>
          <svg
            class="size-3"
            viewBox="0 0 12 12"
            fill="none"
            stroke="currentColor"
            stroke-width="1.5"
          >
            <path d="M11 11V4a3 3 0 0 0-3-3H1" />
          </svg>
        </template>
      </ScrubInput>
      <ScrubInput
        :model-value="node.bottomLeftRadius"
        :min="0"
        @update:model-value="updateCornerProp('bottomLeftRadius', $event)"
        @commit="(v: number, p: number) => commitCornerProp('bottomLeftRadius', v, p)"
      >
        <template #icon>
          <svg
            class="size-3"
            viewBox="0 0 12 12"
            fill="none"
            stroke="currentColor"
            stroke-width="1.5"
          >
            <path d="M1 1v7a3 3 0 0 0 3 3h7" />
          </svg>
        </template>
      </ScrubInput>
      <ScrubInput
        :model-value="node.bottomRightRadius"
        :min="0"
        @update:model-value="updateCornerProp('bottomRightRadius', $event)"
        @commit="(v: number, p: number) => commitCornerProp('bottomRightRadius', v, p)"
      >
        <template #icon>
          <svg
            class="size-3"
            viewBox="0 0 12 12"
            fill="none"
            stroke="currentColor"
            stroke-width="1.5"
          >
            <path d="M11 1v7a3 3 0 0 1-3 3H1" />
          </svg>
        </template>
      </ScrubInput>
    </div>
  </div>
</template>

// src/react_app/properties/AppearanceSection.tsx
import { Blend, Eye, EyeOff, SquareRoundCorner } from 'lucide-react'
import { useState } from 'react'

import { ScrubInput } from '@/react_app/pickers/ScrubInput'
import { sectionWrapper } from '@/react_app/ui/section'
import { Tip, TipProvider } from '@/react_app/ui/Tip'
import { useAppearance, useI18n } from '@open-pencil/react'

export function AppearanceSection() {
  const { panels } = useI18n()
  const {
    node,
    isMulti,
    active,
    hasCornerRadius,
    independentCorners,
    cornerRadiusValue,
    opacityPercent,
    visibilityState,
    updateProp,
    commitProp,
    toggleVisibility,
    toggleIndependentCorners,
    updateCornerProp,
    commitCornerProp
  } = useAppearance()

  const [manualExpanded, setManualExpanded] = useState<boolean | null>(null)

  const showIndependentCorners = (() => {
    if (manualExpanded !== null) return manualExpanded
    if (independentCorners === true) return true
    if (!node) return false
    return !(
      node.topLeftRadius === node.topRightRadius &&
      node.topLeftRadius === node.bottomRightRadius &&
      node.topLeftRadius === node.bottomLeftRadius
    )
  })()

  function onToggleCorners() {
    setManualExpanded(!showIndependentCorners)
    toggleIndependentCorners()
  }

  if (!active) return null

  return (
    <TipProvider>
      <div data-test-id="appearance-section" className={sectionWrapper()}>
        <div className="mb-1.5 flex items-center justify-between">
          <label className="text-[11px] text-muted">{panels.appearance}</label>
          <Tip label={panels.toggleVisibility}>
            <button
              type="button"
              data-test-id="appearance-visibility"
              className={`flex cursor-pointer items-center justify-center rounded border-none bg-transparent p-0.5 text-muted hover:bg-hover hover:text-surface ${
                visibilityState === 'hidden' ? 'text-accent' : ''
              }`}
              onClick={toggleVisibility}
            >
              {visibilityState === 'hidden' ? (
                <EyeOff className="size-3.5" />
              ) : visibilityState === 'mixed' ? (
                <Eye className="size-3.5 opacity-50" />
              ) : (
                <Eye className="size-3.5" />
              )}
            </button>
          </Tip>
        </div>

        <div className="flex gap-1.5">
          <ScrubInput
            suffix="%"
            value={opacityPercent}
            min={0}
            max={100}
            onValueChange={(v) => updateProp('opacity', v / 100)}
            onCommit={(v, p) => commitProp('opacity', v / 100, p / 100)}
            iconSlot={<Blend className="size-3" />}
          />

          {hasCornerRadius ? (
            <>
              {!showIndependentCorners ? (
                <ScrubInput
                  value={cornerRadiusValue}
                  min={0}
                  onValueChange={(v) => updateProp('cornerRadius', v)}
                  onCommit={(v, p) => commitProp('cornerRadius', v, p)}
                  iconSlot={<SquareRoundCorner className="size-3" />}
                />
              ) : null}
              <Tip label={panels.independentCornerRadii}>
                <button
                  type="button"
                  data-test-id="independent-corners-toggle"
                  className={`flex size-[26px] shrink-0 cursor-pointer items-center justify-center rounded border border-border bg-input text-muted hover:bg-hover hover:text-surface ${
                    showIndependentCorners ? '!border-accent !text-accent' : ''
                  }`}
                  onClick={onToggleCorners}
                >
                  <svg
                    className="size-3"
                    viewBox="0 0 12 12"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                  >
                    <path d="M1 4V2.5A1.5 1.5 0 0 1 2.5 1H4" />
                    <path d="M8 1h1.5A2.5 2.5 0 0 1 11 3.5V5" />
                    <path d="M11 8v1a2 2 0 0 1-2 2H8" />
                    <path d="M4 11H3a2 2 0 0 1-2-2V8" />
                  </svg>
                </button>
              </Tip>
            </>
          ) : null}
        </div>

        {hasCornerRadius && showIndependentCorners && !isMulti && node ? (
          <div data-test-id="independent-corners-grid" className="mt-1.5 grid grid-cols-2 gap-1.5">
            {(
              [
                {
                  key: 'topLeftRadius' as const,
                  path: 'M1 11V4a3 3 0 0 1 3-3h7'
                },
                {
                  key: 'topRightRadius' as const,
                  path: 'M11 11V4a3 3 0 0 0-3-3H1'
                },
                {
                  key: 'bottomLeftRadius' as const,
                  path: 'M1 1v7a3 3 0 0 0 3 3h7'
                },
                {
                  key: 'bottomRightRadius' as const,
                  path: 'M11 1v7a3 3 0 0 1-3 3H1'
                }
              ] as const
            ).map((corner) => (
              <ScrubInput
                key={corner.key}
                value={node[corner.key]}
                min={0}
                onValueChange={(v) => updateCornerProp(corner.key, v)}
                onCommit={(v, p) => commitCornerProp(corner.key, v, p)}
                iconSlot={
                  <svg
                    className="size-3"
                    viewBox="0 0 12 12"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                  >
                    <path d={corner.path} />
                  </svg>
                }
              />
            ))}
          </div>
        ) : null}
      </div>
    </TipProvider>
  )
}
