// src/components/properties/PageSection.tsx
<script setup lang="ts">
import { computed } from 'vue'

import { useI18n } from '@open-pencil/vue'
import ColorInput from '@/components/ColorInput.vue'
import { sectionWrapper } from '@/components/ui/section'

import { useEditorStore } from '@/stores/editor'

const editor = useEditorStore()
const pageColor = computed(() => editor.state.pageColor)
const { panels } = useI18n()
</script>

<template>
  <div data-test-id="page-section" :class="sectionWrapper()">
    <label class="mb-1.5 block text-[11px] text-muted">{{ panels.page ?? 'Page' }}</label>
    <ColorInput :color="pageColor" editable @update="editor.setPageColor($event)" />
  </div>
</template>

// src/react_app/properties/PageSection.tsx
import { ColorInput } from '@/react_app/pickers/ColorInput'
import { sectionWrapper } from '@/react_app/ui/section'
import { useEditor, useEditorSelector, useI18n } from '@open-pencil/react'

import type { Color } from '@open-pencil/core'
import type { Editor } from '@open-pencil/core/editor'

type AppEditor = Editor & {
  state: Editor['state'] & { pageColor: Color }
  setPageColor: (color: Color) => void
}

export function PageSection() {
  const editor = useEditor() as AppEditor
  const pageColor = useEditorSelector((e) => (e as AppEditor).state.pageColor)
  const { panels } = useI18n()

  return (
    <div data-test-id="page-section" className={sectionWrapper()}>
      <label className="mb-1.5 block text-[11px] text-muted">{panels.page ?? 'Page'}</label>
      <ColorInput color={pageColor} editable onUpdate={(c) => editor.setPageColor(c)} />
    </div>
  )
}
