// src/components/properties/PositionSection.vue
<script setup lang="ts">
import { PositionControlsRoot, useI18n } from '@open-pencil/vue'

import { useEditorStore } from '@/app/editor/active-store'
import NumberField from '@/components/inputs/NumberField.vue'
import IconButton from '@/components/ui/button/IconButton.vue'
import Tip from '@/components/ui/overlay/Tip.vue'
import PanelGrid from '@/components/ui/panel/PanelGrid.vue'
import PanelSection from '@/components/ui/panel/PanelSection.vue'

const { panels } = useI18n()
const store = useEditorStore()

function handleAlign(
  nodeAlign: (axis: 'horizontal' | 'vertical', pos: 'min' | 'center' | 'max') => void,
  axis: 'horizontal' | 'vertical',
  pos: 'min' | 'center' | 'max'
) {
  const editState = store.state.nodeEditState
  if (editState && editState.selectedVertexIndices.size >= 2) {
    store.nodeEditAlignVertices(axis, pos)
  } else {
    nodeAlign(axis, pos)
  }
}
</script>

<template>
  <PositionControlsRoot
    v-slot="{ active, isMulti, xValue, yValue, wValue, hValue, rotationValue, actions }"
  >
    <PanelSection v-if="active" :label="panels.position">
      <div role="toolbar" :aria-label="panels.position" class="mb-1.5 flex justify-between">
        <div class="flex gap-0.5">
          <IconButton
            :label="panels.alignLeft"
            size="xs"
            @click="handleAlign(actions.align, 'horizontal', 'min')"
          >
            <icon-lucide-align-start-vertical class="size-3.5" />
          </IconButton>
          <IconButton
            :label="panels.alignCenterHorizontally"
            size="xs"
            @click="handleAlign(actions.align, 'horizontal', 'center')"
          >
            <icon-lucide-align-center-vertical class="size-3.5" />
          </IconButton>
          <IconButton
            :label="panels.alignRight"
            size="xs"
            @click="handleAlign(actions.align, 'horizontal', 'max')"
          >
            <icon-lucide-align-end-vertical class="size-3.5" />
          </IconButton>
        </div>
        <div class="flex gap-0.5">
          <IconButton
            :label="panels.alignTop"
            size="xs"
            @click="handleAlign(actions.align, 'vertical', 'min')"
          >
            <icon-lucide-align-start-horizontal class="size-3.5" />
          </IconButton>
          <IconButton
            :label="panels.alignCenterVertically"
            size="xs"
            @click="handleAlign(actions.align, 'vertical', 'center')"
          >
            <icon-lucide-align-center-horizontal class="size-3.5" />
          </IconButton>
          <IconButton
            :label="panels.alignBottom"
            size="xs"
            @click="handleAlign(actions.align, 'vertical', 'max')"
          >
            <icon-lucide-align-end-horizontal class="size-3.5" />
          </IconButton>
        </div>
      </div>

      <PanelGrid :columns="2">
        <Tip :label="panels.xAxis">
          <NumberField
            icon="X"
            data-property="x"
            :aria-label="panels.xAxis"
            :model-value="xValue"
            @update:model-value="actions.updateProp('x', $event)"
            @commit="(v: number, p: number) => actions.commitProp('x', v, p)"
          />
        </Tip>
        <Tip :label="panels.yAxis">
          <NumberField
            icon="Y"
            data-property="y"
            :aria-label="panels.yAxis"
            :model-value="yValue"
            @update:model-value="actions.updateProp('y', $event)"
            @commit="(v: number, p: number) => actions.commitProp('y', v, p)"
          />
        </Tip>
      </PanelGrid>

      <PanelGrid v-if="isMulti" :columns="2" class="mt-1.5">
        <Tip :label="panels.width">
          <NumberField
            icon="W"
            data-property="width"
            :aria-label="panels.width"
            :model-value="wValue"
            :min="1"
            @update:model-value="actions.updateProp('width', $event)"
            @commit="(v: number, p: number) => actions.commitProp('width', v, p)"
          />
        </Tip>
        <Tip :label="panels.height">
          <NumberField
            icon="H"
            data-property="height"
            :aria-label="panels.height"
            :model-value="hValue"
            :min="1"
            @update:model-value="actions.updateProp('height', $event)"
            @commit="(v: number, p: number) => actions.commitProp('height', v, p)"
          />
        </Tip>
      </PanelGrid>

      <PanelGrid :columns="2" class="mt-1.5">
        <Tip :label="panels.rotation">
          <NumberField
            suffix="°"
            data-property="rotation"
            :aria-label="panels.rotation"
            :model-value="rotationValue"
            :min="-360"
            :max="360"
            @update:model-value="actions.updateProp('rotation', $event)"
            @commit="(v: number, p: number) => actions.commitProp('rotation', v, p)"
          >
            <template #icon>
              <icon-lucide-rotate-cw class="size-3" />
            </template>
          </NumberField>
        </Tip>
        <div class="flex h-6 items-center justify-end gap-0.5">
          <IconButton :label="panels.flipHorizontal" size="xs" @click="actions.flip('horizontal')">
            <icon-lucide-flip-horizontal-2 class="size-3.5" />
          </IconButton>
          <IconButton :label="panels.flipVertical" size="xs" @click="actions.flip('vertical')">
            <icon-lucide-flip-vertical-2 class="size-3.5" />
          </IconButton>
          <IconButton :label="panels.rotate90" size="xs" @click="actions.rotate(90)">
            <icon-lucide-rotate-cw-square class="size-3.5" />
          </IconButton>
        </div>
      </PanelGrid>
    </PanelSection>
  </PositionControlsRoot>
</template>

// src/react_app/properties/PositionSection.tsx
import {
  AlignCenterHorizontal,
  AlignCenterVertical,
  AlignEndHorizontal,
  AlignEndVertical,
  AlignStartHorizontal,
  AlignStartVertical,
  FlipHorizontal2,
  FlipVertical2,
  RotateCw,
  RotateCwSquare
} from 'lucide-react'

import { ScrubInput } from '@/react_app/pickers/ScrubInput'
import { iconButton } from '@/react_app/ui/iconButton'
import { sectionWrapper } from '@/react_app/ui/section'
import { Tip, TipProvider } from '@/react_app/ui/Tip'
import { PositionControlsRoot, useEditor, useI18n } from '@open-pencil/react'

import type { Editor } from '@open-pencil/core/editor'

type AppEditor = Editor & {
  state: Editor['state'] & {
    nodeEditState?: { selectedVertexIndices: Set<number> } | null
  }
  nodeEditAlignVertices: (axis: 'horizontal' | 'vertical', pos: 'min' | 'center' | 'max') => void
}

export function PositionSection() {
  const { panels } = useI18n()
  const store = useEditor() as AppEditor

  function handleAlign(
    nodeAlign: (axis: 'horizontal' | 'vertical', pos: 'min' | 'center' | 'max') => void,
    axis: 'horizontal' | 'vertical',
    pos: 'min' | 'center' | 'max'
  ) {
    const es = store.state.nodeEditState
    if (es && es.selectedVertexIndices.size >= 2) {
      store.nodeEditAlignVertices(axis, pos)
    } else {
      nodeAlign(axis, pos)
    }
  }

  return (
    <TipProvider>
      <PositionControlsRoot>
        {({
          active,
          isMulti,
          xValue,
          yValue,
          wValue,
          hValue,
          rotationValue,
          updateProp,
          commitProp,
          align,
          flip,
          rotate
        }) =>
          active ? (
            <div data-test-id="position-section" className={sectionWrapper()}>
              <label className="mb-1.5 block text-[11px] text-muted">{panels.position}</label>

              <div className="mb-1.5 flex gap-2">
                <div className="flex gap-0.5">
                  <Tip label={panels.alignLeft}>
                    <button
                      type="button"
                      className={iconButton({ size: 'md' })}
                      data-test-id="position-align-left"
                      onClick={() => handleAlign(align, 'horizontal', 'min')}
                    >
                      <AlignStartVertical className="size-3.5" />
                    </button>
                  </Tip>
                  <Tip label={panels.alignCenterHorizontally}>
                    <button
                      type="button"
                      className={iconButton({ size: 'md' })}
                      data-test-id="position-align-center-h"
                      onClick={() => handleAlign(align, 'horizontal', 'center')}
                    >
                      <AlignCenterVertical className="size-3.5" />
                    </button>
                  </Tip>
                  <Tip label={panels.alignRight}>
                    <button
                      type="button"
                      className={iconButton({ size: 'md' })}
                      data-test-id="position-align-right"
                      onClick={() => handleAlign(align, 'horizontal', 'max')}
                    >
                      <AlignEndVertical className="size-3.5" />
                    </button>
                  </Tip>
                </div>
                <div className="flex gap-0.5">
                  <Tip label={panels.alignTop}>
                    <button
                      type="button"
                      className={iconButton({ size: 'md' })}
                      data-test-id="position-align-top"
                      onClick={() => handleAlign(align, 'vertical', 'min')}
                    >
                      <AlignStartHorizontal className="size-3.5" />
                    </button>
                  </Tip>
                  <Tip label={panels.alignCenterVertically}>
                    <button
                      type="button"
                      className={iconButton({ size: 'md' })}
                      data-test-id="position-align-center-v"
                      onClick={() => handleAlign(align, 'vertical', 'center')}
                    >
                      <AlignCenterHorizontal className="size-3.5" />
                    </button>
                  </Tip>
                  <Tip label={panels.alignBottom}>
                    <button
                      type="button"
                      className={iconButton({ size: 'md' })}
                      data-test-id="position-align-bottom"
                      onClick={() => handleAlign(align, 'vertical', 'max')}
                    >
                      <AlignEndHorizontal className="size-3.5" />
                    </button>
                  </Tip>
                </div>
              </div>

              <div className="flex gap-1.5">
                <ScrubInput
                  icon="X"
                  value={xValue}
                  onValueChange={(v) => updateProp('x', v)}
                  onCommit={(v, p) => commitProp('x', v, p)}
                />
                <ScrubInput
                  icon="Y"
                  value={yValue}
                  onValueChange={(v) => updateProp('y', v)}
                  onCommit={(v, p) => commitProp('y', v, p)}
                />
              </div>

              {isMulti ? (
                <div className="mt-1.5 flex gap-1.5">
                  <ScrubInput
                    icon="W"
                    value={wValue}
                    min={1}
                    onValueChange={(v) => updateProp('width', v)}
                    onCommit={(v, p) => commitProp('width', v, p)}
                  />
                  <ScrubInput
                    icon="H"
                    value={hValue}
                    min={1}
                    onValueChange={(v) => updateProp('height', v)}
                    onCommit={(v, p) => commitProp('height', v, p)}
                  />
                </div>
              ) : null}

              <div className="mt-1.5 flex items-center gap-1.5">
                <ScrubInput
                  className="flex-1"
                  suffix="°"
                  value={rotationValue}
                  min={-360}
                  max={360}
                  onValueChange={(v) => updateProp('rotation', v)}
                  onCommit={(v, p) => commitProp('rotation', v, p)}
                  iconSlot={<RotateCw className="size-3" />}
                />
                <Tip label={panels.flipHorizontal}>
                  <button
                    type="button"
                    className={iconButton({ size: 'md', className: 'shrink-0' })}
                    data-test-id="position-flip-horizontal"
                    onClick={() => flip('horizontal')}
                  >
                    <FlipHorizontal2 className="size-3.5" />
                  </button>
                </Tip>
                <Tip label={panels.flipVertical}>
                  <button
                    type="button"
                    className={iconButton({ size: 'md', className: 'shrink-0' })}
                    data-test-id="position-flip-vertical"
                    onClick={() => flip('vertical')}
                  >
                    <FlipVertical2 className="size-3.5" />
                  </button>
                </Tip>
                <Tip label={panels.rotate90}>
                  <button
                    type="button"
                    className={iconButton({ size: 'md', className: 'shrink-0' })}
                    data-test-id="position-rotate-90"
                    onClick={() => rotate(90)}
                  >
                    <RotateCwSquare className="size-3.5" />
                  </button>
                </Tip>
              </div>
            </div>
          ) : null
        }
      </PositionControlsRoot>
    </TipProvider>
  )
}
