// src/components/properties/layout/padding/PaddingControls.vue
<script setup lang="ts">
import { useI18n, useLayoutControlsContext } from '@open-pencil/vue'

import type { PaddingProp } from '@/components/properties/layout/types'
import VariableNumberField from '@/components/properties/VariableNumberField.vue'
import IconButton from '@/components/ui/button/IconButton.vue'

const ctx = useLayoutControlsContext()
const { panels } = useI18n()

const paddingSides: Array<{ prop: PaddingProp; icon: string }> = [
  { prop: 'paddingTop', icon: 'top' },
  { prop: 'paddingRight', icon: 'right' },
  { prop: 'paddingBottom', icon: 'bottom' },
  { prop: 'paddingLeft', icon: 'left' }
]
</script>

<template>
  <div class="flex items-start gap-1.5">
    <div class="min-w-0 flex-1">
      <div
        v-if="!ctx.showIndividualPadding && ctx.hasSymmetricPadding"
        class="mt-1.5 grid grid-cols-2 gap-1.5"
      >
        <VariableNumberField
          data-test-id="layout-horizontal-padding-input"
          :model-value="Math.round(ctx.node.paddingLeft)"
          :min="0"
          :node-id="ctx.node.id"
          binding-path="paddingLeft"
          @update:model-value="ctx.setHorizontalPadding"
          @commit="ctx.commitHorizontalPadding"
        >
          <template #icon>
            <icon-lucide-separator-vertical class="size-3.5" />
          </template>
        </VariableNumberField>
        <VariableNumberField
          data-test-id="layout-vertical-padding-input"
          :model-value="Math.round(ctx.node.paddingTop)"
          :min="0"
          :node-id="ctx.node.id"
          binding-path="paddingTop"
          @update:model-value="ctx.setVerticalPadding"
          @commit="ctx.commitVerticalPadding"
        >
          <template #icon>
            <icon-lucide-separator-horizontal class="size-3.5" />
          </template>
        </VariableNumberField>
      </div>

      <div v-else-if="ctx.isGrid || ctx.isFlex" class="mt-1.5 grid grid-cols-2 gap-1.5">
        <VariableNumberField
          v-for="side in paddingSides"
          :key="side.prop"
          :model-value="Math.round(ctx.node[side.prop])"
          :min="0"
          :node-id="ctx.node.id"
          :binding-path="side.prop"
          @update:model-value="ctx.updateProp(side.prop, $event)"
          @commit="(v: number, p: number) => ctx.commitProp(side.prop, v, p)"
        >
          <template #icon>
            <icon-lucide-panel-top v-if="side.icon === 'top'" class="size-3.5" />
            <icon-lucide-panel-right v-else-if="side.icon === 'right'" class="size-3.5" />
            <icon-lucide-panel-bottom v-else-if="side.icon === 'bottom'" class="size-3.5" />
            <icon-lucide-panel-left v-else class="size-3.5" />
          </template>
        </VariableNumberField>
      </div>
    </div>
    <IconButton
      v-if="ctx.isFlex || ctx.isGrid"
      :label="panels.individualPadding"
      :active="ctx.showIndividualPadding"
      class="mt-1.5"
      @click="ctx.toggleIndividualPadding"
    >
      <icon-lucide-scan class="size-3.5" />
    </IconButton>
  </div>
</template>

// packages/react/src/components/properties/LayoutSection/PaddingControls.tsx
import {
  Minus,
  PanelBottom,
  PanelLeft,
  PanelRight,
  PanelTop,
  Plus,
  SeparatorHorizontal,
  SeparatorVertical
} from 'lucide-react'

import { VariableNumberField } from '#react/components/properties/VariableNumberField'
import { useLayoutControlsContext } from '#react/controls/layout/use'

type PaddingProp = 'paddingTop' | 'paddingRight' | 'paddingBottom' | 'paddingLeft'

const paddingSides: Array<{ prop: PaddingProp; icon: 'top' | 'right' | 'bottom' | 'left' }> = [
  { prop: 'paddingTop', icon: 'top' },
  { prop: 'paddingRight', icon: 'right' },
  { prop: 'paddingBottom', icon: 'bottom' },
  { prop: 'paddingLeft', icon: 'left' }
]

export function PaddingControls() {
  const ctx = useLayoutControlsContext()
  const node = ctx.node
  if (!node) return null

  if (!ctx.showIndividualPadding && ctx.hasSymmetricPadding) {
    return (
      <div className="mt-1.5 grid grid-cols-2 gap-1.5">
        <VariableNumberField
          data-property="paddingLeft"
          min={0}
          value={Math.round(node.paddingLeft)}
          icon={<SeparatorVertical className="size-3.5" />}
          nodeId={node.id}
          bindingPath="paddingLeft"
          onCommit={(value, previous) => {
            ctx.setHorizontalPadding(value)
            ctx.commitHorizontalPadding(value, previous)
          }}
        />
        <VariableNumberField
          data-property="paddingTop"
          min={0}
          value={Math.round(node.paddingTop)}
          icon={<SeparatorHorizontal className="size-3.5" />}
          nodeId={node.id}
          bindingPath="paddingTop"
          onCommit={(value, previous) => {
            ctx.setVerticalPadding(value)
            ctx.commitVerticalPadding(value, previous)
          }}
        />
      </div>
    )
  }

  if (!ctx.isGrid && !ctx.isFlex) return null

  return (
    <div className="mt-1.5 grid grid-cols-2 gap-1.5">
      {paddingSides.map((side) => (
        <VariableNumberField
          key={side.prop}
          min={0}
          value={Math.round(node[side.prop])}
          icon={<PaddingIcon icon={side.icon} />}
          nodeId={node.id}
          bindingPath={side.prop}
          onCommit={(value, previous) => ctx.commitProp(side.prop, value, previous)}
        />
      ))}
    </div>
  )
}

function PaddingIcon({ icon }: { icon: 'top' | 'right' | 'bottom' | 'left' }) {
  if (icon === 'top') return <PanelTop className="size-3.5" />
  if (icon === 'right') return <PanelRight className="size-3.5" />
  if (icon === 'bottom') return <PanelBottom className="size-3.5" />
  return <PanelLeft className="size-3.5" />
}

export function PaddingToggleButton() {
  const ctx = useLayoutControlsContext()
  const showMinus = ctx.showIndividualPadding || !ctx.hasUniformPadding
  return (
    <button
      type="button"
      className="flex size-7 shrink-0 cursor-pointer items-center justify-center rounded border border-border bg-transparent text-muted hover:bg-hover hover:text-surface"
      onClick={ctx.toggleIndividualPadding}
    >
      {showMinus ? <Minus className="size-3" /> : <Plus className="size-3" />}
    </button>
  )
}
