// src/react_app/menus/AppMenu.tsx
import * as Menubar from '@radix-ui/react-menubar'
import { Check, ChevronRight, Sidebar } from 'lucide-react'
import { useRef, useState } from 'react'

import { openFileDialog } from '@/composables/use-menu'
import { IS_TAURI } from '@/constants'
import { EditorBridge } from '@/react_app/shell/EditorBridge'
import { menuContent, menuItem, menuSeparator } from '@/react_app/ui/menu'
import { Tip, TipProvider } from '@/react_app/ui/Tip'
import {
  useEditor,
  useEditorCommands,
  useEditorVersion,
  useI18n,
  useInlineRename,
  type MenuEntry
} from '@open-pencil/react'

import type { Editor } from '@open-pencil/core/editor'
import type { Locale } from '@open-pencil/react'

type AppEditor = Editor & {
  state: Editor['state'] & {
    documentName: string
    showUI: boolean
    autosaveEnabled: boolean
  }
  saveFigFile: () => Promise<void>
  saveFigFileAs: () => Promise<void>
  exportSelection: (scale: number, format: string) => Promise<void>
}

const DOCUMENT_NAME_ID = 'document-name'

function AppMenuInner() {
  const store = useEditor() as AppEditor
  useEditorVersion()
  const { menuItem: commandMenuItem } = useEditorCommands()
  const { menu: t, locale, availableLocales, localeLabels, setLocale } = useI18n()
  const isMac = navigator.platform.includes('Mac')
  const mod = isMac ? '⌘' : 'Ctrl+'

  const rename = useInlineRename((_id, name) => {
    store.state.documentName = name
  })
  const [pendingFocus, setPendingFocus] = useState(false)
  const inputRef = useRef<HTMLInputElement | null>(null)

  function startRename() {
    rename.start(DOCUMENT_NAME_ID, store.state.documentName)
    setPendingFocus(true)
  }

  function setNameInputRef(el: HTMLInputElement | null) {
    inputRef.current = el
    if (el && pendingFocus) {
      setPendingFocus(false)
      rename.focusInput(el)
    }
  }

  const languageMenu: MenuEntry[] = availableLocales.map((code: Locale) => ({
    label: localeLabels[code],
    checked: locale === code,
    onCheckedChange: (checked: boolean) => {
      if (checked) setLocale(code)
    }
  }))

  const topMenus = [
    {
      label: t.file,
      items: [
        {
          label: t.new,
          shortcut: `${mod}N`,
          action: () => {
            void import('@/stores/tabs').then((m) => m.createTab())
          }
        },
        { label: t.open, shortcut: `${mod}O`, action: () => void openFileDialog() },
        { separator: true as const },
        { label: t.save, shortcut: `${mod}S`, action: () => void store.saveFigFile() },
        {
          label: t.saveAs,
          shortcut: `${mod}⇧S`,
          action: () => void store.saveFigFileAs()
        },
        { separator: true as const },
        {
          label: t.exportSelection,
          shortcut: `${mod}⇧E`,
          sub: [
            { label: 'PNG', action: () => void store.exportSelection(1, 'png') },
            { label: 'SVG', action: () => void store.exportSelection(1, 'svg') },
            { label: '.fig', action: () => void store.exportSelection(1, 'fig') }
          ]
        },
        { separator: true as const },
        {
          label: t.autosave,
          checked: store.state.autosaveEnabled,
          onCheckedChange: (value: boolean) => {
            store.state.autosaveEnabled = value
          }
        }
      ] as MenuEntry[]
    },
    {
      label: t.edit,
      items: [
        commandMenuItem('edit.undo'),
        commandMenuItem('edit.redo'),
        { separator: true },
        commandMenuItem('selection.duplicate'),
        commandMenuItem('selection.delete'),
        { separator: true },
        commandMenuItem('selection.selectAll')
      ] as MenuEntry[]
    },
    {
      label: t.view,
      items: [
        commandMenuItem('view.zoom100'),
        commandMenuItem('view.zoomFit'),
        commandMenuItem('view.zoomSelection'),
        { separator: true },
        {
          label: t.language,
          sub: languageMenu
        }
      ] as MenuEntry[]
    },
    {
      label: t.object,
      items: [
        commandMenuItem('selection.group'),
        commandMenuItem('selection.ungroup'),
        { separator: true },
        commandMenuItem('selection.createComponent'),
        commandMenuItem('selection.detachInstance'),
        commandMenuItem('selection.goToMainComponent')
      ] as MenuEntry[]
    }
  ]

  const itemCls = menuItem()
  const sepCls = menuSeparator()
  const mainContent = menuContent({ class: 'min-w-52' })
  const subContent = menuContent({ class: 'min-w-44' })

  function renderItems(items: MenuEntry[]) {
    return items.map((item, i) => {
      if (item.separator) {
        return <Menubar.Separator key={i} className={sepCls} />
      }
      if (item.sub) {
        return (
          <Menubar.Sub key={i}>
            <Menubar.SubTrigger className={itemCls}>
              <span className="flex-1">{item.label}</span>
              <ChevronRight className="size-3 text-muted" />
            </Menubar.SubTrigger>
            <Menubar.Portal>
              <Menubar.SubContent sideOffset={4} className={subContent}>
                {renderItems(item.sub)}
              </Menubar.SubContent>
            </Menubar.Portal>
          </Menubar.Sub>
        )
      }
      if (item.onCheckedChange) {
        return (
          <Menubar.CheckboxItem
            key={i}
            className={itemCls}
            checked={!!item.checked}
            onCheckedChange={(v) => item.onCheckedChange?.(v === true)}
          >
            <span className="flex-1">{item.label}</span>
            <Menubar.ItemIndicator className="text-surface">
              <Check className="size-3.5" />
            </Menubar.ItemIndicator>
          </Menubar.CheckboxItem>
        )
      }
      return (
        <Menubar.Item
          key={i}
          className={itemCls}
          disabled={item.disabled}
          onSelect={() => item.action?.()}
        >
          <span className="flex-1">{item.label}</span>
          {item.shortcut ? <span className="text-[11px] text-muted">{item.shortcut}</span> : null}
        </Menubar.Item>
      )
    })
  }

  return (
    <TipProvider>
      <div className="shrink-0 border-b border-border">
        <div className="flex items-center gap-2 px-2 py-1.5">
          <img data-test-id="app-logo" src="/favicon-32.png" className="size-4" alt="OpenPencil" />
          {rename.editingId === DOCUMENT_NAME_ID ? (
            <input
              ref={setNameInputRef}
              data-test-id="app-document-name-input"
              className="min-w-0 flex-1 rounded border border-accent bg-input px-1 py-0.5 text-xs text-surface outline-none"
              defaultValue={store.state.documentName}
              onBlur={(e) => rename.commit(DOCUMENT_NAME_ID, e.currentTarget)}
              onKeyDown={(e) => {
                if (e.code === 'Enter') e.currentTarget.blur()
                rename.onKeydown(e.nativeEvent)
              }}
            />
          ) : (
            <span
              data-test-id="app-document-name"
              className="min-w-0 flex-1 cursor-default truncate rounded px-1 py-0.5 text-xs text-surface hover:bg-hover"
              onDoubleClick={startRename}
            >
              {store.state.documentName}
            </span>
          )}
          <Tip label={`${t.toggleUI} (${mod}\\)`}>
            <button
              type="button"
              data-test-id="app-toggle-ui"
              className="flex size-6 shrink-0 cursor-pointer items-center justify-center rounded text-muted transition-colors hover:bg-hover hover:text-surface"
              onClick={() => {
                store.state.showUI = !store.state.showUI
              }}
            >
              <Sidebar className="size-3.5" />
            </button>
          </Tip>
        </div>
        {!IS_TAURI ? (
          <div className="flex items-center px-1 pb-1">
            <Menubar.Root className="scrollbar-none flex items-center gap-0.5 overflow-x-auto">
              {topMenus.map((menu) => (
                <Menubar.Menu key={menu.label}>
                  <Menubar.Trigger
                    data-test-id={`menubar-${menu.label.toLowerCase()}`}
                    className="flex cursor-pointer items-center rounded px-2 py-1 text-xs text-muted transition-colors select-none hover:bg-hover hover:text-surface data-[state=open]:bg-hover data-[state=open]:text-surface"
                  >
                    {menu.label}
                  </Menubar.Trigger>
                  <Menubar.Portal>
                    <Menubar.Content sideOffset={4} align="start" className={mainContent}>
                      {renderItems(menu.items)}
                    </Menubar.Content>
                  </Menubar.Portal>
                </Menubar.Menu>
              ))}
            </Menubar.Root>
          </div>
        ) : null}
      </div>
    </TipProvider>
  )
}

export function AppMenu({ editor }: { editor: Editor }) {
  return (
    <EditorBridge editor={editor}>
      <AppMenuInner />
    </EditorBridge>
  )
}

// src/components/AppMenu.tsx
<script setup lang="ts">
import {
  MenubarCheckboxItem,
  MenubarContent,
  MenubarItem,
  MenubarItemIndicator,
  MenubarMenu,
  MenubarPortal,
  MenubarRoot,
  MenubarSeparator,
  MenubarSub,
  MenubarSubContent,
  MenubarSubTrigger,
  MenubarTrigger
} from 'reka-ui'

import IconChevronRight from '~icons/lucide/chevron-right'

import { computed } from 'vue'

import { useI18n, useInlineRename } from '@open-pencil/vue'
import { useMenuUI } from '@/components/ui/menu'
import { IS_TAURI } from '@/constants'
import { useAppMenu } from '@/composables/use-app-menu'
import { useEditorStore } from '@/stores/editor'

const store = useEditorStore()

const DOCUMENT_NAME_ID = 'document-name'
const rename = useInlineRename<'document-name'>((_id, name) => {
  store.state.documentName = name
})
const editingName = computed(() => rename.editingId.value === DOCUMENT_NAME_ID)

function setNameInputRef(el: HTMLInputElement | null) {
  if (el) void rename.focusInput(el)
}

function startRename() {
  rename.start(DOCUMENT_NAME_ID, store.state.documentName)
}

function commitRename(input: HTMLInputElement) {
  rename.commit(DOCUMENT_NAME_ID, input)
}

const isMac = navigator.platform.includes('Mac')
const mod = isMac ? '⌘' : 'Ctrl+'
const { menu: t } = useI18n()

interface MenuAction {
  separator?: false
  label: string
  shortcut?: string
  action?: () => void
  disabled?: boolean
  checked?: boolean
  onCheckedChange?: (checked: boolean) => void
  sub?: MenuEntry[]
}

interface MenuSeparator {
  separator: true
}

type MenuEntry = MenuAction | MenuSeparator

const { topMenus } = useAppMenu(mod)
const menuCls = useMenuUI()
const mainMenuCls = useMenuUI({ content: 'min-w-52' })
const subMenuCls = useMenuUI({ content: 'min-w-44' })
</script>

<template>
  <div class="shrink-0 border-b border-border">
    <div class="flex items-center gap-2 px-2 py-1.5">
      <img data-test-id="app-logo" src="/favicon-32.png" class="size-4" alt="OpenPencil" />
      <input
        v-if="editingName"
        :ref="(el) => setNameInputRef(el as HTMLInputElement | null)"
        data-test-id="app-document-name-input"
        class="min-w-0 flex-1 rounded border border-accent bg-input px-1 py-0.5 text-xs text-surface outline-none"
        :value="store.state.documentName"
        @blur="commitRename($event.target as HTMLInputElement)"
        @keydown.enter="($event.target as HTMLInputElement).blur()"
        @keydown="rename.onKeydown"
      />
      <span
        v-else
        data-test-id="app-document-name"
        class="min-w-0 flex-1 cursor-default truncate rounded px-1 py-0.5 text-xs text-surface hover:bg-hover"
        @dblclick="startRename"
        >{{ store.state.documentName }}</span
      >
      <Tip :label="`${t.toggleUI} (${mod}\\)`">
        <button
          data-test-id="app-toggle-ui"
          class="flex size-6 shrink-0 cursor-pointer items-center justify-center rounded text-muted transition-colors hover:bg-hover hover:text-surface"
          @click="store.state.showUI = !store.state.showUI"
        >
          <icon-lucide-sidebar class="size-3.5" />
        </button>
      </Tip>
    </div>
    <div v-if="!IS_TAURI" class="flex items-center px-1 pb-1">
      <MenubarRoot class="scrollbar-none flex items-center gap-0.5 overflow-x-auto">
        <MenubarMenu v-for="menu in topMenus" :key="menu.label">
          <MenubarTrigger
            :data-test-id="`menubar-${menu.label.toLowerCase()}`"
            class="flex cursor-pointer items-center rounded px-2 py-1 text-xs text-muted transition-colors select-none hover:bg-hover hover:text-surface data-[state=open]:bg-hover data-[state=open]:text-surface"
          >
            {{ menu.label }}
          </MenubarTrigger>

          <MenubarPortal>
            <MenubarContent :side-offset="4" align="start" :class="mainMenuCls.content">
              <template v-for="(item, i) in menu.items" :key="i">
                <MenubarSeparator
                  v-if="'separator' in item && item.separator"
                  :class="menuCls.separator"
                />
                <MenubarSub v-else-if="'sub' in item && item.sub">
                  <MenubarSubTrigger :class="menuCls.item">
                    <span class="flex-1">{{ 'label' in item ? item.label : '' }}</span>
                    <IconChevronRight class="size-3 text-muted" />
                  </MenubarSubTrigger>
                  <MenubarPortal>
                    <MenubarSubContent :side-offset="4" :class="subMenuCls.content">
                      <template
                        v-for="(sub, j) in 'sub' in item && item.sub ? item.sub : []"
                        :key="j"
                      >
                        <MenubarSeparator
                          v-if="'separator' in sub && sub.separator"
                          :class="menuCls.separator"
                        />
                        <MenubarCheckboxItem
                          v-else-if="'onCheckedChange' in sub && sub.onCheckedChange"
                          :model-value="'checked' in sub ? sub.checked : undefined"
                          :class="menuCls.item"
                          @update:model-value="sub.onCheckedChange?.($event as boolean)"
                        >
                          <span class="flex-1">{{ 'label' in sub ? sub.label : '' }}</span>
                          <MenubarItemIndicator class="text-surface">
                            <icon-lucide-check class="size-3.5" />
                          </MenubarItemIndicator>
                        </MenubarCheckboxItem>
                        <MenubarItem
                          v-else
                          :class="menuCls.item"
                          :disabled="'disabled' in sub ? sub.disabled : undefined"
                          @select="'action' in sub ? sub.action?.() : undefined"
                        >
                          <span class="flex-1">{{ 'label' in sub ? sub.label : '' }}</span>
                          <span
                            v-if="'shortcut' in sub && sub.shortcut"
                            class="text-[11px] text-muted"
                            >{{ sub.shortcut }}</span
                          >
                        </MenubarItem>
                      </template>
                    </MenubarSubContent>
                  </MenubarPortal>
                </MenubarSub>
                <MenubarCheckboxItem
                  v-else-if="'onCheckedChange' in item && item.onCheckedChange"
                  :model-value="'checked' in item ? item.checked : undefined"
                  :class="menuCls.item"
                  @update:model-value="item.onCheckedChange?.($event as boolean)"
                >
                  <span class="flex-1">{{ 'label' in item ? item.label : '' }}</span>
                  <MenubarItemIndicator class="text-surface">
                    <icon-lucide-check class="size-3.5" />
                  </MenubarItemIndicator>
                </MenubarCheckboxItem>
                <MenubarItem
                  v-else
                  :class="menuCls.item"
                  :disabled="'disabled' in item ? item.disabled : undefined"
                  @select="'action' in item ? item.action?.() : undefined"
                >
                  <span class="flex-1">{{ 'label' in item ? item.label : '' }}</span>
                  <span v-if="'shortcut' in item && item.shortcut" class="text-[11px] text-muted">{{
                    item.shortcut
                  }}</span>
                </MenubarItem>
              </template>
            </MenubarContent>
          </MenubarPortal>
        </MenubarMenu>
      </MenubarRoot>
    </div>
  </div>
</template>
