// src/react_app/panels/CollabPanel.tsx
import * as Popover from '@radix-ui/react-popover'
import { Check, Copy, Share2, Users } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'

import { DEFAULT_COLLAB_STATE } from '@/composables/use-collab'
import { usePopoverUI } from '@/react_app/ui/popover'
import { Tip, TipProvider } from '@/react_app/ui/Tip'
import { initials } from '@/utils/text'
import { toast } from '@/utils/toast'
import { colorToCSS } from '@open-pencil/core'
import { useI18n } from '@open-pencil/react'

import type { CollabReturn, CollabState, RemotePeer } from '@/composables/use-collab'

export function CollabPanel({ collab }: { collab: CollabReturn | null }) {
  const navigate = useNavigate()
  const params = useParams()
  const cls = usePopoverUI({ content: 'z-50 w-72 p-3' })
  const { dialogs } = useI18n()

  const pendingRoomId = (params.roomId as string) || null
  const [popoverOpen, setPopoverOpen] = useState(!!pendingRoomId)
  const [joinInput, setJoinInput] = useState('')
  const [nameDraft, setNameDraft] = useState(collab?.state.value.localName ?? '')
  const [copied, setCopied] = useState(false)

  // Force re-read of Vue reactive collab state
  const [, bump] = useState(0)
  useEffect(() => {
    if (!collab) return
    const id = window.setInterval(() => bump((n) => n + 1), 500)
    return () => clearInterval(id)
  }, [collab])

  const state: CollabState = collab?.state.value ?? DEFAULT_COLLAB_STATE
  const peers: RemotePeer[] = collab?.remotePeers.value ?? []
  const followingPeer = collab?.followingPeer.value ?? null

  const shareUrl = state.roomId ? `${window.location.origin}/share/${state.roomId}` : ''
  const isJoining = !!pendingRoomId && !state.connected

  async function copyLink() {
    if (!shareUrl) return
    await navigator.clipboard.writeText(shareUrl)
    setCopied(true)
    toast.show('Link copied to clipboard')
    setTimeout(() => setCopied(false), 2000)
  }

  function onShare() {
    if (!collab || !nameDraft.trim()) return
    collab.setLocalName(nameDraft.trim())
    const roomId = collab.shareCurrentDoc()
    void navigate(`/share/${roomId}`)
    void navigator.clipboard.writeText(`${window.location.origin}/share/${roomId}`)
    toast.show('Link copied to clipboard')
    setPopoverOpen(false)
  }

  function onJoin() {
    if (!collab) return
    const roomId = pendingRoomId || joinInput.trim().replace(/.*\/share\//, '')
    if (!roomId || !nameDraft.trim()) return
    collab.setLocalName(nameDraft.trim())
    collab.connect(roomId)
    void navigate(`/share/${roomId}`)
    setPopoverOpen(false)
  }

  function onDisconnect() {
    if (!collab) return
    collab.disconnect()
    void navigate('/')
  }

  return (
    <TipProvider>
      <div className="flex w-full items-center justify-end gap-2">
        <div className="flex -space-x-1.5">
          <Tip label={`${state.localName || 'You'} (you)`}>
            <div
              data-test-id="collab-local-avatar"
              className="flex size-6 items-center justify-center rounded-full border-2 border-panel text-[10px] font-semibold text-white"
              style={{ background: colorToCSS(state.localColor) }}
            >
              {initials(state.localName || 'You')}
            </div>
          </Tip>

          {peers.map((peer) => (
            <Tip
              key={peer.clientId}
              label={
                followingPeer === peer.clientId
                  ? `Following ${peer.name} (click to stop)`
                  : `Click to follow ${peer.name}`
              }
            >
              <div
                data-test-id="collab-peer-avatar"
                className={`flex size-6 cursor-pointer items-center justify-center rounded-full border-2 text-[10px] font-semibold text-white transition-all ${
                  followingPeer === peer.clientId
                    ? 'border-white ring-2 ring-white/40'
                    : 'border-panel'
                }`}
                style={{ background: colorToCSS(peer.color) }}
                onClick={() =>
                  collab?.followPeer(followingPeer === peer.clientId ? null : peer.clientId)
                }
              >
                {initials(peer.name)}
              </div>
            </Tip>
          ))}
        </div>

        <div className="flex-1" />

        <Popover.Root open={popoverOpen} onOpenChange={setPopoverOpen}>
          <Popover.Trigger asChild>
            <button
              type="button"
              data-test-id="collab-share-button"
              className={`flex h-7 cursor-pointer items-center gap-1.5 rounded-md border-none px-3 text-xs font-medium transition-colors ${
                state.connected
                  ? 'bg-green-600 text-white hover:bg-green-700'
                  : isJoining
                    ? 'animate-pulse bg-amber-600 text-white'
                    : 'bg-accent text-white hover:bg-accent/90'
              }`}
            >
              <Share2 className="size-3.5" />
              {state.connected ? dialogs.connected : isJoining ? dialogs.joinRoom : dialogs.share}
            </button>
          </Popover.Trigger>

          <Popover.Portal>
            <Popover.Content
              data-test-id="collab-popover"
              className={cls.content}
              sideOffset={8}
              side="bottom"
              align="end"
            >
              {state.connected ? (
                <>
                  <div className="mb-3 text-xs font-medium text-surface">{dialogs.roomLink}</div>
                  <div className="mb-3 flex items-center gap-1.5">
                    <input
                      value={shareUrl}
                      readOnly
                      data-test-id="collab-room-link"
                      className="min-w-0 flex-1 rounded border border-border bg-input px-2 py-1 text-xs text-surface"
                      onFocus={(e) => e.currentTarget.select()}
                    />
                    <button
                      type="button"
                      data-test-id="collab-copy-link"
                      className="flex h-7 cursor-pointer items-center gap-1 rounded border-none bg-accent px-2 text-xs text-white hover:bg-accent/90"
                      onClick={() => void copyLink()}
                    >
                      {copied ? <Check className="size-3" /> : <Copy className="size-3" />}
                      {copied ? 'Copied' : 'Copy'}
                    </button>
                  </div>
                  <div className="mb-2 text-xs font-medium text-surface">
                    {peers.length + 1} {peers.length === 0 ? 'person' : 'people'} in this room
                  </div>
                  <button
                    type="button"
                    data-test-id="collab-disconnect"
                    className="flex h-7 w-full cursor-pointer items-center justify-center rounded border border-border bg-transparent text-xs text-muted hover:bg-hover hover:text-surface"
                    onClick={onDisconnect}
                  >
                    Disconnect
                  </button>
                </>
              ) : isJoining ? (
                <>
                  <div className="mb-1 text-xs font-medium text-surface">
                    {dialogs.joinCollaboration}
                  </div>
                  <div className="mb-3 text-[11px] text-muted">
                    Someone shared this file with you. Enter your name to join.
                  </div>
                  <div className="mb-3">
                    <label className="mb-1 block text-xs text-muted">{dialogs.yourName}</label>
                    <input
                      value={nameDraft}
                      data-test-id="collab-name-input"
                      className="w-full rounded border border-border bg-input px-2 py-1 text-xs text-surface"
                      placeholder={dialogs.enterYourName}
                      autoFocus
                      onChange={(e) => setNameDraft(e.currentTarget.value)}
                      onKeyDown={(e) => {
                        if (e.code === 'Enter') onJoin()
                      }}
                    />
                  </div>
                  <button
                    type="button"
                    data-test-id="collab-join-button"
                    className="flex h-8 w-full cursor-pointer items-center justify-center gap-1.5 rounded border-none bg-accent text-xs font-medium text-white hover:bg-accent/90 disabled:opacity-50"
                    disabled={!nameDraft.trim()}
                    onClick={onJoin}
                  >
                    <Users className="size-3.5" />
                    Join room
                  </button>
                </>
              ) : (
                <>
                  <div className="mb-3">
                    <label className="mb-1 block text-xs text-muted">{dialogs.yourName}</label>
                    <input
                      value={nameDraft}
                      data-test-id="collab-name-input"
                      className="w-full rounded border border-border bg-input px-2 py-1 text-xs text-surface"
                      placeholder={dialogs.enterYourName}
                      onChange={(e) => setNameDraft(e.currentTarget.value)}
                      onKeyDown={(e) => {
                        if (e.code === 'Enter') onShare()
                      }}
                    />
                  </div>
                  <button
                    type="button"
                    data-test-id="collab-share-file"
                    className="mb-3 flex h-8 w-full cursor-pointer items-center justify-center gap-1.5 rounded border-none bg-accent text-xs font-medium text-white hover:bg-accent/90 disabled:opacity-50"
                    disabled={!nameDraft.trim()}
                    onClick={onShare}
                  >
                    <Share2 className="size-3.5" />
                    {dialogs.shareThisFile}
                  </button>
                  <div className="mb-2 flex items-center gap-2">
                    <div className="h-px flex-1 bg-border" />
                    <span className="text-[11px] text-muted">{dialogs.orJoinRoom}</span>
                    <div className="h-px flex-1 bg-border" />
                  </div>
                  <div className="flex items-center gap-1.5">
                    <input
                      value={joinInput}
                      data-test-id="collab-join-input"
                      className="min-w-0 flex-1 rounded border border-border bg-input px-2 py-1 text-xs text-surface"
                      placeholder={dialogs.pasteRoomLinkOrId}
                      onChange={(e) => setJoinInput(e.currentTarget.value)}
                      onKeyDown={(e) => {
                        if (e.code === 'Enter') onJoin()
                      }}
                    />
                    <button
                      type="button"
                      data-test-id="collab-join-room-button"
                      className="flex h-7 cursor-pointer items-center rounded border-none bg-accent px-3 text-xs text-white hover:bg-accent/90 disabled:opacity-50"
                      disabled={!joinInput.trim() || !nameDraft.trim()}
                      onClick={onJoin}
                    >
                      Join
                    </button>
                  </div>
                </>
              )}
            </Popover.Content>
          </Popover.Portal>
        </Popover.Root>
      </div>
    </TipProvider>
  )
}

// src/components/CollabPanel.tsx
<script setup lang="ts">
import { useClipboard } from '@vueuse/core'
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { PopoverRoot, PopoverTrigger, PopoverPortal, PopoverContent } from 'reka-ui'

import { colorToCSS } from '@open-pencil/core'
import Tip from '@/components/ui/Tip.vue'
import { usePopoverUI } from '@/components/ui/popover'
import { DEFAULT_COLLAB_STATE, useCollabInjected } from '@/composables/use-collab'
import { toast } from '@/utils/toast'
import { initials } from '@/utils/text'
import { useI18n } from '@open-pencil/vue'

const route = useRoute()
const router = useRouter()
const cls = usePopoverUI({ content: 'z-50 w-72 p-3' })
const collab = useCollabInjected()
const { copy, copied } = useClipboard({ copiedDuring: 2000 })
const { dialogs } = useI18n()

const joinInput = ref('')
const nameDraft = ref(collab?.state.value.localName ?? '')
const pendingRoomId = (route.params.roomId as string) || null
const popoverOpen = ref(!!pendingRoomId)

const state = computed(() => collab?.state.value ?? DEFAULT_COLLAB_STATE)
const peers = computed(() => collab?.remotePeers.value ?? [])
const followingPeer = computed(() => collab?.followingPeer.value ?? null)

const shareUrl = computed(() => {
  if (!state.value.roomId) return ''
  return `${window.location.origin}/share/${state.value.roomId}`
})

const isJoining = computed(() => !!pendingRoomId && !state.value.connected)

function copyLink() {
  if (!shareUrl.value) return
  copy(shareUrl.value)
  toast.show('Link copied to clipboard')
}

function onShare() {
  if (!collab || !nameDraft.value.trim()) return
  collab.setLocalName(nameDraft.value.trim())
  const roomId = collab.shareCurrentDoc()
  router.push(`/share/${roomId}`)
  copy(`${window.location.origin}/share/${roomId}`)
  toast.show('Link copied to clipboard')
  popoverOpen.value = false
}

function onJoin() {
  if (!collab) return
  const roomId = pendingRoomId || joinInput.value.trim().replace(/.*\/share\//, '')
  if (!roomId || !nameDraft.value.trim()) return
  collab.setLocalName(nameDraft.value.trim())
  collab.connect(roomId)
  router.push(`/share/${roomId}`)
  popoverOpen.value = false
}

function onDisconnect() {
  if (!collab) return
  collab.disconnect()
  router.push('/')
}
</script>

<template>
  <div class="flex w-full items-center justify-end gap-2">
    <!-- Avatar stack -->
    <div class="flex -space-x-1.5">
      <Tip :label="`${state.localName || 'You'} (you)`">
        <div
          data-test-id="collab-local-avatar"
          class="flex size-6 items-center justify-center rounded-full border-2 border-panel text-[10px] font-semibold text-white"
          :style="{ background: colorToCSS(state.localColor) }"
        >
          {{ initials(state.localName || 'You') }}
        </div>
      </Tip>

      <Tip
        v-for="peer in peers"
        :key="peer.clientId"
        :label="
          followingPeer === peer.clientId
            ? `Following ${peer.name} (click to stop)`
            : `Click to follow ${peer.name}`
        "
      >
        <div
          data-test-id="collab-peer-avatar"
          class="flex size-6 cursor-pointer items-center justify-center rounded-full border-2 text-[10px] font-semibold text-white transition-all"
          :class="
            followingPeer === peer.clientId ? 'border-white ring-2 ring-white/40' : 'border-panel'
          "
          :style="{ background: colorToCSS(peer.color) }"
          @click="collab?.followPeer(followingPeer === peer.clientId ? null : peer.clientId)"
        >
          {{ initials(peer.name) }}
        </div>
      </Tip>
    </div>

    <div class="flex-1" />

    <!-- Share button / popover -->
    <PopoverRoot v-model:open="popoverOpen">
      <PopoverTrigger as-child>
        <button
          data-test-id="collab-share-button"
          class="flex h-7 cursor-pointer items-center gap-1.5 rounded-md border-none px-3 text-xs font-medium transition-colors"
          :class="
            state.connected
              ? 'bg-green-600 text-white hover:bg-green-700'
              : isJoining
                ? 'animate-pulse bg-amber-600 text-white'
                : 'bg-accent text-white hover:bg-accent/90'
          "
        >
          <icon-lucide-share-2 class="size-3.5" />
          {{ state.connected ? dialogs.connected : isJoining ? dialogs.joinRoom : dialogs.share }}
        </button>
      </PopoverTrigger>

      <PopoverPortal>
        <PopoverContent
          data-test-id="collab-popover"
          :class="cls.content"
          :side-offset="8"
          side="bottom"
          align="end"
        >
          <!-- Connected state -->
          <template v-if="state.connected">
            <div class="mb-3 text-xs font-medium text-surface">{{ dialogs.roomLink }}</div>
            <div class="mb-3 flex items-center gap-1.5">
              <input
                :value="shareUrl"
                readonly
                data-test-id="collab-room-link"
                class="min-w-0 flex-1 rounded border border-border bg-input px-2 py-1 text-xs text-surface"
                @focus="($event.target as HTMLInputElement).select()"
              />
              <button
                data-test-id="collab-copy-link"
                class="flex h-7 cursor-pointer items-center gap-1 rounded border-none bg-accent px-2 text-xs text-white hover:bg-accent/90"
                @click="copyLink"
              >
                <icon-lucide-check v-if="copied" class="size-3" />
                <icon-lucide-copy v-else class="size-3" />
                {{ copied ? 'Copied' : 'Copy' }}
              </button>
            </div>

            <div class="mb-2 text-xs font-medium text-surface">
              {{ peers.length + 1 }} {{ peers.length === 0 ? 'person' : 'people' }} in this room
            </div>

            <button
              data-test-id="collab-disconnect"
              class="flex h-7 w-full cursor-pointer items-center justify-center rounded border border-border bg-transparent text-xs text-muted hover:bg-hover hover:text-surface"
              @click="onDisconnect"
            >
              Disconnect
            </button>
          </template>

          <!-- Joining via /share/ link -->
          <template v-else-if="isJoining">
            <div class="mb-1 text-xs font-medium text-surface">{{ dialogs.joinCollaboration }}</div>
            <div class="mb-3 text-[11px] text-muted">
              Someone shared this file with you. Enter your name to join.
            </div>

            <div class="mb-3">
              <label class="mb-1 block text-xs text-muted">{{ dialogs.yourName }}</label>
              <input
                v-model="nameDraft"
                data-test-id="collab-name-input"
                class="w-full rounded border border-border bg-input px-2 py-1 text-xs text-surface"
                :placeholder="dialogs.enterYourName"
                autofocus
                @keydown.enter="onJoin"
              />
            </div>

            <button
              data-test-id="collab-join-button"
              class="flex h-8 w-full cursor-pointer items-center justify-center gap-1.5 rounded border-none bg-accent text-xs font-medium text-white hover:bg-accent/90 disabled:opacity-50"
              :disabled="!nameDraft.trim()"
              @click="onJoin"
            >
              <icon-lucide-users class="size-3.5" />
              Join room
            </button>
          </template>

          <!-- Not connected: share or join -->
          <template v-else>
            <div class="mb-3">
              <label class="mb-1 block text-xs text-muted">{{ dialogs.yourName }}</label>
              <input
                v-model="nameDraft"
                data-test-id="collab-name-input"
                class="w-full rounded border border-border bg-input px-2 py-1 text-xs text-surface"
                :placeholder="dialogs.enterYourName"
                @keydown.enter="onShare"
              />
            </div>

            <button
              data-test-id="collab-share-file"
              class="mb-3 flex h-8 w-full cursor-pointer items-center justify-center gap-1.5 rounded border-none bg-accent text-xs font-medium text-white hover:bg-accent/90 disabled:opacity-50"
              :disabled="!nameDraft.trim()"
              @click="onShare"
            >
              <icon-lucide-share-2 class="size-3.5" />
              {{ dialogs.shareThisFile }}
            </button>

            <div class="mb-2 flex items-center gap-2">
              <div class="h-px flex-1 bg-border" />
              <span class="text-[11px] text-muted">{{ dialogs.orJoinRoom }}</span>
              <div class="h-px flex-1 bg-border" />
            </div>

            <div class="flex items-center gap-1.5">
              <input
                v-model="joinInput"
                data-test-id="collab-join-input"
                class="min-w-0 flex-1 rounded border border-border bg-input px-2 py-1 text-xs text-surface"
                :placeholder="dialogs.pasteRoomLinkOrId"
                @keydown.enter="onJoin"
              />
              <button
                data-test-id="collab-join-room-button"
                class="flex h-7 cursor-pointer items-center rounded border-none bg-accent px-3 text-xs text-white hover:bg-accent/90 disabled:opacity-50"
                :disabled="!joinInput.trim() || !nameDraft.trim()"
                @click="onJoin"
              >
                Join
              </button>
            </div>
          </template>
        </PopoverContent>
      </PopoverPortal>
    </PopoverRoot>
  </div>
</template>
