// packages/react/src/components/DesignPanel.tsx
import { useState } from 'react'
import { Layers3 } from 'lucide-react'

import { COMPONENT_TYPES, nodeIcon } from '#react/app/editor/icons'
import { useEditorStore } from '#react/app/editor/store'
import { AppearanceSection } from '#react/components/properties/AppearanceSection'
import { ComponentPropertiesSection } from '#react/components/properties/component-properties/ComponentPropertiesSection'
import { VariantAuthoringSection } from '#react/components/properties/component-properties/VariantAuthoringSection'
import { ConstraintsSection } from '#react/components/properties/constraints/ConstraintsSection'
import { EffectsSection } from '#react/components/properties/EffectsSection'
import { ExportSection } from '#react/components/properties/ExportSection'
import { FillSection } from '#react/components/properties/FillSection'
import { FramePresetSelect } from '#react/components/properties/frame-presets/FramePresetSelect'
import { FramePresetsSection } from '#react/components/properties/FramePresetsSection'
import { LayoutGridSection } from '#react/components/properties/LayoutSection/LayoutGridSection'
import { LayoutSection } from '#react/components/properties/LayoutSection/LayoutSection'
import { MaskSection } from '#react/components/properties/MaskSection'
import { PageSection } from '#react/components/properties/PageSection'
import { PositionSection } from '#react/components/properties/PositionSection'
import { SelectionActionsControl } from '#react/components/properties/SelectionActionsControl'
import { StrokeSection } from '#react/components/properties/StrokeSection'
import { TypographySection } from '#react/components/properties/TypographySection'
import { VariablesSection } from '#react/components/properties/VariablesSection'
import { VariablesDialog } from '#react/components/properties/variables/VariablesDialog'
import { PanelHeader } from '#react/components/ui/panel/PanelHeader'
import { Tip } from '#react/components/ui/Tip'
import { useEditorCommands } from '#react/editor/commands/use'
import { useSelectionState } from '#react/editor/selection-state/use'
import { useI18n } from '#react/i18n'

export function DesignPanel() {
  const store = useEditorStore()
  const { selectedNode, selectedCount } = useSelectionState()
  const { getCommand } = useEditorCommands()
  const { panels } = useI18n()
  const [variablesOpen, setVariablesOpen] = useState(false)
  const activeTool = store.state.activeTool
  const goToMainComponent = getCommand('selection.goToMainComponent')
  const detachInstance = getCommand('selection.detachInstance')
  const isComponentType = selectedNode ? COMPONENT_TYPES.has(selectedNode.type) : false
  const SelectedIcon = selectedNode ? nodeIcon(selectedNode) : null
  const supportsLayoutGuides =
    selectedNode?.type === 'FRAME' ||
    selectedNode?.type === 'COMPONENT' ||
    selectedNode?.type === 'COMPONENT_SET' ||
    selectedNode?.type === 'INSTANCE'
  const showVariantAuthoring =
    selectedNode?.type === 'COMPONENT_SET' ||
    (selectedNode?.type === 'COMPONENT' &&
      selectedNode.parentId &&
      store.graph.getNode(selectedNode.parentId)?.type === 'COMPONENT_SET')

  if (activeTool === 'FRAME') {
    return (
      <div data-test-id="design-panel" className="flex min-h-0 flex-1 flex-col overflow-hidden">
        <div className="scrollbar-thin flex-1 overflow-x-hidden overflow-y-auto pb-4">
          <FramePresetsSection />
        </div>
      </div>
    )
  }

  if (selectedCount > 1) {
    return (
      <div data-test-id="design-panel" className="flex min-h-0 flex-1 flex-col overflow-hidden">
        <div
          data-test-id="design-panel-multi"
          className="scrollbar-thin flex-1 overflow-x-hidden overflow-y-auto pb-4"
        >
          <PanelHeader
            icon={<Layers3 className="size-3.5" aria-hidden="true" />}
            actions={<SelectionActionsControl showBooleanOperations />}
          >
            <span role="heading" aria-level={2}>
              {panels.layersCount({ count: String(selectedCount) })}
            </span>
          </PanelHeader>
          <ComponentPropertiesSection />
          <PositionSection />
          <ConstraintsSection />
          <AppearanceSection />
          <FillSection />
          <StrokeSection />
          <EffectsSection />
          <ExportSection />
        </div>
      </div>
    )
  }

  if (selectedNode) {
    return (
      <div data-test-id="design-panel" className="flex min-h-0 flex-1 flex-col overflow-hidden">
        <div
          data-test-id="design-panel-single"
          className="scrollbar-thin flex-1 overflow-x-hidden overflow-y-auto pb-4"
        >
          <PanelHeader
            component={isComponentType}
            icon={
              SelectedIcon ? (
                <Tip label={selectedNode.type}>
                  <span role="img" aria-label={selectedNode.type} className="contents">
                    <SelectedIcon className="size-3.5" />
                  </span>
                </Tip>
              ) : null
            }
            actions={<SelectionActionsControl />}
          >
            <span role="heading" aria-level={2}>
              {selectedNode.name}
            </span>
          </PanelHeader>
          {selectedNode.type === 'INSTANCE' ? (
            <div className="flex flex-col gap-1 border-b border-border px-3 py-2">
              <button
                type="button"
                className="rounded bg-component/10 px-2 py-1 text-left text-[11px] text-component hover:bg-component/20"
                onClick={() => goToMainComponent.run()}
              >
                {panels.goToMainComponent}
              </button>
              <button
                type="button"
                className="rounded px-2 py-1 text-left text-[11px] text-muted hover:bg-hover"
                onClick={() => detachInstance.run()}
              >
                {panels.detachInstance}
              </button>
            </div>
          ) : null}
          {selectedNode.type === 'INSTANCE' ? <ComponentPropertiesSection /> : null}
          {showVariantAuthoring ? <VariantAuthoringSection /> : null}
          {selectedNode.type === 'FRAME' ? <FramePresetSelect /> : null}
          <PositionSection />
          <ConstraintsSection />
          <LayoutSection />
          <AppearanceSection />
          <MaskSection />
          {selectedNode.type === 'TEXT' ? <TypographySection /> : null}
          <FillSection />
          <StrokeSection />
          {supportsLayoutGuides ? <LayoutGridSection /> : null}
          <EffectsSection />
          <ExportSection />
        </div>
      </div>
    )
  }

  return (
    <div data-test-id="design-panel" className="flex min-h-0 flex-1 flex-col overflow-hidden">
      <div
        data-test-id="design-panel-empty"
        className="scrollbar-thin flex-1 overflow-x-hidden overflow-y-auto pb-4"
      >
        <PageSection />
        <VariablesSection onOpenDialog={() => setVariablesOpen(true)} />
        <ExportSection />
      </div>
      <VariablesDialog open={variablesOpen} onClose={() => setVariablesOpen(false)} />
    </div>
  )
}

// src/components/DesignPanel.vue
<script setup lang="ts">
import { computed, ref } from 'vue'

import { useI18n, useSelectionState, useEditorCommands } from '@open-pencil/vue'

import { COMPONENT_TYPES, nodeIcon } from '@/app/editor/icons'
import PanelHeader from '@/components/ui/panel/PanelHeader.vue'
import Tip from '@/components/ui/Tip.vue'

import VariablesDialog from './variables/VariablesDialog.vue'
import AppearanceSection from './properties/AppearanceSection.vue'
import EffectsSection from './properties/EffectsSection.vue'
import ExportSection from './properties/ExportSection.vue'
import FillSection from './properties/FillSection.vue'
import LayoutSection from './properties/LayoutSection/LayoutSection.vue'
import MaskSection from './properties/MaskSection.vue'
import PageSection from './properties/PageSection.vue'
import ConstraintsSection from './properties/constraints/ConstraintsSection.vue'
import PositionSection from './properties/PositionSection.vue'
import SelectionActionsControl from './properties/SelectionActionsControl.vue'
import StrokeSection from './properties/StrokeSection.vue'
import TypographySection from './properties/TypographySection.vue'
import VariablesSection from './properties/VariablesSection.vue'
import ComponentPropertiesSection from './properties/component-properties/ComponentPropertiesSection.vue'
import FramePresetsSection from './properties/frame-presets/FramePresetsSection.vue'
import FramePresetSelect from './properties/frame-presets/FramePresetSelect.vue'
import ComponentProperties from './properties/ComponentProperties.vue'
import TextProperties from './properties/TextProperties.vue'
import { useEditorStore } from '@/app/editor/active-store'
const variablesOpen = ref(false)
const store = useEditorStore()
const activeTool = computed(() => store.state.activeTool)
const { selectedNode: node, selectedCount: multiCount } = useSelectionState()
const showBooleanOperations = computed(() => multiCount.value >= 2)
const { getCommand } = useEditorCommands()
const goToMainComponent = getCommand('selection.goToMainComponent')
const detachInstance = getCommand('selection.detachInstance')
const isComponentType = computed(() => {
  const type = node.value?.type
  return type ? COMPONENT_TYPES.has(type) : false
})
const selectedIcon = computed(() => (node.value ? nodeIcon(node.value) : undefined))
const supportsLayoutGuides = computed(() => {
  const type = node.value?.type
  return type === 'FRAME' || type === 'COMPONENT' || type === 'COMPONENT_SET' || type === 'INSTANCE'
})
const { panels } = useI18n()
</script>

<template>
  <!-- Frame tool presets replace selection properties, matching Figma. -->
  <div
    v-if="activeTool === 'FRAME'"
    class="scrollbar-thin flex-1 overflow-x-hidden overflow-y-auto pb-4"
  >
    <FramePresetsSection />
  </div>

  <!-- Multi-select summary -->
  <div
    v-else-if="multiCount > 1"
    data-test-id="design-panel-multi"
    class="scrollbar-thin flex-1 overflow-x-hidden overflow-y-auto pb-4"
  >
    <PanelHeader>
      <template #icon>
        <icon-lucide-layers-3 class="size-3.5" aria-hidden="true" />
      </template>
      <span role="heading" aria-level="2">
        {{ panels.layersCount({ count: String(multiCount) }) }}
      </span>
      <template #actions>
        <SelectionActionsControl :show-boolean-operations="showBooleanOperations" />
      </template>
    </PanelHeader>
    <ComponentPropertiesSection />
    <PositionSection />
    <ConstraintsSection />
    <AppearanceSection />
    <FillSection />
    <StrokeSection />
    <EffectsSection />
    <ExportSection />
  </div>

  <!-- Single selection -->
  <div
    v-else-if="node"
    data-test-id="design-panel-single"
    class="scrollbar-thin flex-1 overflow-x-hidden overflow-y-auto pb-4"
  >
    <PanelHeader :component="isComponentType">
      <template #icon>
        <Tip :label="node.type">
          <span role="img" :aria-label="node.type" class="contents">
            <component :is="selectedIcon" class="size-3.5" />
          </span>
        </Tip>
      </template>
      <span role="heading" aria-level="2">{{
        node.type === 'TEXT' ? node.type.toLowerCase() : node.name
      }}</span>
      <template #actions>
        <SelectionActionsControl />
      </template>
      <template #content>
        <!-- Component actions -->
        <div
          v-if="node.type === 'INSTANCE'"
          class="flex flex-col gap-1 border-b border-border px-3 py-2"
        >
          <button
            type="button"
            class="rounded bg-component/10 px-2 py-1 text-left text-[11px] text-component hover:bg-component/20"
            @click="goToMainComponent.run()"
          >
            {{ panels.goToMainComponent }}
          </button>
          <button
            type="button"
            class="rounded px-2 py-1 text-left text-[11px] text-muted hover:bg-hover"
            @click="detachInstance.run()"
          >
            {{ panels.detachInstance }}
          </button>
        </div>
        <ComponentProperties v-if="node.type === 'COMPONENT_SET'"></ComponentProperties>
        <TextProperties v-else-if="node.type === 'TEXT'"></TextProperties>
      </template>
    </PanelHeader>
    <ComponentPropertiesSection v-if="node.type === 'INSTANCE'" />

    <FramePresetSelect v-if="node.type === 'FRAME'" />

    <PositionSection />
    <ConstraintsSection />
    <LayoutSection />
    <AppearanceSection />
    <MaskSection />
    <TypographySection v-if="node.type === 'TEXT'" />
    <FillSection />
    <StrokeSection />
    <LayoutGridSection v-if="supportsLayoutGuides" />
    <EffectsSection />

    <ExportSection />
  </div>

  <div
    v-else
    data-test-id="design-panel-empty"
    class="scrollbar-thin flex-1 overflow-x-hidden overflow-y-auto pb-4"
  >
    <PageSection />
    <VariablesSection @open-dialog="variablesOpen = true" />
    <ExportSection />
  </div>

  <VariablesDialog v-model:open="variablesOpen" />
</template>
