// packages/react/src/components/LayersPanel.tsx
import { useState } from 'react'
import { tv } from 'tailwind-variants'

import { useI18n } from '#react/i18n'
import { AppMenu } from '#react/components/Shell/AppMenu'
import { SegmentedControl } from '#react/components/ui/SegmentedControl'
import { SplitterGroup, SplitterPanel, SplitterResizeHandle } from '#react/components/ui/splitter'
import splitterTheme from '#react/theme/splitter'
import { AssetsPanel } from '#react/components/assets-panel/AssetsPanel'
import { LayerTree } from '#react/components/LayerTree/LayerTree'
import { PagesPanel } from '#react/components/PagesPanel'

export function LayersPanel() {
  const { menu, panels } = useI18n()
  const [activePanel, setActivePanel] = useState<'file' | 'assets'>('file')
  const panelOptions = [
    { value: 'file', label: menu.file },
    { value: 'assets', label: panels.assets }
  ]
  const splitterStyles = tv(splitterTheme)({ direction: 'vertical' })

  return (
    <aside
      data-test-id="layers-panel"
      className="flex min-w-0 flex-1 flex-col overflow-hidden border-r border-border bg-panel"
      style={{ contain: 'paint layout style' }}
    >
      <AppMenu />
      <div className="shrink-0 border-b border-border px-2 py-1.5">
        <SegmentedControl
          value={activePanel}
          options={panelOptions}
          label={panels.layers}
          ui={{ root: 'w-full' }}
          onChange={(value) => {
            if (value === 'file' || value === 'assets') setActivePanel(value)
          }}
          renderOption={(option) => (
            <span
              data-test-id={option.value === 'file' ? 'left-panel-layers-tab' : 'left-panel-assets-tab'}
              className="truncate"
            >
              {option.label}
            </span>
          )}
        />
      </div>
      {activePanel === 'assets' ? (
        <AssetsPanel />
      ) : (
        <SplitterGroup
          id="layers-layout"
          direction="vertical"
          autoSaveId="layers-layout"
          className="flex-1 overflow-hidden"
        >
          <SplitterPanel defaultSize={30} minSize={10} maxSize={60} className="flex flex-col overflow-hidden">
            <PagesPanel />
          </SplitterPanel>
          <SplitterResizeHandle className={splitterStyles.handle()}>
            <div className={splitterStyles.divider()} />
          </SplitterResizeHandle>
          <SplitterPanel defaultSize={70} minSize={20} className="flex flex-col overflow-hidden">
            <header
              data-test-id="layers-header"
              className="shrink-0 px-3 py-2 text-[11px] font-semibold text-surface"
            >
              {panels.layers}
            </header>
            <LayerTree />
          </SplitterPanel>
        </SplitterGroup>
      )}
    </aside>
  )
}

// src/components/LayersPanel.vue
<script setup lang="ts">
import { SplitterGroup, SplitterPanel, SplitterResizeHandle } from 'reka-ui'
import { tv } from 'tailwind-variants'
import { computed, ref } from 'vue'

import { useI18n } from '@open-pencil/vue'

import AppMenu from '@/components/Shell/AppMenu.vue'
import SegmentedControl from '@/components/ui/select/SegmentedControl.vue'
import splitterTheme from '@/theme/splitter'

import AssetsPanel from './assets-panel/AssetsPanel.vue'
import LayerTree from './LayerTree/LayerTree.vue'
import PagesPanel from './PagesPanel.vue'

const { menu, panels } = useI18n()
const activePanel = ref<'file' | 'assets'>('file')
const panelModel = computed({
  get: () => activePanel.value,
  set: (value: string) => {
    if (value === 'file' || value === 'assets') activePanel.value = value
  }
})
const panelOptions = computed(() => [
  { value: 'file', label: menu.value.file },
  { value: 'assets', label: panels.value.assets }
])
const panelTabsUI = { root: 'w-full' }
const splitterStyles = tv(splitterTheme)({ direction: 'vertical' })
</script>

<template>
  <aside
    data-test-id="layers-panel"
    class="flex min-w-0 flex-1 flex-col overflow-hidden border-r border-border bg-panel"
    style="contain: paint layout style"
  >
    <AppMenu />
    <div class="shrink-0 border-b border-border px-2 py-1.5">
      <SegmentedControl
        v-model="panelModel"
        :options="panelOptions"
        :label="panels.layers"
        :ui="panelTabsUI"
      >
        <template #option="{ option }">
          <span
            :data-test-id="
              option.value === 'file' ? 'left-panel-layers-tab' : 'left-panel-assets-tab'
            "
            class="truncate"
          >
            {{ option.label }}
          </span>
        </template>
      </SegmentedControl>
    </div>
    <AssetsPanel v-if="activePanel === 'assets'" />
    <SplitterGroup
      v-else
      direction="vertical"
      auto-save-id="layers-layout"
      class="flex-1 overflow-hidden"
    >
      <SplitterPanel
        :default-size="30"
        :min-size="10"
        :max-size="60"
        class="flex flex-col overflow-hidden"
      >
        <PagesPanel />
      </SplitterPanel>
      <SplitterResizeHandle :class="splitterStyles.handle()">
        <div :class="splitterStyles.divider()" />
      </SplitterResizeHandle>
      <SplitterPanel :default-size="70" :min-size="20" class="flex flex-col overflow-hidden">
        <header
          data-test-id="layers-header"
          class="shrink-0 px-3 py-2 text-[11px] font-semibold text-surface"
        >
          {{ panels.layers }}
        </header>
        <LayerTree data-test-id="layers-tree" />
      </SplitterPanel>
    </SplitterGroup>
  </aside>
</template>
