// packages/react/src/components/PropertiesPanel.tsx
import { useState } from 'react'
import { Code, Sparkles } from 'lucide-react'

import { useI18n } from '#react/i18n'
import { ChatPanel } from '#react/components/ChatPanel'
import { CodePanel } from '#react/components/CodePanel'
import { DesignPanel } from '#react/components/DesignPanel'
import { ZoomDropdown } from '#react/components/editor/ZoomDropdown'

const tabClass =
  'relative rounded px-2.5 py-1 text-[11px] text-muted hover:text-surface data-[state=active]:font-semibold data-[state=active]:text-surface after:absolute after:inset-x-2 after:-bottom-[9px] after:h-0.5 after:rounded-full after:bg-transparent data-[state=active]:after:bg-accent'

export function PropertiesPanel() {
  const { panels } = useI18n()
  const [activeTab, setActiveTab] = useState<'design' | 'code' | 'ai'>('design')

  return (
    <aside
      data-test-id="properties-panel"
      className="flex min-w-0 flex-1 flex-col overflow-hidden border-l border-border bg-panel"
      style={{ contain: 'paint layout style' }}
    >
      <div className="flex min-h-0 flex-1 flex-col">
        <div className="flex h-10 shrink-0 items-center gap-1 border-b border-border px-2">
          <button
            type="button"
            value="design"
            data-test-id="properties-tab-design"
            data-state={activeTab === 'design' ? 'active' : undefined}
            className={tabClass}
            onClick={() => setActiveTab('design')}
          >
            {panels.design}
          </button>
          <button
            type="button"
            value="code"
            data-test-id="properties-tab-code"
            data-state={activeTab === 'code' ? 'active' : undefined}
            className={`flex items-center gap-1 ${tabClass}`}
            onClick={() => setActiveTab('code')}
          >
            <Code className="size-3" />
            {panels.code}
          </button>
          <button
            type="button"
            value="ai"
            data-test-id="properties-tab-ai"
            data-state={activeTab === 'ai' ? 'active' : undefined}
            className={`flex items-center gap-1 ${tabClass}`}
            onClick={() => setActiveTab('ai')}
          >
            <Sparkles className="size-3" />
            {panels.ai}
          </button>
          {activeTab === 'design' ? <ZoomDropdown /> : null}
        </div>
        <div
          hidden={activeTab !== 'design'}
          className="flex min-h-0 flex-1 flex-col"
        >
          <DesignPanel />
        </div>
        <div hidden={activeTab !== 'code'} className="flex min-h-0 flex-1 flex-col">
          <CodePanel active={activeTab === 'code'} />
        </div>
        <div hidden={activeTab !== 'ai'} className="flex min-h-0 flex-1 flex-col">
          <ChatPanel />
        </div>
      </div>
    </aside>
  )
}

// src/components/PropertiesPanel.vue
<script setup lang="ts">
import { TabsContent, TabsList, TabsRoot, TabsTrigger } from 'reka-ui'

import { useI18n } from '@open-pencil/vue'

import { useAIChat } from '@/app/ai/chat/use'

import ChatPanel from './ChatPanel.vue'
import CodePanel from './CodePanel.vue'
import DesignPanel from './DesignPanel.vue'
import ZoomDropdown from './editor/ZoomDropdown.vue'

const { activeTab } = useAIChat()
const { panels } = useI18n()
</script>

<template>
  <aside
    data-test-id="properties-panel"
    class="flex min-w-0 flex-1 flex-col overflow-hidden border-l border-border bg-panel"
    style="contain: paint layout style"
  >
    <TabsRoot v-model="activeTab" class="flex min-h-0 flex-1 flex-col">
      <TabsList class="flex h-10 shrink-0 items-center gap-1 border-b border-border px-2">
        <TabsTrigger
          value="design"
          data-test-id="properties-tab-design"
          class="relative rounded px-2.5 py-1 text-[11px] text-muted hover:text-surface data-[state=active]:font-semibold data-[state=active]:text-surface after:absolute after:inset-x-2 after:-bottom-[9px] after:h-0.5 after:rounded-full after:bg-transparent data-[state=active]:after:bg-accent"
        >
          {{ panels.design }}
        </TabsTrigger>
        <TabsTrigger
          value="code"
          data-test-id="properties-tab-code"
          class="relative flex items-center gap-1 rounded px-2.5 py-1 text-[11px] text-muted hover:text-surface data-[state=active]:font-semibold data-[state=active]:text-surface after:absolute after:inset-x-2 after:-bottom-[9px] after:h-0.5 after:rounded-full after:bg-transparent data-[state=active]:after:bg-accent"
        >
          <icon-lucide-code class="size-3" />
          {{ panels.code }}
        </TabsTrigger>
        <TabsTrigger
          value="ai"
          data-test-id="properties-tab-ai"
          class="relative flex items-center gap-1 rounded px-2.5 py-1 text-[11px] text-muted hover:text-surface data-[state=active]:font-semibold data-[state=active]:text-surface after:absolute after:inset-x-2 after:-bottom-[9px] after:h-0.5 after:rounded-full after:bg-transparent data-[state=active]:after:bg-accent"
        >
          <icon-lucide-sparkles class="size-3" />
          {{ panels.ai }}
        </TabsTrigger>
        <ZoomDropdown v-if="activeTab === 'design'" />
      </TabsList>

      <TabsContent
        value="design"
        class="flex min-h-0 flex-1 flex-col"
        :force-mount="true"
        :hidden="activeTab !== 'design'"
      >
        <DesignPanel />
      </TabsContent>

      <TabsContent
        value="code"
        class="flex min-h-0 flex-1 flex-col"
        :force-mount="true"
        :hidden="activeTab !== 'code'"
      >
        <CodePanel :active="activeTab === 'code'" />
      </TabsContent>

      <TabsContent
        value="ai"
        class="flex min-h-0 flex-1 flex-col"
        :force-mount="true"
        :hidden="activeTab !== 'ai'"
      >
        <ChatPanel />
      </TabsContent>
    </TabsRoot>
  </aside>
</template>
