// src/components/PropertiesPanel.vue
<script setup lang="ts">
import { TabsContent, TabsList, TabsRoot, TabsTrigger } from 'reka-ui'

import { useI18n } from '@open-pencil/vue'

import { useAIChat } from '@/app/ai/chat/use'

import ChatPanel from './ChatPanel.vue'
import CodePanel from './CodePanel.vue'
import DesignPanel from './DesignPanel.vue'
import ZoomDropdown from './editor/ZoomDropdown.vue'

const { activeTab } = useAIChat()
const { panels } = useI18n()
</script>

<template>
  <aside
    data-test-id="properties-panel"
    class="flex min-w-0 flex-1 flex-col overflow-hidden border-l border-border bg-panel"
    style="contain: paint layout style"
  >
    <TabsRoot v-model="activeTab" class="flex min-h-0 flex-1 flex-col">
      <TabsList class="flex h-10 shrink-0 items-center gap-1 border-b border-border px-2">
        <TabsTrigger
          value="design"
          data-test-id="properties-tab-design"
          class="relative rounded px-2.5 py-1 text-[11px] text-muted hover:text-surface data-[state=active]:font-semibold data-[state=active]:text-surface after:absolute after:inset-x-2 after:-bottom-[9px] after:h-0.5 after:rounded-full after:bg-transparent data-[state=active]:after:bg-accent"
        >
          {{ panels.design }}
        </TabsTrigger>
        <TabsTrigger
          value="code"
          data-test-id="properties-tab-code"
          class="relative flex items-center gap-1 rounded px-2.5 py-1 text-[11px] text-muted hover:text-surface data-[state=active]:font-semibold data-[state=active]:text-surface after:absolute after:inset-x-2 after:-bottom-[9px] after:h-0.5 after:rounded-full after:bg-transparent data-[state=active]:after:bg-accent"
        >
          <icon-lucide-code class="size-3" />
          {{ panels.code }}
        </TabsTrigger>
        <TabsTrigger
          value="ai"
          data-test-id="properties-tab-ai"
          class="relative flex items-center gap-1 rounded px-2.5 py-1 text-[11px] text-muted hover:text-surface data-[state=active]:font-semibold data-[state=active]:text-surface after:absolute after:inset-x-2 after:-bottom-[9px] after:h-0.5 after:rounded-full after:bg-transparent data-[state=active]:after:bg-accent"
        >
          <icon-lucide-sparkles class="size-3" />
          {{ panels.ai }}
        </TabsTrigger>
        <ZoomDropdown v-if="activeTab === 'design'" />
      </TabsList>

      <TabsContent
        value="design"
        class="flex min-h-0 flex-1 flex-col"
        :force-mount="true"
        :hidden="activeTab !== 'design'"
      >
        <DesignPanel />
      </TabsContent>

      <TabsContent
        value="code"
        class="flex min-h-0 flex-1 flex-col"
        :force-mount="true"
        :hidden="activeTab !== 'code'"
      >
        <CodePanel :active="activeTab === 'code'" />
      </TabsContent>

      <TabsContent
        value="ai"
        class="flex min-h-0 flex-1 flex-col"
        :force-mount="true"
        :hidden="activeTab !== 'ai'"
      >
        <ChatPanel />
      </TabsContent>
    </TabsRoot>
  </aside>
</template>

// src/components/PropertiesPanel.tsx
import IconLucideCode from '~icons/lucide/code'
import IconLucideSparkles from '~icons/lucide/sparkles'
import { memo } from 'react'

import { useI18n } from '@open-pencil/react'
import { useAIChat } from '@/app/ai/chat/use'
import { useVueRefValue } from '@/shared/useVueRefValue'
import ChatPanel from '@/components/ChatPanel'
import CodePanel from '@/components/CodePanel'
import DesignPanel from '@/components/DesignPanel'
import ZoomDropdown from '@/components/editor/ZoomDropdown'

export const PropertiesPanel = memo(function PropertiesPanel() {
  const { activeTab } = useAIChat()
  const tab = useVueRefValue(activeTab)
  const { panels } = useI18n()

  return (
    <aside
      data-test-id="properties-panel"
      className="flex min-w-0 flex-1 flex-col overflow-hidden border-l border-border bg-panel"
      style={{ contain: 'paint layout style' }}
    >
      <div className="flex min-h-0 flex-1 flex-col">
        <div
          className="flex h-10 shrink-0 items-center gap-1 border-b border-border px-2"
          role="tablist"
        >
          <button
            type="button"
            role="tab"
            aria-selected={tab === 'design'}
            data-test-id="properties-tab-design"
            data-state={tab === 'design' ? 'active' : 'inactive'}
            className="relative rounded px-2.5 py-1 text-[11px] text-muted hover:text-surface data-[state=active]:font-semibold data-[state=active]:text-surface after:absolute after:inset-x-2 after:-bottom-[9px] after:h-0.5 after:rounded-full after:bg-transparent data-[state=active]:after:bg-accent"
            onClick={() => {
              activeTab.value = 'design'
            }}
          >
            {panels.design}
          </button>
          <button
            type="button"
            role="tab"
            aria-selected={tab === 'code'}
            data-test-id="properties-tab-code"
            data-state={tab === 'code' ? 'active' : 'inactive'}
            className="relative flex items-center gap-1 rounded px-2.5 py-1 text-[11px] text-muted hover:text-surface data-[state=active]:font-semibold data-[state=active]:text-surface after:absolute after:inset-x-2 after:-bottom-[9px] after:h-0.5 after:rounded-full after:bg-transparent data-[state=active]:after:bg-accent"
            onClick={() => {
              activeTab.value = 'code'
            }}
          >
            <IconLucideCode className="size-3" />
            {panels.code}
          </button>
          <button
            type="button"
            role="tab"
            aria-selected={tab === 'ai'}
            data-test-id="properties-tab-ai"
            data-state={tab === 'ai' ? 'active' : 'inactive'}
            className="relative flex items-center gap-1 rounded px-2.5 py-1 text-[11px] text-muted hover:text-surface data-[state=active]:font-semibold data-[state=active]:text-surface after:absolute after:inset-x-2 after:-bottom-[9px] after:h-0.5 after:rounded-full after:bg-transparent data-[state=active]:after:bg-accent"
            onClick={() => {
              activeTab.value = 'ai'
            }}
          >
            <IconLucideSparkles className="size-3" />
            {panels.ai}
          </button>
          {tab === 'design' ? <ZoomDropdown /> : null}
        </div>

        <div
          role="tabpanel"
          hidden={tab !== 'design'}
          className="flex min-h-0 flex-1 flex-col"
        >
          <DesignPanel />
        </div>
        <div role="tabpanel" hidden={tab !== 'code'} className="flex min-h-0 flex-1 flex-col">
          <CodePanel />
        </div>
        <div role="tabpanel" hidden={tab !== 'ai'} className="flex min-h-0 flex-1 flex-col">
          <ChatPanel />
        </div>
      </div>
    </aside>
  )
})

PropertiesPanel.displayName = 'PropertiesPanel'
export default PropertiesPanel
