// packages/vue/src/primitives/PropertyList/PropertyListAdd.vue
<script setup lang="ts" generic="K extends PropertyListKey">
import { computed } from 'vue'
import { Primitive } from 'reka-ui'

import { usePropertyListPart } from '#vue/primitives/PropertyList/context'
import type { PropertyListItemFor, PropertyListKey, PropertyListPartProps } from './types'

const {
  propKey,
  item,
  as = 'button',
  asChild = false,
  disabled: disabledProp = false
} = defineProps<PropertyListPartProps<K> & { item: PropertyListItemFor<K> }>()
const emit = defineEmits<{ add: [item: PropertyListItemFor<K>] }>()
const context = usePropertyListPart(propKey)
const disabled = computed(() => disabledProp || context.disabled.value)
defineOptions({ inheritAttrs: false })

function add() {
  if (disabled.value) return
  emit('add', item)
  context.actions.add(item)
}
</script>

<template>
  <Primitive
    v-bind="$attrs"
    :as="as"
    :as-child="asChild"
    :type="!asChild && as === 'button' ? 'button' : undefined"
    :disabled="disabled"
    data-slot="add"
    @click="add"
  >
    <slot />
  </Primitive>
</template>

// packages/react/src/primitives/PropertyList/PropertyListAdd.tsx
import type { ElementType, ReactNode } from 'react'
import { Slot } from '@radix-ui/react-slot'

import { usePropertyListPart } from '#react/primitives/PropertyList/context'
import type { PropertyListItemFor, PropertyListKey } from './types'

interface PropertyListAddProps<K extends PropertyListKey> {
  propKey: K
  item: PropertyListItemFor<K>
  as?: ElementType
  asChild?: boolean
  disabled?: boolean
  onAdd?: (item: PropertyListItemFor<K>) => void
  children?: ReactNode
  className?: string
  [key: string]: unknown
}

export function PropertyListAdd<K extends PropertyListKey>({
  propKey,
  item,
  as: Tag = 'button',
  asChild = false,
  disabled: disabledProp = false,
  onAdd,
  children,
  ...attrs
}: PropertyListAddProps<K>) {
  const context = usePropertyListPart(propKey)
  const disabled = disabledProp || context.disabled

  function add() {
    if (disabled) return
    onAdd?.(item)
    context.actions.add(item)
  }

  const Comp = asChild ? Slot : (Tag as 'button')
  return (
    <Comp
      {...attrs}
      type={!asChild && Tag === 'button' ? 'button' : undefined}
      disabled={disabled}
      data-slot="add"
      onClick={add}
    >
      {children}
    </Comp>
  )
}
