// packages/vue/src/primitives/PropertyList/PropertyListRemove.vue
<script setup lang="ts" generic="K extends PropertyListKey">
import { computed } from 'vue'
import { Primitive } from 'reka-ui'

import { usePropertyListPart } from '#vue/primitives/PropertyList/context'
import type { PropertyListKey, PropertyListPartProps } from './types'

const {
  propKey,
  index,
  as = 'button',
  asChild = false,
  disabled: disabledProp = false
} = defineProps<PropertyListPartProps<K> & { index: number }>()
const emit = defineEmits<{ remove: [index: number] }>()
const context = usePropertyListPart(propKey)
const disabled = computed(() => disabledProp || context.disabled.value)
defineOptions({ inheritAttrs: false })

function remove() {
  if (disabled.value) return
  emit('remove', index)
  context.actions.remove(index)
}
</script>

<template>
  <Primitive
    v-bind="$attrs"
    :as="as"
    :as-child="asChild"
    :type="!asChild && as === 'button' ? 'button' : undefined"
    :disabled="disabled"
    data-slot="remove"
    @click="remove"
  >
    <slot />
  </Primitive>
</template>

// packages/react/src/primitives/PropertyList/PropertyListRemove.tsx
import type { ElementType, ReactNode } from 'react'
import { Slot } from '@radix-ui/react-slot'

import { usePropertyListPart } from '#react/primitives/PropertyList/context'
import type { PropertyListKey } from './types'

interface PropertyListRemoveProps<K extends PropertyListKey> {
  propKey: K
  index: number
  as?: ElementType
  asChild?: boolean
  disabled?: boolean
  onRemove?: (index: number) => void
  children?: ReactNode
  className?: string
  [key: string]: unknown
}

export function PropertyListRemove<K extends PropertyListKey>({
  propKey,
  index,
  as: Tag = 'button',
  asChild = false,
  disabled: disabledProp = false,
  onRemove,
  children,
  ...attrs
}: PropertyListRemoveProps<K>) {
  const context = usePropertyListPart(propKey)
  const disabled = disabledProp || context.disabled

  function remove() {
    if (disabled) return
    onRemove?.(index)
    context.actions.remove(index)
  }

  const Comp = asChild ? Slot : (Tag as 'button')
  return (
    <Comp
      {...attrs}
      type={!asChild && Tag === 'button' ? 'button' : undefined}
      disabled={disabled}
      data-slot="remove"
      onClick={remove}
    >
      {children}
    </Comp>
  )
}
