// packages/vue/src/primitives/PropertyList/PropertyListItem.vue
<script setup lang="ts" generic="K extends PropertyListKey">
import { computed } from 'vue'
import { Primitive } from 'reka-ui'

import { usePropertyListPart } from '#vue/primitives/PropertyList/context'
import type {
  PropertyListItemActions,
  PropertyListItemFor,
  PropertyListItemSlotProps,
  PropertyListKey,
  PropertyListPatchFor
} from './types'

import type { Component, VNode } from 'vue'

const {
  propKey,
  index,
  dragging = false,
  disabled: disabledProp = false,
  as = 'div',
  asChild = false
} = defineProps<{
  propKey: K
  index: number
  dragging?: boolean
  disabled?: boolean
  as?: string | Component
  asChild?: boolean
}>()
const emit = defineEmits<{
  update: [index: number, item: PropertyListItemFor<K>]
  patch: [index: number, changes: PropertyListPatchFor<K>]
  remove: [index: number]
  toggleVisibility: [index: number]
}>()
defineSlots<{
  default(props: PropertyListItemSlotProps<K>): VNode[]
}>()
defineOptions({ inheritAttrs: false })

const context = usePropertyListPart(propKey)

const item = computed(() => context.items.value[index])
const hidden = computed(() => item.value?.visible === false)
const disabled = computed(() => disabledProp || context.disabled.value)
const actions: PropertyListItemActions<K> = {
  update: (nextItem) => {
    if (disabled.value) return
    emit('update', index, nextItem)
    context.actions.update(index, nextItem)
  },
  patch: (changes) => {
    if (disabled.value) return
    emit('patch', index, changes)
    context.actions.patch(index, changes)
  },
  remove: () => {
    if (disabled.value) return
    emit('remove', index)
    context.actions.remove(index)
  },
  toggleVisibility: () => {
    if (disabled.value) return
    emit('toggleVisibility', index)
    context.actions.toggleVisibility(index)
  }
}
const slotProps = computed<PropertyListItemSlotProps<K>>(() => ({
  item: item.value,
  index,
  hidden: hidden.value,
  dragging,
  disabled: disabled.value,
  actions
}))
</script>

<template>
  <Primitive
    v-bind="$attrs"
    :as="as"
    :as-child="asChild"
    :data-hidden="hidden ? '' : undefined"
    :data-dragging="dragging ? '' : undefined"
    :data-disabled="disabled ? '' : undefined"
    data-slot="item"
  >
    <slot v-bind="slotProps" />
  </Primitive>
</template>

// packages/react/src/primitives/PropertyList/PropertyListItem.tsx
import type { ElementType, ReactNode } from 'react'
import { Slot } from '@radix-ui/react-slot'

import { usePropertyListPart } from '#react/primitives/PropertyList/context'
import type {
  PropertyListItemActions,
  PropertyListItemFor,
  PropertyListItemSlotProps,
  PropertyListKey,
  PropertyListPatchFor
} from './types'

interface PropertyListItemProps<K extends PropertyListKey> {
  propKey: K
  index: number
  dragging?: boolean
  disabled?: boolean
  as?: ElementType
  asChild?: boolean
  onUpdate?: (index: number, item: PropertyListItemFor<K>) => void
  onPatch?: (index: number, changes: PropertyListPatchFor<K>) => void
  onRemove?: (index: number) => void
  onToggleVisibility?: (index: number) => void
  children?: ReactNode | ((props: PropertyListItemSlotProps<K>) => ReactNode)
  className?: string
  [key: string]: unknown
}

export function PropertyListItem<K extends PropertyListKey>({
  propKey,
  index,
  dragging = false,
  disabled: disabledProp = false,
  as: Tag = 'div',
  asChild = false,
  onUpdate,
  onPatch,
  onRemove,
  onToggleVisibility,
  children,
  ...attrs
}: PropertyListItemProps<K>) {
  const context = usePropertyListPart(propKey)
  const item = context.items[index] as PropertyListItemFor<K> | undefined
  const hidden = item?.visible === false
  const disabled = disabledProp || context.disabled

  const actions: PropertyListItemActions<K> = {
    update: (nextItem) => {
      if (disabled) return
      onUpdate?.(index, nextItem)
      context.actions.update(index, nextItem)
    },
    patch: (changes) => {
      if (disabled) return
      onPatch?.(index, changes)
      context.actions.patch(index, changes)
    },
    remove: () => {
      if (disabled) return
      onRemove?.(index)
      context.actions.remove(index)
    },
    toggleVisibility: () => {
      if (disabled) return
      onToggleVisibility?.(index)
      context.actions.toggleVisibility(index)
    }
  }

  const slotProps: PropertyListItemSlotProps<K> = { item, index, hidden, dragging, disabled, actions }
  const content = typeof children === 'function' ? children(slotProps) : children

  const Comp = asChild ? Slot : (Tag as 'div')
  return (
    <Comp
      {...attrs}
      data-hidden={hidden ? '' : undefined}
      data-dragging={dragging ? '' : undefined}
      data-disabled={disabled ? '' : undefined}
      data-slot="item"
    >
      {content}
    </Comp>
  )
}
