// src/components/variables/VariablesDialog.vue
<script setup lang="ts">
import { watch, type Component } from 'vue'
import { tv } from 'tailwind-variants'
import { templateRef } from '@vueuse/core'
import {
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuPortal,
  ContextMenuRoot,
  ContextMenuSeparator,
  ContextMenuTrigger,
  DialogClose,
  DialogTitle,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuPortal,
  DropdownMenuRoot,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
  TabsContent,
  TabsList,
  TabsRoot,
  TabsTrigger
} from 'reka-ui'
import { FlexRender } from '@tanstack/vue-table'

import { variablesAddTestId, vTestId, useI18n, useVariablesEditor } from '@open-pencil/vue'

import IconHash from '~icons/lucide/hash'
import IconPalette from '~icons/lucide/palette'
import IconToggleLeft from '~icons/lucide/toggle-left'
import IconType from '~icons/lucide/type'
import IconX from '~icons/lucide/x'
import ColorInput from '@/components/ColorPicker/ColorInput.vue'
import AppPlaceholder from '@/components/ui/AppPlaceholder.vue'
import Tip from '@/components/ui/Tip.vue'
import { AppDialogRoot } from '@/components/ui/dialog'
import { useMenuUI } from '@/components/ui/menu'
import variableTableTheme from '@/theme/variable-table'

import type { VariableType } from '@open-pencil/scene-graph'

const open = defineModel<boolean>('open', { default: false })
const menuCls = useMenuUI({ content: 'w-40', item: 'justify-start gap-2' })
const addVariableMenuCls = useMenuUI({ content: 'w-48' })
const variableTable = tv(variableTableTheme)
const tableStyles = variableTable()

const variableTypeIcons: Record<VariableType, Component> = {
  COLOR: IconPalette,
  FLOAT: IconHash,
  STRING: IconType,
  BOOLEAN: IconToggleLeft
}

const { panels, variableTypes: variableTypeText, variables, common } = useI18n()

const variableTypes: Array<{
  type: VariableType
  label: () => string
  description: () => string
}> = [
  {
    type: 'COLOR',
    label: () => variableTypeText.value.color,
    description: () => variableTypeText.value.colorHint
  },
  {
    type: 'FLOAT',
    label: () => variableTypeText.value.number,
    description: () => variableTypeText.value.numberHint
  },
  {
    type: 'STRING',
    label: () => variableTypeText.value.text,
    description: () => variableTypeText.value.textHint
  },
  {
    type: 'BOOLEAN',
    label: () => variableTypeText.value.boolean,
    description: () => variableTypeText.value.booleanHint
  }
]

const ctx = useVariablesEditor({
  colorInput: ColorInput,
  icons: variableTypeIcons,
  fallbackIcon: IconToggleLeft,
  deleteIcon: IconX
})
const collectionInput = templateRef<HTMLInputElement>('collectionInput')
const modeInput = templateRef<HTMLInputElement>('modeInput')

watch(collectionInput, (input) => {
  void ctx.collectionRename.focusInput(input)
})
watch(modeInput, (input) => {
  void ctx.modeRename.focusInput(input)
})

function getModeId(columnId: string): string | undefined {
  return columnId.startsWith('mode-') ? columnId.slice(5) : undefined
}

function modeId(columnId: string): string {
  return columnId.slice(5)
}

function modeLabelClass(defaultMode: boolean) {
  return variableTable({ defaultMode }).modeLabel()
}

function resizeHandleClass(resizing: boolean) {
  return variableTable({ resizing }).resizeHandle()
}
</script>

<template>
  <AppDialogRoot
    v-model:open="open"
    height="tall"
    :ui="{ content: 'w-[800px] max-w-[90vw]' }"
    data-test-id="variables-dialog"
    :aria-describedby="undefined"
  >
    <DialogTitle class="sr-only">{{ variables.localVariables }}</DialogTitle>
    <div v-if="!ctx.hasCollections.value" class="flex flex-1 flex-col">
      <div class="flex shrink-0 items-center justify-between border-b border-border px-4 py-3">
        <h2 class="text-sm font-semibold text-surface">{{ variables.localVariables }}</h2>
        <DialogClose
          :aria-label="common.close"
          class="flex size-6 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted hover:bg-hover hover:text-surface"
        >
          <icon-lucide-x class="size-4" />
        </DialogClose>
      </div>
      <AppPlaceholder :label="variables.noVariableCollections">
        <template #icon>
          <icon-lucide-folder class="size-5" />
        </template>
        <template #action>
          <button
            data-test-id="variables-create-collection"
            class="cursor-pointer rounded bg-hover px-3 py-1.5 text-xs text-surface hover:bg-border"
            @click="ctx.addCollection"
          >
            {{ variables.createCollection }}
          </button>
        </template>
      </AppPlaceholder>
    </div>

    <template v-else>
      <TabsRoot v-model="ctx.activeCollectionId.value" class="flex flex-1 flex-col overflow-hidden">
        <div class="flex shrink-0 items-center border-b border-border">
          <TabsList class="flex flex-1 gap-0.5 overflow-x-auto px-3 py-1">
            <template v-for="col in ctx.collections.value" :key="col.id">
              <input
                v-if="ctx.collectionRename.editingId.value === col.id"
                ref="collectionInput"
                class="w-24 rounded border border-accent bg-input px-2 py-0.5 text-xs text-surface outline-none"
                :value="col.name"
                @blur="ctx.collectionRename.commit(col.id, $event)"
                @keydown="ctx.collectionRename.onKeydown"
              />
              <TabsTrigger
                v-else
                :value="col.id"
                data-test-id="variables-collection-tab"
                class="cursor-pointer rounded border-none px-2.5 py-1 text-xs whitespace-nowrap text-muted data-[state=active]:bg-hover data-[state=active]:text-surface"
                @dblclick="ctx.startRenameCollection(col.id)"
              >
                {{ col.name }}
              </TabsTrigger>
            </template>
          </TabsList>

          <div class="flex items-center gap-1.5 px-3">
            <DropdownMenuRoot>
              <DropdownMenuTrigger as-child>
                <button
                  data-test-id="variables-collection-menu"
                  class="flex size-6 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted hover:bg-hover hover:text-surface"
                >
                  <icon-lucide-ellipsis class="size-3.5" />
                </button>
              </DropdownMenuTrigger>
              <DropdownMenuPortal>
                <DropdownMenuContent
                  side="bottom"
                  :side-offset="4"
                  align="start"
                  :class="menuCls.content"
                >
                  <DropdownMenuItem
                    :class="menuCls.item"
                    @select="ctx.startRenameCollection(ctx.activeCollectionId.value)"
                  >
                    <icon-lucide-pencil :class="menuCls.icon" />
                    {{ variables.renameCollection }}
                  </DropdownMenuItem>
                  <DropdownMenuSeparator class="mx-1.5 my-1 h-px bg-border" />
                  <DropdownMenuItem
                    :class="menuCls.item"
                    class="text-red-500"
                    data-test-id="variables-delete-collection"
                    @select="ctx.removeCollection(ctx.activeCollectionId.value)"
                  >
                    <icon-lucide-trash-2 :class="menuCls.icon" />
                    {{ variables.deleteCollection }}
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenuPortal>
            </DropdownMenuRoot>
            <div class="flex items-center gap-1 rounded border border-border px-2 py-0.5">
              <icon-lucide-search class="size-3 text-muted" />
              <input
                v-model="ctx.searchTerm.value"
                data-test-id="variables-search-input"
                class="w-24 border-none bg-transparent text-xs text-surface outline-none placeholder:text-muted"
                :placeholder="common.search"
              />
            </div>
            <Tip :label="variables.createCollection">
              <button
                data-test-id="variables-add-collection"
                class="flex size-6 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted hover:bg-hover hover:text-surface"
                @click="ctx.addCollection"
              >
                <icon-lucide-folder-plus class="size-3.5" />
              </button>
            </Tip>
            <DialogClose
              :aria-label="common.close"
              class="flex size-6 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted hover:bg-hover hover:text-surface"
            >
              <icon-lucide-x class="size-4" />
            </DialogClose>
          </div>
        </div>

        <TabsContent
          v-for="col in ctx.collections.value"
          :key="col.id"
          :value="col.id"
          class="flex flex-1 flex-col overflow-hidden outline-none"
        >
          <div class="flex-1 overflow-auto">
            <table
              class="w-full min-w-full border-collapse"
              :style="{ width: `${ctx.table.getCenterTotalSize()}px` }"
            >
              <thead class="sticky top-0 z-10 bg-panel">
                <tr
                  v-for="headerGroup in ctx.table.getHeaderGroups()"
                  :key="headerGroup.id"
                  class="border-b border-border"
                >
                  <th
                    v-for="header in headerGroup.headers"
                    :key="header.id"
                    class="relative px-4 py-2 text-left text-[11px] font-medium text-muted"
                    :style="{ width: `${header.getSize()}px` }"
                  >
                    <template v-if="getModeId(header.column.id)">
                      <input
                        v-if="ctx.modeRename.editingId.value === getModeId(header.column.id)"
                        ref="modeInput"
                        class="-mx-1 w-full rounded border border-accent bg-input px-1 py-0 text-[11px] font-medium text-surface outline-none"
                        :value="header.column.columnDef.header"
                        @blur="ctx.modeRename.commit(modeId(header.column.id), $event)"
                        @keydown="ctx.modeRename.onKeydown"
                      />
                      <ContextMenuRoot v-else>
                        <ContextMenuTrigger as-child>
                          <span
                            :data-default="
                              getModeId(header.column.id) === col.defaultModeId || undefined
                            "
                            :class="
                              modeLabelClass(getModeId(header.column.id) === col.defaultModeId)
                            "
                            @dblclick="ctx.startRenameMode(modeId(header.column.id))"
                          >
                            {{ header.column.columnDef.header }}
                          </span>
                        </ContextMenuTrigger>
                        <ContextMenuPortal>
                          <ContextMenuContent :class="menuCls.content">
                            <ContextMenuItem
                              :class="menuCls.item"
                              @select="ctx.startRenameMode(modeId(header.column.id))"
                            >
                              <icon-lucide-pencil :class="menuCls.icon" />
                              {{ variables.renameMode }}
                            </ContextMenuItem>
                            <ContextMenuItem
                              :class="menuCls.item"
                              @select="ctx.duplicateMode(modeId(header.column.id))"
                            >
                              <icon-lucide-copy :class="menuCls.icon" />
                              {{ variables.duplicateMode }}
                            </ContextMenuItem>
                            <ContextMenuItem
                              v-if="getModeId(header.column.id) !== col.defaultModeId"
                              :class="menuCls.item"
                              @select="ctx.setDefaultMode(modeId(header.column.id))"
                            >
                              <icon-lucide-pin :class="menuCls.icon" />
                              {{ variables.setDefaultMode }}
                            </ContextMenuItem>
                            <ContextMenuSeparator :class="menuCls.separator" />
                            <ContextMenuItem
                              :class="[menuCls.item, 'text-red-500']"
                              :disabled="col.modes.length <= 1"
                              @select="ctx.removeMode(modeId(header.column.id))"
                            >
                              <icon-lucide-trash-2 :class="menuCls.icon" />
                              {{ variables.deleteMode }}
                            </ContextMenuItem>
                          </ContextMenuContent>
                        </ContextMenuPortal>
                      </ContextMenuRoot>
                    </template>
                    <FlexRender
                      v-else-if="!header.isPlaceholder"
                      :render="header.column.columnDef.header"
                      :props="header.getContext()"
                    />
                    <div
                      v-if="header.column.getCanResize()"
                      :data-resizing="header.column.getIsResizing() || undefined"
                      :class="resizeHandleClass(header.column.getIsResizing())"
                      @mousedown="header.getResizeHandler()?.($event)"
                      @touchstart="header.getResizeHandler()?.($event)"
                      @dblclick="header.column.resetSize()"
                    />
                  </th>
                  <th class="w-8 px-1 py-2">
                    <Tip :label="variables.addMode">
                      <button
                        data-test-id="variables-add-mode"
                        class="flex size-5 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted hover:bg-hover hover:text-surface"
                        @click="ctx.addMode"
                      >
                        <icon-lucide-plus class="size-3" />
                      </button>
                    </Tip>
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr
                  v-for="row in ctx.table.getRowModel().rows"
                  :key="row.id"
                  data-test-id="variable-row"
                  :class="tableStyles.row()"
                >
                  <td
                    v-for="cell in row.getVisibleCells()"
                    :key="cell.id"
                    class="px-4 py-1.5"
                    :style="{ width: `${cell.column.getSize()}px` }"
                  >
                    <FlexRender :render="cell.column.columnDef.cell" :props="cell.getContext()" />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <div
            class="flex w-full shrink-0 items-center justify-between gap-2 border-t border-border px-4 py-2"
          >
            <span class="text-xs text-muted">{{ panels.createVariable }}</span>
            <DropdownMenuRoot>
              <DropdownMenuTrigger as-child>
                <button
                  data-test-id="variables-add-variable"
                  class="flex cursor-pointer items-center gap-1.5 rounded bg-hover px-2.5 py-1.5 text-xs text-surface hover:bg-border"
                >
                  <icon-lucide-plus class="size-3.5" />
                  {{ panels.add }}
                  <icon-lucide-chevron-down class="size-3" />
                </button>
              </DropdownMenuTrigger>
              <DropdownMenuPortal>
                <DropdownMenuContent
                  side="top"
                  :side-offset="8"
                  align="end"
                  :class="addVariableMenuCls.content"
                >
                  <DropdownMenuItem
                    v-for="item in variableTypes"
                    :key="item.type"
                    :class="menuCls.item"
                    v-test-id="variablesAddTestId(item.type)"
                    @select="ctx.addVariable(item.type)"
                  >
                    <component :is="variableTypeIcons[item.type]" :class="menuCls.icon" />
                    <span class="flex min-w-0 flex-1 flex-col">
                      <span>{{ item.label() }}</span>
                      <span class="truncate text-[10px] text-muted">{{ item.description() }}</span>
                    </span>
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenuPortal>
            </DropdownMenuRoot>
          </div>
        </TabsContent>
      </TabsRoot>
    </template>
  </AppDialogRoot>
</template>

// packages/react/src/components/properties/variables/VariablesDialog.tsx
import { useEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import {
  ChevronDown,
  Ellipsis,
  Folder,
  FolderPlus,
  Hash,
  Palette,
  Pencil,
  Plus,
  Search,
  ToggleLeft,
  Trash2,
  Type,
  X
} from 'lucide-react'
import type { VariableType } from '@open-pencil/scene-graph'

import { IS_BROWSER } from '@open-pencil/core/constants'

import { RenameInput } from '#react/components/properties/variables/EditableCell'
import { FloatingMenu } from '#react/components/properties/variables/FloatingMenu'
import { VariableTable } from '#react/components/properties/variables/VariableTable'
import { AppPlaceholder } from '#react/components/ui/AppPlaceholder'
import { useDialogUI } from '#react/components/ui/dialog'
import { useMenuUI } from '#react/components/ui/menu'
import { Tip } from '#react/components/ui/Tip'
import { useI18n } from '#react/i18n'
import { variablesAddTestId } from '#react/testing/test-id'
import { useVariablesDialogState } from '#react/variables/dialog'

const VARIABLE_TYPES: VariableType[] = ['COLOR', 'FLOAT', 'STRING', 'BOOLEAN']

export function VariablesDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  if (!open || !IS_BROWSER) return null
  return <VariablesDialogOpen onClose={onClose} />
}

function VariablesDialogOpen({ onClose }: { onClose: () => void }) {
  const { dialogs, panels, variableTypes } = useI18n()
  const ctx = useVariablesDialogState()
  const cls = useDialogUI({ content: 'w-[800px] max-w-[90vw]' }, { height: 'tall' })
  const menuCls = useMenuUI({ content: 'w-40', item: 'justify-start gap-2' })
  const addVariableMenuCls = useMenuUI({ content: 'w-48', item: 'justify-start gap-2' })
  const collectionMenuRef = useRef<HTMLButtonElement>(null)
  const addVariableRef = useRef<HTMLButtonElement>(null)
  const [collectionMenuOpen, setCollectionMenuOpen] = useState(false)
  const [addVariableOpen, setAddVariableOpen] = useState(false)

  useEffect(() => {
    function onKey(event: KeyboardEvent) {
      if (event.key !== 'Escape' && event.code !== 'Escape') return
      const target = event.target
      if (target instanceof HTMLElement && target.closest('[data-menu-content], [data-picker-content]')) {
        return
      }
      onClose()
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [onClose])

  const typeItems = VARIABLE_TYPES.map((type) => ({
    type,
    label: typeLabel(type, variableTypes),
    description: typeHint(type, variableTypes),
    Icon: typeIcon(type)
  }))

  return createPortal(
    <>
      <div data-slot="dialog-overlay" className={cls.overlay} onClick={onClose} />
      <div
        role="dialog"
        aria-modal="true"
        data-slot="dialog-content"
        data-test-id="variables-dialog"
        className={cls.content}
      >
        <h2 className="sr-only">{dialogs.localVariables}</h2>
        {!ctx.hasCollections ? (
          <div className="flex flex-1 flex-col">
            <div className="flex shrink-0 items-center justify-between border-b border-border px-4 py-3">
              <h2 className="text-sm font-semibold text-surface">{dialogs.localVariables}</h2>
              <button
                type="button"
                aria-label={dialogs.close}
                className="flex size-6 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted hover:bg-hover hover:text-surface"
                onClick={onClose}
              >
                <X className="size-4" />
              </button>
            </div>
            <AppPlaceholder
              label={dialogs.noVariableCollections}
              icon={<Folder className="size-5" />}
              action={
                <button
                  type="button"
                  data-test-id="variables-create-collection"
                  className="cursor-pointer rounded bg-hover px-3 py-1.5 text-xs text-surface hover:bg-border"
                  onClick={ctx.addCollection}
                >
                  {dialogs.createCollection}
                </button>
              }
            />
          </div>
        ) : (
          <div className="flex flex-1 flex-col overflow-hidden">
            <div className="flex shrink-0 items-center border-b border-border">
              <div className="flex flex-1 gap-0.5 overflow-x-auto px-3 py-1" role="tablist">
                {ctx.collections.map((collection) =>
                  ctx.collectionRename.editingId === collection.id ? (
                    <RenameInput
                      key={collection.id}
                      className="w-24 rounded border border-accent bg-input px-2 py-0.5 text-xs text-surface outline-none"
                      defaultValue={collection.name}
                      onCommit={(event) => ctx.collectionRename.commit(collection.id, event)}
                      onKeyDown={ctx.collectionRename.onKeydown}
                    />
                  ) : (
                    <button
                      key={collection.id}
                      type="button"
                      role="tab"
                      data-test-id="variables-collection-tab"
                      data-state={
                        collection.id === ctx.activeCollectionId ? 'active' : 'inactive'
                      }
                      className="cursor-pointer rounded border-none px-2.5 py-1 text-xs whitespace-nowrap text-muted data-[state=active]:bg-hover data-[state=active]:text-surface"
                      onClick={() => ctx.setActiveCollection(collection.id)}
                      onDoubleClick={() => ctx.startRenameCollection(collection.id)}
                    >
                      {collection.name}
                    </button>
                  )
                )}
              </div>
              <div className="flex items-center gap-1.5 px-3">
                <button
                  ref={collectionMenuRef}
                  type="button"
                  data-test-id="variables-collection-menu"
                  className="flex size-6 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted hover:bg-hover hover:text-surface"
                  onClick={() => setCollectionMenuOpen((current) => !current)}
                >
                  <Ellipsis className="size-3.5" />
                </button>
                <div className="flex items-center gap-1 rounded border border-border px-2 py-0.5">
                  <Search className="size-3 text-muted" />
                  <input
                    data-test-id="variables-search-input"
                    className="w-24 border-none bg-transparent text-xs text-surface outline-none placeholder:text-muted"
                    placeholder={dialogs.search}
                    value={ctx.searchTerm}
                    onChange={(event) => ctx.setSearchTerm(event.target.value)}
                  />
                </div>
                <Tip label={dialogs.createCollection}>
                  <button
                    type="button"
                    data-test-id="variables-add-collection"
                    className="flex size-6 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted hover:bg-hover hover:text-surface"
                    onClick={ctx.addCollection}
                  >
                    <FolderPlus className="size-3.5" />
                  </button>
                </Tip>
                <button
                  type="button"
                  aria-label={dialogs.close}
                  className="flex size-6 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted hover:bg-hover hover:text-surface"
                  onClick={onClose}
                >
                  <X className="size-4" />
                </button>
              </div>
            </div>
            {ctx.activeCollection ? (
              <VariableTable ctx={ctx} collection={ctx.activeCollection} />
            ) : null}
            <div className="flex w-full shrink-0 items-center justify-between gap-2 border-t border-border px-4 py-2">
              <span className="text-xs text-muted">{panels.createVariable}</span>
              <button
                ref={addVariableRef}
                type="button"
                data-test-id="variables-add-variable"
                className="flex cursor-pointer items-center gap-1.5 rounded bg-hover px-2.5 py-1.5 text-xs text-surface hover:bg-border"
                onClick={() => setAddVariableOpen((current) => !current)}
              >
                <Plus className="size-3.5" />
                {panels.add}
                <ChevronDown className="size-3" />
              </button>
            </div>
          </div>
        )}
      </div>
      <FloatingMenu
        open={collectionMenuOpen}
        onClose={() => setCollectionMenuOpen(false)}
        triggerRef={collectionMenuRef}
        className={menuCls.content}
      >
        <button
          type="button"
          role="menuitem"
          className={menuCls.item}
          onClick={() => {
            ctx.startRenameCollection(ctx.activeCollectionId)
            setCollectionMenuOpen(false)
          }}
        >
          <Pencil className={menuCls.icon} />
          {dialogs.renameCollection}
        </button>
        <div className="mx-1.5 my-1 h-px bg-border" />
        <button
          type="button"
          role="menuitem"
          className={`${menuCls.item} text-red-500`}
          data-test-id="variables-delete-collection"
          onClick={() => {
            ctx.removeCollection(ctx.activeCollectionId)
            setCollectionMenuOpen(false)
          }}
        >
          <Trash2 className={menuCls.icon} />
          {dialogs.deleteCollection}
        </button>
      </FloatingMenu>
      <FloatingMenu
        open={addVariableOpen}
        onClose={() => setAddVariableOpen(false)}
        triggerRef={addVariableRef}
        side="top"
        align="end"
        sideOffset={8}
        className={addVariableMenuCls.content}
      >
        {typeItems.map((item) => (
          <button
            key={item.type}
            type="button"
            role="menuitem"
            className={menuCls.item}
            data-test-id={variablesAddTestId(item.type)}
            onClick={() => {
              ctx.addVariable(item.type)
              setAddVariableOpen(false)
            }}
          >
            <item.Icon className={menuCls.icon} />
            <span className="flex min-w-0 flex-1 flex-col">
              <span>{item.label}</span>
              <span className="truncate text-[10px] text-muted">{item.description}</span>
            </span>
          </button>
        ))}
      </FloatingMenu>
    </>,
    document.body
  )
}

function typeLabel(
  type: VariableType,
  variableTypes: { color: string; number: string; text: string; boolean: string }
): string {
  if (type === 'COLOR') return variableTypes.color
  if (type === 'FLOAT') return variableTypes.number
  if (type === 'STRING') return variableTypes.text
  return variableTypes.boolean
}

function typeHint(
  type: VariableType,
  variableTypes: {
    colorHint: string
    numberHint: string
    textHint: string
    booleanHint: string
  }
): string {
  if (type === 'COLOR') return variableTypes.colorHint
  if (type === 'FLOAT') return variableTypes.numberHint
  if (type === 'STRING') return variableTypes.textHint
  return variableTypes.booleanHint
}

function typeIcon(type: VariableType) {
  if (type === 'COLOR') return Palette
  if (type === 'FLOAT') return Hash
  if (type === 'STRING') return Type
  return ToggleLeft
}
