// packages/react/src/primitives/FontPicker/FontPickerRoot.tsx
<script setup lang="ts">
import { nextTick } from 'vue'
import { templateRef, unrefElement } from '@vueuse/core'
import {
  ComboboxAnchor,
  ComboboxContent,
  ComboboxInput,
  ComboboxItem,
  ComboboxItemIndicator,
  ComboboxPortal,
  ComboboxRoot,
  ComboboxTrigger,
  ComboboxVirtualizer,
  ComboboxViewport,
  type AcceptableValue
} from 'reka-ui'

import {
  useFontPicker,
  type FontAccessController,
  type FontFamilyOption
} from '#vue/primitives/FontPicker/useFontPicker'

import type { FontPickerUI } from '#vue/primitives/FontPicker/types'

const { listFamilies, localFontAccess, ui, emptySearchText, emptyFontsText, emptyFontsHint } =
  defineProps<{
    listFamilies: () => Promise<string[] | FontFamilyOption[]>
    localFontAccess?: FontAccessController
    ui?: FontPickerUI
    emptySearchText?: string
    emptyFontsText?: string
    emptyFontsHint?: string
  }>()

const modelValue = defineModel<string>({ required: true })
const emit = defineEmits<{ select: [family: string] }>()

const contentRef = templateRef<HTMLElement>('contentRef')

function focusSearchInput() {
  nextTick(() => {
    const content = unrefElement(contentRef)
    if (!(content instanceof HTMLElement)) return
    content.querySelector<HTMLInputElement>('input')?.focus()
  })
}

const { searchTerm, open, filtered, loading, accessState, requestAccess, select } = useFontPicker({
  modelValue,
  listFamilies,
  localFontAccess,
  onSelect: (family) => emit('select', family)
})
</script>

<template>
  <ComboboxRoot
    v-model:open="open"
    :model-value="modelValue"
    :ignore-filter="true"
    @update:model-value="
      (v: AcceptableValue) => {
        if (typeof v === 'string') select(v)
      }
    "
  >
    <ComboboxAnchor as-child>
      <ComboboxTrigger as-child>
        <slot name="trigger" :value="modelValue" :open="open">
          <button :class="ui?.trigger">
            <span class="truncate">{{ modelValue }}</span>
          </button>
        </slot>
      </ComboboxTrigger>
    </ComboboxAnchor>

    <ComboboxPortal>
      <ComboboxContent
        :side-offset="2"
        align="start"
        position="popper"
        :class="ui?.content"
        @open-auto-focus.prevent
        ref="contentRef"
        @vue:mounted="focusSearchInput"
      >
        <slot name="search" :search-term="searchTerm">
          <ComboboxInput
            v-model="searchTerm"
            :display-value="() => ''"
            :class="ui?.search"
            placeholder="Search fonts…"
            autocomplete="off"
            autocorrect="off"
            autocapitalize="off"
            spellcheck="false"
          />
        </slot>

        <ComboboxViewport :class="ui?.viewport ?? 'max-h-72 overflow-y-auto'">
          <ComboboxVirtualizer
            v-slot="{ option }"
            :options="filtered"
            :text-content="(option: FontFamilyOption) => option.family"
            :estimate-size="36"
          >
            <ComboboxItem
              :value="option.family"
              :class="ui?.item"
              :style="{ fontFamily: `'${option.family}', sans-serif` }"
            >
              <slot
                name="item"
                :family="option.family"
                :source="option.source"
                :selected="option.family === modelValue"
              >
                <ComboboxItemIndicator>
                  <slot name="indicator" :selected="option.family === modelValue" />
                </ComboboxItemIndicator>
                <span class="truncate">{{ option.family }}</span>
              </slot>
            </ComboboxItem>
          </ComboboxVirtualizer>

          <div v-if="filtered.length === 0 && searchTerm" :class="ui?.empty">
            {{ emptySearchText ?? 'No fonts found' }}
          </div>
          <div v-else-if="filtered.length === 0" :class="ui?.empty">
            <div>
              <p v-if="accessState === 'prompt'">
                Allow local font access to browse installed fonts.
              </p>
              <p v-else-if="accessState === 'denied'">
                Local font access is blocked for this site.
              </p>
              <p v-else-if="accessState === 'unsupported'">
                Local fonts are not available in this browser.
              </p>
              <p v-else>{{ emptyFontsText ?? 'No local fonts available.' }}</p>
              <p v-if="emptyFontsHint" class="mt-1">{{ emptyFontsHint }}</p>
              <button
                v-if="accessState === 'prompt'"
                type="button"
                :class="ui?.emptyAction"
                :disabled="loading"
                @click="requestAccess"
              >
                {{ loading ? 'Loading…' : 'Allow local fonts' }}
              </button>
            </div>
          </div>
        </ComboboxViewport>
      </ComboboxContent>
    </ComboboxPortal>
  </ComboboxRoot>
</template>

// packages/react/src/FontPicker/FontPickerRoot.tsx
import { useRef, type ReactNode } from 'react'

import { useFontPicker } from './useFontPicker'

export interface FontPickerRootSlotProps {
  value: string
  open: boolean
  setOpen: (open: boolean) => void
  searchTerm: string
  setSearchTerm: (term: string) => void
  filtered: string[]
  select: (family: string) => void
  setInputRef: (el: HTMLInputElement | null) => void
}

export interface FontPickerRootProps {
  value: string
  listFamilies: () => Promise<string[]>
  onValueChange?: (family: string) => void
  onSelect?: (family: string) => void
  triggerClassName?: string
  contentClassName?: string
  itemClassName?: string
  searchClassName?: string
  viewportClassName?: string
  emptyClassName?: string
  emptySearchText?: string
  emptyFontsText?: string
  emptyFontsHint?: string
  trigger?: ReactNode | ((state: { value: string; open: boolean }) => ReactNode)
  search?:
    | ReactNode
    | ((state: {
        searchTerm: string
        setSearchTerm: (t: string) => void
        setInputRef: (el: HTMLInputElement | null) => void
      }) => ReactNode)
  item?: ReactNode | ((state: { family: string; selected: boolean }) => ReactNode)
  indicator?: ReactNode | ((state: { selected: boolean }) => ReactNode)
  empty?: ReactNode
  children?: ReactNode | ((state: FontPickerRootSlotProps) => ReactNode)
}

/**
 * Headless font picker with a minimal native combobox structure (no Reka UI).
 */
export function FontPickerRoot({
  value,
  listFamilies,
  onValueChange,
  onSelect,
  triggerClassName,
  contentClassName,
  itemClassName,
  searchClassName,
  viewportClassName,
  emptyClassName,
  emptySearchText,
  emptyFontsText,
  emptyFontsHint,
  trigger,
  search,
  item,
  indicator,
  empty,
  children
}: FontPickerRootProps) {
  const inputRef = useRef<HTMLInputElement | null>(null)

  function setInputRef(el: HTMLInputElement | null) {
    inputRef.current = el
  }

  const { searchTerm, setSearchTerm, open, setOpen, filtered, select } = useFontPicker({
    value,
    listFamilies,
    onValueChange,
    onSelect
  })

  const slot: FontPickerRootSlotProps = {
    value,
    open,
    setOpen,
    searchTerm,
    setSearchTerm,
    filtered,
    select,
    setInputRef
  }

  if (typeof children === 'function') {
    return <>{children(slot)}</>
  }
  if (children) return <>{children}</>

  const triggerNode =
    typeof trigger === 'function'
      ? trigger({ value, open })
      : (trigger ?? (
          <button type="button" className={triggerClassName} onClick={() => setOpen(!open)}>
            <span>{value}</span>
          </button>
        ))

  return (
    <div data-font-picker="" style={{ position: 'relative', display: 'inline-block' }}>
      {triggerNode}
      {open ? (
        <div className={contentClassName} role="listbox">
          {typeof search === 'function'
            ? search({ searchTerm, setSearchTerm, setInputRef })
            : (search ?? (
                <input
                  ref={setInputRef}
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className={searchClassName}
                  placeholder="Search fonts…"
                  autoComplete="off"
                  autoCorrect="off"
                  autoCapitalize="off"
                  spellCheck={false}
                />
              ))}
          <div className={viewportClassName ?? 'max-h-72 overflow-y-auto'}>
            {filtered.map((family) => {
              const selected = family === value
              if (typeof item === 'function') {
                return <div key={family}>{item({ family, selected })}</div>
              }
              return (
                <button
                  key={family}
                  type="button"
                  role="option"
                  aria-selected={selected}
                  className={itemClassName}
                  style={{ fontFamily: `'${family}', sans-serif` }}
                  onClick={() => select(family)}
                >
                  {typeof indicator === 'function' ? indicator({ selected }) : indicator}
                  <span>{family}</span>
                </button>
              )
            })}
            {filtered.length === 0 && searchTerm ? (
              <div className={emptyClassName}>{emptySearchText ?? 'No fonts found'}</div>
            ) : null}
            {filtered.length === 0 && !searchTerm ? (
              <div className={emptyClassName}>
                {empty ?? (
                  <div>
                    <p>{emptyFontsText ?? 'No local fonts available.'}</p>
                    {emptyFontsHint ? <p>{emptyFontsHint}</p> : null}
                  </div>
                )}
              </div>
            ) : null}
          </div>
        </div>
      ) : null}
    </div>
  )
}
