// src/components/CollabPanel/CollabSharePopover.vue
<script setup lang="ts">
import { computed } from 'vue'
import { tv } from 'tailwind-variants'
import { PopoverContent, PopoverPortal, PopoverRoot, PopoverTrigger } from 'reka-ui'

import ConnectedRoom from '@/components/CollabPanel/ConnectedRoom.vue'
import JoinRoomPrompt from '@/components/CollabPanel/JoinRoomPrompt.vue'
import ShareOrJoinRoom from '@/components/CollabPanel/ShareOrJoinRoom.vue'
import { useCollabPanelContext } from '@/components/CollabPanel/context'
import { usePopoverUI } from '@/components/ui/popover'
import collaborationTheme from '@/theme/collaboration'

const collab = useCollabPanelContext()
const cls = usePopoverUI({ content: 'z-50 w-72 p-3' })
const connection = computed(() => {
  if (collab.state.connected) return 'connected'
  if (collab.isJoining) return 'joining'
  return 'idle'
})
const collaboration = tv(collaborationTheme)
const styles = computed(() => collaboration({ connection: connection.value }))
</script>

<template>
  <PopoverRoot v-model:open="collab.popoverOpen">
    <PopoverTrigger as-child>
      <button
        data-test-id="collab-share-button"
        :data-connection="connection"
        :class="styles.shareButton()"
      >
        <icon-lucide-share-2 class="size-3.5" />
        {{
          collab.state.connected
            ? collab.messages.connected
            : collab.isJoining
              ? collab.messages.joinRoom
              : collab.messages.share
        }}
      </button>
    </PopoverTrigger>

    <PopoverPortal>
      <PopoverContent
        data-test-id="collab-popover"
        :class="cls.content"
        :side-offset="8"
        side="bottom"
        align="end"
      >
        <ConnectedRoom v-if="collab.state.connected" />
        <JoinRoomPrompt v-else-if="collab.isJoining" />
        <ShareOrJoinRoom v-else />
      </PopoverContent>
    </PopoverPortal>
  </PopoverRoot>
</template>

// src/components/CollabPanel/CollabSharePopover.tsx
import IconLucideShare2 from '~icons/lucide/share-2'
import * as Popover from '@radix-ui/react-popover'
import { memo, useMemo } from 'react'
import { tv } from 'tailwind-variants'

import ConnectedRoom from '@/components/CollabPanel/ConnectedRoom'
import JoinRoomPrompt from '@/components/CollabPanel/JoinRoomPrompt'
import ShareOrJoinRoom from '@/components/CollabPanel/ShareOrJoinRoom'
import { useCollabPanelContext } from '@/components/CollabPanel/context'
import { usePopoverUI } from '@/components/ui/popover'
import collaborationTheme from '@/theme/collaboration'

export const CollabSharePopover = memo(function CollabSharePopover() {
  const collab = useCollabPanelContext()
  const cls = usePopoverUI({ content: 'z-50 w-72 p-3' })
  const connection = collab.state.connected ? 'connected' : collab.isJoining ? 'joining' : 'idle'
  const collaboration = tv(collaborationTheme)
  const styles = useMemo(() => collaboration({ connection }), [collaboration, connection])

  return (
    <Popover.Root open={collab.popoverOpen} onOpenChange={collab.setPopoverOpen}>
      <Popover.Trigger asChild>
        <button
          type="button"
          data-test-id="collab-share-button"
          data-connection={connection}
          className={styles.shareButton()}
        >
          <IconLucideShare2 className="size-3.5" />
          {collab.state.connected
            ? collab.dialogs.connected
            : collab.isJoining
              ? collab.dialogs.joinRoom
              : collab.dialogs.share}
        </button>
      </Popover.Trigger>
      <Popover.Portal>
        <Popover.Content
          data-test-id="collab-popover"
          className={cls.content}
          sideOffset={8}
          side="bottom"
          align="end"
        >
          {collab.state.connected ? (
            <ConnectedRoom />
          ) : collab.isJoining ? (
            <JoinRoomPrompt />
          ) : (
            <ShareOrJoinRoom />
          )}
        </Popover.Content>
      </Popover.Portal>
    </Popover.Root>
  )
})

CollabSharePopover.displayName = 'CollabSharePopover'
export default CollabSharePopover
