// src/components/ui/panel/PanelHeader.tsx
import { tv } from 'tailwind-variants'
import type { ReactNode } from 'react'
import type { ClassValue } from 'tailwind-variants'

import type { ComponentUI } from '@/components/ui/types'
import type { PanelHeaderTheme } from '@/theme/panel/header'
import theme from '@/theme/panel/header'

export interface PanelHeaderProps {
  component?: boolean
  className?: ClassValue
  ui?: ComponentUI<PanelHeaderTheme>
  icon?: ReactNode
  children?: ReactNode
  actions?: ReactNode
}

export function PanelHeader({
  component = false,
  className,
  ui,
  icon,
  children,
  actions
}: PanelHeaderProps) {
  const styles = tv(theme)({ component })
  return (
    <header
      data-slot="root"
      data-component={component ? '' : undefined}
      className={styles.root({ class: [ui?.root, className] })}
    >
      <div data-slot="icon" className={styles.icon({ class: ui?.icon })}>
        {icon}
      </div>
      <div data-slot="title" className={styles.title({ class: ui?.title })}>
        {children}
      </div>
      {actions && (
        <div data-slot="actions" className={styles.actions({ class: ui?.actions })}>
          {actions}
        </div>
      )}
    </header>
  )
}

// src/components/ui/panel/PanelHeader.vue
<script lang="ts">
import type { VNode } from 'vue'
import type { ClassValue } from 'tailwind-variants'

import type { ComponentUI } from '@/components/ui/types'
import type { PanelHeaderTheme } from '@/theme/panel/header'

export interface PanelHeaderProps {
  component?: boolean
  class?: ClassValue
  ui?: ComponentUI<PanelHeaderTheme>
}

export interface PanelHeaderSlots {
  icon?(): VNode[]
  default(): VNode[]
  actions?(): VNode[]
  content?(): VNode[]
}
</script>

<script setup lang="ts">
import { tv } from 'tailwind-variants'

import theme from '@/theme/panel/header'

const { component = false, class: className, ui } = defineProps<PanelHeaderProps>()
const slots = defineSlots<PanelHeaderSlots>()
const styles = tv(theme)({ component })
</script>

<template>
  <header
    data-slot="root"
    :data-component="component ? '' : undefined"
    :class="styles.root({ class: [ui?.root, className] })"
  >
    <div data-slot="icon" :class="styles.icon({ class: ui?.icon })">
      <slot name="icon" />
    </div>
    <div data-slot="title" :class="styles.title({ class: ui?.title })">
      <slot />
    </div>
    <div v-if="slots.actions" data-slot="actions" :class="styles.actions({ class: ui?.actions })">
      <slot name="actions" />
    </div>
    <div v-if="slots.content" data-slot="content" :class="styles.content({ class: ui?.content })">
      <slot name="content" />
    </div>
  </header>
</template>
