// src/App.tsx
import * as Tooltip from '@radix-ui/react-tooltip'
import { memo, useEffect, type ReactNode } from 'react'
import { Outlet } from 'react-router'

import { EditorProvider, useI18n } from '@open-pencil/react'
import { useEditorStore } from '@/app/editor/active-store'
import { toast } from '@/app/shell/ui'
import { useAppTheme } from '@/app/shell/theme'
import { scheduleStartupUpdateCheck } from '@/app/shell/updater'
import AppToast from '@/components/Shell/AppToast'

export const App = memo(function App() {
  const store = useEditorStore()
  const { dialogs } = useI18n()
  useAppTheme()

  useEffect(() => {
    document.title = 'OpenPencil'
  }, [])

  useEffect(() => {
    toast.setupGlobalErrorHandler()
    scheduleStartupUpdateCheck(dialogs)
  }, [dialogs])

  return (
    <EditorProvider editor={store}>
      <Tooltip.Provider delayDuration={400}>
        <Outlet />
        <AppToast />
      </Tooltip.Provider>
    </EditorProvider>
  )
})

App.displayName = 'App'

export default App

// Keep a typed children helper for storybook/wrappers.
export type AppShellProps = { children?: ReactNode }

// src/App.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import { useHead } from '@unhead/vue'
import { TooltipProvider } from 'reka-ui'

import { provideEditor, useI18n } from '@open-pencil/vue'
import AppToast from '@/components/Shell/AppToast.vue'
import ReactEditorHost from '@/components/Shell/ReactEditorHost.vue'
import { useEditorStore } from '@/app/editor/active-store'
import { toast } from '@/app/shell/ui'
import { useAppTheme } from '@/app/shell/theme'
import { scheduleStartupUpdateCheck } from '@/app/shell/updater'

useHead({ titleTemplate: (title) => (title ? `${title} — OpenPencil` : 'OpenPencil') })

const store = useEditorStore()
const { dialogs } = useI18n()
provideEditor(store)
useAppTheme()

onMounted(() => {
  toast.setupGlobalErrorHandler()
  scheduleStartupUpdateCheck(dialogs)
})
</script>

<template>
  <TooltipProvider :delay-duration="400">
    <RouterView />
    <AppToast />
    <!-- React islands host (EditorProvider + smoke) during Vue→React parallel migration -->
    <ReactEditorHost />
  </TooltipProvider>
</template>
