// src/components/LayerTree/LayerTreeRenameRow.tsx
import { memo, useEffect, useMemo, useRef } from 'react'
import { tv } from 'tailwind-variants'

import type { LayerNode } from '@open-pencil/react'
import { nodeIcon } from '@/app/editor/icons'
import LayerTreeDisclosure from '@/components/LayerTree/LayerTreeDisclosure'
import type { LayerRenameControls, LayerTreeItemActions } from '@/components/LayerTree/types'
import { useLayerTreeUI } from '@/components/LayerTree/ui'
import layerTreeTheme from '@/theme/layer-tree'

export type LayerTreeRenameRowProps = {
  node: LayerNode
  hasChildren: boolean
  padLeft: string
  expanded: boolean
  actions: LayerTreeItemActions
  renameControls: LayerRenameControls
}

export const LayerTreeRenameRow = memo(function LayerTreeRenameRow({
  node,
  hasChildren,
  padLeft,
  expanded,
  actions,
  renameControls
}: LayerTreeRenameRowProps) {
  const renameInputRef = useRef<HTMLInputElement>(null)
  const ui = useLayerTreeUI()
  const layerTree = tv(layerTreeTheme)
  const styles = useMemo(() => layerTree({ expanded }), [expanded, layerTree])
  const NodeIcon = nodeIcon(node)

  useEffect(() => {
    const input = renameInputRef.current
    if (input) void renameControls.focusInput(input)
  }, [renameControls])

  return (
    <div
      data-slot="rename-row"
      className={styles.renameRow({ class: ui?.renameRow })}
      style={{ paddingLeft: padLeft }}
    >
      <LayerTreeDisclosure
        expanded={expanded}
        visible={hasChildren}
        onToggle={actions.toggleExpand}
      />
      <NodeIcon data-slot="rename-icon" className={styles.renameIcon({ class: ui?.renameIcon })} />
      <input
        ref={renameInputRef}
        data-layer-edit
        data-test-id="layers-item-input"
        data-slot="rename-input"
        className={styles.renameInput({ class: ui?.renameInput })}
        defaultValue={node.name}
        onBlur={(event) => renameControls.commit(node.id, event)}
        onKeyDown={(event) => {
          event.stopPropagation()
          renameControls.onKeydown(event)
        }}
      />
    </div>
  )
})

LayerTreeRenameRow.displayName = 'LayerTreeRenameRow'
export default LayerTreeRenameRow

// src/components/LayerTree/LayerTreeRenameRow.vue
<script setup lang="ts">
import { tv } from 'tailwind-variants'
import { computed, useTemplateRef, watch } from 'vue'

import { useI18n, type LayerNode } from '@open-pencil/vue'

import { nodeIcon } from '@/app/editor/icons'
import layerTreeTheme from '@/theme/layer-tree'

import LayerTreeDisclosure from './LayerTreeDisclosure.vue'
import LayerTreeRowShell from './LayerTreeRowShell.vue'
import type { LayerRenameControls, LayerTreeItemActions } from './types'
import { useLayerTreeUI } from './ui'

const { renameControls, expanded } = defineProps<{
  node: LayerNode
  hasChildren: boolean
  padLeft: string
  expanded: boolean
  actions: LayerTreeItemActions
  renameControls: LayerRenameControls
}>()

const renameInput = useTemplateRef<HTMLInputElement>('renameInput')
const { rename } = useI18n()
const ui = useLayerTreeUI()
const layerTree = tv(layerTreeTheme)
const styles = computed(() => layerTree({ expanded }))

watch(renameInput, (input) => {
  if (input) void renameControls.focusInput(input)
})
</script>

<template>
  <LayerTreeRowShell
    :pad-left="padLeft"
    data-slot="rename-row"
    :class="styles.renameRow({ class: ui?.renameRow })"
  >
    <LayerTreeDisclosure
      :label="node.name"
      :ui="{
        disclosure: styles.disclosure({ class: ui?.disclosure }),
        placeholder: styles.disclosurePlaceholder({ class: ui?.disclosurePlaceholder })
      }"
      :expanded="expanded"
      :visible="hasChildren"
      @toggle="actions.toggleExpand"
    />
    <component
      :is="nodeIcon(node)"
      data-slot="rename-icon"
      :class="styles.renameIcon({ class: ui?.renameIcon })"
    />
    <input
      ref="renameInput"
      data-layer-edit
      data-test-id="layers-item-input"
      data-slot="rename-input"
      :aria-label="rename.layerName"
      :class="styles.renameInput({ class: ui?.renameInput })"
      :value="node.name"
      @blur="renameControls.commit(node.id, $event)"
      @keydown.stop="renameControls.onKeydown"
    />
  </LayerTreeRowShell>
</template>
