// src/components/ui/feedback/AppBadge.vue
<script setup lang="ts">
import { twMerge } from 'tailwind-merge'
import { computed } from 'vue'

const { ui } = defineProps<{
  ui?: {
    base?: string
  }
}>()

const cls = computed(() =>
  twMerge('shrink-0 rounded bg-accent/10 px-1 py-px text-[9px] text-primary', ui?.base)
)
</script>

<template>
  <span :class="cls"><slot /></span>
</template>

// src/components/ui/AppBadge.tsx
import { twMerge } from 'tailwind-merge'
import type { ReactNode } from 'react'

export interface AppBadgeProps {
  ui?: { base?: string }
  children?: ReactNode
}

export function AppBadge({ ui, children }: AppBadgeProps) {
  return (
    <span className={twMerge('shrink-0 rounded bg-accent/10 px-1 py-px text-[9px] text-accent', ui?.base)}>
      {children}
    </span>
  )
}
