// src/components/ui/select/AppSelect.vue
<script setup lang="ts" generic="T extends string | number">
import {
  SelectContent,
  SelectItem,
  SelectItemIndicator,
  SelectItemText,
  SelectPortal,
  SelectRoot,
  SelectScrollDownButton,
  SelectScrollUpButton,
  SelectTrigger,
  SelectValue,
  SelectViewport
} from 'reka-ui'
import { tv } from 'tailwind-variants'

import type { ComponentUI } from '@/components/ui/types'
import theme from '@/theme/select/app'
import type { AppSelectTheme } from '@/theme/select/app'

interface AppSelectProps<TValue extends string | number> {
  label?: string
  options: { value: TValue; label: string; disabled?: boolean }[]
  placeholder?: string
  ui?: ComponentUI<AppSelectTheme>
}

defineOptions({ inheritAttrs: false })

const { options, label, placeholder, ui } = defineProps<AppSelectProps<T>>()
const modelValue = defineModel<T>({ required: true })
const styles = tv(theme)()
</script>

<template>
  <SelectRoot v-model="modelValue">
    <SelectTrigger
      v-bind="$attrs"
      :class="styles.trigger({ class: ui?.trigger })"
      :aria-label="label"
    >
      <SelectValue :placeholder="placeholder" :class="styles.value({ class: ui?.value })" />
      <icon-lucide-chevron-down class="ml-1 size-3 shrink-0 text-muted" />
    </SelectTrigger>
    <SelectPortal>
      <SelectContent
        position="popper"
        :side-offset="2"
        :class="styles.content({ class: ui?.content })"
      >
        <SelectScrollUpButton class="flex items-center justify-center py-0.5 text-muted">
          <icon-lucide-chevron-up class="size-3.5" />
        </SelectScrollUpButton>
        <SelectViewport :class="styles.viewport({ class: ui?.viewport })">
          <SelectItem
            v-for="opt in options"
            :key="String(opt.value)"
            :value="opt.value"
            :disabled="opt.disabled"
            :class="styles.item({ class: ui?.item })"
          >
            <SelectItemIndicator :class="styles.indicator({ class: ui?.indicator })">
              <icon-lucide-check class="size-3 text-accent" />
            </SelectItemIndicator>
            <SelectItemText>{{ opt.label }}</SelectItemText>
          </SelectItem>
        </SelectViewport>
        <SelectScrollDownButton class="flex items-center justify-center py-0.5 text-muted">
          <icon-lucide-chevron-down class="size-3.5" />
        </SelectScrollDownButton>
      </SelectContent>
    </SelectPortal>
  </SelectRoot>
</template>

// src/components/ui/AppSelect.tsx
import { tv } from 'tailwind-variants'
import { SelectContent, SelectItem, SelectItemIndicator, SelectItemText, SelectPortal, Root as SelectRoot, SelectTrigger, SelectValue, SelectViewport } from '@radix-ui/react-select'

import IconLucideCheck from '~icons/lucide/check'
import IconLucideChevronDown from '~icons/lucide/chevron-down'

import type { AppSelectTheme } from '@/theme/app-select'
import type { ComponentUI } from '@/components/ui/types'
import theme from '@/theme/app-select'

export interface AppSelectProps<T extends string | number = string> {
  value: T
  options: { value: T; label: string }[]
  label?: string
  placeholder?: string
  ui?: ComponentUI<AppSelectTheme>
  onChange?: (value: T) => void
  className?: string
}

export function AppSelect<T extends string | number = string>({
  value,
  options,
  label,
  placeholder,
  ui,
  onChange,
  className
}: AppSelectProps<T>) {
  const styles = tv(theme)()

  function handleChange(val: string) {
    if (onChange) {
      const typed = (typeof value === 'number' ? Number(val) : val) as T
      onChange(typed)
    }
  }

  return (
    <SelectRoot value={String(value)} onValueChange={handleChange}>
      <SelectTrigger
        className={styles.trigger({ class: [ui?.trigger, className] })}
        aria-label={label}
      >
        <SelectValue placeholder={placeholder} className={styles.value({ class: ui?.value })} />
        <IconLucideChevronDown className="ml-1 size-3 shrink-0 text-muted" />
      </SelectTrigger>
      <SelectPortal>
        <SelectContent
          position="popper"
          sideOffset={2}
          className={styles.content({ class: ui?.content })}
        >
          <SelectViewport className={styles.viewport({ class: ui?.viewport })}>
            {options.map((opt) => (
              <SelectItem
                key={String(opt.value)}
                value={String(opt.value)}
                className={styles.item({ class: ui?.item })}
              >
                <SelectItemIndicator className={styles.indicator({ class: ui?.indicator })}>
                  <IconLucideCheck className="size-3 text-accent" />
                </SelectItemIndicator>
                <SelectItemText>{opt.label}</SelectItemText>
              </SelectItem>
            ))}
          </SelectViewport>
        </SelectContent>
      </SelectPortal>
    </SelectRoot>
  )
}
